### ISSUE TITLE
[BUG] Orders not canceled in Pure MM unit tests.

### ISSUE THREAD

**Issue by Nullably** [hummingbot/hummingbot#1811]
**Describe the bug**
When doing unit testing on pure market making strategy, sometimes orders that were previously supposed to cancel are left as active orders in the strategy.

For example, you can try running the following unit test (add it to PureMarketMakingV2UnitTest class).

```python
    def test_order_not_canceled(self):
        self.clock.remove_iterator(self.strategy)

        self.strategy: PureMarketMakingStrategyV2 = PureMarketMakingStrategyV2(
            [self.market_info],
            filter_delegate=self.filter_delegate,
            sizing_delegate=self.constant_sizing_delegate,
            pricing_delegate=self.constant_pricing_delegate,
            order_refresh_time=45,
            order_refresh_tolerance_pct=-1
        )
        self.clock.add_iterator(self.strategy)
        self.clock.backtest_til(self.start_timestamp + self.clock_tick_size)
        self.assertEqual(1, len(self.strategy.active_bids))
        self.assertEqual(1, len(self.strategy.active_asks))

        order: LimitOrder = self.strategy.active_asks[0][1]
        simulate_limit_order_fill(self.maker_market, order)
        # self.simulate_maker_market_trade(True, 5.0)
        self.assertEqual(1, len(self.strategy.active_bids))
        self.assertEqual(0, len(self.strategy.active_asks))

        self.clock.backtest_til(self.start_timestamp + 2 * self.clock_tick_size + 1)
        self.assertEqual(1, len(self.strategy.active_bids))
        self.assertEqual(1, len(self.strategy.active_asks))

        self.clock.backtest_til(self.start_timestamp + (10 * self.clock_tick_size) + 2)
        self.assertEqual(1, len(self.strategy.active_bids))
        self.assertEqual(1, len(self.strategy.active_asks))
```

The test will fail at the last step, however if you change on how to simulate orders filled, instead of using `simulate_limit_order_fill`, use `simulate_maker_market_trade`. The test will pass.

Upon debugging with `print`, here is the output.

```python
Testing started at 11:16 AM ...
/Users/jack/anaconda3/envs/hummingbot/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/_jb_unittest_runner.py --target test_pure_market_making_v2.PureMarketMakingV2UnitTest.test_multiple_orders_equal_sizes_2
Launching unittests with arguments python -m unittest test_pure_market_making_v2.PureMarketMakingV2UnitTest.test_multiple_orders_equal_sizes_2 in /Users/jack/github/hummingbot/test

c_tick 1546300860.0
c_tick active_non_hangings: 0
c_tick 1546300920.0
c_tick active_non_hangings: 1
LimitOrder('buy://COINALPHA-WETH/3442ff25c4d8502fcc56893ccff18c0ef2fca6a1c8270d6392687da828b6fc4e', 'COINALPHA-WETH', True, 'COINALPHA', 'WETH', 99.0000, 1.000000)
cancelling order: LimitOrder('buy://COINALPHA-WETH/3442ff25c4d8502fcc56893ccff18c0ef2fca6a1c8270d6392687da828b6fc4e', 'COINALPHA-WETH', True, 'COINALPHA', 'WETH', 99.0000, 1.000000)
c_tick 1546300980.0
c_tick active_non_hangings: 0
c_tick 1546301040.0
c_tick active_non_hangings: 2
LimitOrder('buy://COINALPHA-WETH/dd302798ef8f1e4aecd0e96fde4c154ecf58624ff1c5ebdaea2c465df84001c5', 'COINALPHA-WETH', True, 'COINALPHA', 'WETH', 99.0000, 1.000000)
LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
cancelling order: LimitOrder('buy://COINALPHA-WETH/dd302798ef8f1e4aecd0e96fde4c154ecf58624ff1c5ebdaea2c465df84001c5', 'COINALPHA-WETH', True, 'COINALPHA', 'WETH', 99.0000, 1.000000)
cancelling order: LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
c_tick 1546301100.0
c_tick active_non_hangings: 1
LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
ERROR:hummingsim.backtest.market:Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "hummingbot/strategy/strategy_base.pyx", line 45, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
cancelling order: LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 826, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
AttributeError: 'NoneType' object has no attribute 'market'
ERROR:hummingsim.backtest.market:Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "hummingbot/strategy/strategy_base.pyx", line 45, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 826, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
c_tick 1546301160.0
AttributeError: 'NoneType' object has no attribute 'market'
ERROR:hummingsim.backtest.market:Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "hummingbot/strategy/strategy_base.pyx", line 45, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 826, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
c_tick active_non_hangings: 1
AttributeError: 'NoneType' object has no attribute 'market'
ERROR:hummingsim.backtest.market:Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "hummingbot/strategy/strategy_base.pyx", line 45, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 826, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
AttributeError: 'NoneType' object has no attribute 'market'
ERROR:hummingsim.backtest.market:Unexpected error while processing event 103.
LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "hummingbot/strategy/strategy_base.pyx", line 45, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 826, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
AttributeError: 'NoneType' object has no attribute 'market'
ERROR:hummingsim.backtest.market:Unexpected error while processing event 103.
Traceback (most recent call last):
cancelling order: LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "hummingbot/strategy/strategy_base.pyx", line 45, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 826, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
AttributeError: 'NoneType' object has no attribute 'market'
ERROR:hummingsim.backtest.market:Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "hummingbot/strategy/strategy_base.pyx", line 45, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 826, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
c_tick 1546301220.0
AttributeError: 'NoneType' object has no attribute 'market'
ERROR:hummingsim.backtest.market:Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "hummingbot/strategy/strategy_base.pyx", line 45, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 826, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
c_tick active_non_hangings: 1
AttributeError: 'NoneType' object has no attribute 'market'
ERROR:hummingsim.backtest.market:Unexpected error while processing event 103.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "hummingbot/strategy/strategy_base.pyx", line 45, in hummingbot.strategy.strategy_base.SellOrderCompletedListener.c_call
  File "hummingbot/strategy/pure_market_making/pure_market_making_v2.pyx", line 826, in hummingbot.strategy.pure_market_making.pure_market_making_v2.PureMarketMakingStrategyV2.c_did_complete_sell_order
LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
AttributeError: 'NoneType' object has no attribute 'market'
cancelling order: LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
c_tick 1546301280.0
c_tick active_non_hangings: 1
LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
cancelling order: LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
c_tick 1546301340.0
c_tick active_non_hangings: 1
LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
cancelling order: LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
c_tick 1546301400.0
c_tick active_non_hangings: 1
LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
cancelling order: LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
c_tick 1546301460.0
c_tick active_non_hangings: 1
LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
cancelling order: LimitOrder('sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164', 'COINALPHA-WETH', False, 'COINALPHA', 'WETH', 101.000, 1.000000)
```

Note, the order `sell://COINALPHA-WETH/2318c884ec745dedf848926fb74bf502a0e9ffc222bcb9b0f613f8f24ab2e164` is failed to cancel.

petioptrv discovered this issue while he was working on #1801

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1aft) by [Unito](https://www.unito.io)

**Comment by Nullably** [comment]
No longer an issue.
