### ISSUE TITLE
[BUG] Celo_arb asyncio TimeoutError

### ISSUE THREAD

**Issue by dennisocana** [hummingbot/hummingbot#1948]
**Describe the bug**

The `celo_arb` strategy is running fine as expected, found errors in logs.

```
2020-06-26 09:18:29,183 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
```

![image](https://user-images.githubusercontent.com/50150287/85842854-ecad0a80-b7d2-11ea-804a-ad73a5fc930b.png)

Configuration :

```
strategy: celo_arb
secondary_exchange: bittrex
secondary_market: CELO-USD
order_amount: 3.0
min_profitability: -10.0
celo_slippage_buffer: 0.01
```

**Release version** : dev-0.29.0

**Log file** : [logs_celo_bittrex.log](https://github.com/CoinAlpha/hummingbot/files/4836109/logs_celo_bittrex.log)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1pd1cfj) by [Unito](https://www.unito.io)

**Comment by dennisocana** [comment]
I switched to a `t2.medium` instance and did not see the errors overnight.
