### ISSUE TITLE
Retry order on MarketOrderFailureEvent 

### ISSUE THREAD

**Issue by Marty19** [hummingbot/hummingbot#2338]
Occasionally I get an order failure when using Coinbase Pro. Not sure of the reason as balance is sufficient. This results in a single sided order being created and stops the hang feature from working correctly

I was wondering if it would be possible to have an option to retry placing the order x times on failure in order to keep the orders in pairs.

Also, if order retry fails then attempt to cancel the active paired order.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak77t) by [Unito](https://www.unito.io)

**Comment by Marty19** [comment]
Here is an example of the problem where the buy side of the order pair is successfully created but the sell fails. In this case the sell should retry or the buy order be cancelled.

`2020-10-14 10:39:36,001 - 19512 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTC-EUR) Creating 1 bid orders at (Size, Price): ['0.02 BTC, 9713.35 EUR']
2020-10-14 10:39:36,002 - 19512 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTC-EUR) Creating 1 ask orders at (Size, Price): ['0.02 BTC, 9791.37 EUR']
2020-10-14 10:39:36,429 - 19512 - hummingbot.market.coinbase_pro.coinbase_pro_market - NETWORK - Error submitting sell limit_maker order to Coinbase Pro for 0.02000000 BTC-EUR 9791.37000000.
Traceback (most recent call last):
  File "hummingbot/market/coinbase_pro/coinbase_pro_market.pyx", line 796, in hummingbot.market.coinbase_pro.coinbase_pro_market.CoinbaseProMarket.execute_sell
    order_result = await self.place_order(order_id, trading_pair, decimal_amount, False, order_type, decimal_price)
  File "hummingbot/market/coinbase_pro/coinbase_pro_market.pyx", line 708, in place_order
    order_result = await self._api_request("post", path_url=path_url, data=data)
  File "hummingbot/market/coinbase_pro/coinbase_pro_market.pyx", line 320, in _api_request
    async with client.request(http_method,
  File "hummingbot/market/coinbase_pro/coinbase_pro_market.pyx", line 324, in hummingbot.market.coinbase_pro.coinbase_pro_market.CoinbaseProMarket._api_request
    raise IOError(f"Error fetching data from {url}. HTTP status is {response.status}. {data}")
OSError: Error fetching data from https://api.pro.coinbase.com/orders. HTTP status is 429. {'message': 'Private rate limit exceeded'}
2020-10-14 10:39:36,430 - 19512 - hummingbot.market.coinbase_pro.coinbase_pro_market - WARNING - Failed to submit sell order to Coinbase Pro. Check API key and network connection.
2020-10-14 10:39:36,437 - 19512 - hummingbot.market.coinbase_pro.coinbase_pro_market - INFO - Created OrderType.LIMIT_MAKER buy order buy-BTC-EUR-1602664776002500 for 0.02000000 BTC-EUR.
2020-10-14 10:39:36,455 - 19512 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1602664776.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BTC-EUR", "amount": "0.02000000", "price": "9713.35000000", "order_id": "buy-BTC-EUR-1602664776002500", "event_name": "BuyOrderCreatedEvent", "event_source": "coinbase_pro"}`
