### ISSUE TITLE
[BUG] Unable to re-enter Ethereum private key after accidentally adding incorrect input

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#2346]
**Describe the bug**
If you accidentally entered an incorrect Ethereum private key on Hummingbot, it will give you the following error and won't allow you to correct the private key. Using command `CTRL + X` doesn't work as well, and you'll have to restart your instance to be able to add the correct Ethereum private key.

```
2020-09-19 08:08:19,702 - 6248 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: when sending a str, it must be a hex string. Got: 'dasdasdadasd'
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\connect_command.py", line 143, in connect_ethereum
  File "hummingbot\client\config\security.py", line 106, in add_private_key
  File "hummingbot\core\utils\wallet_setup.py", line 34, in import_and_save_wallet
  File "site-packages\eth_utils\decorators.py", line 20, in _wrapper
  File "site-packages\eth_account\account.py", line 212, in privateKeyToAccount
  File "site-packages\eth_utils\decorators.py", line 20, in _wrapper
  File "site-packages\eth_account\account.py", line 237, in from_key
  File "site-packages\eth_utils\decorators.py", line 20, in _wrapper
  File "site-packages\eth_account\account.py", line 583, in _parsePrivateKey
  File "site-packages\hexbytes\main.py", line 24, in __new__
  File "site-packages\eth_utils\conversions.py", line 152, in hexstr_if_str
ValueError: when sending a str, it must be a hex string. Got: 'dasdasdadasd' ##incorrect input added
```

Similar behavior may occur if you accidentally added a private key longer than 32 byte

```
2020-09-19 08:10:40,903 - 15380 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: The private key must be exactly 32 bytes long, instead of 59 bytes.
Traceback (most recent call last):
  File "site-packages\eth_account\account.py", line 583, in _parsePrivateKey
  File "site-packages\eth_keys\datatypes.py", line 252, in __init__
  File "site-packages\eth_keys\validation.py", line 91, in validate_private_key_bytes
  File "site-packages\eth_keys\validation.py", line 56, in validate_bytes_length
eth_keys.exceptions.ValidationError: Unexpected private key length: Expected 32, but got 30 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\connect_command.py", line 143, in connect_ethereum
  File "hummingbot\client\config\security.py", line 106, in add_private_key
  File "hummingbot\core\utils\wallet_setup.py", line 34, in import_and_save_wallet
  File "site-packages\eth_utils\decorators.py", line 20, in _wrapper
  File "site-packages\eth_account\account.py", line 212, in privateKeyToAccount
  File "site-packages\eth_utils\decorators.py", line 20, in _wrapper
  File "site-packages\eth_account\account.py", line 237, in from_key
  File "site-packages\eth_utils\decorators.py", line 20, in _wrapper
  File "site-packages\eth_account\account.py", line 585, in _parsePrivateKey
ValueError: The private key must be exactly 32 bytes long, instead of 59 bytes.
```

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):

1. Open Hummingbot
1. Run `connect ethereum`
1. Add random private key lower than 32 byte or add private key and add extra letters and numbers to exceed 32 byte.
1. Press enter and an error will be displayed on the logs.
1. Try to re-enter your private key and it will not allow you to do so
1. Press `CTRL +X` and you will get a  message that config is trying to be exited and remain that way.
...

**Screenshots**
input lower that 32 byte:
![ethereum](https://user-images.githubusercontent.com/57189990/93654825-5cd5d000-fa52-11ea-9817-fe3157272f9f.PNG)
input longer than 32 byte:
![ethereum1](https://user-images.githubusercontent.com/57189990/93654826-5e06fd00-fa52-11ea-9bf6-f5affcc45602.PNG)

**Release version**
0.31.0

**Attachments**
[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/5248832/logs_hummingbot.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak7cg) by [Unito](https://www.unito.io)

**Comment by sigit2306** [comment]
There's similar behavior of ctrl+x trying to exit config from `connect celo` command when prompted `Enter your celo account address` pressing ctrl+x does not instantly exit config but still prompted with `Enter you celo account password` pressing ctrl+x once again successfully exit config.
![image](https://user-images.githubusercontent.com/12313129/93848184-0f1bca80-fcd3-11ea-93b1-d614d4dacd18.png)

**Comment by PtrckM** [comment]
Similar issue on `generate_certs` when trying to exit the configuration prompt where bot will continue to generate a certificate.

![image](https://user-images.githubusercontent.com/54516858/103124707-8c385080-46c3-11eb-9fac-c575f16cb684.png)
![image](https://user-images.githubusercontent.com/54516858/103124747-b25df080-46c3-11eb-9a00-a95d399842aa.png)
