### ISSUE TITLE
[Feature] Support multiple trading pairs from one exchange

### ISSUE THREAD

**Issue by Tburm** [hummingbot/hummingbot#2392]
**Feature Suggestion**
I would like support for multiple trading pairs from the same exchange. Currently you can only track one trading pair on an exchange, which limits potential trading strategies. 

**Impact**
The desired behavior will allow me to create triangular arbitrage strategies. One example is altering the `celo-arb` strategy to support triangular arbitrage. Celo only supports selling on the exchange for cUSD, so the current strategy only supports trading CELO-USD on an exchange and CELO-cUSD on a Celo node. I would like to trade CELO-cUSD on a Celo node and trade CELO-BTC + BTC-USD on an exchange.

**Additional context**
The example above is a custom strategy, so for simplicity I plugged the following config into the `arbitrage` strategy. This would not lead to an actual arbitrage opportunity, but this contrived example will show the behavior of specifying the same market twice.

```
#####################################
###   Arbitrage strategy config   ###
#####################################

template_version: 4
strategy: arbitrage

# The following configuations are only required for the
# arbitrage strategy

# Exchange and token parameters
primary_market: bittrex
secondary_market: bittrex
primary_market_trading_pair: BTC-USD
secondary_market_trading_pair: ETH-USD

# Minimum profitability target required to place an order
# Expressed in percentage value, e.g. 1 = 1% target profit
min_profitability: 100.0

# The conversion rate for secondary base asset value to primary base asset value.
# e.g. if primary base asset is USD, secondary is DAI and 1 USD is worth 1.25 DAI, "
# the conversion rate is 0.8 (1 / 1.25)
secondary_to_primary_base_conversion_rate: 1.0

# The conversion rate for secondary quote asset value to primary quote asset value.
# e.g. if primary quote asset is USD, secondary is DAI and 1 USD is worth 1.25 DAI, "
# the conversion rate is 0.8 (1 / 1.25)
secondary_to_primary_quote_conversion_rate: 1.0

# For more detailed information, see:
# https://docs.hummingbot.io/strategies/arbitrage/#configuration-parameters
```

The resulting logs:

```
2020-09-28 00:52:11,941 - 1 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2020-09-28 00:52:12,018 - 1 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2020-09-28 00:52:12,019 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Subscribed to BTC-USD deltas
2020-09-28 00:52:12,019 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Subscribed to ETH-USD deltas
2020-09-28 00:52:12,235 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Websocket connection started...
2020-09-28 00:52:12,267 - 1 - hummingbot.core.management.console - INFO - Started debug console at localhost:8211.
2020-09-28 00:52:12,381 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Saved BTC-USD snapshots.
2020-09-28 00:52:12,569 - 1 - hummingbot.connector.exchange.bittrex.bittrex_order_book_tracker - INFO - Initialized order book for BTC-USD. 1/2 completed.
2020-09-28 00:52:13,000 - 1 - hummingbot.strategy.arbitrage.arbitrage - INFO - Markets are ready. Trading started.
2020-09-28 00:52:13,001 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 192, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_tick
    self.c_process_market_pair(market_pair)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 317, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_process_market_pair
    self.c_calculate_arbitrage_top_order_profitability(market_pair)
  File "hummingbot/strategy/arbitrage/arbitrage.pyx", line 254, in hummingbot.strategy.arbitrage.arbitrage.ArbitrageStrategy.c_calculate_arbitrage_top_order_profitability
    market_pair.second.get_price(False)
  File "/home/hummingbot/hummingbot/strategy/market_trading_pair_tuple.py", line 37, in get_price
    return self.market.get_price(self.trading_pair, is_buy)
  File "hummingbot/connector/exchange_base.pyx", line 203, in hummingbot.connector.exchange_base.ExchangeBase.get_price
    return self.c_get_price(trading_pair, is_buy)
  File "hummingbot/connector/exchange_base.pyx", line 100, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
    OrderBook order_book = self.c_get_order_book(trading_pair)
  File "hummingbot/connector/exchange/paper_trade/paper_trade_market.pyx", line 899, in hummingbot.connector.exchange.paper_trade.paper_trade_market.PaperTradeMarket.c_get_order_book
    raise ValueError(f"No order book exists for '{trading_pair}'.")
ValueError: No order book exists for 'ETH-USD'.
```

In this example the `BTC-USD` trading pair is initialized, but the `ETH-USD` market is not being tracked.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rak87z) by [Unito](https://www.unito.io)

**Comment by cryptonit** [comment]
i have a similar usecase

arbitrage between 2 pairs on same exchange

but additional to fix beeing able set up 2 pairs on same exchange i also need the ability

to modify 

secondary_to_primary_base_conversion_rate: 1.0
and/or
secondary_to_primary_quote_conversion_rate: 1.0

dynamic based on a by myself provided api

it would be good if u add script support so we can code solutions for such usecases by ourself

needed would be a way to read a value from an cuspm api via script
and
ability to set additiona values which are in real time (without stop start of strategy) adjusted via script
example

secondary_to_primary_base_conversion_rate
secondary_to_primary_quote_conversion_rate

similar as we able ajust this values via script
https://github.com/CoinAlpha/hummingbot/blob/master/scripts/update_parameters_test_script.py

**Comment by Tburm** [comment]
That sounds like a separate issue, but would definitely complement this change. Right now the script function is only available in the `pure_market_making` strategy. If it was available in the `arbitrage` strategy your idea would be possible.
