### ISSUE TITLE
[BUG] silly commands not working on Windows Binary

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#2477]
**Describe the bug**

* Animation unable to display throwing error `Unhandled error in background task: [Errno 2] No such file or directory:`

**Steps To Reproduce**

* launch HB
* type `hummingbot`

```
2020-10-14 20:11:08,828 - 14208 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [Errno 2] No such file or directory: 'hummingbot/client/command/silly_resources/hb_with_flower_1.txt'
Traceback (most recent call last):
  File "hummingbot\core\utils\async_utils.py", line 9, in safe_wrapper
  File "hummingbot\client\command\silly_commands.py", line 34, in silly_hummingbot
FileNotFoundError: [Errno 2] No such file or directory: 'hummingbot/client/command/silly_resources/hb_with_flower_1.txt'
2020-10-14 20:12:28,082 - 14980 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 
Traceback (most recent call last):
  File "hummingbot\core\utils\async_call_scheduler.py", line 80, in _coro_scheduler
asyncio.exceptions.CancelledError
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/95988075-ebbfe780-0e5a-11eb-9a8d-7908f3c9aa4d.png)

**Release version**
0.32.0

**Workaround**

* As a workaround create the folder and manually copy the files as shown below
![image](https://user-images.githubusercontent.com/54516858/95988182-1ad65900-0e5b-11eb-9a6d-9e97a76c50ce.png)

![image](https://user-images.githubusercontent.com/54516858/95988198-20cc3a00-0e5b-11eb-8ac6-cd0776440e11.png)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakh23) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Closing ticket since Binary has been removed on version 1.0.0
