### ISSUE TITLE
[BUG] Unable to use mysql as database 

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#2510]
**Describe the bug**

* Unable to use mysql as database for hummingbot. Reference: [Advance Database Configuration](https://docs.hummingbot.io/operation/adv-command-ref/#advanced-database-configuration)

**Steps To Reproduce**

* install and start mysql
  create DB, assign user and password
  install hummingbot from source build
  edit `conf/conf_global.yml`
  launch hummingbot after entering password bot will crashed with the following errors:

```
Traceback (most recent call last):
  File "bin/hummingbot.py", line 75, in <module>
    ev_loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "bin/hummingbot.py", line 50, in main
    hb = HummingbotApplication.main_application()
  File "/home/patrick/hb-sql/hummingbot/client/hummingbot_application.py", line 63, in main_application
    cls._main_app = HummingbotApplication()
  File "/home/patrick/hb-sql/hummingbot/client/hummingbot_application.py", line 96, in __init__
    self.trade_fill_db: SQLConnectionManager = SQLConnectionManager.get_trade_fills_instance()
  File "/home/patrick/hb-sql/hummingbot/model/sql_connection_manager.py", line 65, in get_trade_fills_instance
    cls._scm_trade_fills_instance = SQLConnectionManager(SQLConnectionType.TRADE_FILLS)
  File "/home/patrick/hb-sql/hummingbot/model/sql_connection_manager.py", line 108, in __init__
    engine_options)
  File "/home/patrick/hb-sql/hummingbot/model/sql_connection_manager.py", line 87, in get_db_engine
    return create_engine(f"{dialect}://{username}:{password}@{host}:{port}/{db_name}")
  File "/home/patrick/.local/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/patrick/.local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/patrick/.local/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 118, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'
```

```
mysql    26770  0.1  0.9 1774264 79920 ?       Ssl  18:07   0:04 /usr/sbin/mysqld
```

```
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      26770/mysqld
```

```
# Advanced database options, currently supports SQLAlchemy's included dialects
# Reference: https://docs.sqlalchemy.org/en/13/dialects/
db_engine: mysql
db_host: 127.0.0.1
db_port: '3306'
db_username: hbuser
db_password: hbpassword
db_name: hbsql
```

* Unable to install [missing module](https://pypi.org/project/MySQL-python/)

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting MySQLdb
  Could not find a version that satisfies the requirement MySQLdb (from versions: )
No matching distribution found for MySQLdb
```

**Release version**
0.32.0

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakj7q) by [Unito](https://www.unito.io)

**Comment by djspacedevil** [comment]
Hello,

i install mysql-connector-python
`pip install mysql-connector-python`

And change in the global_conf.yml the db_engine to 
`mysql+mysqlconnector`

After that, i become a mysql Error
