### ISSUE TITLE
Bittrex - Freezing on Raspberry Pi

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#2626]
**Describe the bug**
Immediately froze after starting the bot,

**Steps To Reproduce**
install hummingbot using rpi source build
create pmm as strategy
select bittrex as exchange
set spread and order refresh time
start bot immediately hangs

```
2020-11-13 19:22:13,808 - 27171 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Subscribed to ETH-USDT deltas
2020-11-13 19:22:14,272 - 27171 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Websocket connection started...
2020-11-13 19:22:14,273 - 27171 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - ERROR - Unexpected error when listening on socket stream.
Traceback (most recent call last):
  File "/home/pi/hummingbot/hummingbot/connector/exchange/bittrex/bittrex_api_order_book_data_source.py", line 177, in listen_for_order_book_diffs
    async for raw_message in self._socket_stream():
  File "/home/pi/hummingbot/hummingbot/connector/exchange/bittrex/bittrex_api_order_book_data_source.py", line 200, in _socket_stream
    yield await conn.msg_queue.get()
AttributeError: 'Connection' object has no attribute 'msg_queue'
2020-11-13 19:22:14,276 - 27171 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Subscribed to ETH-USDT deltas

```

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/99067347-85f38680-25e5-11eb-95ce-b305830161c6.png)

**Release version**
0.33.0

**Attachments**
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/5536485/logs_conf_pure_mm_1.log)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1raktjw) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Getting the same issue when running with Bittrex on Hummingbot with RaspberryPi

Steps:
1. Create PMM strategy
2. Connect Bittrex API
3. Start bot then it will not respond.

Version:
 0.36.0

```
2021-02-24 23:44:48,277 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Websocket connection started...
2021-02-24 23:44:48,278 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - ERROR - Unexpected error when listening on socket stream.
Traceback (most recent call last):
  File "/hummingbot/connector/exchange/bittrex/bittrex_api_order_book_data_source.py", line 177, in listen_for_order_book_diffs
    async for raw_message in self._socket_stream():
  File "/hummingbot/connector/exchange/bittrex/bittrex_api_order_book_data_source.py", line 200, in _socket_stream
    yield await conn.msg_queue.get()
AttributeError: 'Connection' object has no attribute 'msg_queue'
2021-02-24 23:44:48,279 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Subscribed to ADA-USD deltas
2021-02-24 23:44:49,125 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Websocket connection started...
2021-02-24 23:44:49,125 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - ERROR - Unexpected error when listening on socket stream.
Traceback (most recent call last):
  File "/hummingbot/connector/exchange/bittrex/bittrex_api_order_book_data_source.py", line 177, in listen_for_order_book_diffs
    async for raw_message in self._socket_stream():
  File "/hummingbot/connector/exchange/bittrex/bittrex_api_order_book_data_source.py", line 200, in _socket_stream
    yield await conn.msg_queue.get()
AttributeError: 'Connection' object has no attribute 'msg_queue'
2021-02-24 23:44:49,126 - 1 - hummingbot.connector.exchange.bittrex.bittrex_api_order_book_data_source - INFO - Subscribed to ADA-USD deltas
```
![image](https://user-images.githubusercontent.com/73840223/109082786-8e5c7100-773f-11eb-8708-68794a964bf1.png)

**Comment by djspacedevil** [comment]
I have the same error.

[logs_conf_pure_mm_1_matic_bittrex.log](https://github.com/CoinAlpha/hummingbot/files/6071744/logs_conf_pure_mm_1_matic_bittrex.log)

**Comment by djspacedevil** [comment]
Hello, i found the problem. Hummingbot use an different git branch for the package signalr-client-aio
To fix this we must replace it. 
`pip install --upgrade --force-reinstall git+https://github.com/CoinAlpha/python-signalr-client`

**Comment by 3cl1ps** [comment]
hey, any got news on this ?
tried to send the pip install signalr to the container wihtout success.

**Comment by PtrckM** [comment]
The issue seems to self resolve and is no longer being encountered on version `dev-1.0.0`

<img width="1679" alt="Screen Shot 2022-01-19 at 10 16 34 AM" src="https://user-images.githubusercontent.com/54516858/150060926-68f768f5-303c-4718-9a5f-45a6831e3b1f.png">

![image](https://user-images.githubusercontent.com/54516858/150060921-1b7cb6f9-bf97-4b1f-a5a6-81dddffa7932.png)
![image](https://user-images.githubusercontent.com/54516858/150061082-a4f3d4a1-61db-4171-8c53-f334055e7268.png)

![image](https://user-images.githubusercontent.com/54516858/150061313-6f17af24-13e0-4de3-a246-68b3ccd7e07a.png)


Note: if you are using conda `Python 3.8.2` or higher versions and getting the issue below during `./install` please update `setup/environment-linux-aarch64.yml` dependency from `cryptography==2.8` to `cryptography==3.1.1`

![image](https://user-images.githubusercontent.com/54516858/150060746-c9af3511-4d0a-4b29-a6bb-591eb3c1a8b8.png)
