### ISSUE TITLE
Hanging Order - Refreshed by max_order_age: Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by jonatasfreitasv** [hummingbot/hummingbot#2820]
**Describe the bug**
Error when hang order is refreshed by max_order_age and wallet not have extra amount then order.
I think this bug occurs because have delay in Exchange to put locked amount to available again and when bot try to put order again, not have balance.

**Steps To Reproduce**

* Have hang order
* In wallet, have no extra amount then order.
* max_order_age try to refresh order and put again.

**Discord username: JonFv**

**Logs**

```
2021-01-09 16:22:31,000 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - Refreshing Sell order with ID - x-XEKWYICX-SHDUT1610207650002551 because it reached maximum order age of 1700.0 seconds.
2021-01-09 16:22:31,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (HARD-USDT) Cancelling the limit order x-XEKWYICX-SHDUT1610207650002551. [clock=2021-01-09 16:22:31+00:00]
2021-01-09 16:22:31,001 - 1 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (HARD-USDT) Creating 1 ask orders at (Size, Price): ['37.74 HARD, 0.6268 USDT']
2021-01-09 16:22:31,158 - 1 - hummingbot.connector.exchange.binance.binance_exchange - INFO - Successfully cancelled order x-XEKWYICX-SHDUT1610207650002551.
2021-01-09 16:22:31,167 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1610209351.0, "order_id": "x-XEKWYICX-SHDUT1610207650002551", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "binance"}
2021-01-09 16:22:31,450 - 1 - hummingbot.script.script_iterator - INFO - received: CallNotify {'msg': 'Script status: short_volatility: 0.17%  long_volatility: 0.09% - short:0.001665140288069269835983682 long0.000915702573995562675910205 -- short:0.166514028806926983598368200 long0.091570257399556267591020500'}
2021-01-09 16:22:31,700 - 1 - hummingbot.connector.exchange.binance.binance_exchange - NETWORK - Error submitting SELL LIMIT_MAKER order to Binance for 37.74000000 HARD-USDT 0.62680000.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 848, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.create_order
    order_result = await self.query_api(self._binance_client.create_order, **api_params)
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 228, in query_api
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 240, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    raise ex
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 230, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    return await self._async_scheduler.call_async(partial(func, *args, **kwargs),
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 1201, in create_order
    return self._post('order', True, data=params)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 240, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-2010): Account has insufficient balance for requested action.
2021-01-09 16:22:31,701 - 1 - hummingbot.connector.exchange.binance.binance_exchange - WARNING - APIError(code=-2010): Account has insufficient balance for requested action.
2021-01-09 16:22:32,460 - 1 - hummingbot.script.script_iterator - INFO - received: CallNotify {'msg': 'Script status: short_volatility: 0.17%  long_volatility: 0.09% - short:0.001665140288069269835983682 long0.000915702573995562675910205 -- short:0.166514028806926983598368200 long0.091570257399556267591020500'}
```

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rakxf5) by [Unito](https://www.unito.io)

**Comment by JeremyKono** [comment]
After the error, did the age of your orders refreshed or it did not create the orders?

**Comment by jonatasfreitasv** [comment]
After this error, hang order no created any more...order is canceled for ever.
