### ISSUE TITLE
Command "config binance_markets" converts argument to lower case

### ISSUE THREAD

**Issue by zappra** [hummingbot/hummingbot#3061]
**Describe the bug**
If you use the command, eg. "config binance_markets ALGO-USDT" the pair name will be converted to lower case. This will then trigger an error when running the "trades" command

If you use "config binance_markets" and then enter eg. ALGO-USDT at the prompt it works correctly

**Release version**
dev-0.37.0

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ram917) by [Unito](https://www.unito.io)

**Comment by zappra** [comment]
Similarly, you can enter "algo-usdt" at the prompt and it WON'T be converted to upper case, causing the same error

**Comment by glenntomas** [comment]
Tried to replicate the issue with running `config binance_markets ALGO-USDT`
- Shows pair name is in lowercase
![image](https://user-images.githubusercontent.com/73885708/110846773-23866a80-82e7-11eb-8ee8-0a4f6cf70ebf.png)

- Run `trades` command, throws an error
![image](https://user-images.githubusercontent.com/73885708/110847950-7d3b6480-82e8-11eb-9bc7-e95953db24d2.png)
```
2021-03-11 19:54:27,747 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: APIError(code=-1100): Illegal characters found in parameter 'symbol'; legal range is '^[A-Z0-9-_.]{1,20}$'.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/trades_command.py", line 54, in trades_report
    await self.market_trades_report(connector, days, market)
  File "/home/hummingbot/hummingbot/client/command/trades_command.py", line 60, in market_trades_report
    trades: List[Trade] = await connector.get_my_trades(market, days)
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 1119, in get_my_trades
    trades = await self.get_all_my_trades(trading_pair)
  File "/home/hummingbot/hummingbot/core/utils/__init__.py", line 15, in memoize
    cache[key] = await fn(*args, **kwargs)
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 1113, in get_all_my_trades
    trades = await self.query_api(self._binance_client.get_my_trades,
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 229, in query_api
    async with self._throttler.weighted_task(request_weight=request_weight):
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 241, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    raise ex
  File "hummingbot/connector/exchange/binance/binance_exchange.pyx", line 231, in hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange.query_api
    return await self._async_scheduler.call_async(partial(func, *args, **kwargs),
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 128, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 117, in schedule_async_call
    return await fut
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 80, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 1836, in get_my_trades
    return self._get('myTrades', True, data=params)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 237, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 202, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 197, in _request
    return self._handle_response()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/binance/client.py", line 230, in _handle_response
    raise BinanceAPIException(self.response)
binance.exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'symbol'; legal range is '^[A-Z0-9-_.]{1,20}$'. 
```

- Tried to use "config binance_markets" and then enter eg. ALGO-USDT at the prompt, the `trades` command works correctly

![image](https://user-images.githubusercontent.com/73885708/110849266-0010ef00-82ea-11eb-81db-3abf14e3d51a.png)

**Release version**
dev-0.37.0

[logs_hummingbot.log](https://github.com/CoinAlpha/hummingbot/files/6125750/logs_hummingbot.log)

**Comment by rapcmia** [comment]
Closing ticket since the `binance_markets` parameter is no longer available as part of Binance spot improvements for Hummingbot version 1.0.0, please see this [link](https://hummingbot.org/release-notes/1.0.0/#binance-and-binance-perpetual-improvement)
