### ISSUE TITLE
Digifinex - Random network disconnection

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#3335]
**Describe the bug**
Opening ticket for tracking. Digifinex randomly getting network disconnection however bot recovers and doesn't cause lost order.

```
2021-05-07 10:41:21,007 - 29777 - hummingbot.client.ui.hummingbot_cli - ERROR - Unhandled error in prompt_toolkit: code = 1006 (connection closed abnormally [internal]), no reason
NoneType: None
```

```python
2021-05-08 00:00:02,431 - 29777 - hummingbot.connector.exchange.digifinex.digifinex_websocket - ERROR - Websocket error: 'server rejected WebSocket connection: HTTP 502'
Traceback (most recent call last):
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 50, in connect
    self._client = await websockets.connect(self._WS_URL)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
2021-05-08 00:00:02,431 - 29777 - hummingbot.connector.exchange.digifinex.digifinex_websocket - NETWORK - {"id":1620432002431491,"method":"trades.subscribe","params":["ETH_USDT"]}
2021-05-08 00:00:02,431 - 29777 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - ERROR - Unexpected error.
Traceback (most recent call last):
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 113, in listen_for_trades
    await ws.subscribe("trades", list(map(
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 153, in subscribe
    id = await self.request(category + ".subscribe", channels)
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 149, in request
    return await self._emit(method, data)
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 143, in _emit
    await self._client.send(req)
AttributeError: 'NoneType' object has no attribute 'send'
2021-05-08 00:00:02,496 - 29777 - hummingbot.connector.exchange.digifinex.digifinex_websocket - ERROR - Websocket error: 'server rejected WebSocket connection: HTTP 502'
Traceback (most recent call last):
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 50, in connect
    self._client = await websockets.connect(self._WS_URL)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
2021-05-08 00:00:02,496 - 29777 - hummingbot.connector.exchange.digifinex.digifinex_websocket - NETWORK - {"id":1620432002496761,"method":"depth.subscribe","params":["ETH_USDT"]}
2021-05-08 00:00:02,496 - 29777 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - NETWORK - Unexpected error with WebSocket connection.
Traceback (most recent call last):
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_api_order_book_data_source.py", line 147, in listen_for_order_book_diffs
    await ws.subscribe("depth", list(map(
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 153, in subscribe
    id = await self.request(category + ".subscribe", channels)
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 149, in request
    return await self._emit(method, data)
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_websocket.py", line 143, in _emit
    await self._client.send(req)
AttributeError: 'NoneType' object has no attribute 'send'
2021-05-08 00:00:02,497 - 29777 - hummingbot.connector.exchange.digifinex.digifinex_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 30 seconds. Check network connection.
```

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):

1. Set up any strategy and use Digifinex as your exchange.
1. Start the strategy and run the bot for a while.
1. Monitor or inspect the logs and you will see that there are disconnections happening on random times.
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/117535916-c418b280-b02a-11eb-8e91-484566dd750c.png)

**Release version**
0.38.1

**Attachments**
[logs_conf_pure_mm_1.log](https://github.com/CoinAlpha/hummingbot/files/6445685/logs_conf_pure_mm_1.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ramdpa) by [Unito](https://www.unito.io)

**Comment by sidmontanez** [comment]
Hi @RC-13. I tried to run my bot under Digifinex for about 8 hours and I have not encountered the issue yet.  
![image](https://user-images.githubusercontent.com/78310937/117548942-39f03e80-b06a-11eb-8720-a74f75814270.png)

**Comment by dennisocana** [comment]
@RC-13 are you still getting this error with your bot?

**Comment by RC-13** [comment]
@dennisocana Yes, we still get this on our test bot. The connection error appears randomly, The screenshot is from today (8 min ago)
![image](https://user-images.githubusercontent.com/57189990/127074766-6c5debeb-a961-4920-aad2-9ce931afd617.png)

**Comment by dennisocana** [comment]
@RC-13 please post the configs here as well. I'm checking the logs how the errors affect the bot's expected behavior based on your configuration.

**Comment by RC-13** [comment]
Config has been added. Adding additional details regarding this issue,
Scenario tested:
1. Use different API key: Issue still persists
2. Use different accounts (support and dev account): Didn't encounter the issue
- Both accounts have sufficient assets to place orders on both sides. - No connection issue
- Tried different markets which allow the bot to place orders one-sided. - No connection issue
3. Add balance limit to one of the assets
- It seems that the connection issue appears whenever the bot keeps attempting to submit an order that is below the exchange minimum
- After adding balance limit (balance limit on DOGE token under support account) and let the bot run for a while the network error occur:
![image](https://user-images.githubusercontent.com/57189990/127083532-74a05e35-ab26-4f95-9947-e27958595d87.png)

**Comment by gerald-hb** [comment]
A user from discord (siebenmik#9420) experience the same issue. `config` and `logs` attached
[message.txt](https://github.com/CoinAlpha/hummingbot/files/7192742/message.txt)
[conf.txt](https://github.com/CoinAlpha/hummingbot/files/7192743/conf.txt)

**Comment by MementoRC** [comment]
@cardosofede Is this still an issue?
