### ISSUE TITLE
Loopring - Failed to fetch updates and failed to cancel order

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#3453]
**Describe the bug**
Creating a ticket for tracking. The loopring test test bot keeps getting `Failed to fetch updates on Loopring` or `Failed to fetch tracked Loopring order` and `failed to cancel order` this leads to instances where once order remain active in the bot however it is already been cancelled in the exchange causing the bot not to create new orders.

```python
2021-05-28 04:53:07,000 - 21841 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (LRC-USDT) Creating 2 bid orders at (Size, Price): ['56.509 LRC, 0.4159 USDT', '56.509 LRC, 0.4117 USDT']
2021-05-28 04:53:07,000 - 21841 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (LRC-USDT) Creating 2 ask orders at (Size, Price): ['53.49 LRC, 0.4243 USDT', '53.49 LRC, 0.4285 USDT']
2021-05-28 04:53:08,834 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Created ordertype.limit tradetype.buy order buy-LRC-USDT-1622177587000804 for 56.509 LRC-USDT.
2021-05-28 04:53:08,843 - 21841 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622177588000, "type": "OrderType.LIMIT", "trading_pair": "LRC-USDT", "amount": "56.509", "price": "0.4159", "order_id": "buy-LRC-USDT-1622177587000804", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "loopring"}
2021-05-28 04:53:08,844 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Created ordertype.limit tradetype.sell order sell-LRC-USDT-1622177587001046 for 53.490 LRC-USDT.
2021-05-28 04:53:08,852 - 21841 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622177588000, "type": "OrderType.LIMIT", "trading_pair": "LRC-USDT", "amount": "53.490", "price": "0.4285", "order_id": "sell-LRC-USDT-1622177587001046", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "loopring"}
2021-05-28 04:53:08,853 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Created ordertype.limit tradetype.buy order buy-LRC-USDT-1622177587000857 for 56.509 LRC-USDT.
2021-05-28 04:53:08,861 - 21841 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622177588000, "type": "OrderType.LIMIT", "trading_pair": "LRC-USDT", "amount": "56.509", "price": "0.4117", "order_id": "buy-LRC-USDT-1622177587000857", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "loopring"}
2021-05-28 04:53:08,944 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Created ordertype.limit tradetype.sell order sell-LRC-USDT-1622177587001012 for 53.490 LRC-USDT.
2021-05-28 04:53:08,954 - 21841 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622177588000, "type": "OrderType.LIMIT", "trading_pair": "LRC-USDT", "amount": "53.490", "price": "0.4243", "order_id": "sell-LRC-USDT-1622177587001012", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "loopring"}
2021-05-28 04:53:40,613 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Issue with Loopring API GET to /api/v3/order, response: 
2021-05-28 04:53:40,613 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - 
2021-05-28 04:53:40,614 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Failed to fetch tracked Loopring order sell-LRC-USDT-1622177587001012(14576372452430371941455464045700846420874668963345007359436669569669726034322) from api (code: {'hash': '9646378989383967846606365443081822170025127883798090908225478351894858740052', 'clientOrderId': 'buy-LRC-USDT-1622177587000857', 'side': 'BUY', 'market': 'LRC-USDT', 'price': '0.4116', 'volumes': {'baseAmount': '56509000000000000000', 'quoteAmount': '23264755', 'baseFilled': '0', 'quoteFilled': '0', 'fee': '0'}, 'validity': {'start': 1622177588, 'end': 1625197987}, 'orderType': 'LIMIT_ORDER', 'tradeChannel': 'ORDER_BOOK', 'status': 'processing', 'filledSize': '0', 'filledVolume': '0', 'filledFee': '0'})
2021-05-28 04:53:40,615 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Failed to fetch updates on Loopring. Check network connection.
2021-05-28 04:53:40,615 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - 'resultInfo'
2021-05-28 04:53:50,835 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Issue with Loopring API GET to /api/v3/order, response: 
2021-05-28 04:53:50,835 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - 
2021-05-28 04:53:50,835 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Failed to fetch tracked Loopring order sell-LRC-USDT-1622177587001046(15963384040018701919464908584843175555213539998702853602442453249690110979331) from api (code: {'hash': '14576372452430371941455464045700846420874668963345007359436669569669726034322', 'clientOrderId': 'sell-LRC-USDT-1622177587001012', 'side': 'SELL', 'market': 'LRC-USDT', 'price': '0.4243', 'volumes': {'baseAmount': '53490000000000000000', 'quoteAmount': '22695807', 'baseFilled': '0', 'quoteFilled': '0', 'fee': '0'}, 'validity': {'start': 1622177588, 'end': 1625197987}, 'orderType': 'LIMIT_ORDER', 'tradeChannel': 'ORDER_BOOK', 'status': 'processing', 'filledSize': '0', 'filledVolume': '0', 'filledFee': '0'})
2021-05-28 04:53:50,836 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Failed to fetch updates on Loopring. Check network connection.
2021-05-28 04:53:50,837 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - 'resultInfo'
2021-05-28 04:54:07,001 - 21841 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (LRC-USDT) Cancelling the limit order buy-LRC-USDT-1622177587000804. [clock=2021-05-28 04:54:07+00:00]
2021-05-28 04:54:07,002 - 21841 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (LRC-USDT) Cancelling the limit order buy-LRC-USDT-1622177587000857. [clock=2021-05-28 04:54:07+00:00]
2021-05-28 04:54:07,002 - 21841 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (LRC-USDT) Cancelling the limit order sell-LRC-USDT-1622177587001012. [clock=2021-05-28 04:54:07+00:00]
2021-05-28 04:54:07,002 - 21841 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (LRC-USDT) Cancelling the limit order sell-LRC-USDT-1622177587001046. [clock=2021-05-28 04:54:07+00:00]
2021-05-28 04:54:08,453 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Successfully cancelled order buy-LRC-USDT-1622177587000804
2021-05-28 04:54:08,462 - 21841 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622177648.0, "order_id": "buy-LRC-USDT-1622177587000804", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "loopring"}
2021-05-28 04:54:08,494 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Successfully cancelled order sell-LRC-USDT-1622177587001012
2021-05-28 04:54:08,503 - 21841 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622177648.0, "order_id": "sell-LRC-USDT-1622177587001012", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "loopring"}
2021-05-28 04:54:08,568 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Successfully cancelled order buy-LRC-USDT-1622177587000857
2021-05-28 04:54:08,577 - 21841 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622177648.0, "order_id": "buy-LRC-USDT-1622177587000857", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "loopring"}
2021-05-28 04:54:08,785 - 21841 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Successfully cancelled order sell-LRC-USDT-1622177587001046
2021-05-28 04:54:08,793 - 21841 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1622177648.0, "order_id": "sell-LRC-USDT-1622177587001046", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "loopring"}
```
```python
2021-11-24 22:19:11,393 - 16316 - hummingbot.connector.exchange.loopring.loopring_exchange - WARNING - Failed to cancel order buy-ETH-USDT-1637750326800254
2021-11-24 22:19:11,393 - 16316 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - name 'message' is not defined
2021-11-24 22:19:11,393 - 16316 - hummingbot.connector.exchange.loopring.loopring_api_order_book_data_source - ERROR - Unexpected error with WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/http.py", line 112, in read_response
    status_line = await read_line(stream)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/http.py", line 192, in read_line
    raise EOFError("line without CRLF")
EOFError: line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/client.py", line 192, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/http.py", line 114, in read_response
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/loopring/hummingbot/connector/exchange/loopring/loopring_api_order_book_data_source.py", line 167, in listen_for_order_book_diffs
    async with websockets.connect(f"{WS_URL}?wsApiKey={ws_key}") as ws:
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/client.py", line 604, in __aenter__
    return await self
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/client.py", line 629, in __await_impl__
    await protocol.handshake(
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/client.py", line 382, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/websockets/legacy/client.py", line 198, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
2021-11-24 22:19:13,678 - 16316 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - Issue with Loopring API DELETE to api/v3/order, response: 
2021-11-24 22:19:13,678 - 16316 - hummingbot.connector.exchange.loopring.loopring_exchange - INFO - {"resultInfo":{"code":100001,"message":"order in status CANCELLED can't be cancelled"}}
```
**Steps To Reproduce**

1. Create a basic pure market-making strategy and start the bot.
2. Monitor the log pane whenever a cycle ends, the first cycle may run normally then the next cycle will display an error fetching update or alternately.
3. To see the stuck order, leave the bot running for long period 
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/119931236-9680b280-bfb3-11eb-85ee-fb2409677d24.png)

**Release version**
0.39.0 and 0.45.0

**Attachments**
[logs_loopring_lrc-usdt.log](https://github.com/CoinAlpha/hummingbot/files/6558271/logs_loopring_lrc-usdt.log)
[loopring-logs.zip](https://github.com/CoinAlpha/hummingbot/files/7599130/loopring-logs.zip)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rammez) by [Unito](https://www.unito.io)

**Comment by MementoRC** [comment]
@cardosofede Status?
