### ISSUE TITLE
Unable to run balancer or uniswap using docker

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#4002]
**Describe the bug**
- unable to start uniswap or balancer (related issue: https://github.com/CoinAlpha/gateway-api/issues/139)

**Steps To Reproduce**
- use `./create.sh` to create and start hummingbot client, choose latest or development
  - setup ethereum and generate certificate for gateway
- use `./create-gateway.sh` to create and start gateway for balancer/uniswap, choose latest or development
  - with enabled or disabled gas station

- balancer
```
2021-08-26 05:13:34,498 - 1 - hummingbot.connector.connector.balancer.balancer_connector - NETWORK - Error getting quote price for WETH-DAI  sell order for 0.03 amount.
Traceback (most recent call last):
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/cachetools/cache.py", line 39, in __getitem__
    return self.__data[key]
KeyError: "((<hummingbot.connector.connector.balancer.balancer_connector.BalancerConnector object at 0x7f2ecd79fc40>, 'WETH-DAI', False, Decimal('0.03')), {})"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/__init__.py", line 15, in memoize
    return cache[key]
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/cachetools/ttl.py", line 84, in __getitem__
    return cache_getitem(self, key)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/cachetools/cache.py", line 41, in __getitem__
    return self.__missing__(key)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/cachetools/cache.py", line 68, in __missing__
    raise KeyError(key)
KeyError: "((<hummingbot.connector.connector.balancer.balancer_connector.BalancerConnector object at 0x7f2ecd79fc40>, 'WETH-DAI', False, Decimal('0.03')), {})"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/connector/balancer/balancer_connector.py", line 216, in get_quote_price
    exceptions = check_transaction_exceptions(account_standing)
  File "/home/hummingbot/hummingbot/core/utils/ethereum.py", line 60, in check_transaction_exceptions
    if eth_balance < gas_cost:
TypeError: '<' not supported between instances of 'decimal.Decimal' and 'NoneType'
2021-08-26 05:13:34,498 - 1 - hummingbot.connector.connector.balancer.balancer_connector - WARNING - '<' not supported between instances of 'decimal.Decimal' and 'NoneType'

```

- uniswap
```
2021-08-26 05:15:45,744 - 1 - hummingbot.connector.connector.uniswap.uniswap_connector - INFO - Missing data from price result. Incomplete return result for (dict_keys(['network', 'timestamp', 'latency', 'base', 'quote', 'amount', 'expectedAmount', 'price', 'gasLimit', 'gasCost', 'trade']))
2021-08-26 05:15:47,837 - 1 - hummingbot.connector.connector.uniswap.uniswap_connector - INFO - Missing data from price result. Incomplete return result for (dict_keys(['network', 'timestamp', 'latency', 'base', 'quote', 'amount', 'expectedAmount', 'price', 'gasLimit', 'gasCost', 'trade']))
2021-08-26 05:15:47,837 - 1 - hummingbot.strategy.amm_arb.amm_arb - INFO - No arbitrage opportunity.
```

**Screenshots**
![docker1](https://user-images.githubusercontent.com/54516858/130905340-1acb7302-91f5-446d-8d4f-95080181c738.png)
![docker2](https://user-images.githubusercontent.com/54516858/130905357-f2213829-1765-4e0b-9501-83423cf4caa5.png)
![docker3](https://user-images.githubusercontent.com/54516858/130905362-2e65807d-85e6-4128-8a9c-e834e1bd97b8.png)

- gateway shows NaN on logs
![gw_withgas2](https://user-images.githubusercontent.com/54516858/130905499-69c9863f-b269-4bd9-9eef-826269c9294a.png)

**Release version**
0.42.0 & dev-0.43.0 / 0.8.0 & 0.9.0

**Attachments**
[belenser.zip](https://github.com/CoinAlpha/hummingbot/files/7051778/belenser.zip)

**Workaround**
While the gateway and client both running, copy template for https://github.com/CoinAlpha/gateway-api/blob/master/conf/global_conf.yml.example to `hummingbot_conf/global_conf.yml` and edit the environment to suit your needs then for the path of logs and certs change it to just: 

```
CERT_PATH: ./certs
LOG_PATH: ./logs
```
![image](https://user-images.githubusercontent.com/54516858/130908611-2ec09393-441c-4c79-a01d-f29a09d2cca7.png)
![image](https://user-images.githubusercontent.com/54516858/130907860-a00a7c66-9d3f-489d-bf1d-248329c50264.png)

**Comment by PtrckM** [comment]
fix on gateway development and download the new [create-script.sh](https://github.com/CoinAlpha/hummingbot/pull/4214)
