### ISSUE TITLE
NDAX - Failing to cancel order due to rate-limiting

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4224]
**Describe the bug**
Opening ticket for tracking:
The NDAX test bot encounter cancellation issue after running for about 2 days, this results to orphaning the orders in the exchange. It seems that it was triggered by attempts to submit an order that is below the exchange rate limit and as well as disconnections.

```python
2021-09-20 06:35:06,002 - 29842 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Failed to cancel order - 7771631881502002117. Order not yet created. This is most likely due to rate-limiting.
Traceback (most recent call last):
  File "/home/ubuntu/ndax/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/ndax/hummingbot/connector/exchange/ndax/ndax_exchange.py", line 541, in _execute_cancel
    raise NdaxInFlightOrderNotCreated(
hummingbot.connector.exchange.ndax.ndax_in_flight_order.NdaxInFlightOrderNotCreated: Failed to cancel order - 7771631881502002117. Order not yet created. This is most likely due to rate-limiting.
```

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):

1. Create a pure market making strategy or Avellaneda market making strategy
1. Enable hanging order 
1. Start the bot and leave it running for about 2 days and inspect after.

**Screenshots**

![ndax-fail-to-clear-order](https://user-images.githubusercontent.com/57189990/133965375-c01a6c47-6e61-4517-8807-466d9aefe21a.png)
![image](https://user-images.githubusercontent.com/57189990/133965444-7a232d5d-a880-4eed-bacf-5979ab96d6b6.png)

**Release version**
0.43.1

**Attachments**

[ndax-logs.zip](https://github.com/CoinAlpha/hummingbot/files/7193982/ndax-logs.zip)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1ran60k) by [Unito](https://www.unito.io)

**Comment by rolandgem** [comment]
any updates on this? @dennisocana @RC-13

**Comment by rapcmia** [comment]
NDAX has been removed from supported connectors
