### ISSUE TITLE
Probit Global: Failed to authenticate API key

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4484]
**Describe the bug**
Opening ticket for tracking:
While checking the Probit Global testing bot, the bot encounter an issue with cancelling an order, fetching status update, and  multiple websocket retry, all are cause by the API key failing to get authenticated (unauthorized). 

Note: Probit seems to have an ongoing issue on their side at the moment but there are no announcement posted.
```python
2021-10-18 01:51:22,174 - 5954 - hummingbot.connector.exchange.probit.probit_exchange - NETWORK - Unexpected error while fetching trading rules. Error: Error parsing data from https://api.probit.com/api/exchange/v1/market. Error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.probit.com/api/exchange/v1/market')
Traceback (most recent call last):
  File "/home/ubuntu/hitbtc/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 349, in _api_request
    parsed_response = await response.json()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.probit.com/api/exchange/v1/market')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/hitbtc/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 256, in _trading_rules_polling_loop
    await self._update_trading_rules()
  File "/home/ubuntu/hitbtc/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 268, in _update_trading_rules
    market_info = await self._api_request(
  File "/home/ubuntu/hitbtc/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 354, in _api_request
    raise IOError(f"Error parsing data from {path_url}. Error: {str(e)}")
OSError: Error parsing data from https://api.probit.com/api/exchange/v1/market. Error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.probit.com/api/exchange/v1/market')
```
```python
2021-10-18 01:51:22,175 - 5954 - hummingbot.connector.exchange.probit.probit_exchange - WARNING - Could not fetch new trading rules from ProBit. Check network connection.
2021-10-18 01:51:22,217 - 5954 - hummingbot.connector.exchange.probit.probit_api_user_stream_data_source - NETWORK - Unexpected error occured with ProBit WebSocket Connection
2021-10-18 01:51:22,217 - 5954 - hummingbot.connector.exchange.probit.probit_api_user_stream_data_source - INFO - Authenticating to User Stream...
2021-10-18 01:51:22,217 - 5954 - hummingbot.connector.exchange.probit.probit_api_user_stream_data_source - INFO - Error occurred when authenticating to user stream. 
Traceback (most recent call last):
  File "/home/ubuntu/hitbtc/probit/hummingbot/connector/exchange/probit/probit_api_user_stream_data_source.py", line 77, in _authenticate
    await ws.send(ujson.dumps(auth_payload, escape_forward_slashes=False))
AttributeError: 'NoneType' object has no attribute 'send'
2021-10-18 01:51:22,218 - 5954 - hummingbot.connector.exchange.probit.probit_api_user_stream_data_source - ERROR - Unexpected error with Probit WebSocket connection. Retrying after 30 seconds...
```
```python
2021-10-18 02:15:52,359 - 5954 - hummingbot.connector.exchange.probit.probit_exchange - NETWORK - Failed to cancel all orders.
Traceback (most recent call last):
  File "/home/ubuntu/hitbtc/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 338, in _api_request
    headers = await self._probit_auth.get_auth_headers(client)
  File "/home/ubuntu/hitbtc/probit/hummingbot/connector/exchange/probit/probit_auth.py", line 71, in get_auth_headers
    raise e
  File "/home/ubuntu/hitbtc/probit/hummingbot/connector/exchange/probit/probit_auth.py", line 60, in get_auth_headers
    token_resp = await resp.json()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://accounts.probit.com/token')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/hitbtc/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 862, in cancel_all
    await safe_gather(*tasks)
  File "/home/ubuntu/hitbtc/probit/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/hitbtc/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 354, in _api_request
    raise IOError(f"Error parsing data from {path_url}. Error: {str(e)}")
OSError: Error parsing data from https://api.probit.com/api/exchange/v1/cancel_order. Error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://accounts.probit.com/token')
```

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Start a Hummingbot instance
2. Connect Probit Global API information
3. Run `connect` command
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/137665077-b1c7aa6d-6125-4f3f-a5fc-a5347b56362b.png)

**Release version**
0.45.0

**Attachments**
[logs_probit_btc-usdt.log](https://github.com/CoinAlpha/hummingbot/files/7361634/logs_probit_btc-usdt.log)
*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by RC-13** [comment]
It looks like the issue is in the exchange side, upon checking today, we can now connect the API key and confirmed that the key is authenticated and can place order.
![image](https://user-images.githubusercontent.com/57189990/137853622-7c35edcb-ff81-42d3-904b-4b03d3537265.png)
