### ISSUE TITLE
Unexpected error while processing event 106 , 201

### ISSUE THREAD

**Issue by M-Mortaz** [hummingbot/hummingbot#4564]
**Describe the bug**
There is thousands error log as following:
_**1. Unexpected error while processing event 201.**_

```
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/home/hummingbot/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 230, in _did_create_order
    self.save_market_states(self._config_file_path, market, no_commit=True)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 165, in save_market_states
    market_states: Optional[MarketState] = self.get_market_states(config_file_path, market)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 193, in get_market_states
    market_states: Optional[MarketState] = query.one_or_none()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3316, in one_or_none
    ret = list(self)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3388, in __iter__
    self.session._autoflush()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1586, in _autoflush
    self.flush()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2571, in _flush
    flush_context.transaction = transaction = self.begin(
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 947, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 316, in _begin
    self._assert_active()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 288, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) disk I/O error
[SQL: INSERT INTO "Order" (id, config_file_path, strategy, market, symbol, base_asset, quote_asset, creation_timestamp, order_type, amount, leverage, price, last_status, last_update_timestamp, exchange_order_id, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('XLM-USDT', 'conf_pure_mm.yml', 'pure_market_making', 'binance', 'XLM-USDT', 'XLM', 'USDT', 1635133309335, 'LIMIT', 251.3828673, 1, 0.359043, 'BuyOrderCreated', 1635133309335, '313142789', 'NILL')]
(Background on this error at: http://sqlalche.me/e/e3q8) (Background on this error at: http://sqlalche.me/e/7s2a)
```

**_2. Unexpected error while processing event 106._**

```
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/home/hummingbot/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 381, in _did_cancel_order
    self._update_order_status(event_tag, market, evt)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 363, in _update_order_status
    order_record: Optional[Order] = session.query(Order).filter(Order.id == order_id).one_or_none()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3316, in one_or_none
    ret = list(self)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3388, in __iter__
    self.session._autoflush()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1586, in _autoflush
    self.flush()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2479, in flush
    self._flush(objects)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2571, in _flush
    flush_context.transaction = transaction = self.begin(
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 947, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 316, in _begin
    self._assert_active()
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 288, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.OperationalError) disk I/O error
[SQL: INSERT INTO "Order" (id, config_file_path, strategy, market, symbol, base_asset, quote_asset, creation_timestamp, order_type, amount, leverage, price, last_status, last_update_timestamp, exchange_order_id, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('XLM-USD', 'conf_pure_mm.yml', 'pure_market_making', 'binance', 'XLM-USDT', 'XLM', 'USDT', 1635133309335, 'LIMIT', 251.3828673, 1, 0.359043, 'BuyOrderCreated', 1635133309335, '313142789', 'NILL')]
(Background on this error at: http://sqlalche.me/e/e3q8) (Background on this error at: http://sqlalche.me/e/7s2a)
```

**Steps To Reproduce**
I have no idea how to reproduce it. I will try to find it but It is too much complicated.

**Screenshots**
Note: in our cloud, we have 50 bots that are deployed via docker and they are isolated from each other, so divide error count in screenshots by 50 to get just for one bot errors count.
![Screenshot from 2021-10-25 14-39-51](https://user-images.githubusercontent.com/45900756/138686727-e2036fd6-8193-4074-a513-dcde63b69233.png)
Count of errors:
![Screenshot from 2021-10-25 14-54-28](https://user-images.githubusercontent.com/45900756/138686840-e685d952-3d5e-44ff-890c-faba067d176f.png)
**Release version**

V 0.41.0

Machine Info:
Ubuntu 20.04
X64
Docker Swarm on multiple machines.
About 120 core CPU and 320G  ram in total cloud services that Hummingbots deployed on them.
Thanks in advance.

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1rp394q) by [Unito](https://www.unito.io)

**Comment by RC-13** [comment]
@M-Mortaz I'm not sure if this will help however can you check if you have sufficient storage for your docker instance. It appears that the error is due to failing to insert new entries on the sql tables.

**Comment by glenntomas** [comment]
@M-Mortaz Hi! I would like to follow up on this, Is the suggestion of my colleague worked for you? Let us know if it works. Thanks!

**Comment by mahdi13** [comment]
@RC-13 @glenntomas @glenntomas 
Hi, thanks for your responses. I'll continue the conversation on behalf of my partner @M-Mortaz. 

> I'm not sure if this will help however can you check if you have sufficient storage It seems that the error is due to failing to insert new entries on the sql tables.

We've checked the infrastructure. There is no disk space problem.

> Thank you for reaching out. Can you send us your config so we can try to reproduce and check if we will get the same issue. Thank you.

We use a custom connector, alongside binance in a pure market-making strategy. But none of the stack traces are related to our connector nor binance, so we assume it's a core-related issue. Here is the configuration:
![Untitled](https://user-images.githubusercontent.com/600658/142724592-93f00b12-6963-4345-be98-825466d80a9f.png)

**Comment by dennisocana** [comment]
There is a partial fix in this PR https://github.com/hummingbot/hummingbot/pull/5088 specifically for the Error 107.
