### ISSUE TITLE
Probit - bot attempting to cancel filled order

### ISSUE THREAD

**Issue by PtrckM** [hummingbot/hummingbot#4601]
**Describe the bug**

* Bot will try to cancel an order during a filled order event.

**Steps To Reproduce**

1. create pure_mm use probit global as exchange and select any token pair
1. set tight spread (fast fill order)
1. wait for fill order to happen

```
2021-10-28 00:31:35,032 - 3184 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Cancelling the limit order B-ETH-USDT-1635381075001548. [clock=2021-10-28 00:31:35+00:00]
2021-10-28 00:31:35,195 - 3184 - hummingbot.connector.exchange.probit.probit_exchange - NETWORK - Failed to cancel order B-ETH-USDT-1635381075001548: Error fetching data from https://api.probit.com/api/exchange/v1/cancel_order. HTTP status is 400. Message: {'errorCode': 'INVALID_ORDER', 'message': '', 'details': {'order_id': 'not_exist'}} Params: None Data: {'market_id': 'ETH-USDT', 'order_id': '2643303603'}
Traceback (most recent call last):
  File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 561, in _execute_cancel
    await self._api_request(
  File "/home/ubuntu/probit/hummingbot/connector/exchange/probit/probit_exchange.py", line 356, in _api_request
    raise IOError(f"Error fetching data from {path_url}. HTTP status is {response.status}. "
OSError: Error fetching data from https://api.probit.com/api/exchange/v1/cancel_order. HTTP status is 400. Message: {'errorCode': 'INVALID_ORDER', 'message': '', 'details': {'order_id': 'not_exist'}} Params: None Data: {'market_id': 'ETH-USDT', 'order_id': '2643303603'}
2021-10-28 00:31:35,195 - 3184 - hummingbot.connector.exchange.probit.probit_exchange - WARNING - Failed to cancel the order B-ETH-USDT-1635381075001548 on Probit. Check API key and network connection.
2021-10-28 00:31:36,969 - 3184 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Maker buy order of 0.003 ETH filled. [clock=2021-10-28 00:31:36+00:00]
2021-10-28 00:31:36,989 - 3184 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1635381096.0, "order_id": "B-ETH-USDT-1635381075001548", "trading_pair": "ETH-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT_MAKER", "price": "3949.79", "amount": "0.003", "trade_fee": [0.0, [["PROB", "0.05352292807015284"]]], "exchange_trade_id": "ETH-USDT:5822275", "leverage": 1, "position": "NILL", "event_name": "OrderFilledEvent", "event_source": "probit"}
2021-10-28 00:31:36,989 - 3184 - hummingbot.connector.exchange.probit.probit_exchange - INFO - The BUY order B-ETH-USDT-1635381075001548 has completed according to order status API.
2021-10-28 00:31:36,996 - 3184 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Maker buy order B-ETH-USDT-1635381075001548 (0.00300 ETH @ 3949.79 USDT) has been completely filled. [clock=2021-10-28 00:31:36+00:00]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54516858/139167329-5fb21e02-044b-4045-ac0e-637ab207c780.png)

**Release version**
dev-0.45.0

**Attachments**
[probit.zip](https://github.com/CoinAlpha/hummingbot/files/7430152/probit.zip)

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1t7ajxd) by [Unito](https://www.unito.io)

**Comment by rapcmia** [comment]
Tested but unable to replicate. Ticket closed for now and will reopen if happens again
