### ISSUE TITLE
Bitfinex: unexpected error processing multiple level orders

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4633]
**Describe the bug**
When Bitfinex is set to open multiple orders at the same time, the following error keeps coming up:

```python
2021-11-02 08:18:46,516 - 5320 - hummingbot.connector.exchange.bitfinex.bitfinex_exchange - ERROR - Unexpected error while processing event 201.
Traceback (most recent call last):
  File "hummingbot\\core\\pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
  File "hummingbot\\core\\event\\event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
  File "hummingbot\core\event\event_forwarder.py", line 24, in __call__
  File "hummingbot\connector\markets_recorder.py", line 230, in _did_create_order
  File "hummingbot\connector\markets_recorder.py", line 165, in save_market_states
  File "hummingbot\connector\markets_recorder.py", line 193, in get_market_states
  File "site-packages\sqlalchemy\orm\query.py", line 3316, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3388, in __iter__
  File "site-packages\sqlalchemy\orm\session.py", line 1586, in _autoflush
  File "site-packages\sqlalchemy\orm\session.py", line 2479, in flush
  File "site-packages\sqlalchemy\orm\session.py", line 2571, in _flush
  File "site-packages\sqlalchemy\orm\session.py", line 947, in begin
  File "site-packages\sqlalchemy\orm\session.py", line 316, in _begin
  File "site-packages\sqlalchemy\orm\session.py", line 288, in _assert_active
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: Order.id
[SQL: INSERT INTO "Order" (id, config_file_path, strategy, market, symbol, base_asset, quote_asset, creation_timestamp, order_type, amount, leverage, price, last_status, last_update_timestamp, exchange_order_id, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('buy-BTG-USD-1635812286000862', 'bitfinex.yml', 'pure_market_making', 'bitfinex', 'BTG-USD', 'BTG', 'USD', 1635812286562, 'LIMIT', 0.2, 1, 63.03163, 'BuyOrderCreated', 1635812286562, None, 'NILL')]
(Background on this error at: http://sqlalche.me/e/gkpj) (Background on this error at: http://sqlalche.me/e/7s2a)
```

this sometimes leads to some orders failing to get cancelled in the exchange.
Note that if bot is creating a single level, the issue doesn't persist. Also, this behavior appears only in a windows environment.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):

1. Create a pure market making strategy or Avellaneda market making strategy using Bitfinex
1. Set 2 or more order levels and make sure that the available balance will be able to create 2 or more orders
1. Start the strategy and check the log pane.
...

**Screenshots**
![02 11 bitfinex](https://user-images.githubusercontent.com/57189990/139760196-68bd2fbc-811b-4a80-8f72-6c6124ed0607.JPG)

**Release version**
0.44.0

**Attachments**

[logs_bitfinex.log](https://github.com/CoinAlpha/hummingbot/files/7456911/logs_bitfinex.log)

_WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!_

**Optional: your discord username:**

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1u9ccmm) by [Unito](https://www.unito.io)

**Comment by nikspz** [comment]
Closing since this connector version removed in 2.3.0 release
