### ISSUE TITLE
Pure MM - Unable to use Blocktane as price_source_exchange

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#4664]
**Describe the bug**
Unable to run a bot using the pure market making strategy when Blocktane is used as price_source_exchange.

```
2021-11-08 09:24:41,002 - 3713 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 711, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_tick
    proposal = self.c_create_base_proposal()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 740, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.c_create_base_proposal
    buy_reference_price = sell_reference_price = self.get_price()
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 382, in hummingbot.strategy.pure_market_making.pure_market_making.PureMarketMakingStrategy.get_price
    price = price_provider.get_price_by_type(self._price_type)
  File "hummingbot/strategy/order_book_asset_price_delegate.pyx", line 21, in hummingbot.strategy.order_book_asset_price_delegate.OrderBookAssetPriceDelegate.get_price_by_type
    return self._market.get_price_by_type(self._trading_pair, price_type)
  File "hummingbot/connector/exchange_base.pyx", line 270, in hummingbot.connector.exchange_base.ExchangeBase.get_price_by_type
    return (self.c_get_price(trading_pair, True) + self.c_get_price(trading_pair, False)) / Decimal("2")
  File "hummingbot/connector/exchange_base.pyx", line 93, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
    OrderBook order_book = self.c_get_order_book(trading_pair)
  File "hummingbot/connector/exchange/paper_trade/paper_trade_exchange.pyx", line 906, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.c_get_order_book
    raise ValueError(f"No order book exists for '{trading_pair}'.")
ValueError: No order book exists for 'BTC-USDT'.
```

**Steps To Reproduce**
1. Create and run a pure market making strategy
2. Set price_source_exchange to Blocktane

**Screenshots**
<img width="1423" alt="Screen Shot 2021-11-08 at 10 03 08 AM" src="https://user-images.githubusercontent.com/64377055/140674350-c864a891-49af-4e10-a6db-cae0f4ba7cff.png">

**Release version**
development-0.46.0

**Attachments**
Logs and config:
[blocktane.zip](https://github.com/CoinAlpha/hummingbot/files/7493827/blocktane.zip)

**Comment by nikspz** [comment]
still ongoing issue on dev-1.6.0

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/pull/5943 deployed to development branch
connector will be removed on the next release version 1.11
