### ISSUE TITLE
Bitfinex - Errors resulting to stuck orders in the exchange

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#4706]
**Describe the bug**
When running a long term pure market making bot using Bitfinex, there are instances that it'll throw an error resulting to orders getting stuck in the exchange. Sample of the error from one the orders that got stuck:

```python
2021-11-13 18:58:27,432 - 21712 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTG-USD) Creating 1 bid orders at (Size, Price): ['0.3 BTG, 64.45445 USD']
2021-11-13 18:58:33,338 - 21712 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - INFO - Initialized order book for BTG-USD. 1/1 completed.
2021-11-13 18:58:35,823 - 21712 - hummingbot.connector.exchange.bitfinex.bitfinex_api_order_book_data_source - ERROR - 1
2021-11-13 18:58:35,823 - 21712 - hummingbot.connector.exchange.bitfinex.bitfinex_api_order_book_data_source - NETWORK - Unexpected error with WebSocket connection.
Traceback (most recent call last):
  File "/home/ubuntu/bitfinex/hummingbot/connector/exchange/bitfinex/bitfinex_api_order_book_data_source.py", line 429, in listen_for_order_book_diffs
    snapshot = self._prepare_snapshot(trading_pair, [BookStructure(*i) for i in ujson.loads(raw_snapshot)[1]])
KeyError: 1
2021-11-13 18:58:35,824 - 21712 - hummingbot.connector.exchange.bitfinex.bitfinex_api_order_book_data_source - WARNING - Unexpected error with WebSocket connection. Retrying in 30 seconds. Check network connection.
2021-11-13 18:58:36,571 - 21712 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - ERROR - 'float' object is not subscriptable
2021-11-13 18:58:36,571 - 21712 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - NETWORK - Unexpected error processing order book messages for BTG-USD.
Traceback (most recent call last):
  File "/home/ubuntu/bitfinex/hummingbot/connector/exchange/bitfinex/bitfinex_order_book_tracker.py", line 185, in _track_single_book
    d_bids, d_asks = active_order_tracker.convert_snapshot_message_to_order_book_row(
  File "hummingbot/connector/exchange/bitfinex/bitfinex_active_order_tracker.pyx", line 220, in hummingbot.connector.exchange.bitfinex.bitfinex_active_order_tracker.BitfinexActiveOrderTracker.convert_snapshot_message_to_order_book_row
    np_bids, np_asks = self.c_convert_snapshot_message_to_np_arrays(message)
  File "hummingbot/connector/exchange/bitfinex/bitfinex_active_order_tracker.pyx", line 134, in hummingbot.connector.exchange.bitfinex.bitfinex_active_order_tracker.BitfinexActiveOrderTracker.c_convert_snapshot_message_to_np_arrays
    price = Decimal(order[0])
TypeError: 'float' object is not subscriptable
```

**Steps To Reproduce**
1. Create a pure market making bot using Bitfinex

**Screenshots**
<img width="1423" alt="Screen Shot 2021-11-14 at 8 56 26 AM" src="https://user-images.githubusercontent.com/64377055/141663783-f3c69505-68b1-4038-a7f6-007e2199ddbb.png">

<img width="964" alt="Screen Shot 2021-11-14 at 9 00 24 AM" src="https://user-images.githubusercontent.com/64377055/141663788-67836dd9-26f7-4bb8-9a05-673553b07014.png">

**Release version**
development-0.46.0

**Attachments**
Logs and config: [bitfinex.zip](https://github.com/CoinAlpha/hummingbot/files/7533006/bitfinex.zip)

**Comment by 0xferit** [comment]
Any updates on this?

**Comment by nikspz** [comment]
Closing since this connector version removed in 2.3.0 release
