### ISSUE TITLE
Digifinex - lost track of hanging order

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4731]
**Describe the bug**
After encountering a network issue during a cancellation event, the Digifinex test bot lost tracked of the hanging order which is supposed to be re-created after reaching the max order age. The hanging order remain in the client however, it is not recreated in the exchanged causing the logs to get spammed with the following error:

```python
2021-11-15 02:44:50,148 - 5314 - hummingbot.connector.exchange.digifinex.digifinex_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_exchange.py", line 495, in _status_polling_loop
    await safe_gather(
  File "/home/ubuntu/digifinex/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_exchange.py", line 548, in _update_order_status
    raise update_result
  File "/home/ubuntu/digifinex/hummingbot/connector/exchange/digifinex/digifinex_rest_api.py", line 102, in request
    raise IOError(f"{url} API call failed, response: {parsed_response} ({msgs[code]})")
OSError: https://openapi.digifinex.com/v3/spot/order/detail?order_id=cca19a6e7845ba0a40a777d45faa2f83 API call failed, response: {'code': 10008} (Timestamp for this request is invalid)
2021-11-15 02:44:50,148 - 5314 - hummingbot.connector.exchange.digifinex.digifinex_exchange - WARNING - Could not fetch account updates from Digifinex. Check API key and network connection.
```

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making or avellaneda market making strategy using Digifinex as connector
2. Enable hanging order and set the hanging order to a high value, 10% or more.
3. Leave the bot running for couple of days
...

**Screenshots**
![Digifinex-lost-hanging-order](https://user-images.githubusercontent.com/57189990/141890912-d9f0eb88-9a03-4489-8f42-8c33ad22e6be.png)

**Release version**
0.45.0

**Attachments**
[digifinex-logs.zip](https://github.com/CoinAlpha/hummingbot/files/7543161/digifinex-logs.zip)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Connector has been removed
