### ISSUE TITLE
Bitmart subscription to the user stream fails

### ISSUE THREAD

**Issue by mhrvth** [hummingbot/hummingbot#4958]
**Describe the bug**

After sending a request to subscribe to the user stream in the Bitmart connector, the server replies with a rejection and no user stream updates are received:

![image](https://user-images.githubusercontent.com/7762229/147234790-96c375c6-1faf-47eb-aaee-786ccd9987f1.png)

The subscription request is consistent with the Bitmart API specification.

Moreover it appears to cause further problems with inflight orders:

`2021-12-23 12:24:30,032 - 83596 - hummingbot.connector.exchange.bitmart.bitmart_exchange - ERROR - 
Traceback (most recent call last):
  File "hummingbot/connector/in_flight_order_base.pyx", line 88, in hummingbot.connector.in_flight_order_base.InFlightOrderBase.get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/Users/matejhorvath/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matejhorvath/github/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 585, in _status_polling_loop
    await safe_gather(
  File "/Users/matejhorvath/github/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/matejhorvath/github/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 633, in _update_order_status
    order_id = await tracked_order.get_exchange_order_id()
  File "hummingbot/connector/in_flight_order_base.pyx", line 87, in get_exchange_order_id
    async with timeout(GET_EX_ORDER_ID_TIMEOUT):
  File "/Users/matejhorvath/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/Users/matejhorvath/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2021-12-23 12:24:30,050 - 83596 - hummingbot.connector.exchange.bitmart.bitmart_exchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "hummingbot/connector/in_flight_order_base.pyx", line 88, in hummingbot.connector.in_flight_order_base.InFlightOrderBase.get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/Users/matejhorvath/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matejhorvath/github/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 585, in _status_polling_loop
    await safe_gather(
  File "/Users/matejhorvath/github/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/matejhorvath/github/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 633, in _update_order_status
    order_id = await tracked_order.get_exchange_order_id()
  File "hummingbot/connector/in_flight_order_base.pyx", line 87, in get_exchange_order_id
    async with timeout(GET_EX_ORDER_ID_TIMEOUT):
  File "/Users/matejhorvath/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/Users/matejhorvath/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
`

**Steps To Reproduce**

1. Create a pure MM strategy with the Bitmart connector
2. Run the strategy
3. Examine what's being received in the user stream and the logs

**Release version**

0.46

**Comment by mhrvth** [comment]
It seems like the URL is incorrect:

https://developer-pro.bitmart.com/en/ws/spot_ws/overview.html

**Comment by superlazycoder** [comment]
I have corrected this issue on my pull request https://github.com/hummingbot/hummingbot/pull/5353 if someone can check it out, that would be great.

**Comment by rapcmia** [comment]
The fix for this issue has been applied on the release of Hummingbot version 1.5
