### ISSUE TITLE
Bitmart: Inconsistent order creation

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#4963]
**Describe the bug**
Inconsistent order creation is seen while running a pure market-making strategy using Bitmart connector. Whenever a cycle finishes, the next one will throw a message that one order fails to be submitted due to insufficient balance despite in the status it displays that there is an available balance. This can be easily seen when one or both assets can only handle one order at a time. 
```python
2021-12-24 00:00:51,001 - 32118 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTC-USDT) Creating 1 bid orders at (Size, Price): ['0.00035 BTC, 50784.03 USDT']
2021-12-24 00:00:51,001 - 32118 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTC-USDT) Creating 1 ask orders at (Size, Price): ['0.00025 BTC, 50834.84 USDT']
2021-12-24 00:00:51,111 - 32118 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Created LIMIT_MAKER BUY order hummingbot-B-BTC-USDT-1640304051001612 for 0.00035 BTC-USDT.
2021-12-24 00:00:51,126 - 32118 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1640304051.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BTC-USDT", "amount": "0.00035", "price": "50784.03", "order_id": "hummingbot-B-BTC-USDT-1640304051001612", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "bitmart"}
2021-12-24 00:00:51,790 - 32118 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Created LIMIT_MAKER SELL order hummingbot-S-BTC-USDT-1640304051001864 for 0.00025 BTC-USDT.
2021-12-24 00:00:51,802 - 32118 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1640304051.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BTC-USDT", "amount": "0.00025", "price": "50834.84", "order_id": "hummingbot-S-BTC-USDT-1640304051001864", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "SellOrderCreatedEvent", "event_source": "bitmart"}
2021-12-24 00:00:54,001 - 32118 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTC-USDT) Cancelling the limit order hummingbot-B-BTC-USDT-1640304051001612. [clock=2021-12-24 00:00:54+00:00]
2021-12-24 00:00:54,001 - 32118 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTC-USDT) Cancelling the limit order hummingbot-S-BTC-USDT-1640304051001864. [clock=2021-12-24 00:00:54+00:00]
2021-12-24 00:01:00,404 - 32118 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Successfully cancelled order hummingbot-B-BTC-USDT-1640304051001612.
2021-12-24 00:01:00,413 - 32118 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1640304060.0, "order_id": "hummingbot-B-BTC-USDT-1640304051001612", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "bitmart"}
2021-12-24 00:01:00,414 - 32118 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Successfully cancelled order hummingbot-S-BTC-USDT-1640304051001864.
2021-12-24 00:01:00,422 - 32118 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1640304060.0, "order_id": "hummingbot-S-BTC-USDT-1640304051001864", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "bitmart"}
2021-12-24 00:01:01,001 - 32118 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTC-USDT) Creating 1 bid orders at (Size, Price): ['0.00035 BTC, 50784.03 USDT']
2021-12-24 00:01:01,002 - 32118 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (BTC-USDT) Creating 1 ask orders at (Size, Price): ['0.00035 BTC, 50834.84 USDT']
2021-12-24 00:01:01,110 - 32118 - hummingbot.connector.exchange.bitmart.bitmart_exchange - INFO - Created LIMIT_MAKER BUY order hummingbot-B-BTC-USDT-1640304061001982 for 0.00035 BTC-USDT.
2021-12-24 00:01:01,121 - 32118 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1640304061.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "BTC-USDT", "amount": "0.00035", "price": "50784.03", "order_id": "hummingbot-B-BTC-USDT-1640304061001982", "exchange_order_id": null, "leverage": 1, "position": "NILL", "event_name": "BuyOrderCreatedEvent", "event_source": "bitmart"}
2021-12-24 00:01:01,312 - 32118 - hummingbot.connector.exchange.bitmart.bitmart_exchange - NETWORK - Error submitting SELL LIMIT_MAKER order to BitMart for 0.00035 BTC-USDT 50834.84.
Traceback (most recent call last):
  File "/home/ubuntu/bitmart/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 458, in _create_order
    order_result = await self._api_request("post", CONSTANTS.CREATE_ORDER_PATH_URL, api_params, "SIGNED")
  File "/home/ubuntu/bitmart/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 352, in _api_request
    raise IOError(f"Error calling {url}. HTTP status is {response.status}. "
```
**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create a pure market making strategy using Bitmart
2. Make sure that the market use has a balance that can handle the exact order size you specified
3.  Start the strategy
4. Run status --live
5. Monitor both status and the log file

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/147301350-157e187a-334c-47b4-a3bd-e1f6e96cdea7.png)
Note: Due to another known issue, there is a cancellation delay in the gif image.

![BitMart-inconsistent-order-creation](https://user-images.githubusercontent.com/57189990/147301473-8dc30d0a-f759-420f-8d01-3ab39d190a46.gif)

**Release version**
0.46.0

**Attachments**
[logs_conf_pure_mm_1-copy.log](https://github.com/hummingbot/hummingbot/files/7771900/logs_conf_pure_mm_1-copy.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Fix has been applied on the release of Hummingbot version 1.5
