### ISSUE TITLE
cross_exchange_market_making: decimal.InvalidOperation

### ISSUE THREAD

**Issue by phraktle** [hummingbot/hummingbot#4977]
**Describe the bug**
Running a cross-exchange market making strategy on some markets results in `Unexpected error running clock tick`. Details below.

**Steps To Reproduce**
Start cross-exchange mm on the following markets:

```
maker_market: ftx
taker_market: gate_io
maker_market_trading_pair: SLRS-USD
taker_market_trading_pair: SLRS-USDT
```

**Release version**
0.4.6

**Attachments**

Log details:
```
2022-01-04 19:43:11,001 - 401445 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.pyx", line 378, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_tick
    self.c_process_market_pair(market_pair, market_pair_to_active_orders[market_pair])
  File "hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.pyx", line 479, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_process_market_pair
    self.c_check_and_create_new_orders(market_pair, has_active_bid, has_active_ask)
  File "hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.pyx", line 1255, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_check_and_create_new_orders
    ask_size = self.c_get_market_making_size(market_pair, False)
  File "hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.pyx", line 854, in hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making.CrossExchangeMarketMakingStrategy.c_get_market_making_size
    order_amount = min(maker_balance, taker_balance, user_order)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

**Comment by JeremyKono** [comment]
Did you try and change the taker exchange and see if the issue still persists? Seems like people have run into this issue when they choose gate.io as their taker exchange

**Comment by phraktle** [comment]
Yes, seems to work the other way around.

**Comment by rapcmia** [comment]
We suggest to check the XEMM script using v2 strategies that will be added to development 1.27.0
