### ISSUE TITLE
Ascendex can't fetch account updates due to long hummingbot sending long URI (HTTP 414)

### ISSUE THREAD

**Issue by globeone** [hummingbot/hummingbot#5001]
**Describe the bug**
// A clear and concise description of what the bug is.
When running one bot for all 52 Ascendex market pairs for liquidity mining the bot throws an HTTP 414 error with the Ascedex API which stops the communication with Ascedex

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
create a liquidity mining bot with the default configuration
add all 52 trading pairs to the bot
The bot will start to set up the orders with Ascendex then fail with
HTTP status is 414. Message: URI length exceeds the configured limit of 2048 characters
which will repeat until Ascedex breaks the connection with the bot

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: (see attached config file)
2. Start the bot using this command: start
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/10052587/149397612-d5bd5b4a-f667-4474-89ae-71d638c725a8.png)

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
0.46.0
**Attachments**
[conf_liquid_a_usdt.txt](https://github.com/hummingbot/hummingbot/files/7865511/conf_liquid_a_usdt.txt)
[logs_conf_liquid_a_usdt.log.txt](https://github.com/hummingbot/hummingbot/files/7865512/logs_conf_liquid_a_usdt.log.txt)

**Traceback**
`Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 655, in _status_polling_loop
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 704, in _update_order_status
    resp = await self._api_request(
  File "/home/hummingbot/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 412, in _api_request
    raise IOError(f"Error calling {url}. HTTP status is {response.status}. "
OSError: Error calling https://ascendex.com/4/api/pro/v1/cash/order/status. HTTP status is 414. Message: URI length exceeds the configured limit of 2048 characters`

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
Bhagavate bilala#6332

**Comment by globeone** [comment]
![image](https://user-images.githubusercontent.com/10052587/149414039-9c9d1161-cf76-4867-ae90-7ae0d06619bf.png)

So ran some more experiments with this one as well. Am getting this error even only using 8 market pairs so the number of market pairs is irrelevant. Something else is sending an very long order_status request to Ascendex

**Comment by globeone** [comment]
![image](https://user-images.githubusercontent.com/10052587/149414584-55f441b1-aad8-4ffc-8d04-3783a3aff54e.png)

All these Trading started messages lead to and API Limit reached of 50 calls per seconds. There should be a way to set the API call limit manually for these types of cases.

**Comment by globeone** [comment]
A complete wipe of the robot including all the humminbot_files directories and setting a new API key seems to work as a workaround. So Ascendex API keys seem to get 'dirty' after a while.

**Comment by globeone** [comment]
![image](https://user-images.githubusercontent.com/10052587/149418065-2cff6b9d-69b5-4028-8aff-73c1b7810227.png)

**Comment by rapcmia** [comment]
Please be advised that this is related to #5002 in which [Ascendex API docs](https://ascendex.github.io/ascendex-pro-api/#how-to-subscribe) stated that it can only limit 10 markets per connection. You may want to try using multiple API keys or sub-accounts for markets more than 10.
