### ISSUE TITLE
Binance_paper_trade: Failed to initialized

### ISSUE THREAD

**Issue by RC-13** [hummingbot/hummingbot#5017]
**Describe the bug**
When running any strategy using `Binance_paper_trade`, the strategy fails to start due to an ` Unknown error during initialization.`
```python
2022-01-19 22:36:42,847 - 16472 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/home/ubuntu/stage-foundation/hummingbot/strategy/pure_market_making/start.py", line 59, in start
    self._initialize_markets(market_names)
  File "/home/ubuntu/stage-foundation/hummingbot/client/hummingbot_application.py", line 245, in _initialize_markets
    connector = create_paper_trade_market(conn_setting.parent_name, trading_pairs)
  File "/home/ubuntu/stage-foundation/hummingbot/connector/exchange/paper_trade/__init__.py", line 28, in create_paper_trade_market
    return PaperTradeExchange(obt_obj,
  File "hummingbot/connector/exchange/paper_trade/paper_trade_exchange.pyx", line 176, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.__init__
    super(ExchangeBase, self).__init__()
  File "hummingbot/connector/connector_base.pyx", line 51, in hummingbot.connector.connector_base.ConnectorBase.__init__
    self._event_reporter = EventReporter(event_source=self.display_name)
  File "hummingbot/connector/exchange/paper_trade/paper_trade_exchange.pyx", line 226, in hummingbot.connector.exchange.paper_trade.paper_trade_exchange.PaperTradeExchange.display_name.__get__
    return f"{self._order_book_tracker.exchange_name}_PaperTrade"
AttributeError: 'BinanceOrderBookTracker' object has no attribute 'exchange_name'
```
Checked the other paper_trade connectors and confirm that only Binance_paper_trade is having an issue.

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. Create any strategy and use `binance_paper_trade`
2. Start  the strategy

**Screenshots**
![image](https://user-images.githubusercontent.com/57189990/150230789-696dd81b-9588-4a67-969e-3f2a4f778f5d.png)

**Release version**
Hummingbot 1.0.0

**Attachments**

[logs_conf_pure_mm_1.log](https://github.com/hummingbot/hummingbot/files/7901001/logs_conf_pure_mm_1.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Fixed on Hummingbot version 1.0.0
