### ISSUE TITLE
HB requires sqlalchemy<1.4

### ISSUE THREAD

**Issue by oberstet** [hummingbot/hummingbot#5032]
**Describe the bug**

Hummingbot requires `sqlalchemy<1.4` because it does `from sqlalchemy.engine import RowProxy`, which has been removed (or moved?). It works with `sqlalchemy-1.3.24`.

**Steps To Reproduce**

`pip install -e .` from the root directory, and try to start Hummingbot.

**Release version**

Current master.

**Attachments**

```
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/oberstet/hummingbot$ ./bin/hummingbot.py --help
Traceback (most recent call last):
  File "/home/oberstet/scm/oberstet/hummingbot/./bin/hummingbot.py", line 13, in <module>
    from hummingbot.client.hummingbot_application import HummingbotApplication
  File "/home/oberstet/scm/oberstet/hummingbot/hummingbot/client/hummingbot_application.py", line 9, in <module>
    from hummingbot.client.command import __all__ as commands
  File "/home/oberstet/scm/oberstet/hummingbot/hummingbot/client/command/__init__.py", line 1, in <module>
    from .config_command import ConfigCommand
  File "/home/oberstet/scm/oberstet/hummingbot/hummingbot/client/command/config_command.py", line 25, in <module>
    from hummingbot.strategy.pure_market_making import (
  File "/home/oberstet/scm/oberstet/hummingbot/hummingbot/strategy/pure_market_making/__init__.py", line 3, in <module>
    from .pure_market_making import PureMarketMakingStrategy
  File "hummingbot/strategy/pure_market_making/pure_market_making.pyx", line 1, in init hummingbot.strategy.pure_market_making.pure_market_making
    from decimal import Decimal
  File "hummingbot/strategy/order_tracker.pxd", line 7, in init hummingbot.strategy.strategy_base
    cdef class OrderTracker(TimeIterator):
  File "hummingbot/strategy/order_tracker.pyx", line 17, in init hummingbot.strategy.order_tracker
    from .market_trading_pair_tuple import MarketTradingPairTuple
  File "/home/oberstet/scm/oberstet/hummingbot/hummingbot/strategy/market_trading_pair_tuple.py", line 5, in <module>
    from hummingbot.core.data_type.order_book import OrderBook
  File "hummingbot/core/data_type/order_book.pyx", line 28, in init hummingbot.core.data_type.order_book
    from sqlalchemy.engine import RowProxy
ImportError: cannot import name RowProxy
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/oberstet/hummingbot$ python -c "from sqlalchemy.engine import RowProxy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine' (/home/oberstet/cpy39_1/lib/python3.9/site-packages/sqlalchemy/engine/__init__.py)
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/oberstet/hummingbot$ pip show sqlalchemy
Name: SQLAlchemy
Version: 1.4.31
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: /home/oberstet/cpy39_1/lib/python3.9/site-packages
Requires: greenlet
Required-by: hummingbot
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/oberstet/hummingbot$ pip install "sqlalchemy<1.4"
Collecting sqlalchemy<1.4
  Downloading SQLAlchemy-1.3.24-cp39-cp39-manylinux2010_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 3.4 MB/s            
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.4.31
    Uninstalling SQLAlchemy-1.4.31:
      Successfully uninstalled SQLAlchemy-1.4.31
Successfully installed sqlalchemy-1.3.24
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/oberstet/hummingbot$ python -c "from sqlalchemy.engine import RowProxy"
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/oberstet/hummingbot$ ./bin/hummingbot.py --help
```

**Comment by oberstet** [comment]
after retesting a completely fresh venv, there are 2 dependencies missing:

* asyncssh
* ptpython

```
(cpy39_2) (base) oberstet@intel-nuci7:~/scm/oberstet/hummingbot$ ./bin/hummingbot_quickstart.py 
Traceback (most recent call last):
  File "/home/oberstet/scm/oberstet/hummingbot/./bin/hummingbot_quickstart.py", line 30, in <module>
    from hummingbot.core.management.console import start_management_console
  File "/home/oberstet/scm/oberstet/hummingbot/hummingbot/core/management/console.py", line 10, in <module>
    import asyncssh
ModuleNotFoundError: No module named 'asyncssh'

cpy39_2) (base) oberstet@intel-nuci7:~/scm/oberstet/hummingbot$ ./bin/hummingbot_quickstart.py 
Traceback (most recent call last):
  File "/home/oberstet/scm/oberstet/hummingbot/./bin/hummingbot_quickstart.py", line 30, in <module>
    from hummingbot.core.management.console import start_management_console
  File "/home/oberstet/scm/oberstet/hummingbot/hummingbot/core/management/console.py", line 13, in <module>
    from ptpython.repl import embed
ModuleNotFoundError: No module named 'ptpython'
```

https://github.com/oberstet/hummingbot/commit/ae34ca8b4f233446f5a95050455cf30e53d60554

----

remaining warnings for a fully fresh install

```
web3 5.26.0 requires eth-abi<3.0.0,>=2.0.0b6, but you'll have eth-abi 3.0.0 which is incompatible.
web3 5.26.0 requires eth-account<0.6.0,>=0.5.6, but you'll have eth-account 0.6.0 which is incompatible.
web3 5.26.0 requires eth-typing<3.0.0,>=2.0.0, but you'll have eth-typing 3.0.0 which is incompatible.
web3 5.26.0 requires eth-utils<2.0.0,>=1.9.5, but you'll have eth-utils 2.0.0 which is incompatible.
web3 5.26.0 requires websockets<10,>=9.1, but you'll have websockets 10.1 which is incompatible.
tox 3.13.2 requires importlib-metadata<1,>=0.12, but you'll have importlib-metadata 4.10.1 which is incompatible.
tox 3.13.2 requires pluggy<1,>=0.12.0, but you'll have pluggy 1.0.0 which is incompatible.
pytest 4.6.11 requires pluggy<1.0,>=0.12, but you'll have pluggy 1.0.0 which is incompatible.
dydx-v3-python 1.4.5 requires eth-account<0.6.0,>=0.4.0, but you'll have eth-account 0.6.0 which is incompatible.
dydx-python 0.11.3 requires eth-account<0.6.0,>=0.4.0, but you'll have eth-account 0.6.0 which is incompatible.
dydx-python 0.11.3 requires requests==2.22.0, but you'll have requests 2.27.1 which is incompatible.
python-telegram-bot 13.10 requires cachetools==4.2.2, but you'll have cachetools 5.0.0 which is incompatible.
```

**Comment by nikspz** [comment]
It's needed to execute `conda activate hummingbot` before the start

**Comment by oberstet** [comment]
> It's needed to execute `conda activate hummingbot` before the start

this issue was about the _version_ that is required. just try a version >=1.4, and it will fail. anyways, I don't care anymore, not using HB ..
