### ISSUE TITLE
Unexpected error while processing event 107 on partial trades with same trade id

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#5037]
**Describe the bug**
Getting an `Unexpected error while processing event 107` when partial trades are executed on a single order. So far this has been observed to be happening on Kucoin and OKEx but possibly happening to other connectors as well.

```python
2022-01-24 08:44:34,077 - 1249 - hummingbot.connector.exchange.okex.okex_exchange - ERROR - Unexpected error while processing event 107.
Traceback (most recent call last):
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: TradeFill.market, TradeFill.order_id, TradeFill.exchange_trade_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/connector/markets_recorder.py", line 271, in _did_fill_order
    self.save_market_states(self._config_file_path, market, session=session)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/connector/markets_recorder.py", line 157, in save_market_states
    market_states: Optional[MarketState] = self.get_market_states(config_file_path, market, session=session)
  File "/Users/reiniersalazar/hummingbot_c6/hummingbot/connector/markets_recorder.py", line 185, in get_market_states
    market_states: Optional[MarketState] = query.one_or_none()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2836, in one_or_none
    return self._iter().one_or_none()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1640, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 318, in orm_pre_session_exec
    session._autoflush()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2237, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2226, in _autoflush
    self.flush()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1096, in _emit_insert_statements
    c = connection._execute_20(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/reiniersalazar/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: TradeFill.market, TradeFill.order_id, TradeFill.exchange_trade_id
[SQL: INSERT INTO "TradeFill" (config_file_path, strategy, market, symbol, base_asset, quote_asset, timestamp, order_id, trade_type, order_type, price, amount, leverage, trade_fee, exchange_trade_id, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('okex.yml', 'pure_market_making', 'okex', 'DOGE-USDT', 'DOGE', 'USDT', 1642985074000, '93027a12dac34fBC1642985062019119', 'BUY', 'LIMIT_MAKER', 139587, 1, 1, '{"percent": 0.001, "percent_token": null, "flat_fees": []}', '405643983761874949', 'NIL')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Steps To Reproduce**
1. Create and run a pure_mm or avellaneda_mm strategy
2. Set tight spreads and wait for partial trades to happen on a single order

**Screenshots**
<img width="1423" alt="Screen Shot 2022-01-24 at 8 45 05 AM" src="https://user-images.githubusercontent.com/64377055/150714267-a4e59e5c-9506-4169-a062-3f14148aea60.png">

**Release version**
dev-1.0.0

**Attachments**
Logs/config: [partial_107.zip](https://github.com/hummingbot/hummingbot/files/7922264/partial_107.zip)

**Comment by rapcmia** [comment]
Fix has been merged to staging branch `v1.2-staging` for Hummingbot 1.2.0
