### ISSUE TITLE
Unable to run SUKU-USDT on kucoin

### ISSUE THREAD

**Issue by leastchaos** [hummingbot/hummingbot#5105]
**Describe the bug**
// A clear and concise description of what the bug is.
Unable to run suku-usdt on kucoin.
Bot is able to run with other token pair. on same exchange on same API key.

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
Create any strategy and run on SUKU-USDT kucoin

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
tested on v0.46.0 and v1.0.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
Pure market making
```
2022-02-08 23:10:23,334 - 1355581 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-02-08 23:10:23,388 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-02-08 23:10:23,499 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_order_book_tracker - INFO - Initialized order book for SUKU-USDT. 1/1 completed.
2022-02-08 23:10:23,500 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_api_user_stream_data_source - INFO - Connecting to wss://ws-api.kucoin.com/endpoint?token=2neAiuYvAU737TOajb2U3uT8AEZqSWYe0fBD4LoHuXJDSC7gIzJiH4kNTWhCPISWo6nDpAe7aUaNYJAsOHdlCgckKNO9Zbo-h8Oh_Hwr8RWHUJZ2i10VFXwZIngtMdMrjqPnP-biofG7QW8t6LVl0etp02Guva-gJBvJHl5Vs9Y=.UPI6O1_KfSuzpMn8P_gHsw==&acceptUserMessage=true.
2022-02-08 23:10:25,005 - 1355581 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (SUKU-USDT) Creating 1 bid orders at (Size, Price): ['1E+3 SUKU, 0.37537 USDT']
2022-02-08 23:10:25,054 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_exchange - NETWORK - Error submitting buy limit_maker order to Kucoin for 1000.0000 SUKU-USDT 0.37537.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 747, in hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange.execute_buy
    exchange_order_id = await self.place_order(order_id, trading_pair, decimal_amount, True, order_type,
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 715, in place_order
    return str(exchange_order_id["data"]["orderId"])
KeyError: 'data'
2022-02-08 23:10:25,054 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_exchange - WARNING - Failed to submit buy order to Kucoin. Check API key and network connection.
2022-02-08 23:10:25,057 - 1355581 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1644361825.0, "order_id": "buy-SUKU-USDT-1644361825006063", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "kucoin"}
2022-02-08 23:10:27,004 - 1355581 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (SUKU-USDT) Creating 1 bid orders at (Size, Price): ['1E+3 SUKU, 0.37537 USDT']
2022-02-08 23:10:27,043 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_exchange - NETWORK - Error submitting buy limit_maker order to Kucoin for 1000.0000 SUKU-USDT 0.37537.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 747, in hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange.execute_buy
    exchange_order_id = await self.place_order(order_id, trading_pair, decimal_amount, True, order_type,
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 715, in place_order
    return str(exchange_order_id["data"]["orderId"])
KeyError: 'data'
2022-02-08 23:10:27,044 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_exchange - WARNING - Failed to submit buy order to Kucoin. Check API key and network connection.
2022-02-08 23:10:27,046 - 1355581 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1644361827.0, "order_id": "buy-SUKU-USDT-1644361827005071", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "kucoin"}
2022-02-08 23:10:28,064 - 1355581 - hummingbot.client.hummingbot_application - INFO - stop command initiated.

```
Liquidity mining
```
2022-02-08 23:14:38,846 - 1355581 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-02-08 23:14:38,928 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-02-08 23:14:39,214 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_api_user_stream_data_source - INFO - Connecting to wss://ws-api.kucoin.com/endpoint?token=2neAiuYvAU737TOajb2U3uT8AEZqSWYe0fBD4LoHuXJDSC7gIzJiH4kNTWhCPISWo6nDpAe7aUaNYJAsOHdlCgckKNO9Zbo-h8Oh_Hwr8RWHUJZ2i10VFXwZIngtMdMrjqPnP-biofG7QW8t6LVl0ZV4bHmyF-apJBvJHl5Vs9Y=.Mbo517pxF0DdF5y0kwUhDw==&acceptUserMessage=true.
2022-02-08 23:14:39,217 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_order_book_tracker - INFO - Initialized order book for SUKU-USDT. 1/1 completed.
2022-02-08 23:14:39,217 - 1355581 - hummingbot.strategy.liquidity_mining.liquidity_mining - WARNING - kucoin is not ready. Please wait...
2022-02-08 23:14:40,001 - 1355581 - hummingbot.strategy.liquidity_mining.liquidity_mining - WARNING - kucoin is not ready. Please wait...
2022-02-08 23:14:41,008 - 1355581 - hummingbot.strategy.liquidity_mining.liquidity_mining - INFO - kucoin is ready. Trading started.
2022-02-08 23:14:41,009 - 1355581 - hummingbot.strategy.liquidity_mining.liquidity_mining - INFO - (SUKU-USDT) Creating a bid order [ p: 0.37418 s: 533.9681 ] value: 199.80 USDT spread: 1.00%
2022-02-08 23:14:41,067 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_exchange - NETWORK - Error submitting buy limit_maker order to Kucoin for 533.9681 SUKU-USDT 0.37418.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 747, in hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange.execute_buy
    exchange_order_id = await self.place_order(order_id, trading_pair, decimal_amount, True, order_type,
  File "hummingbot/connector/exchange/kucoin/kucoin_exchange.pyx", line 715, in place_order
    return str(exchange_order_id["data"]["orderId"])
KeyError: 'data'
2022-02-08 23:14:41,068 - 1355581 - hummingbot.connector.exchange.kucoin.kucoin_exchange - WARNING - Failed to submit buy order to Kucoin. Check API key and network connection.
2022-02-08 23:14:41,072 - 1355581 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1644362081.0, "order_id": "buy-SUKU-USDT-1644362081009956", "order_type": "OrderType.LIMIT_MAKER", "event_name": "MarketOrderFailureEvent", "event_source": "kucoin"}
2022-02-08 23:14:45,537 - 1355581 - hummingbot.client.hummingbot_application - INFO - stop command initiated.

```
*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by rapcmia** [comment]
Hi, @leastchaos I tried to check this pair on Kucoin today and run both PureMM and LiquidityMM strategies, it seems to be working ok on version 1.0.1, Can you please have another look if this is working for you? Thank you

**Comment by Alkhalifah-blockchain** [comment]
I am facing the same issue on SUKU-BTC and SUKU-USDT on both 0.46 and 1.0.1, it is worth noting that I do not face this issue when running the strategy on my personal computer, but I face it when I run the strategy on AWS.

**Comment by pulkitsharma** [comment]
Facing the same issue

**Comment by pulkitsharma** [comment]
Debugged the issue. It seems the SUKU-BTC and SUKU-USDT pairs are not allowed in the region of my aws instance. I have a US instance. 
I got the following error while submitting the order.
{'code': '400500', 'msg': 'Your located country/region is currently not supported for the trading of this token'}
