### ISSUE TITLE
Bybit Perpetual - Error submitting orders

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#5113]
**Describe the bug**
Failing to submit orders when running a perpetual market making strategy using Bybit Perpetual. Tested on pairs like BTC-USDT, ETH-USDT, LINK-USDT and SOL-USDT but seems to affect all supported pairs.

```python
2022-02-14 11:09:37,010 - 4985 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Creating 1 LIMIT bid orders at (Size, Price): ['0.001 BTC, 41384.5 USDT'] to OPEN position.
2022-02-14 11:09:37,011 - 4985 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BTC-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['0.001 BTC, 42220.5 USDT'] to OPEN position.
2022-02-14 11:09:37,082 - 4985 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1644808177.0, "order_id": "SBCUT17ef635057376cea1bcc9ae42506d92851887f071f8", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "bybit_perpetual"}
2022-02-14 11:09:37,086 - 4985 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_derivative - NETWORK - Error submitting SELL LIMIT order to Bybit Perpetual for 0.001 BTC-USDT 42220.5. Error: Order is rejected by the API. Error Msg: order_link_id fail. Parameters: {'side': 'Sell', 'symbol': 'BTCUSDT', 'qty': Decimal('0.001'), 'time_in_force': 'GoodTillCancel', 'close_on_trigger': False, 'order_link_id': 'SBCUT17ef635057376cea1bcc9ae42506d92851887f071f8', 'reduce_only': False, 'order_type': 'Limit', 'price': Decimal('42220.5'), 'timestamp': '1644808177014', 'api_key': 'chUftVkE9iREm8LzPF', 'sign': '13b7d1e68564e519adee4d3a9005374f44cf0d4d858f16d36c6108bcc9d92f5f'} Parameters: {'side': 'Sell', 'symbol': 'BTCUSDT', 'qty': Decimal('0.001'), 'time_in_force': 'GoodTillCancel', 'close_on_trigger': False, 'order_link_id': 'SBCUT17ef635057376cea1bcc9ae42506d92851887f071f8', 'reduce_only': False, 'order_type': 'Limit', 'price': Decimal('42220.5'), 'timestamp': '1644808177014', 'api_key': 'chUftVkE9iREm8LzPF', 'sign': '13b7d1e68564e519adee4d3a9005374f44cf0d4d858f16d36c6108bcc9d92f5f'}
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot_c2/hummingbot/connector/derivative/bybit_perpetual/bybit_perpetual_derivative.py", line 474, in _create_order
    raise ValueError(f"Order is rejected by the API. "
ValueError: Order is rejected by the API. Error Msg: order_link_id fail. Parameters: {'side': 'Sell', 'symbol': 'BTCUSDT', 'qty': Decimal('0.001'), 'time_in_force': 'GoodTillCancel', 'close_on_trigger': False, 'order_link_id': 'SBCUT17ef635057376cea1bcc9ae42506d92851887f071f8', 'reduce_only': False, 'order_type': 'Limit', 'price': Decimal('42220.5'), 'timestamp': '1644808177014', 'api_key': 'chUftVkE9iREm8LzPF', 'sign': '13b7d1e68564e519adee4d3a9005374f44cf0d4d858f16d36c6108bcc9d92f5f'}
2022-02-14 11:09:37,088 - 4985 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_derivative - WARNING - Error submitting order to Bybit Perpetual. 
2022-02-14 11:09:37,089 - 4985 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1644808177.0, "order_id": "BBCUT17ef635057276cea1bcc9ae42506d92851887f071f8", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "bybit_perpetual"}
2022-02-14 11:09:37,091 - 4985 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_derivative - NETWORK - Error submitting BUY LIMIT order to Bybit Perpetual for 0.001 BTC-USDT 41384.5. Error: Order is rejected by the API. Error Msg: order_link_id fail. Parameters: {'side': 'Buy', 'symbol': 'BTCUSDT', 'qty': Decimal('0.001'), 'time_in_force': 'GoodTillCancel', 'close_on_trigger': False, 'order_link_id': 'BBCUT17ef635057276cea1bcc9ae42506d92851887f071f8', 'reduce_only': False, 'order_type': 'Limit', 'price': Decimal('41384.5'), 'timestamp': '1644808177011', 'api_key': 'chUftVkE9iREm8LzPF', 'sign': '14d0af02c7b3f442c46fa1b5a9efa83619bf5fc11fed35ec59385856a99adaba'} Parameters: {'side': 'Buy', 'symbol': 'BTCUSDT', 'qty': Decimal('0.001'), 'time_in_force': 'GoodTillCancel', 'close_on_trigger': False, 'order_link_id': 'BBCUT17ef635057276cea1bcc9ae42506d92851887f071f8', 'reduce_only': False, 'order_type': 'Limit', 'price': Decimal('41384.5'), 'timestamp': '1644808177011', 'api_key': 'chUftVkE9iREm8LzPF', 'sign': '14d0af02c7b3f442c46fa1b5a9efa83619bf5fc11fed35ec59385856a99adaba'}
Traceback (most recent call last):
  File "/Users/reiniersalazar/hummingbot_c2/hummingbot/connector/derivative/bybit_perpetual/bybit_perpetual_derivative.py", line 474, in _create_order
    raise ValueError(f"Order is rejected by the API. "
ValueError: Order is rejected by the API. Error Msg: order_link_id fail. Parameters: {'side': 'Buy', 'symbol': 'BTCUSDT', 'qty': Decimal('0.001'), 'time_in_force': 'GoodTillCancel', 'close_on_trigger': False, 'order_link_id': 'BBCUT17ef635057276cea1bcc9ae42506d92851887f071f8', 'reduce_only': False, 'order_type': 'Limit', 'price': Decimal('41384.5'), 'timestamp': '1644808177011', 'api_key': 'chUftVkE9iREm8LzPF', 'sign': '14d0af02c7b3f442c46fa1b5a9efa83619bf5fc11fed35ec59385856a99adaba'}
2022-02-14 11:09:37,091 - 4985 - hummingbot.connector.derivative.bybit_perpetual.bybit_perpetual_derivative - WARNING - Error submitting order to Bybit Perpetual. 
```

**Steps To Reproduce**
1. Create and run a perpetual market making strategy using Bybit Perpetual

**Screenshots**
<img width="1422" alt="Screen Shot 2022-02-14 at 11 32 40 AM" src="https://user-images.githubusercontent.com/64377055/153796359-dd4f05ce-83dd-48fb-b1df-90d110cd47eb.png">

**Release version**
1.0.0

**Attachments**
Logs and config: [bybit.zip](https://github.com/hummingbot/hummingbot/files/8057706/bybit.zip)

**Comment by rapcmia** [comment]
The fix for this issue has been applied on the Hummingbot version 1.4 release
