### ISSUE TITLE
'int' object has no attribute 'is_nan'

### ISSUE THREAD

**Issue by sydneyitguy** [hummingbot/hummingbot#5115]
**Describe the bug**
History doesn't show up and error occurs in background task

**Steps To Reproduce**
type `history` on command

Here are the steps to reproduce the issue (see attachments in the section below):
I'm not sure what is the exact cause for the issue, but maybe because we have one of the pair balance becomes zero

**Release version**
1.0.1 (latest version pulled from master branch on 14 Feb)

**Attachments**
crash log:

```
hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'int' object has no attribute 'is_nan'
Traceback (most recent call last):
  File "/home/user/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/user/hummingbot/hummingbot/client/command/history_command.py", line 88, in history_report
    self.report_performance_by_market(market, symbol, perf, precision)
  File "/home/user/hummingbot/hummingbot/client/command/history_command.py", line 161, in report_performance_by_market
    PerformanceMetrics.smart_round(perf.cur_base_bal, precision),
  File "/home/user/hummingbot/hummingbot/client/performance.py", line 142, in smart_round
    if value is None or value.is_nan():
AttributeError: 'int' object has no attribute 'is_nan'
2022-02-15 11:05:32,570 - 28627 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'int' object has no attribute 'is_nan'
Traceback (most recent call last):
  File "/home/user/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/user/hummingbot/hummingbot/client/command/history_command.py", line 88, in history_report
    self.report_performance_by_market(market, symbol, perf, precision)
  File "/home/user/hummingbot/hummingbot/client/command/history_command.py", line 161, in report_performance_by_market
    PerformanceMetrics.smart_round(perf.cur_base_bal, precision),
  File "/home/user/hummingbot/hummingbot/client/performance.py", line 142, in smart_round
    if value is None or value.is_nan():
AttributeError: 'int' object has no attribute 'is_nan'
```

**Comment by sydneyitguy** [comment]
Potential hot fix:

[/home/updatebot/hummingbot/hummingbot/client/performance.py](https://github.com/hummingbot/hummingbot/blob/master/hummingbot/client/performance.py#L142)

```python
value.is_nan() -> Decimal(value).is_nan()
```

**Comment by rapcmia** [comment]
Tested using Arbitrage strategy, we are getting the same results for docker and source build when one of the pairs have exactly 0 balance. On the screenshot below using XRP-USDT pairs, it returned the error of `Unhandled error in background task: 'int' object has no attribute 'is_nan'`

![when one of the pair has exactly 0 assets](https://user-images.githubusercontent.com/73840223/154637755-a541f40f-1007-4254-9736-bddc3fa3fb04.jpg)

On this trimmed recording below,  you would noticed at the start that USDT has `0.2670605` and ran `history` command and did not encounter the error.

https://user-images.githubusercontent.com/73840223/154638363-42ac6a86-12cd-4ae0-9e9e-e01e11962745.mp4

Attached log file:
[logs_arb-test.log](https://github.com/hummingbot/hummingbot/files/8095017/logs_arb-test.log)

**Comment by nikspz** [comment]
Issue showed again in #5550 PR using Cross Exchange Market making strategy using CEX /papertrade for maker_market and  - uniswap (kovan) / pangolin mainnet for taker_market
You could check comment Looking more closely into the bug
https://github.com/hummingbot/hummingbot/pull/5550#issuecomment-1205680582
![image](https://user-images.githubusercontent.com/83953535/183078681-c77c26c2-2c7c-4795-88e8-7f0712ac8953.png)
![image](https://user-images.githubusercontent.com/83953535/183079521-cb0e932d-4aed-4b68-99eb-ccc27ee8c687.png)
![image](https://user-images.githubusercontent.com/83953535/183079531-bb0cefb8-d33d-4390-9ef5-2ffe068d2123.png)
![image](https://user-images.githubusercontent.com/83953535/183079546-5672985c-a357-4aa6-a2c5-8e7648fafaba.png)
![image](https://user-images.githubusercontent.com/83953535/183079569-e143376b-3ea8-4a21-8026-32e7bdaa27ef.png)

**Comment by MementoRC** [comment]
Why is this a bounty? The solution has been found, has it not? The dev version still has this unfixed, should I make the PR?

**Comment by MementoRC** [comment]
Also, I had also independently found this but somehow must have forgotten to submit it, for what's it's worth:
https://github.com/MementoRC/hummingbot/commit/7a06e5f2bde9ac786fd04495a427455c6356c9dd

**Comment by JeremyKono** [comment]
Assigning this issue to you @MementoRC. Thank you for the contribution!

**Comment by rapcmia** [comment]
The fix has been added to the upcoming version 1.9.0 release.
