### ISSUE TITLE
TWAP - Failed to Set up end_datetime

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5164]
**Describe the bug**
TWAP - Failed to Set up end_datetime

**Release version**
Dev 1.2.0

**Steps To Reproduce**
1. Create new twap strategy
2. After creation try to change end_datetime

Actual behavior:
Bot returns an ERROR - fromisoformat: argument must be str
end_datetime set to `None`

Expected:
end_datetime changed to the value set up by user

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/8180371/logs_hummingbot.log)
```
2022-03-03 10:48:32,984 - 4294 - hummingbot.client.hummingbot_application - ERROR - fromisoformat: argument must be str
Traceback (most recent call last):
  File "/home/cerr/development111/hummingbot/client/command/config_command.py", line 167, in _config_single_key
    await self.prompt_a_config(config_var, input_value=input_value, assign_default=False)
  File "/home/cerr/development111/hummingbot/client/command/create_command.py", line 122, in prompt_a_config
    err_msg = await config.validate(input_value)
  File "/home/cerr/development111/hummingbot/client/config/config_var.py", line 84, in validate
    self._on_validated(value)
  File "/home/cerr/development111/hummingbot/strategy/twap/twap_config_map.py", line 45, in set_order_delay_default
    start_datetime = datetime.fromisoformat(start_datetime_string)
TypeError: fromisoformat: argument must be str
```

![image](https://user-images.githubusercontent.com/83953535/156633054-8e7b12c5-b013-4c8b-b468-b22936a7315c.png)
![image](https://user-images.githubusercontent.com/83953535/156633575-b84e0daf-a5f9-4c74-a85d-72b7d374f81f.png)

**Comment by nikspz** [comment]
![image](https://user-images.githubusercontent.com/83953535/156634255-73d4b647-4b37-4cdc-8fbc-a66c5b0c056f.png)
"" not work either

**Comment by nikspz** [comment]
Failed to set up on v1.2. staging
1. When creating strategy
2. When trying to set up it on previously created config
![image](https://user-images.githubusercontent.com/83953535/159208063-9ee606af-2d51-4fc3-a3fc-81845f715b7e.png)

**Comment by nikspz** [comment]
replicated on master / staging 1.3.0.
Issue - failed to add an end date for twap strategy

**Comment by nikspz** [comment]
replicated on staging 1.6.0

**Comment by nikspz** [comment]
replicated on development 1.9.0 
![image](https://user-images.githubusercontent.com/83953535/197071353-4a24aee2-ea62-4dd4-8ce7-73f61f4f2b6d.png)

ps
For workaround:
Manually edit the strategy file from../conf/my_twap.yml and set the values for end_datetime

**Comment by nikspz** [comment]
replicated on development 1.10.0

ps
For workaround:
Manually edit the strategy file from../conf/my_twap.yml and set the values for end_datetime

**Comment by nikspz** [comment]
Replicated for dev-1.15.0
For workaround:
Manually edit the strategy file from../conf/my_twap.yml and set the values for end_datetime

**Comment by nikspz** [comment]
reproduced for dev-1.27.0
![image](https://github.com/hummingbot/hummingbot/assets/83953535/ed4f640f-6329-4ea5-a4a3-fd277fe47737)
