### ISSUE TITLE
dYdX perpetual - Getting error of the JSON object must be str, bytes or bytearray

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5196]
**Describe the bug**
While testing dYdX perpetual on both local (Ubuntu or WSL) and AWS, there are instances that starting or relaunching the bot it will return an error of `the JSON object must be str, bytes or bytearray, not dict` and stuck for a long time. There is also `Unhandled error in background task: list.remove(x):x not in the list`  when you run the `stop` command.

![image](https://user-images.githubusercontent.com/73840223/159900603-4107d752-3f70-4f1e-94a6-595ab7dccb11.png)

```
2022-03-24 18:24:13,520 - 14781 - hummingbot.client.hummingbot_application - ERROR - the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "/home/rapcmia/github/dev/hummingbot/client/command/start_command.py", line 130, in start_market_making
    self.markets_recorder.restore_market_states(config_path, market)
  File "/home/rapcmia/github/dev/hummingbot/connector/markets_recorder.py", line 170, in restore_market_states
    market.restore_tracking_states(market_states.saved_state)
  File "/home/rapcmia/github/dev/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py", line 665, in restore_tracking_states
    in_flight_json: Dict[str, Any] = json.loads(in_flight_repr)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

2022-03-24 18:24:16,327 - 14781 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2022-03-24 18:24:16,328 - 14781 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
  File "/home/rapcmia/github/dev/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/dev/hummingbot/client/command/stop_command.py", line 37, in stop_loop
    self.clock.remove_iterator(self.strategy)
  File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
    self._child_iterators.remove(iterator)
ValueError: list.remove(x): x not in list
```
Tried to recompile the branch and select other markets but still getting the error 

**Steps To Reproduce**
1. Setup a perpetual market making strategy using dYdX perpetual 
2. Start the bot or Stop/Start the bot after creating orders
3. Monitor the bot behavior and logs

**Release version**
staging (dev-1.2) and development (dev-1.3) branch

**Attachments**
[perp-dydx.zip](https://github.com/hummingbot/hummingbot/files/8340853/perp-dydx.zip)

**Comment by RC-13** [comment]
Dropping a note here in case this will be re-tested. Try cleaning the data file folder, I had the same error and after cleaning, I was able to start my strategy although this issue will come back again once the orders placed are not properly canceled.

**Comment by rapcmia** [comment]
When testing dYdX perpetual on AWS and local connection, we are getting `Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...` which also causes delays on order cancellation. Upon checking the traceback it also returns the same error `TypeError: the JSON object must be str, bytes or bytearray, not NoneType`

```
2022-04-25 06:28:22,604 - 3442 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/dydx_perpetual/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_api_order_book_data_source.py", line 180, in listen_for_subscriptions
    async for ws_response in ws.iter_messages():
  File "/home/ubuntu/dydx_perpetual/hummingbot/core/web_assistant/ws_assistant.py", line 69, in iter_messages
    response = await self._connection.receive()
  File "/home/ubuntu/dydx_perpetual/hummingbot/core/web_assistant/connections/ws_connection.py", line 65, in receive
    response = self._build_resp(msg)
  File "/home/ubuntu/dydx_perpetual/hummingbot/core/web_assistant/connections/ws_connection.py", line 125, in _build_resp
    data = msg.json()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 95, in json
    return loads(self.data)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```
![image](https://user-images.githubusercontent.com/73840223/165038458-89277af2-89bd-425d-ab46-d9f1b4bf00ca.png)

Steps to reproduce:
1. Setup simple Perpetual market making for dYdX perpetual
2. Start the bot and monitor the logpane

Attached:
[logs_dydx_link-usd.log](https://github.com/hummingbot/hummingbot/files/8552410/logs_dydx_link-usd.log)

**Comment by phpmac** [comment]
> 在 AWS 和本地连接上测试 dYdX perpetual 时，我们得到了`Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...`这也会导致订单取消延迟。检查回溯后，它也会返回相同的错误`TypeError: the JSON object must be str, bytes or bytearray, not NoneType`
> 
> ```
> 2022-04-25 06:28:22,604 - 3442 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
> Traceback (most recent call last):
>   File "/home/ubuntu/dydx_perpetual/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_api_order_book_data_source.py", line 180, in listen_for_subscriptions
>     async for ws_response in ws.iter_messages():
>   File "/home/ubuntu/dydx_perpetual/hummingbot/core/web_assistant/ws_assistant.py", line 69, in iter_messages
>     response = await self._connection.receive()
>   File "/home/ubuntu/dydx_perpetual/hummingbot/core/web_assistant/connections/ws_connection.py", line 65, in receive
>     response = self._build_resp(msg)
>   File "/home/ubuntu/dydx_perpetual/hummingbot/core/web_assistant/connections/ws_connection.py", line 125, in _build_resp
>     data = msg.json()
>   File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 95, in json
>     return loads(self.data)
>   File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 341, in loads
>     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
> TypeError: the JSON object must be str, bytes or bytearray, not NoneType
> ```
> 
> ![图片](https://user-images.githubusercontent.com/73840223/165038458-89277af2-89bd-425d-ab46-d9f1b4bf00ca.png)
> 
> 重现步骤：
> 
> 1. 为 dYdX 永续合约设置简单的永续合约做市
> 2. 启动机器人并监控日志窗格
> 
> 附： [logs_dydx_link-usd.log](https://github.com/hummingbot/hummingbot/files/8552410/logs_dydx_link-usd.log)

yes,

**Comment by cpeiren** [comment]
When running a script on AWS while connecting to dydx, it gives me this error, didn't go away after I update to 1.5.0.


> 2022-07-14 21:24:35,743 - 100316 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_api_order_book_data_source.py", line 176, in listen_for_subscriptions
    async for ws_response in ws.iter_messages():
  File "/home/ubuntu/hummingbot/hummingbot/core/web_assistant/ws_assistant.py", line 69, in iter_messages
    response = await self._connection.receive()
  File "/home/ubuntu/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 64, in receive
    response = self._build_resp(msg)
  File "/home/ubuntu/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 131, in _build_resp
    data = msg.json()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 95, in json
    return loads(self.data)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType


steps to reproduce:

create a simple script like this to check the connection and run:

> class Checkconnection(ScriptStrategyBase):

    #: Define markets to instruct Hummingbot to create connectors on the exchanges and markets you need
    markets = {connector_name:set(coin_selected)}

    def on_tick(self):
        pass

    def tick(self, timestamp: float):
        """
        Clock tick entry point, is run every second (on normal tick setting).
        Checks if all connectors are ready, if so the strategy is ready to trade.

        :param timestamp: current tick timestamp
        """
        self.logger().info('active markets:')
        self.logger().info([market.ready for market in self.active_markets])
        if not self.ready_to_trade:
            self.ready_to_trade = all(ex.ready for ex in self.connectors.values())
            if not self.ready_to_trade:
                for con in [c for c in self.connectors.values() if not c.ready]:
                    self.logger().warning(f"{con.name} is not ready. Please wait...")
                return
        else:
            self.on_tick()

[logs_check_connection.log](https://github.com/hummingbot/hummingbot/files/9115616/logs_check_connection.log)

**Comment by cpeiren** [comment]
I noticed the issue comes from in_flight_order_base.pyx, looks like the 'data' variable received from API is a string instead of a json file. I haven't figured out exactly how to fix it, but hopefully, it shed some light.

**Comment by afkj0hn** [comment]
Getting the exact same issue as @rapcmia running latest release, version 1.6.0 on macOS from source.

Steps to reproduce:
1. Setup simple Perpetual market making for dYdX perpetual
2. Start the bot and monitor the logpane

**Comment by lolo31660** [comment]
Same issue on my side. Is there any update ?

**Comment by rawoke083** [comment]
Still the same issues ? No update or workarounds ?

**Comment by rapcmia** [comment]
Fix has been deployed on the upcoming Hummingbot 1.10 release
