### ISSUE TITLE
dYdX - `NoneType`  object has no attribute `exchange_order_id`

### ISSUE THREAD

**Issue by SC4RECOIN** [hummingbot/hummingbot#5207]
**Describe the bug**
```
2022-03-30 14:37:31,003 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object has no attribute 'exchange_order_id'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py", line 474, in cancel_order
    exchange_order_id = in_flight_order.exchange_order_id
AttributeError: 'NoneType' object has no attribute 'exchange_order_id'
```

https://github.com/hummingbot/hummingbot/blob/master/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py#L474

**Steps To Reproduce**
run perpetual-market-making strategy on dYdX

**Release version**
v 1.1.1

**Comment by rapcmia** [comment]
Hi @SC4RECOIN good day,
Please be advised that Dydx perpetual has been recently updated and improved by one of our community devs. This will be available on the upcoming Hummingbot 1.10 release and also on development branch. As per testing this update we had not observed this issue happened and already fixed. 

Closing this ticket for now, else you can reopen if issue persist. Thank you
