### ISSUE TITLE
Huobi - continuous `Error listening to order book streams` when placing orders

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5220]
Upon checking with the team bot got an  `Error listening to order book streams` and `ERROR - Unexpected error with Huobi WebSocket connection` when placing orders with Huobi as exchange connector. 
Using latest development branch (commit 99f1562bc28de5f2587e8f373a9d6940ccc7bdd2)
p.s. Not showing on current master branch (1.2.0 release)

**Steps To Reproduce**
1. Install latest dev branch
2. connect fresh Huobi API keys
3. Run pure market making strategy using Huobi as exchange

Actual:
`Error listening to order book streams` and `ERROR - Unexpected error with Huobi WebSocket connection` when placing orders with Huobi as exchange connector

Expected:
No errors showing, bot place orders according config and refresh time.

[logs_conf_pure_mm_3.log](https://github.com/hummingbot/hummingbot/files/8449716/logs_conf_pure_mm_3.log)
[huobi.zip](https://github.com/hummingbot/hummingbot/files/8449725/huobi.zip)

```
2022-04-08 06:13:28,184 - 13049 - hummingbot.connector.exchange.huobi.huobi_api_user_stream_data_source - ERROR - Unexpected error with Huobi WebSocket connection. Retrying after 30 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/devel/hummingbot/connector/exchange/huobi/huobi_api_user_stream_data_source.py", line 121, in listen_for_user_stream
    async for ws_response in self._ws_assistant.iter_messages():
  File "/home/ubuntu/devel/hummingbot/core/web_assistant/ws_assistant.py", line 69, in iter_messages
    response = await self._connection.receive()
  File "/home/ubuntu/devel/hummingbot/core/web_assistant/connections/ws_connection.py", line 63, in receive
    msg = await self._process_message(msg)
  File "/home/ubuntu/devel/hummingbot/core/web_assistant/connections/ws_connection.py", line 85, in _process_message
    msg = await self._check_msg_types(msg)
  File "/home/ubuntu/devel/hummingbot/core/web_assistant/connections/ws_connection.py", line 90, in _check_msg_types
    msg = await self._check_msg_closed_type(msg)
  File "/home/ubuntu/devel/hummingbot/core/web_assistant/connections/ws_connection.py", line 100, in _check_msg_closed_type
    raise ConnectionError(
ConnectionError: The WS connection was closed unexpectedly. Close code = 1006 msg data: None
2022-04-08 06:13:28,372 - 13049 - hummingbot.connector.exchange.huobi.huobi_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/devel/hummingbot/connector/exchange/huobi/huobi_api_order_book_data_source.py", line 170, in listen_for_subscriptions
    async for ws_response in ws.iter_messages():
  File "/home/ubuntu/devel/hummingbot/core/web_assistant/ws_assistant.py", line 69, in iter_messages
    response = await self._connection.receive()
  File "/home/ubuntu/devel/hummingbot/core/web_assistant/connections/ws_connection.py", line 65, in receive
    response = self._build_resp(msg)
  File "/home/ubuntu/devel/hummingbot/core/web_assistant/connections/ws_connection.py", line 125, in _build_resp
    data = msg.json()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 95, in json
    return loads(self.data)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

![image](https://user-images.githubusercontent.com/83953535/162389483-c2e6480a-6e87-4c11-8331-391cbdee00c4.png)

**Release version**
dev 1.3.0 AWS Ubuntu, Source

**Comment by awayme** [comment]
same error here, any update on this?

**Comment by sydneyitguy** [comment]
Same error on 1.4.0

**Comment by JeremyKono** [comment]
Severity: P2
Bounty: 50,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to certified exchange

**Comment by han-qiu** [comment]
Aug 30, 2022 was able to reproduce on master branch

**Comment by JeremyKono** [comment]
We still have no details about the said PR, no PR has been opened on the Hummingbot Foundation repo as of now. It's still open to the public

**Comment by han-qiu** [comment]
@JeremyKono I can take this one, could you assign it to me? Thanks!

**Comment by han-qiu** [comment]
Submitted the PR.
The issue was caused by duplicated logic in order book tracker class.

**Comment by nikspz** [comment]
Fixed with https://github.com/hummingbot/hummingbot/pull/5666
