### ISSUE TITLE
Can't run bin/hummingbot.py: 

### ISSUE THREAD

**Issue by kopeboy** [hummingbot/hummingbot#5231]
Follow the install instructions for macOS found at https://hummingbot.org/installation/source/
Arrive at 
```
# 6) Run Hummingbot
bin/hummingbot.py
```
and you get:
```
Traceback (most recent call last):
  File "/Users/kopeboy/hummingbot/bin/hummingbot.py", line 11, in <module>
    from hummingbot.client.config.config_helpers import (
  File "/Users/kopeboy/hummingbot/hummingbot/client/config/config_helpers.py", line 3, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'
```

**Comment by rapcmia** [comment]
Hi @kopeboy I usually found this error happening if you failed to run step 5 of the manual source installation. Please try again

```
# 1) Clone Hummingbot repo
git clone https://github.com/hummingbot/hummingbot.git

# 2) Navigate into the hummingbot folder
cd hummingbot

# 3) Run install script
./install

# 4) Activate the environment
conda activate hummingbot

# 5) Compile
./compile

# 6) Run Hummingbot
bin/hummingbot.py
```
