### ISSUE TITLE
Logging in password: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by kimteaduck** [hummingbot/hummingbot#5285]
I have completed the installation as faithfully as possible in the Windows source procedure("Install Hummingbot from Source").

However, an error message has occurred as shown in the message screen below and asks what to do.

>> my pc environment : window11, python: 3.8.2, miniconda  

20:03:06 - root - Error loading configs. Your config file may be corrupt. 'cp949' codec can't decode byte 0xe2 in positi
on 5574: illegal multibyte sequence (See log file for stack trace dump)
20:03:06 - root - Error writing configs: 'cp949' codec can't decode byte 0xe2 in position 5574: illegal multibyte sequen
ce (See log file for stack trace dump)
Traceback (most recent call last):
 File "bin/hummingbot.py", line 92, in <module>
   ev_loop.run_until_complete(main())
 File "C:\Minconda\envs\hummingbot\lib\asyncio\base_events.py", line 616, in run_until_complete
   return future.result()

 File "bin/hummingbot.py", line 67, in main
   AllConnectorSettings.initialize_paper_trade_settings(global_config_map.get("**paper_trade_exchanges**").value )

 File "C:\Users\sossedge\hummingbot\hummingbot\client\settings.py", line 173, in initialize_paper_trade_settings
   for e in **paper_trade_exchanges**:

TypeError: 'NoneType' object is not iterable
(hummingbot)
sossedge@korea MINGW64 ~/hummingbot (master)
$
​​
![image](https://user-images.githubusercontent.com/39983082/166671445-37b4d829-b263-419a-b53b-63919e9cef88.png)

**Comment by kimteaduck** [comment]
file_open = open("file path", 'r', encoding="UTF-8")

**Comment by kimteaduck** [comment]
I solved it by inserting encoding="UTF-8"
