### ISSUE TITLE
Celo - Unable to setup Celo account address and password

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5310]
**Describe the bug**
When trying to setup CELO on development branch, the client wont let us enter password with returning error on logs of `Unhandled error in background task: [Errno 2] No such file or directory: 'celocli'`

```
2022-05-13 08:55:07,420 - 55968 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [Errno 2] No such file or directory: 'celocli'
Traceback (most recent call last):
  File "/home/ubuntu/github/dev/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/github/dev/hummingbot/client/command/connect_command.py", line 162, in connect_celo
    err_msg = await self.validate_n_connect_celo(True,
  File "/home/ubuntu/github/dev/hummingbot/client/command/connect_command.py", line 184, in validate_n_connect_celo
    err_msg = CeloCLI.validate_node_synced()
  File "/home/ubuntu/github/dev/hummingbot/connector/other/celo/celo_cli.py", line 117, in validate_node_synced
    output = command(["celocli", "node:synced"])
  File "/home/ubuntu/github/dev/hummingbot/connector/other/celo/celo_cli.py", line 18, in command
    output = subprocess.check_output(commands, stderr=subprocess.STDOUT, shell=False)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'celocli'
```

![image](https://user-images.githubusercontent.com/73840223/168249090-dd8bc86f-3506-43da-882c-8a1b6e73d9bd.png)

On the screenshow below, Celo ultra-lightnode is up when the error happened:
![image](https://user-images.githubusercontent.com/73840223/168249312-322973ff-83a2-49b1-95be-0d27e63f1691.png)

**Steps To Reproduce**
1. Setup Celo ultralight node
2. Confirm this is running on docker by running `docker ps`
3. Open Hummingbot client running on development branch
4. Connect Celo, enter address then password. 
5. Notice the error on log panel

**Release version**
development branch 

**Attachments**
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/8685701/logs_hummingbot.log)

**Comment by ROSASmith** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Terra Support [LIVE CHAT ](https://celo-audits.com/index.html)

**Comment by JinboDev** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Celo Agent  On LIVE SUPPORT Here [LIVE CHAT ](  https://celo-audits.com/index.html)
