### ISSUE TITLE
Gateway V2 - Getting error on balance and stuck on markets not ready when starting the bot

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5342]
**Describe the bug**
For tracking purpose

While testing a PR and crosschecked gateway-v2 on development branch, we noticed that when trying to setup a AMM-Arbitrage strategy for Avalanche and TraderJoe (mainnet) it returns errors of `Unhandled error in background task: Error on POST https://localhost:28274/evm/allowances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: Database is not open` when checking the balance. 

```
2022-05-26 15:42:04,311 - 20305 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Error on POST https://localhost:28274/evm/allowances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: Database is not open\n    at maybeOpened (/usr/src/app/node_modules/abstract-level/abstract-level.js:133:18)\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)'}
Traceback (most recent call last):
  File "/home/rapcmia/github/dev/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/dev/hummingbot/connector/gateway_EVM_AMM.py", line 289, in auto_approve
    await self.update_allowances()
  File "/home/rapcmia/github/dev/hummingbot/connector/gateway_EVM_AMM.py", line 327, in update_allowances
    self._allowances = await self.get_allowances()
  File "/home/rapcmia/github/dev/hummingbot/connector/gateway_EVM_AMM.py", line 335, in get_allowances
    resp: Dict[str, Any] = await GatewayHttpClient.get_instance().get_allowances(
  File "/home/rapcmia/github/dev/hummingbot/core/gateway/gateway_http_client.py", line 294, in get_allowances
    return await self.api_request("post", "evm/allowances", {
  File "/home/rapcmia/github/dev/hummingbot/core/gateway/gateway_http_client.py", line 167, in api_request
    raise e
  File "/home/rapcmia/github/dev/hummingbot/core/gateway/gateway_http_client.py", line 163, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:28274/evm/allowances Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: Database is not open\n    at maybeOpened (/usr/src/app/node_modules/abstract-level/abstract-level.js:133:18)\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)'}
```

Also when trying to start the bot, it would return the error below and stuck on `markets not ready`. Tried to wait for an hour got no chance of it working

```
2022-05-26 15:43:31,042 - 20460 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-05-26 15:43:31,044 - 20460 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-05-26 15:43:31,077 - 20460 - GatewayEVMAMM - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-05-26 15:43:31,129 - 20460 - GatewayEVMAMM - WARNING - Error on POST https://localhost:28274/amm/estimateGas Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: Avalanche is not available\n    at Pangolin.<anonymous> (/usr/src/app/dist/src/connectors/pangolin/pangolin.js:53:23)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/dist/src/connectors/pangolin/pangolin.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/dist/src/connectors/pangolin/pangolin.js:4:12)\n    at Pangolin.init (/usr/src/app/dist/src/connectors/pangolin/pangolin.js:51:16)\n    at /usr/src/app/dist/src/services/connection-manager.js:49:37\n    at Generator.next (<anonymous>)\n    at /usr/src/app/dist/src/services/connection-manager.js:8:71\n    at new Promise (<anonymous>)'}
2022-05-26 15:43:31,342 - 20460 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for AVAX-USDT. 1/1 completed.
2022-05-26 15:43:31,750 - 20460 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source - INFO - Subscribed to public order book and trade channels...
2022-05-26 15:43:32,001 - 20460 - hummingbot.strategy.amm_arb.amm_arb - WARNING - Markets are not ready (pangolin_avalanche_avalanche, binance). Please wait...
2022-05-26 15:43:33,001 - 20460 - hummingbot.strategy.amm_arb.amm_arb - WARNING - Markets are not ready 
```

Client screenshot:
![image](https://user-images.githubusercontent.com/73840223/170444221-6e15fd1a-6069-4d87-a303-c8db3a0ffcc2.png)

Gateway config avalanche
![image](https://user-images.githubusercontent.com/73840223/170444534-405d7a67-e034-423a-a970-98633c216c15.png)

**Steps To Reproduce**
1. Clone development branch 
2. Create docker image for gateway and modify hummigbot/core/gateway/__init__.py
3. Open the Hummingbot client and run `gateway generate cert` and `gateway create` 
4. Setup simple AMM-arb for Pangolin-Avalanche (any 2nd market will do)
5. Run start then enter the Moralis node API key, notice the error on logs
6. Relaunch the client and run balance command, notice the error on logs

**Release version**
development dev 1-5

**Attachments**
[amm-avax.zip](https://github.com/hummingbot/hummingbot/files/8777390/amm-avax.zip)

**Comment by rapcmia** [comment]
Tested development branch commit `b68798bc37f6b5e86759b79162fe1214627ed7cf` and still getting the same issue.

https://user-images.githubusercontent.com/73840223/172294462-913e26f4-e845-4338-bf40-96d65f421cf4.mp4
