### ISSUE TITLE
Beaxy - Error after connecting API keys

### ISSUE THREAD

**Issue by rxlxrxsx** [hummingbot/hummingbot#5369]
**Describe the bug**
Getting an error after connecting the API keys using Beaxy.

```python
2022-06-02 23:11:43,940 - 14121 - hummingbot.connector.exchange.beaxy.beaxy_exchange - WARNING - Exception while making api request.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/beaxy/beaxy_exchange.pyx", line 1016, in hummingbot.connector.exchange.beaxy.beaxy_exchange.BeaxyExchange._api_request
    headers = await self.beaxy_auth.generate_auth_dict(http_method, path_url, data_str)
  File "/Users/reiniersalazar/hummingbot/hummingbot/connector/exchange/beaxy/beaxy_auth.py", line 141, in generate_auth_dict
    auth_token = await self.get_token()
  File "/Users/reiniersalazar/hummingbot/hummingbot/connector/exchange/beaxy/beaxy_auth.py", line 64, in get_token
    await self._update_token()
  File "/Users/reiniersalazar/hummingbot/hummingbot/connector/exchange/beaxy/beaxy_auth.py", line 96, in _update_token
    raise IOError(f'Error while connecting to login token endpoint. HTTP status is {response.status}.')
OSError: Error while connecting to login token endpoint. HTTP status is 400.
```

<img width="1423" alt="Screen Shot 2022-06-02 at 11 11 52 PM" src="https://user-images.githubusercontent.com/64377055/171663159-da948ee3-14c8-40d2-9e45-ac151ea806ba.png">

**Steps To Reproduce**
1. Run the client
2. Connect Beaxy API keys

**Release version**
dev 1.5.0

**Comment by sCLARKware** [comment]
I'm getting the same error on Hummingbot version 1.4 (production release)

**Comment by rapcmia** [comment]
Connector not supported
