### ISSUE TITLE
Gateway can't connect to host

### ISSUE THREAD

**Issue by mifeng** [hummingbot/hummingbot#5445]
**Describe the bug**
I started Gateway from a fresh Hummingbot `staging_1_5_0` installation but it doesn't seem to find the container

Error in logs:
```
2022-06-30 14:01:55,136 - 3384 - hummingbot.core.gateway.gateway_http_client - ERROR - Cannot connect to host localhost:29138 ssl:default [None]
2022-06-30 14:01:55,137 - 3384 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Cannot connect to host localhost:29138 ssl:default [None]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
ConnectionResetError
```
**Environment**

* MacOS (Intel)
* Installation from source
* `staging_1_5_0 branch`

<img width="1788" alt="Screen Shot 2022-06-30 at 2 07 07 PM" src="https://user-images.githubusercontent.com/1795030/176778436-61804691-0ea5-4cf5-ab1e-b1c890cf8755.png">

**Comment by mifeng** [comment]
I tried it on my Pixelbook (Linux Debian) and got the same thing
