### ISSUE TITLE
Gateway Container | Operation not permitted, copyfile

### ISSUE THREAD

**Issue by shlatchz** [hummingbot/hummingbot#5506]
**Describe the bug**
After adding a new gateway, by running `gateway create`, I see the following errors in container

```
[nodemon] app crashed - waiting for file changes before starting...
yarn run v1.22.5
Error: EPERM: operation not permitted, copyfile '/usr/src/app/dist/src/templates/harmony.yml' -> '/usr/src/app/conf/harmony.yml'
    at Object.copyFileSync (node:fs:2792:3)
    at initiateWithTemplate (/usr/src/app/dist/src/services/config-manager-v2.js:72:18)
    at new ConfigurationNamespace (/usr/src/app/dist/src/services/config-manager-v2.js:95:13)
    at ConfigManagerV2.addNamespace (/usr/src/app/dist/src/services/config-manager-v2.js:222:78)
    at ConfigManagerV2.loadConfigRoot (/usr/src/app/dist/src/services/config-manager-v2.js:291:18)
    at new ConfigManagerV2 (/usr/src/app/dist/src/services/config-manager-v2.js:178:14)
    at Function.getInstance (/usr/src/app/dist/src/services/config-manager-v2.js:186:41)
    at getLogPath (/usr/src/app/dist/src/services/logger.js:43:55)
    at Object.<anonymous> (/usr/src/app/dist/src/services/logger.js:49:18)
    at Module._compile (node:internal/modules/cjs/loader:1109:14) {
  errno: -1,
  syscall: 'copyfile',
  code: 'EPERM',
  path: '/usr/src/app/dist/src/templates/harmony.yml',
  dest: '/usr/src/app/conf/harmony.yml'
}
Error: EPERM: operation not permitted, copyfile '/usr/src/app/dist/src/templates/harmony.yml' -> '/usr/src/app/conf/harmony.yml'
    at Object.copyFileSync (node:fs:2792:3)
    at initiateWithTemplate (/usr/src/app/dist/src/services/config-manager-v2.js:72:18)
    at new ConfigurationNamespace (/usr/src/app/dist/src/services/config-manager-v2.js:95:13)
    at ConfigManagerV2.addNamespace (/usr/src/app/dist/src/services/config-manager-v2.js:222:78)
    at ConfigManagerV2.loadConfigRoot (/usr/src/app/dist/src/services/config-manager-v2.js:291:18)
    at new ConfigManagerV2 (/usr/src/app/dist/src/services/config-manager-v2.js:178:14)
    at Function.getInstance (/usr/src/app/dist/src/services/config-manager-v2.js:186:41)
    at getLogPath (/usr/src/app/dist/src/services/logger.js:43:55)
    at Object.<anonymous> (/usr/src/app/dist/src/services/logger.js:49:18)
    at Module._compile (node:internal/modules/cjs/loader:1109:14) {
  errno: -1,
  syscall: 'copyfile',
  code: 'EPERM',
  path: '/usr/src/app/dist/src/templates/harmony.yml',
  dest: '/usr/src/app/conf/harmony.yml'
}
```

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:
Here are the steps to reproduce the issue (see attachments in the section below):
In windows wsl:
1. Run hummingbot by initiating `start.sh`
2. Create a gateway with `gateway create`

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
1.5.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/9125892/logs_hummingbot.log)
[conf_global.yml.log](https://github.com/hummingbot/hummingbot/files/9125895/conf_global.yml.log)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by shlatchz** [comment]
I resolved it by manually connecting to container and copying the yml files from `/usr/src/app/dist/src/templates/harmony.yml` to `/usr/src/app/conf/harmony.yml`

**Comment by rapcmia** [comment]
Hi @shlatchz good day,
We have some improvements added to the gateway source build over the previous releases. Please see the link below for the steps that we usually use to setup and works all the time.

https://docs.hummingbot.org/developers/gateway/setup/
