### ISSUE TITLE
Client - time_synchronizer - Error getting server time.

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5557]
Upon crosschecking with the QA and CA team. 
Currently have the `time_synchronizer - Error getting server time`. and also `WARNING - Could not refresh server time.` messages on the `initial start`

This issue not showed yesterday when checking latest development branch.
Environment: AWS Ubuntu Source, `dev-1.7.0`, also showing on the master branch (`1.6.0`) for same AWS

**Steps To Reproduce**
set up on AWS Ubuntu source
clone and install latest master or development branch
start the bot

Expected:
No error showing

Actual:
Bot showing `time_synchronizer - WARNING - Could not refresh server time. Check network connection.`

Traceback:

[logs_hummingbot(master branch).log](https://github.com/hummingbot/hummingbot/files/9240226/logs_hummingbot.master.branch.log)
```
2022-08-02 04:56:45,255 - 2948 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/home/ubuntu/master/hummingbot/connector/time_synchronizer.py", line 59, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/home/ubuntu/master/hummingbot/connector/exchange/latoken/latoken_web_utils.py", line 197, in get_current_server_time
    response = await rest_assistant.execute_request(
  File "/home/ubuntu/master/hummingbot/core/web_assistant/rest_assistant.py", line 71, in execute_request
    error_response = await response.json()
  File "/home/ubuntu/master/hummingbot/core/web_assistant/connections/data_types.py", line 114, in json
    json_ = await self._aiohttp_response.json()
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://api.latoken.com/v2/time')
2022-08-02 04:56:45,256 - 2948 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
```

**Comment by nikspz** [comment]
Upon checking logs issue could be related to latoken exchange. Not showing now, so close that issue for now

**Comment by zethereumGmail** [comment]
This is happening again on the dev-1.20.0 branch

**Comment by nikspz** [comment]
hi @zethereumGmail the issue not related to the exchange, but most likely related to the restricted area to get data.
Anyway, upon checking before bot should be able to place orders anyway
