### ISSUE TITLE
Eve - Getting "There was an error requesting exchange info" on start of the client 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5562]
**Describe the bug**
For tracking purpose
We noticed that the client would return an `EveExchange - ERROR - There was an error requesting exchange info.` when initially started. It doesn't seem to affect bot performance.

![image](https://user-images.githubusercontent.com/73840223/182562939-fe571389-d2be-47c0-80fa-ffef2e1fe457.png)

```
2022-08-03 16:28:47,216 - 24255 - hummingbot.connector.exchange.eve.eve_exchange.EveExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rapcmia/github/dev/hummingbot/connector/utilities/oms_connector/oms_connector_exchange.py", line 536, in _initialize_trading_pair_symbol_map
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path, params=params)
  File "/home/rapcmia/github/dev/hummingbot/connector/exchange_py_base.py", line 833, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/rapcmia/github/dev/hummingbot/connector/utilities/oms_connector/oms_connector_exchange.py", line 511, in _api_request
    return await rest_assistant.execute_request(
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/rest_assistant.py", line 67, in execute_request
    response = await self.call(request=request, timeout=timeout)
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/rest_assistant.py", line 84, in call
    resp = await wait_for(self._connection.call(request), timeout)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/connections/rest_connection.py", line 10, in call
    aiohttp_resp = await self._client_session.request(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.eve.apstage.net:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')]

```

**Steps To Reproduce**
- Start the client

**Release version**
dev-1.7

**Comment by rapcmia** [comment]
This issue does not happen anymore on development branch
