### ISSUE TITLE
Client - Gateio and Binance getting failed to submit orders, check API key and network connection

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5575]
**Describe the bug**
After updating to the latest development branch `51efe47c2691c72` and monitoring long term testbots, both `Binance and Gateio ` connectors are not working with an error of `Failed to submit orders to ...Check API key and network connection`

Tested on Pure market-making, Avellaneda and Liquidity mining strategies and getting the same results.

Binance
![image](https://user-images.githubusercontent.com/73840223/183346730-b0281646-4faf-4506-94c0-cd41c4c9e960.png)

```
2022-08-08 05:13:38,002 - 433553 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - NETWORK - Error submitting sell LIMIT_MAKER order to Binance for 0.01000000 ETH-USDT 1750.84000000.
Traceback (most recent call last):
  File "/home/ubuntu/binance/hummingbot/connector/exchange_py_base.py", line 474, in _create_order
    exchange_order_id, update_timestamp = await self._place_order(
TypeError: _place_order() got an unexpected keyword argument 'expiration_ts'
```

Gateio
![image](https://user-images.githubusercontent.com/73840223/183346798-827e625e-28c9-40bf-beb9-e02ce9da59fd.png)

```
2022-08-08 05:19:38,003 - 433632 - hummingbot.connector.exchange.gate_io.gate_io_exchange.GateIoExchange - NETWORK - Error submitting buy LIMIT order to Gate_io for 0.0100 ETH-USDT 1665.52.
Traceback (most recent call last):
  File "/home/ubuntu/gateio/hummingbot/connector/exchange_py_base.py", line 474, in _create_order
    exchange_order_id, update_timestamp = await self._place_order(
TypeError: _place_order() got an unexpected keyword argument 'expiration_ts'
```

Tried to create new API keys and checked both AWS and local instance getting the same error. Crosscheck on previous versions and the last working commit on development branch is `94ee6c77ed36db397d7e0f29a02698f973a8abf9`. 

**Steps To Reproduce**
1. Setup any hummingbot strategy and use Gateio or Binance as connector
2. Start the client and monitor log panel
3. Upon creating orders, it would return failed to submit

**Release version**
Development branch dev-1.7

**Attachments**
[gateio and binance.zip](https://github.com/hummingbot/hummingbot/files/9279050/gateio.and.binance.zip)

**Comment by rapcmia** [comment]
fixed
