### ISSUE TITLE
Ascendex - Error parsing the trading pair rule

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5595]
**Describe the bug**

While reviewing our test bot log file, we found some instances of this error `ERROR - Error parsing the trading pair rule ....` for the listed market pair below which has been added to recently to Ascendex :

- [DAO-USDT](https://ascendex.com/en/support/articles/73312-dao-maker-dao-is-listed-on-ascendex-trade-now)
- [LOVELY-USDT](https://ascendex.com/en/support/articles/73115-lovely-inu-lovely-is-listed-on-ascendex-stake-lovely-to-earn-rewa)
- [QUICK-USDT](https://ascendex.com/en/support/articles/73284-quickswap-quick-is-listed-on-ascendex-trade-now)

```
2022-08-15 04:47:45,306 - 511634 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'DAO/USDT', 'displayName': 'DAO/USDT', 'baseAsset': 'DAO', 'quoteAsset': 'USDT', 'status': 'InternalTrading', 'minNotional': '5', 'maxNotional': '200000', 'marginTradable': False, 'commissionType': 'Quote', 'commissionReserveRate': '0.002', 'tickSize': '0.0001', 'lotSize': '1'}. Skipping.
Traceback (most recent call last):
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 1065, in _format_trading_rules
    trading_pair = await AscendExAPIOrderBookDataSource.trading_pair_associated_to_exchange_symbol(rule["symbol"],
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 220, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 530, in __getitem__
    return self._fwdm[key]
KeyError: 'DAO/USDT'
```

```
2022-08-11 02:05:05,161 - 443647 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'QUICK/USDT', 'displayName': 'QUICK/USDT', 'baseAsset': 'QUICK', 'quoteAsset': 'USDT', 'status': 'InternalTrading', 'minNotional': '5', 'maxNotional': '200000', 'marginTradable': False, 'commissionType': 'Quote', 'commissionReserveRate': '0.002', 'tickSize': '0.00001', 'lotSize': '1'}. Skipping.
Traceback (most recent call last):
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 1065, in _format_trading_rules
    trading_pair = await AscendExAPIOrderBookDataSource.trading_pair_associated_to_exchange_symbol(rule["symbol"],
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 220, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 530, in __getitem__
    return self._fwdm[key]
KeyError: 'QUICK/USDT'
2022-08-11 02:05:05,161 - 443647 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'LOVELY/USDT', 'displayName': 'LOVELY/USDT', 'baseAsset': 'LOVELY', 'quoteAsset': 'USDT', 'status': 'InternalTrading', 'minNotional': '5', 'maxNotional': '200000', 'marginTradable': False, 'commissionType': 'Quote', 'commissionReserveRate': '0.002', 'tickSize': '0', 'lotSize': '1'}. Skipping.
Traceback (most recent call last):
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 1065, in _format_trading_rules
    trading_pair = await AscendExAPIOrderBookDataSource.trading_pair_associated_to_exchange_symbol(rule["symbol"],
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 220, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 530, in __getitem__
    return self._fwdm[key]
KeyError: 'LOVELY/USDT'
```
Despite the error messages, the client is seem to be working as expected

**Steps To Reproduce**
1. Setup simple Pure market making strategy
2. Start the bot and monitor log panel

**Release version**
Development branch dev-1.7

[pmm-ascendex.zip](https://github.com/hummingbot/hummingbot/files/9348695/pmm-ascendex.zip)

**Comment by nikspz** [comment]
Reproduced on dev-1.7.0 starting a strategy using ascendex as exchange
bot showed `ERROR - Error parsing the trading pair rule` for pairs: BSGG/USDT, CHZ3L/USDT, CHZ5L/USDT, CHZ3S/USDT, CHZ5S/USDT, BSV3L/USDT, BSV5L/USDT, BSV3S/USDT, BSV5S/USDT,  ETC3L/USDT, ETC5L/USDT, ETC3S/USDT, ETC5S/USDT, LOOKS3L/USDT, LOOKS5L/USDT, LOOKS3S/USDT, LOOKS5S/USDT, YFI3L/USDT, YFI5L/USDT, YFI3S/USDT, YFI5S/USDT




```
2022-08-19 02:38:12,663 - 534800 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-08-19 02:38:12,736 - 534800 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-08-19 02:38:13,319 - 534800 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-08-19 02:38:13,393 - 534800 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for ETH-USDT. 1/1 completed.
2022-08-19 02:38:13,618 - 534800 - hummingbot.connector.exchange.ascend_ex.ascend_ex_order_book_tracker - INFO - Initialized order book for ETH-USDT. 1/1 completed.
2022-08-19 02:38:13,699 - 534800 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'BSGG/USDT', 'displayName': 'BSGG/USDT', 'baseAsset': 'BSGG', 'quoteAsset': 'USDT', 'status': 'InternalTrading', 'minNotional': '5', 'maxNotional': '200000', 'marginTradable': False, 'commissionType': 'Quote', 'commissionReserveRate': '0.002', 'tickSize': '0.000001', 'lotSize': '1'}. Skipping.
Traceback (most recent call last):
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 1065, in _format_trading_rules
    trading_pair = await AscendExAPIOrderBookDataSource.trading_pair_associated_to_exchange_symbol(rule["symbol"],
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 220, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 530, in __getitem__
    return self._fwdm[key]
KeyError: 'BSGG/USDT'
2022-08-19 02:38:13,703 - 534800 - hummingbot.connector.exchange.ascend_ex.ascend_ex_exchange - ERROR - Error parsing the trading pair rule {'symbol': 'CHZ3L/USDT', 'displayName': 'CHZ3L/USDT', 'baseAsset': 'CHZ3L', 'quoteAsset': 'USDT', 'status': 'InternalTrading', 'minNotional': '5', 'maxNotional': '200000', 'marginTradable': False, 'commissionType': 'Quote', 'commissionReserveRate': '0.002', 'tickSize': '0.00000001', 'lotSize': '1'}. Skipping.
Traceback (most recent call last):
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_exchange.py", line 1065, in _format_trading_rules
    trading_pair = await AscendExAPIOrderBookDataSource.trading_pair_associated_to_exchange_symbol(rule["symbol"],
  File "/home/ubuntu/ascendex/hummingbot/connector/exchange/ascend_ex/ascend_ex_api_order_book_data_source.py", line 220, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/bidict/_base.py", line 530, in __getitem__
    return self._fwdm[key]
KeyError: 'CHZ3L/USDT'
.................................................................

2022-08-19 02:38:13,714 - 534800 - hummingbot.connector.exchange.kucoin.kucoin_api_order_book_data_source.KucoinAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2022-08-19 02:38:14,079 - 534800 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - INFO - Subscribed to ['ETH-USDT'] orderbook trading and delta streams...
2022-08-19 02:38:14,154 - 534800 - hummingbot.connector.exchange.ascend_ex.ascend_ex_api_order_book_data_source - INFO - Subscribed to ['ETH-USDT'] orderbook trading and delta streams...
2022-08-19 02:38:15,003 - 534800 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 bid orders at (Size, Price): ['0.015 ETH, 1802.41 USDT']
2022-08-19 02:38:15,004 - 534800 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (ETH-USDT) Creating 1 ask orders at (Size, Price): ['0.001 ETH, 1838.83 USDT']
2022-08-19 02:38:15,177 - 534800 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order HMBotBEHUT182b3f725dc53f051fd1c0ff73020a3001b8c764e60 for 0.015 ETH-USDT.
2022-08-19 02:38:15,207 - 534800 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1660876695.0, "type": "OrderType.LIMIT", "trading_pair": "ETH-USDT", "amount": "0.015", "price": "1802.41", "order_id": "HMBotBEHUT182b3f725dc53f051fd1c0ff73020a3001b8c764e60", "creation_timestamp": 1660876695.0, "exchange_order_id": "HMBot182b3f725dcU0290229957jdHOz", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "ascend_ex"}
```
[logs_pmm-ascendex.log](https://github.com/hummingbot/hummingbot/files/9380501/logs_pmm-ascendex.log)
[ascendex Error parsing the trading pair rule.zip](https://github.com/hummingbot/hummingbot/files/9380497/ascendex.Error.parsing.the.trading.pair.rule.zip)

**Comment by nikspz** [comment]
The issue not showing on the initial start anymore for development 1.7.0 and master branch
![image](https://user-images.githubusercontent.com/83953535/186073635-3535545b-bff3-4551-94b8-f32edb093eef.png)
![image](https://user-images.githubusercontent.com/83953535/186073988-0ec083f6-977e-4a29-8e16-774397d42b51.png)
