### ISSUE TITLE
Orderbook streaming issue on Liquid exchange

### ISSUE THREAD

**Issue by JosephWN** [hummingbot/hummingbot#5620]
**Describe the bug**
When I connected to Liquid exchange with API key, stated pure market making strategy, I could not get the orderbook stream, and got error info like this:

2022-08-25 16:19:05,700 - 15808 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-08-25 16:19:05,909 - 15808 - hummingbot.connector.exchange.liquid.liquid_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-08-25 16:19:05,909 - 15808 - hummingbot.connector.exchange.liquid.liquid_exchange - WARNING - This exchange connector does not provide trades feed. Strategies which depend on it will not work properly.
2022-08-25 16:19:05,911 - 15808 - hummingbot.connector.exchange.liquid.liquid_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hbot1/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    ws: WSAssistant = await self._connected_websocket_assistant()
  File "/home/ubuntu/hummingbot/hbot1/hummingbot/core/data_type/order_book_tracker_data_source.py", line 182, in _connected_websocket_assistant
    raise NotImplementedError
NotImplementedError

**Steps To Reproduce**
1. connect to Liquid exchange with API keys, successfully connected because I get my accout balance.
2. create pure_market_making strategy and set up the config.
3. start
4. get error info.

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
//hummingbot v1.6.0 on Ubuntu 18.04

**Attachments**
2022-08-25 16:19:05,700 - 15808 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-08-25 16:19:05,909 - 15808 - hummingbot.connector.exchange.liquid.liquid_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-08-25 16:19:05,909 - 15808 - hummingbot.connector.exchange.liquid.liquid_exchange - WARNING - This exchange connector does not provide trades feed. Strategies which depend on it will not work properly.
2022-08-25 16:19:05,911 - 15808 - hummingbot.connector.exchange.liquid.liquid_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hbot1/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    ws: WSAssistant = await self._connected_websocket_assistant()
  File "/home/ubuntu/hummingbot/hbot1/hummingbot/core/data_type/order_book_tracker_data_source.py", line 182, in _connected_websocket_assistant
    raise NotImplementedError
NotImplementedError
2022-08-25 16:19:06,149 - 15808 - hummingbot.connector.exchange.liquid.liquid_exchange - ERROR - Error parsing the trading_pair rule ARE-BTC. Skipping.
Traceback (most recent call last):
  File "hummingbot/connector/exchange/liquid/liquid_exchange.pyx", line 492, in hummingbot.connector.exchange.liquid.liquid_exchange.LiquidExchange._format_trading_rules
    min_base_increment = math.pow(10, -rule.get("assets_precision", Constants.DEFAULT_ASSETS_PRECISION))
AttributeError: 'NoneType' object has no attribute 'get'
2022-08-25 16:19:06,244 - 15808 - hummingbot.connector.exchange.liquid.liquid_order_book_tracker - INFO - Initialized order book for BTC-USDT. 1/1 completed.
2022-08-25 16:19:07,731 - 15808 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-08-25 16:19:10,913 - 15808 - hummingbot.connector.exchange.liquid.liquid_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/hummingbot/hbot1/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    ws: WSAssistant = await self._connected_websocket_assistant()
  File "/home/ubuntu/hummingbot/hbot1/hummingbot/core/data_type/order_book_tracker_data_source.py", line 182, in _connected_websocket_assistant
    raise NotImplementedError
NotImplementedError

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
[log_conf.zip](https://github.com/hummingbot/hummingbot/files/9426690/log_conf.zip)

**Comment by rapcmia** [comment]
Liquid connector has been removed
