### ISSUE TITLE
Bitmart PureMM Strategy: Market connectors are not ready.

### ISSUE THREAD

**Issue by ethereumnitrate** [hummingbot/hummingbot#5660]
**Describe the bug**
// A clear and concise description of what the bug is.
When trying to run the pure market making strategy on bitmart, it gives the following errors on the right panel:
              pure_market_making - Markets are not ready. No market making trades are permitted.
 
When running the "status" command, I get the following:
                Market connectors are not ready.

I am able to query my balance and get the correct balance on bitmart. I am also able to see "Yes" for both Keys Added and Keys confirmed when I run the "connect" command.        

**Steps To Reproduce**
// A concise description of the **steps to reproduce the buggy behavior**:

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters ( See Screen shot)
    https://discord.com/channels/530578568154054663/1015211243931455518/1015213454866522204
2. Just type in start
3. Type in status
...

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
// Include your bot's version number (Can be found at the upper left corner of your CLI).
Version: 1.7.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
2022-09-02 12:50:19,275 - 5267 - hummingbot.connector.exchange.bitmart.bitmart_exchange.BitmartExchange - ERROR - Error parsing the trading pair rule {'symbol': 'MAKI_USDT', 'symbol_id': 1585, 'base_currency': 'MAKI', 'quote_currency': 'USDT', 'quote_increment': '0.01', 'base_min_size': '0.010000000000000000000000000000', 'price_min_precision': 1, 'price_max_precision': 4, 'expiration': 'NA', 'min_buy_amount': '5.000000000000000000000000000000', 'min_sell_amount': '5.000000000000000000000000000000', 'trade_status': 'trading'}. Skipping.
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 243, in _format_trading_rules
    max_order_size=Decimal(str(rule["base_max_size"])),
KeyError: 'base_max_size'
2022-09-02 12:50:19,275 - 5267 - hummingbot.connector.exchange.bitmart.bitmart_exchange.BitmartExchange - ERROR - Error parsing the trading pair rule {'symbol': 'MRHB_USDT', 'symbol_id': 2295, 'base_currency': 'MRHB', 'quote_currency': 'USDT', 'quote_increment': '1', 'base_min_size': '1.000000000000000000000000000000', 'price_min_precision': 3, 'price_max_precision': 6, 'expiration': 'NA', 'min_buy_amount': '5.000000000000000000000000000000', 'min_sell_amount': '5.000000000000000000000000000000', 'trade_status': 'trading'}. Skipping.
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 243, in _format_trading_rules
    max_order_size=Decimal(str(rule["base_max_size"])),
KeyError: 'base_max_size'
2022-09-02 12:50:19,545 - 5267 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for QLINDO-USDT. 1/1 completed.
2022-09-02 12:51:07,288 - 5267 - hummingbot.connector.exchange.bitmart.bitmart_api_user_stream_data_source.BitmartAPIUserStreamDataSource - ERROR - Unexpected error while listening to user stream. Retrying after 5 seconds...
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/core/data_type/user_stream_tracker_data_source.py", line 48, in listen_for_user_stream
    await self._process_websocket_messages(websocket_assistant=self._ws_assistant, queue=output)
  File "/root/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_api_user_stream_data_source.py", line 83, in _process_websocket_messages
    async for ws_response in websocket_assistant.iter_messages():
  File "/root/hummingbot/hummingbot/core/web_assistant/ws_assistant.py", line 69, in iter_messages
    response = await self._connection.receive()
  File "/root/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 62, in receive
    msg = await self._process_message(msg)
  File "/root/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 84, in _process_message
    msg = await self._check_msg_types(msg)
  File "/root/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 89, in _check_msg_types
    msg = await self._check_msg_closed_type(msg)
  File "/root/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 99, in _check_msg_closed_type
    raise ConnectionError(
ConnectionError: The WS connection was closed unexpectedly. Close code = 1006 msg data: None
2022-09-02 12:51:12,695 - 5267 - hummingbot.connector.exchange.bitmart.bitmart_api_user_stream_data_source.BitmartAPIUserStreamDataSource - INFO - Subscribed to private account and orders channels...
2022-09-02 13:00:00,001 - 5267 - hummingbot.strategy.pure_market_making.pure_market_making - WARNING - Markets are not ready. No market making trades are permitted.

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by andydemeulemeester** [comment]
![image](https://user-images.githubusercontent.com/5653918/188180990-005d2eb2-fc46-4cde-8e6e-f847045400ab.png)

Experiencing the same lately, connecting to bitmart works, but at the end it says market connectors are not ready.
Even with version 0.46.0 the same issue.
Bitmart changed something?

**Comment by CaufieldZ** [comment]
BitMart removed the base_max_size field. I heard from their developers that this value has long been deprecated, so it was removed from OpenAPI.

**Comment by PeterCHK** [comment]
As a temporary fix, replace all base_max_size with 99999999999999.

**Comment by ethereumnitrate** [comment]
> As a temporary fix, replace all base_max_size with 99999999999999.

Is this done via the code, and then recompile, or is there a setting on the HB CLI that we can do this?

**Comment by ethereumnitrate** [comment]
Some additional information. All evidence points to what PeterCHK and CaufieldZ say:

From Log File:
  File "/root/hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py", line 243, in _format_trading_rules
    max_order_size=Decimal(str(rule["base_max_size"])),
KeyError: 'base_max_size'

**Comment by ethereumnitrate** [comment]
For anyone that has the same issue, I was able to get it running by doing the following:
On Ubuntu 18.04

1. Go to the file /hummingbot/hummingbot/connector/exchange/bitmart/bitmart_exchange.py 
2. On line 243, change the following line:
    max_order_size=Decimal(str(rule["base_max_size"]))
   to
     max_order_size=Decimal(999999999999999)
3. recompile by going to your ~/hummingbot directory, and run: ./compile
4. Start the hummingbot: ./bin/hummingbot.py

This ran without the error, and it was able to start my strategy.

**Comment by PeterCHK** [comment]
@CaufieldZ yes, you can follow @ethereumnitrate's method of recompiling. 
For me, I was using docker, I went inside the docker "docker exec -it <container_id> bash", then changed the max_order_size, using step 1 and 2 of what @ethereumnitrate proposed. 
Then restarted the docker container. "docker restart <container_id>" and "docker attach <container_id>"

**Comment by andydemeulemeester** [comment]
Thank you @ethereumnitrate and @PeterCHK. This fix works

**Comment by yahah1461** [comment]
> @CaufieldZ yes, you can follow @ethereumnitrate's method of recompiling. For me, I was using docker, I went inside the docker "docker exec -it <container_id> bash", then changed the max_order_size, using step 1 and 2 of what @ethereumnitrate proposed. Then restarted the docker container. "docker restart <container_id>" and "docker attach <container_id>"

Can you tell me exactly, how you did it? Having a hard time here

**Comment by ethereumnitrate** [comment]
> > @CaufieldZ yes, you can follow @ethereumnitrate's method of recompiling. For me, I was using docker, I went inside the docker "docker exec -it <container_id> bash", then changed the max_order_size, using step 1 and 2 of what @ethereumnitrate proposed. Then restarted the docker container. "docker restart <container_id>" and "docker attach <container_id>"
> 
> Can you tell me exactly, how you did it? Having a hard time here

How are you running HB? My solution is good if you're running from source and compiling.

**Comment by fengtality** [comment]
Bounty

Sponsor: Firo
Bounty Amount: 200 USDT
Developer Payment: 160 USDT (80%)
Status: OPEN

**Comment by tomasgaudino** [comment]
hi there! can i take this one?

**Comment by fengtality** [comment]
Yes, this bounty is assigned to @tomasgaudino. Please try to provide updates here on your progress

**Comment by tomasgaudino** [comment]
Thanks! I've just opened this PR: https://github.com/hummingbot/hummingbot/pull/6573

But I told fede not to merge yet because i only could make it work upgrading the endpoint from v1 to v2, and v4 is available. Next week I'll confirm is v4 is working

**Comment by fengtality** [comment]
thanks, so fast!! supporting v4 may not be in scope for this bounty, as
long as it solves issue. we'll ask bounty sponsor to test this PR

**Comment by tomasgaudino** [comment]
ok then! one important aspect to consider before merging is that using v2 forces the connector to replace client order id with exchange order id, and fede told me that the best practice is to keep the client one. as soon we solve that i'll provide updates 🦾

**Comment by nikspz** [comment]
Closing this bounty as paid. 
Fix available on latest development and release 1.20.0
