### ISSUE TITLE
Perp MM clock error with order override 

### ISSUE THREAD

**Issue by 0x100x** [hummingbot/hummingbot#5704]
trying to do order_override in my perp market making config. upon setting the config to true and adding the fields, it returns clock error.
![unknown](https://user-images.githubusercontent.com/113479113/190035979-944d08fc-739f-426f-850a-b1a5bd9f9910.png)
![image](https://user-images.githubusercontent.com/113479113/190036012-58b2596e-a56b-40d3-bb6c-eb7331ba6dba.png)

**Comment by 0x100x** [comment]
2022-08-31 22:03:40,001 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/home/hummingbot/hummingbot/strategy/perpetual_market_making/perpetual_market_making.py", line 501, in tick
    proposal = self.create_base_proposal()
  File "/home/hummingbot/hummingbot/strategy/perpetual_market_making/perpetual_market_making.py", line 652, in create_base_proposal
    if order_override is not None and len(order_override) > 0:
TypeError: object of type 'bool' has no len()

**Comment by nikspz** [comment]
Works on bot ver 1.7.0
[conf_perpetual_market_making_1.txt](https://github.com/hummingbot/hummingbot/files/9595151/conf_perpetual_market_making_1.txt)

![image](https://user-images.githubusercontent.com/83953535/190925596-fda1c1da-3cd8-4b6e-82f1-b71822920966.png)
![image](https://user-images.githubusercontent.com/83953535/190925601-d33df714-9dc7-447b-9c86-194f68949df1.png)

Works on Latest development (1.8.0)
[conf_perpetual_market_making_dev.txt](https://github.com/hummingbot/hummingbot/files/9595152/conf_perpetual_market_making_dev.txt)
![image](https://user-images.githubusercontent.com/83953535/190925839-0dfd9c70-e9e0-4dab-875b-51a10f9b655a.png)
![image](https://user-images.githubusercontent.com/83953535/190925855-55947317-f734-405d-a24c-341bd2ca7ef8.png)
