### ISSUE TITLE
Gateway not starting with development docker

### ISSUE THREAD

**Issue by MementoRC** [hummingbot/hummingbot#5731]
**Describe the bug**
The Gateway fails to start from a development docker

**Steps To Reproduce**
Here are the steps to reproduce the issue (see attachments in the section below):
1. `create.sh` -> choose 'development'
2. In HB: `gateway create`
...

**Screenshots**
![image](https://user-images.githubusercontent.com/93164135/192121091-c0123052-fda1-4071-b36d-715977536d4e.png)

**Release version**
dev-1.8.0

**Attachments**
No info in logs

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**

**Comment by MementoRC** [comment]
The gateway created has the same image name: `hummingbot/gateway-v2:gateway-v2-master` but creates the following error when started manually
```
Error: ENOENT: no such file or directory, copyfile '/usr/src/app/dist/src/templates/root.yml' -> '/usr/src/app/conf/root.yml'
    at Object.copyFileSync (node:fs:2792:3)
    at Function.getInstance (/usr/src/app/dist/src/services/config-manager-v2.js:184:30)
    at getLogPath (/usr/src/app/dist/src/services/logger.js:43:55)
    at Object.<anonymous> (/usr/src/app/dist/src/services/logger.js:49:18)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/usr/src/app/dist/src/templates/root.yml',
  dest: '/usr/src/app/conf/root.yml'
}
```

**Comment by rapcmia** [comment]
Hi @MementoRC good day to you, could you possibly try again our development branch and run the same steps how you encounter the issue? let us know if this works for you know since we updated the init.py back to `gateway-v2-dev` thanks

**Comment by MementoRC** [comment]
@rapcmia The steps above are working as expected in `dev-1.9.0` - The issue is resolved. It looks like the gateway logs are still not getting mounted, or maybe I am reading this incorrectly:
```docker run -it --log-opt max-size=10m --log-opt max-file=5 \
 --name $INSTANCE_NAME \
 --network host \
 --mount "type=bind,source=$CONF_FOLDER,destination=/conf/" \
 --mount "type=bind,source=$LOGS_FOLDER,destination=/logs/" \
 --mount "type=bind,source=$DATA_FOLDER,destination=/data/" \
 --mount "type=bind,source=$PMM_SCRIPTS_FOLDER,destination=/pmm_scripts/" \
 --mount "type=bind,source=$SCRIPTS_FOLDER,destination=/scripts/" \
 --mount "type=bind,source=$CERTS_FOLDER,destination=/home/hummingbot/.hummingbot-gateway/certs/" \
 --mount "type=bind,source=$GATEWAY_CONF_FOLDER,destination=/home/hummingbot/.hummingbot-gateway/conf/" \
 --mount "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock" \
 -e CONF_FOLDER="$CONF_FOLDER" \
 -e DATA_FOLDER="$DATA_FOLDER" \
 -e PMM_SCRIPTS_FOLDER="$PMM_SCRIPTS_FOLDER" \
 -e SCRIPTS_FOLDER="$SCRIPTS_FOLDER" \
 -e CERTS_FOLDER="$CERTS_FOLDER" \
 -e GATEWAY_LOGS_FOLDER="$GATEWAY_LOGS_FOLDER" \
 -e GATEWAY_CONF_FOLDER="$GATEWAY_CONF_FOLDER" \
 hummingbot/hummingbot:$TAG
}
```
