### ISSUE TITLE
Refresh nonce before send transaction

### ISSUE THREAD

**Issue by gzliudan** [hummingbot/hummingbot#5835]
**Feature Suggestion**
If we executed transaction in other wallet software, such as metamask, then switch to hummingbot and send transaction in hummingbot, hummingbot will report error like below:
```text
2022-10-26 11:46:32 | error |   nonce has already been used [ See: https://links.ethers.org/v5-errors-NONCE_EXPIRED ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":151,\"error\":{\"code\":-32000,\"message\":\"nonce too low\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf9016b1a843b9aca00832dc6c09490055edc794e839567a5631d42752db732e10c8f80b901048803dbee0000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000225bdb55d1b6288a719b00000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000d4ce02705041f04135f1949bc835c1fe0885513c0000000000000000000000000000000000000000000000000000000063590dad000000000000000000000000000000000000000000000000000000000000000200000000000000000000000034514748f86a8da01ef082306b6d6e738f777f5a0000000000000000000000005d5f074837f5d4618b3916ba74de1bf9662a3fed8188a0d2b1881f18c4d0cab20b8fc480eeda2a015948e84d468b6f45e1e4a3f1e6492ba00f13013e0b81626a773fe739cd80b074898b472e58f4680409fe1b095339b18e\"],\"id\":151,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.xinfin.network"}, method="sendTransaction", transaction="0xf9016b1a843b9aca00832dc6c09490055edc794e839567a5631d42752db732e10c8f80b901048803dbee0000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000225bdb55d1b6288a719b00000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000d4ce02705041f04135f1949bc835c1fe0885513c0000000000000000000000000000000000000000000000000000000063590dad000000000000000000000000000000000000000000000000000000000000000200000000000000000000000034514748f86a8da01ef082306b6d6e738f777f5a0000000000000000000000005d5f074837f5d4618b3916ba74de1bf9662a3fed8188a0d2b1881f18c4d0cab20b8fc480eeda2a015948e84d468b6f45e1e4a3f1e6492ba00f13013e0b81626a773fe739cd80b074898b472e58f4680409fe1b095339b18e", code=NONCE_EXPIRED, version=providers/5.6.8) | Error: nonce has already been used [ See: https://links.ethers.org/v5-errors-NONCE_EXPIRED ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":151,\"error\":{\"code\":-32000,\"message\":\"nonce too low\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf9016b1a843b9aca00832dc6c09490055edc794e839567a5631d42752db732e10c8f80b901048803dbee0000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000225bdb55d1b6288a719b00000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000d4ce02705041f04135f1949bc835c1fe0885513c0000000000000000000000000000000000000000000000000000000063590dad000000000000000000000000000000000000000000000000000000000000000200000000000000000000000034514748f86a8da01ef082306b6d6e738f777f5a0000000000000000000000005d5f074837f5d4618b3916ba74de1bf9662a3fed8188a0d2b1881f18c4d0cab20b8fc480eeda2a015948e84d468b6f45e1e4a3f1e6492ba00f13013e0b81626a773fe739cd80b074898b472e58f4680409fe1b095339b18e\"],\"id\":151,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.xinfin.network"}, method="sendTransaction", transaction="0xf9016b1a843b9aca00832dc6c09490055edc794e839567a5631d42752db732e10c8f80b901048803dbee0000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000225bdb55d1b6288a719b00000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000d4ce02705041f04135f1949bc835c1fe0885513c0000000000000000000000000000000000000000000000000000000063590dad000000000000000000000000000000000000000000000000000000000000000200000000000000000000000034514748f86a8da01ef082306b6d6e738f777f5a0000000000000000000000005d5f074837f5d4618b3916ba74de1bf9662a3fed8188a0d2b1881f18c4d0cab20b8fc480eeda2a015948e84d468b6f45e1e4a3f1e6492ba00f13013e0b81626a773fe739cd80b074898b472e58f4680409fe1b095339b18e", code=NONCE_EXPIRED, version=providers/5.6.8)
    at Logger.makeError (/home/node/hummingbot.xdc/gateway/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/node/hummingbot.xdc/gateway/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at checkError (/home/node/hummingbot.xdc/gateway/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:152:16)
    at StaticJsonRpcProvider.<anonymous> (/home/node/hummingbot.xdc/gateway/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:703:47)
    at step (/home/node/hummingbot.xdc/gateway/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/node/hummingbot.xdc/gateway/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/node/hummingbot.xdc/gateway/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

So I suggest renew nonce before send transaction, or set a expire time for nonce.

**Comment by fengtality** [comment]
This is bc Hummingbot has to handle nonces in order to continually manage the transactions it sends. That's why the wallet is mapped to each DEX connector. 

I recommend using a dedicated wallet for Hummingbot Gateway and not using it for manual trading.
