### ISSUE TITLE
Gateway-v2 - Unable to add wallet on some connectors causing "Unhandled error in background task"

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#5887]
**Describe the bug**
While checking development branch latest commit `785f70593621512` we found out that it does not let us setup wallet for gateway on some connectors causing `Unhandled error in background task: local variable 'wallet_account_id' referenced before assignment`

![image](https://user-images.githubusercontent.com/73840223/202074868-096e91cd-ecb9-48be-8478-b4ada998a78d.png)

```
2022-11-16 10:52:02,283 - 1549 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: local variable 'wallet_account_id' referenced before assignment
Traceback (most recent call last):
  File "/home/rapcmia/github/dev/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/rapcmia/github/dev/hummingbot/client/command/gateway_command.py", line 431, in _gateway_connect
    chain, network, wallet_private_key, id=wallet_account_id
UnboundLocalError: local variable 'wallet_account_id' referenced before assignment
```

The issue is noticeably affecting the following connectors but it does not happen on `Ref (near)`
- Uniswap ( mainnet, goerli, arbitrum_one, optimism and polygon)
- Avalanche (pangolin and tradejoe)
- Perpetual protocol (optimism)
- Mad Meerkat and VVS (cronos)

Last known working commit is `9d8c366148ebb1bd3f2ea2d018ddb1faf7ab6ec8`

**Steps To Reproduce**
1. Install latest development branch 
2. Setup source or docker gateway build
3. Setup wallet by running `gateway connect xxx` using the connectors above
4. Notice the error on the log panel

**Release version**
Development 1.10

**Attachments**
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/10017854/logs_hummingbot.log)

**Comment by rapcmia** [comment]
Fixed
