### ISSUE TITLE
Perpetual protocol - Getting AttributeError: 'ValueError' object has no attribute 'get'

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5902]
Bot returns an AttributeError: 'ValueError' object has no attribute 'get' after 4-10 hours of longrun

**Steps To Reproduce**
Clone and install latest dev branch
Create a spot-perpetual arbitrage using `perp` 
Start and run strategy for 4-10 hours till that issue showing

Actual:
Call to https://localhost:18230/amm/perp/position failed.
Bot returns an error 'ValueError' object has no attribute 'get' 

**Release version**
development-1.10.0

[logs_conf_spot_perpetual_arbitrage_1.log](https://github.com/hummingbot/hummingbot/files/10064297/logs_conf_spot_perpetual_arbitrage_1.log)
[58885.zip](https://github.com/hummingbot/hummingbot/files/10064295/58885.zip)

```2022-11-22 01:03:38,094 - 113294 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:18230/amm/perp/position failed. See logs for more details.
2022-11-22 01:03:38,095 - 113294 - GatewayEVMPerpetual - ERROR - 'ValueError' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/ubuntu/perp5885/hummingbot/connector/gateway/amm/gateway_evm_perpetual.py", line 456, in _status_polling_loop
    await safe_gather(
  File "/home/ubuntu/perp5885/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/perp5885/hummingbot/connector/gateway/amm/gateway_evm_perpetual.py", line 555, in update_positions
    trading_pair = f"{position.get('base')}-{position.get('quote')}"
AttributeError: 'ValueError' object has no attribute 'get'
2022-11-22 01:23:58,152 - 113294 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:18230/amm/perp/market-prices failed. See logs for more details.
2022-11-22 01:23:58,152 - 113294 - GatewayEVMPerpetual - WARNING - Error on POST https://localhost:18230/amm/perp/market-prices Error: {'message': 'Unknown error.', 'httpErrorCode': 500, 'errorCode': 1099, 'stack': 'Error: Unknown error.\n    at /usr/src/app/dist/src/connectors/perp/perp.controllers.js:24:19\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/dist/src/connectors/perp/perp.controllers.js:6:65)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
2022-11-22 02:43:57,557 - 113294 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:18230/amm/perp/position failed. See logs for more details.
2022-11-22 02:43:57,558 - 113294 - GatewayEVMPerpetual - ERROR - 'ValueError' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/ubuntu/perp5885/hummingbot/connector/gateway/amm/gateway_evm_perpetual.py", line 456, in _status_polling_loop
    await safe_gather(
  File "/home/ubuntu/perp5885/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/ubuntu/perp5885/hummingbot/connector/gateway/amm/gateway_evm_perpetual.py", line 555, in update_positions
    trading_pair = f"{position.get('base')}-{position.get('quote')}"
AttributeError: 'ValueError' object has no attribute 'get'
```

![image](https://user-images.githubusercontent.com/83953535/203234626-bf5aec64-7cb6-4f57-ab11-e9d4fbb92d91.png)

**Comment by rapcmia** [comment]
connector removed
