### ISSUE TITLE
Binance perpetual - Failed to connect API keys, getting NETWORK - Error getting server time. 

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#5914]
Note: For monitoring purpose

Bot showing NETWORK - Error getting server time. on the initial start. 
Failed to connect binance perpetual API keys

**Release version**
Development branch

**Steps To Reproduce**
1. Clone and install latest development branch
2. Start the bot
3. Pay attention to the log pane
4. try to connect binance_perpetual API keys

Actual:
Bot showing NETWORK - Error getting server time. on the initial start. 
Failed to connect binance_perpetual API keys

Expected:
No issues showing
You could connect binance_perpetual API keys successfully

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/10102169/logs_hummingbot.log)

```
2022-11-28 07:30:13,554 - 25016 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/ubuntu/development/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/ubuntu/development/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 250, in load_token_data
    tokens = await GatewayHttpClient.get_instance().get_tokens(self.chain, self.network)
  File "/home/ubuntu/development/hummingbot/core/gateway/gateway_http_client.py", line 300, in get_tokens
    return await self.api_request("get", f"{network_path}/tokens", {
  File "/home/ubuntu/development/hummingbot/core/gateway/gateway_http_client.py", line 174, in api_request
    client = self._http_client(self._client_config_map)
  File "/home/ubuntu/development/hummingbot/core/gateway/gateway_http_client.py", line 82, in _http_client
    ssl_ctx = ssl.create_default_context(cafile=f"{cert_path}/ca_cert.pem")
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/ssl.py", line 745, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
FileNotFoundError: [Errno 2] No such file or directory
2022-11-28 07:30:13,637 - 25016 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/home/ubuntu/development/hummingbot/connector/time_synchronizer.py", line 65, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/home/ubuntu/development/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_web_utils.py", line 125, in get_current_server_time
    response = await api_request(
  File "/home/ubuntu/development/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_web_utils.py", line 113, in api_request
    raise IOError(f"Error executing request {method.name} {path}. "
OSError: Error executing request GET /time. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
2022-11-28 07:30:13,639 - 25016 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
2022-11-28 07:30:14,197 - 25016 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source - ERROR - There was an error requesting exchange info (Error executing request GET /exchangeInfo. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
})
Traceback (most recent call last):
  File "/home/ubuntu/development/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_api_order_book_data_source.py", line 139, in init_trading_pair_symbols
    data = await web_utils.api_request(
  File "/home/ubuntu/development/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_web_utils.py", line 113, in api_request
    raise IOError(f"Error executing request {method.name} {path}. "
OSError: Error executing request GET /exchangeInfo. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/83953535/204224709-98e93d87-e753-4c97-a26c-8ff23a90a8a2.png)

**Comment by nikspz** [comment]
From developer position closing the issue would be okay, 
that’s expected behavior for binance since binance restricted in the US location.

Issue showed on AWS, now can't reproduce using AWS
![image](https://user-images.githubusercontent.com/83953535/204437851-51f562a3-8a16-46e2-ae9a-f244116c638e.png)
