### ISSUE TITLE
Mock servers are failing - http://127.0.0.1:50861/www.google.com/

### ISSUE THREAD

**Issue by Dmdv** [hummingbot/hummingbot#5933]
**Describe the bug**
Tests running in 'development' are failing with connection error.
At this moment this is blocking me from testing new exchange connector. 

**Steps To Reproduce**
```
git checkout development
./compile
```
```
make test
```

The error is related to this link

```
http://127.0.0.1:50861/www.google.com/
```

**Screenshots**

```
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'hummingbot.connector.exchange.huobi.huobi_order_book_tracker')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/nose/loader.py", line 416, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/centralex/hummingbot/hummingbot/test/hummingbot/connector/exchange/huobi/test_huobi_exchange.py", line 14, in <module>
    from hummingbot.connector.exchange.huobi.huobi_exchange import HuobiExchange
  File "hummingbot/connector/exchange/huobi/huobi_exchange.pyx", line 20, in init hummingbot.connector.exchange.huobi.huobi_exchange
ModuleNotFoundError: No module named 'hummingbot.connector.exchange.huobi.huobi_order_book_tracker'

======================================================================
ERROR: test_get_request_response (test.hummingbot.core.mock_api.test_mock_web_server.MockWebServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/centralex/hummingbot/hummingbot/test/hummingbot/core/mock_api/test_mock_web_server.py", line 47, in test_get_request_response
    r = requests.get("http://www.google.com/")
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "<string>", line 3, in request
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/unittest/mock.py", line 1146, in _execute_mock_call
    result = effect(*args, **kwargs)
  File "/Users/centralex/hummingbot/hummingbot/hummingbot/core/mock_api/mock_web_server.py", line 187, in reroute_request
    return MockWebServer.orig_session_request(self, method, str(a_url), **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=9099): Max retries exceeded with url: http://127.0.0.1:50861/www.google.com/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83e72e8ee0>: Failed to establish a new connection: [Errno 61] Connection refused')))
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: KqueueSelector
asyncio: ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f83e73660d0>
asyncio: ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f83e72dedc0>
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_query_string (test.hummingbot.core.mock_api.test_mock_web_server.MockWebServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f83e72e8580>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9099): Max retries exceeded with url: http://127.0.0.1:50861/www.google.com/?qs1=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83e72e8580>: Failed to establish a new connection: [Errno 61] Connection refused')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/centralex/hummingbot/hummingbot/test/hummingbot/core/mock_api/test_mock_web_server.py", line 67, in test_query_string
    r = requests.get("http://www.google.com/?qs1=1")
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "<string>", line 3, in request
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/unittest/mock.py", line 1146, in _execute_mock_call
    result = effect(*args, **kwargs)
  File "/Users/centralex/hummingbot/hummingbot/hummingbot/core/mock_api/mock_web_server.py", line 187, in reroute_request
    return MockWebServer.orig_session_request(self, method, str(a_url), **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=9099): Max retries exceeded with url: http://127.0.0.1:50861/www.google.com/?qs1=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83e72e8580>: Failed to establish a new connection: [Errno 61] Connection refused')))

======================================================================
ERROR: test_update_response (test.hummingbot.core.mock_api.test_mock_web_server.MockWebServerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f83e7399ac0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9099): Max retries exceeded with url: http://127.0.0.1:50861/www.google.com/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83e7399ac0>: Failed to establish a new connection: [Errno 61] Connection refused')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/centralex/hummingbot/hummingbot/test/hummingbot/core/mock_api/test_mock_web_server.py", line 53, in test_update_response
    r = requests.get("http://www.google.com/")
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "<string>", line 3, in request
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/unittest/mock.py", line 1146, in _execute_mock_call
    result = effect(*args, **kwargs)
  File "/Users/centralex/hummingbot/hummingbot/hummingbot/core/mock_api/mock_web_server.py", line 187, in reroute_request
    return MockWebServer.orig_session_request(self, method, str(a_url), **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=9099): Max retries exceeded with url: http://127.0.0.1:50861/www.google.com/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f83e7399ac0>: Failed to establish a new connection: [Errno 61] Connection refused')))

======================================================================
FAIL: test_market_became_wider (test.hummingbot.strategy.cross_exchange_market_making.test_cross_exchange_market_making_gateway.HedgedMarketMakingUnitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/hummingbot/lib/python3.8/unittest/mock.py", line 1348, in patched
    return func(*newargs, **newkeywargs)
  File "/Users/centralex/hummingbot/hummingbot/test/hummingbot/strategy/cross_exchange_market_making/test_cross_exchange_market_making_gateway.py", line 643, in test_market_became_wider
    self.assertEqual(1, len(self.strategy.active_maker_bids))
AssertionError: 1 != 0
    '1 != 0' = '%s != %s' % _common_shorten_repr(1, 0)
    '1 != 0' = self._formatMessage('1 != 0', '1 != 0')
>>  raise self.failureException('1 != 0')

-------------------- >> begin captured logging << --------------------
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: Markets are ready.
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: Conversion rates are ready. Trading started.
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: (COINALPHA-HBOT) Creating limit bid order for 3.0000 COINALPHA at 0.94527 HBOT. Current hedging price: 0.95000000 HBOT (Rate adjusted: 0.95000000 WHBOT). [clock=2019-01-01 00:00:05+00:00]
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: (COINALPHA-HBOT) Creating limit ask order for 3.0000 COINALPHA at 1.0553 HBOT. Current hedging price: 1.05000000 HBOT (Rate adjusted: 1.05000000 WHBOT). [clock=2019-01-01 00:00:05+00:00]
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: WHBOT-HBOT (fixed) conversion rate: 1
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: WCOINALPHA-COINALPHA (fixed) conversion rate: 1
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: COINALPHA-HBOT (fixed) conversion rate: 1
hummingbot.core.network_iterator: INFO: Network status has changed to NetworkStatus.CONNECTED. Starting networking...
hummingbot.core.event.event_reporter: EVENT_LOG: {"timestamp": 1546300805.0, "type": "OrderType.LIMIT", "trading_pair": "COINALPHA-HBOT", "amount": "3.0000", "price": "0.94527", "order_id": "buy://COINALPHA-HBOT/a8b2d3c51e7988855de3a54e7b", "creation_timestamp": 1546300805.0, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "mock_paper_exchange"}
hummingbot.core.event.event_reporter: EVENT_LOG: {"timestamp": 1546300805.0, "type": "OrderType.LIMIT", "trading_pair": "COINALPHA-HBOT", "amount": "3.0000", "price": "0.94527", "order_id": "buy://COINALPHA-HBOT/a8b2d3c51e7988855de3a54e7b", "creation_timestamp": 1546300805.0, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "mock_paper_decentralized_exchange"}
hummingbot.core.event.event_reporter: EVENT_LOG: {"timestamp": 1546300805.0, "type": "OrderType.LIMIT", "trading_pair": "COINALPHA-HBOT", "amount": "3.0000", "price": "1.0553", "order_id": "sell://COINALPHA-HBOT/82f83e3169f6d71972511ca8c1", "creation_timestamp": 1546300805.0, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "mock_paper_decentralized_exchange"}
hummingbot.core.event.event_reporter: EVENT_LOG: {"timestamp": 1546300805.0, "type": "OrderType.LIMIT", "trading_pair": "COINALPHA-HBOT", "amount": "3.0000", "price": "1.0553", "order_id": "sell://COINALPHA-HBOT/82f83e3169f6d71972511ca8c1", "creation_timestamp": 1546300805.0, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "mock_paper_exchange"}
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: (COINALPHA-HBOT) The current limit bid order for 3.0000 COINALPHA at 0.94527 HBOT is now below the suggested order price at 0.98507. Going to cancel the old order and create a new one... [clock=2019-01-01 00:01:40+00:00]
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: (COINALPHA-HBOT) Canceling the limit order buy://COINALPHA-HBOT/a8b2d3c51e7988855de3a54e7b. [clock=2019-01-01 00:01:40+00:00]
hummingbot.core.event.event_reporter: EVENT_LOG: {"timestamp": 1546300900.0, "order_id": "buy://COINALPHA-HBOT/a8b2d3c51e7988855de3a54e7b", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "mock_paper_exchange"}
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: DEBUG: Current buy order price=0.94527, suggested order price=0.98507 [clock=2019-01-01 00:01:40+00:00]
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: (COINALPHA-HBOT) The current limit ask order for 3.0000 COINALPHA at 1.0553 HBOT is now below the suggested order price at 1.0151. Going to cancel the old order and create a new one... [clock=2019-01-01 00:01:40+00:00]
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: INFO: (COINALPHA-HBOT) Canceling the limit order sell://COINALPHA-HBOT/82f83e3169f6d71972511ca8c1. [clock=2019-01-01 00:01:40+00:00]
hummingbot.core.event.event_reporter: EVENT_LOG: {"timestamp": 1546300900.0, "order_id": "sell://COINALPHA-HBOT/82f83e3169f6d71972511ca8c1", "exchange_order_id": null, "event_name": "OrderCancelledEvent", "event_source": "mock_paper_exchange"}
hummingbot.strategy.cross_exchange_market_making.cross_exchange_market_making: DEBUG: Current sell order price=1.0553, suggested order price=1.0151 [clock=2019-01-01 00:01:40+00:00]
hummingbot.logger.log_server_client: INFO: Network status has changed to NetworkStatus.CONNECTED. Starting networking...
hummingbot.logger.log_server_client: INFO: Network status has changed to NetworkStatus.CONNECTED. Starting networking...
hummingbot.core.network_iterator: INFO: Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking...
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 2987 tests in 250.779s
```

**Release version**
Development branch

**Comment by nikspz** [comment]
Hey @Dmdv, can't reproduce on the latest development (dev-1.11.0 using AWS Ubuntu Source)

[screen.log](https://github.com/hummingbot/hummingbot/files/10183711/screen.log)
![image](https://user-images.githubusercontent.com/83953535/206401124-0ccd7683-d4fc-4f48-a156-05ef4851016d.png)


You could try latest development for it. Also possible version could be your location restrictions or environment/bot version
