### ISSUE TITLE
Custom API Feature not working in Pure Market Making

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#5981]
**Describe the bug**
The feature that allows you to get the price from an external API is not working in PMM.

**Steps To Reproduce**
1. Create a PMM strategy
2. Change the config of price source for custom api
3. Select the url of an API that retrieves the price of the asset that you are trading. (In my case I created a simple API with FastAPI)
4. Run the strategy

**Release version**
Dev-1.12.0

**Logs**
`2022-12-26 16:30:46,130 - 2958 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/strategy/pure_market_making/start.py", line 93, in start
    ext_market = create_paper_trade_market(exchange, [raw_trading_pair])
TypeError: create_paper_trade_market() missing 1 required positional argument: 'trading_pairs'
2022-12-26 16:30:46,131 - 2958 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2022-12-26 16:30:46,133 - 2958 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2022-12-26 16:30:46,173 - 2958 - hummingbot.core.network_iterator - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-12-26 16:30:47,918 - 2958 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for BTC-USDT. 1/1 completed.
2022-12-26 16:30:47,953 - 2958 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source.BinanceAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2022-12-26 16:30:51,370 - 2958 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2022-12-26 16:32:23,313 - 2958 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2022-12-26 16:32:23,315 - 2958 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/client/command/stop_command.py", line 39, in stop_loop
    self.clock.remove_iterator(self.strategy)
  File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
    self._child_iterators.remove(iterator)
ValueError: list.remove(x): x not in list
2022-12-26 16:33:16,112 - 2958 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2022-12-26 16:33:16,113 - 2958 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: list.remove(x): x not in list
Traceback (most recent call last):
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/client/command/stop_command.py", line 39, in stop_loop
    self.clock.remove_iterator(self.strategy)
  File "hummingbot/core/clock.pyx", line 83, in hummingbot.core.clock.Clock.remove_iterator
    self._child_iterators.remove(iterator)
ValueError: list.remove(x): x not in list`

**Comment by MementoRC** [comment]
Is this opened as a bounty or is this something that @cardosofede is working on? Is there a bounty for it?

**Comment by cardosofede** [comment]
@MementoRC I already fix this, but there is no bounty associated to that

**Comment by MementoRC** [comment]
@cardosofede It would be good if it did not show-up in the `Open Bounties` category

**Comment by MementoRC** [comment]
@rapcmia THis somehow is still on the Bounty board, just FYI

**Comment by nikspz** [comment]
Fix has been deployed to development branch and will be available on the next release version 1.12.0.
