### ISSUE TITLE
uniswap-mainnet - Error submitting approval order for tokens, workaround: aprove manually on uniswap

### ISSUE THREAD

**Issue by varche1** [hummingbot/hummingbot#5990]
**Describe the bug**
The `amm_arb` strategy could not be run because `/evm/approve` fails with the error: Error submitting approval order for USDT on uniswap-mainnet.

There are enough funds at https://etherscan.io/address/0xbca8c16af62e799d6d0f667e653efae7ef735807

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. `$ git checkout v1.11.0`
2. `$ docker build --file=Dockerfile.arm --tag=hummingbot .`
3. 
```
$ docker run -it --log-opt max-size=10m --log-opt max-file=5 --network host --name hummingbot-instance \
--mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_conf,destination=/conf/" \
--mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_logs,destination=/logs/" \
--mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_data,destination=/data/" \
--mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_scripts,destination=/scripts/"  \
--mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_certs,destination=/home/hummingbot/.hummingbot-gateway/certs/"  \
--mount "type=bind,source=$(pwd)/hummingbot_files/gateway_conf,destination=/gateway-conf/" \
--mount "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock" \
-e CERTS_FOLDER="$(pwd)/hummingbot_files/hummingbot_certs" \
-e GATEWAY_LOGS_FOLDER="$(pwd)/hummingbot_files/gateway_logs" \
-e GATEWAY_CONF_FOLDER="$(pwd)/hummingbot_files/gateway_conf" \
hummingbot
```
4. Create gateway (as usual. [The result](https://share.cleanshot.com/rNwQ84Fg) is `Gateway: ONLINE`)
5. Add `uniswap` to gateway. The result:
<img width="599" alt="CleanShot 2022-12-29 at 17 43 11@2x" src="https://user-images.githubusercontent.com/1057853/209976503-6c8c2634-90d6-44c3-b8d6-7b163bce90ca.png">

6. Add `binance` exchange
7. Check `balance`
<img width="426" alt="CleanShot 2022-12-29 at 17 45 14@2x" src="https://user-images.githubusercontent.com/1057853/209976758-ef7242f7-7848-4fd0-82d7-89e8fdc14e8b.png">

8. Create `amm_arb` strategy (config at the attachments) with defaults:
<img width="839" alt="CleanShot 2022-12-29 at 17 47 58@2x" src="https://user-images.githubusercontent.com/1057853/209977108-fc31a5ba-75d6-4710-94fd-502dc3cb56e0.png">

9. Start the strategy. Balances look good:
<img width="840" alt="CleanShot 2022-12-29 at 17 52 00@2x" src="https://user-images.githubusercontent.com/1057853/209977511-35a76775-08fb-4ad9-a122-a6592ef53b11.png">

10. Stop the strategy in a few minutes

There are a lot of errors like that (in hummingbot_files/hummingbot_logs/logs_conf_amm_arb_3.log):
```
2022-12-29 15:52:33,403 - 1 - GatewayEVMAMM - ERROR - Error submitting approval order for USDT on uniswap-mainnet.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 318, in approve_token
    resp: Dict[str, Any] = await self._get_gateway_instance().approve_token(
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 360, in approve_token
    return await self.api_request(
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 229, in api_request
    raise e
  File "/home/hummingbot/hummingbot/core/gateway/gateway_http_client.py", line 217, in api_request
    raise ValueError(f"Error on {method.upper()} {url} Error: {parsed_response}")
ValueError: Error on POST https://localhost:16237/evm/approve Error: {'message': 'Unknown error.', 'httpErrorCode': 503, 'errorCode': 1099, 'stack': 'Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\\"jsonrpc\\":\\"2.0\\",\\"id\\":1496,\\"error\\":{\\"code\\":-32000,\\"message\\":\\"insufficient funds for gas * price + value\\"}}","error":{"code":-32000},"requestBody":"{\\"method\\":\\"eth_sendRawTransaction\\",\\"params\\":[\\"0x02f8b20180850c570bd200850c570bd200832dc6c094dac17f958d2ee523a2206206994597c13d831ec780b844095ea7b300000000000000000000000068b3465833fb72a70ecdf485e0e4c7bd8665fc45ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc080a0d20539f328d1d7d2d195ae7f98abb10f3ef138f21b7338e8210ab4f93b10455fa03a7224f3d06c5ac38a2c29aaad4cc70af5833bc8ac6589df524bfffda34f713b\\"],\\"id\\":1496,\\"jsonrpc\\":\\"2.0\\"}","requestMethod":"POST","url":"https://mainnet.infura.io/v3/df570986c2d84cbca09c11c78745ba30"}, method="sendTransaction", transaction="0x02f8b20180850c570bd200850c570bd200832dc6c094dac17f958d2ee523a2206206994597c13d831ec780b844095ea7b300000000000000000000000068b3465833fb72a70ecdf485e0e4c7bd8665fc45ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc080a0d20539f328d1d7d2d195ae7f98abb10f3ef138f21b7338e8210ab4f93b10455fa03a7224f3d06c5ac38a2c29aaad4cc70af5833bc8ac6589df524bfffda34f713b", code=INSUFFICIENT_FUNDS, version=providers/5.6.8)\n    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:233:21)\n    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:242:20)\n    at checkError (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:144:16)\n    at StaticJsonRpcProvider.<anonymous> (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:703:47)\n    at step (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'}
```

There is a log in the gateway's log file (hummingbot_files/gateway_logs/logs_gateway_app.log.2022-12-29) that looks suspicious:
```
2022-12-30 05:12:48 | info | 	Calling approve method called for spender 0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45 requesting allowance 115792089237316195423570985008687907853269984665640564039457584007913129639935 from owner 0xBCA8C16af62E799D6d0F667e653Efae7Ef735807. | undefined
```

Looks like we call approve for amount equals `115792089237316195423570985008687907853269984665640564039457584007913129639935`

I've try to patch `/evm/approve` call to provide smaller amount of USDT/WETH, but it didn't help.

I'm pretty sure 0.1 ETH is enough for the `approve` operation, isn't it?

_Maybe the following information is important. Maybe not:_
I've tried several wallets:

- `0xbca8c16af62e799d6d0f667e653efae7ef735807` doesn't have any uniswap operation yet
- `0xe4784f34b8bAc19DDF1A64Bd83f9D2eD63D0e23c` has several uniswap operations. The problem is the same

...

**Screenshots**
see `Steps To Reproduce` section. Overview is:
<img width="1728" alt="CleanShot 2022-12-29 at 18 03 36@2x" src="https://user-images.githubusercontent.com/1057853/209978927-0c3a46ed-a7b3-4c52-98f7-c97b5f5db069.png">

**Release version**
v1.11.0

**Attachments**
[logs_conf_amm_arb_3.log](https://github.com/hummingbot/hummingbot/files/10320380/logs_conf_amm_arb_3.log)
[gateway.log](https://github.com/hummingbot/hummingbot/files/10320385/gateway.log)
[conf_amm_arb_3_yml.txt](https://github.com/hummingbot/hummingbot/files/10320395/conf_amm_arb_3_yml.txt)
[conf_client_yml.txt](https://github.com/hummingbot/hummingbot/files/10320399/conf_client_yml.txt)
[gateway_connections_json.txt](https://github.com/hummingbot/hummingbot/files/10320404/gateway_connections_json.txt)

*WARNING: Do NOT publish any exchange API keys or your wallet's private key. Whoever has access to them may steal your assets!*

**Optional: your discord username:**
ivangureev#0116

**Comment by varche1** [comment]
I have handled the problem but not the way It should be handled: I used a uniswap application (https://app.uniswap.org/#/swap) and tried to swap USDT -> ETH. Uniswap asked me to make a approve transaction. I did it for

- USDT: https://etherscan.io/tx/0x90bcbfe140fc9946a0d06b08a46ce3537403a080dcb9544ec5b7f0e956f3bacc
- WEHT: https://etherscan.io/tx/0xb1f1d70b4d6905b59b00484117f0e5d0c12a07c30c0a5d6a1905af5e48c0a302

Just by approving at MetaMask. Transaction costs was less 1$ each.

Looks like Hummingbot constructs a wrong Ethereum transaction for approve method.

After I did it, the strategy started well:
<img width="1728" alt="CleanShot 2022-12-29 at 18 59 43@2x" src="https://user-images.githubusercontent.com/1057853/209985117-8e16fe44-f233-422d-b8a3-92889ce0c5b2.png">

**Comment by rapcmia** [comment]
There are instances like this happens for approve-token command, therefore manually approve the tokens are recommended.
