### ISSUE TITLE
"Price query failed" if quickswap's pair is on quickswap v3

### ISSUE THREAD

**Issue by akolotov** [hummingbot/hummingbot#5992]
**Describe the bug**
Ran `amb_arb` strategy between `WETH-BOB/uniswap_polygon_mainnet` and `WETH-BOB/quickswap_polygon_mainnet` when the bot started the gateway reports about an error:
``` 
Price query failed: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getReserves()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4) | Error: Price query failed: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getReserves()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
    at /usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:74:23
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
After some research I have figured out that the issue happens in the connector `quickswap` -- it works only with V2 pools whereas the pair "WETH-BOB" exists on QuickSwapV3. Upgrade of Quickswap SDK did not help since V3 it has no support of V3 either.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Create and configure the gateway to communicate to uniswap and quickswap. 
2. `gateway config polygon.networks.mainnet.tokenListType URL`
3. `gateway config polygon.networks.mainnet.tokenListSource https://token-list.sushi.com/`
4. Start the gateway
5. Configure `amm_arb` strategy to monitor pairs WETH-BOB on uniswap and quickswap.
6. Wait for market readiness. 

**Screenshots**
![image](https://user-images.githubusercontent.com/20793260/210070662-e4ff91d2-56aa-4204-8957-77f725b5bdb4.png)

**Release version**
1.11.0

**Attachments**
I have modified a bit the connectors for uniswap and quickswap to be more verbose so they allow to see which call of `estimateSellTrade` or `estimateBuyTrade` fails.
The attached log: [logs_gateway_app.log.2022-12-30.log](https://github.com/hummingbot/hummingbot/files/10324767/logs_gateway_app.log.2022-12-30.log)

**Optional: your discord username:**
Alexander Kolotov#0291

**Comment by nikspz** [comment]
hey @akolotov we're currently making changes to approval handling.
Could you please share what rate oracle source you use? 
Also config or config screenshot could help to triage the issue

**Comment by akolotov** [comment]
@nikspz 
> Could you please share what rate oracle source you use?

I did not configure any rate oracle specifically.

> Also config or config screenshot could help to triage the issue

```
# cat data/gateway_conf/polygon.yml 
networks:
  mainnet:
    chainID: 137
    nodeURL: https://polygon-mainnet.infura.io/v3/d.......5
    tokenListType: URL
    tokenListSource: https://token-list.sushi.com/
    nativeCurrencySymbol: MATIC
  mumbai:
    chainID: 80001
    nodeURL: https://rpc.ankr.com/polygon_mumbai
    tokenListType: FILE
    tokenListSource: src/chains/polygon/polygon_tokens_mumbai.json
    nativeCurrencySymbol: MATIC
manualGasPrice: 100
gasLimitTransaction: 3000000
```

```
# cat data/hummingbot_conf/gateway_connections.json 
[{"connector": "uniswap", "chain": "polygon", "network": "mainnet", "trading_type": "EVM_AMM", "wallet_address": "0xcafecafecafecafecafecafecafecafecafecafe", "additional_spenders": []}, {"connector": "quickswap", "chain": "polygon", "network": "mainnet", "trading_type": "EVM_AMM", "wallet_address": "0xcafecafecafecafecafecafecafecafecafecafe", "additional_spenders": []}]
```

```
# cat data/hummingbot_conf/strategies/conf_amm_arb_pol_weth-bob.yml
##########################################
###   AMM Arbitrage strategy config   ###
##########################################

template_version: 5
strategy: amm_arb

# The following configurations are only required for the AMM arbitrage trading strategy

# Connectors and markets parameters
connector_1: uniswap_polygon_mainnet
market_1: WETH-BOB
connector_2: quickswap_polygon_mainnet
market_2: WETH-BOB

order_amount: 1.7

# Minimum profitability target required to place an order
# Expressed in percentage value, e.g. 1 = 1% target profit
min_profitability: 0.1

# A buffer for which to adjust order price for higher chance of the order getting filled.
# This is important for AMM which transaction takes a long time where a slippage is acceptable rather having
# the transaction get rejected. The submitted order price will be adjust higher (by percentage value) for buy order
# and lower for sell order. (Enter 1 for 1%)
market_1_slippage_buffer: 0.5

# A buffer to add to the price to account for slippage when buying/selling on second connector market
# (Enter 1 for 1%)
market_2_slippage_buffer: 0.5

# A flag (true/false), if true the bot submits both arbitrage taker orders (buy and sell) simultaneously
# If false, the bot will wait for first exchange order filled before submitting the other order
concurrent_orders_submission: true

# A flag (true/false), if true would enable a price shim feature on the AMM connector to allow developer to simulate
# different prices on the AMM market. This is used for development and testing purpose only.
debug_price_shim: false

# After how many seconds should blockchain transactions be cancelled if they are not included in a block?
gateway_transaction_cancel_interval: 300
```

**Comment by rapcmia** [comment]
Hi @akolotov good day
There has not been any much  update for quickswap other than the changes for tokenlistsource for most of gateway connectors. Looks like there would be a need for an update to add the v3 to this connector and we strongly suggest if you can take part of our [January poll](https://discord.com/channels/530578568154054663/1054516248014233610) for nomination of issues and PRs for the release 1.12

**Comment by nikspz** [comment]
Similar issue with approval on uniswap polygon
https://github.com/hummingbot/hummingbot/issues/6375

**Comment by rapcmia** [comment]
Gateway has been updated as of version 2.3.0 focusing on chains Ethereum and Solana. 
Quickswap has been removed from supported AMM connectors
