### ISSUE TITLE
Eve - Error on requesting exchange info

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6000]
**Describe the bug**

Note: _For monitoring purpose only, issue does not affect the other connectors nor the client_

Getting error at the start of the client for Eve exchange `There was an error requesting exchange info`

![image](https://user-images.githubusercontent.com/73840223/210692004-681f3abc-88d2-475c-adfc-43fa5b111d5c.png)

```
2023-01-05 10:58:24,273 - 4165 - hummingbot.connector.exchange.eve.eve_exchange.EveExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rapcmia/github/dev/hummingbot/connector/utilities/oms_connector/oms_connector_exchange.py", line 532, in _initialize_trading_pair_symbol_map
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path, params=params)
  File "/home/rapcmia/github/dev/hummingbot/connector/exchange_py_base.py", line 845, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/rapcmia/github/dev/hummingbot/connector/utilities/oms_connector/oms_connector_exchange.py", line 507, in _api_request
    return await rest_assistant.execute_request(
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/rest_assistant.py", line 66, in execute_request
    response = await self.call(request=request, timeout=timeout)
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/rest_assistant.py", line 84, in call
    resp = await wait_for(self._connection.call(request), timeout)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/connections/rest_connection.py", line 10, in call
    aiohttp_resp = await self._client_session.request(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.eve.apstage.net:443 ssl:default [Name or service not known]
2023-01-05 10:58:25,940 - 4165 - hummingbot.connector.exchange.eve.eve_exchange.EveExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/rapcmia/github/dev/hummingbot/connector/utilities/oms_connector/oms_connector_exchange.py", line 532, in _initialize_trading_pair_symbol_map
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path, params=params)
  File "/home/rapcmia/github/dev/hummingbot/connector/exchange_py_base.py", line 845, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/rapcmia/github/dev/hummingbot/connector/utilities/oms_connector/oms_connector_exchange.py", line 507, in _api_request
    return await rest_assistant.execute_request(
  File "/home/rapcmia/github/dev/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://apieve.cdnhop.net/AP/GetInstruments. HTTP status is 404. Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>
```

**Steps To Reproduce**
- Start the Hummingbot client

**Release version**
1.11.0 and development branch

**Comment by nikspz** [comment]
Closing this ticket since eve connector was removed from the Client with https://github.com/hummingbot/hummingbot/pull/6017 in 1.12 Release
