### ISSUE TITLE
can't connect to kraken exchange

### ISSUE THREAD

**Issue by Ortalr** [hummingbot/hummingbot#6053]
```connect kraken``` results in an exception:

2023-02-01 16:23:39,553 - 1 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: local variable 'connector_config' referenced before assignment
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/connect_command.py", line 63, in connect_exchange
    await self._perform_connect(connector_config)
UnboundLocalError: local variable 'connector_config' referenced before assignment

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. new HB instance, docker, v1.12.0
2. connect kraken

**Screenshots**
// If applicable, add screenshots to help explain your problem.

**Release version**
1.12.0

**Optional: your discord username:**
Ortal

**Comment by tenebreux** [comment]
Same problem here.

**Comment by MementoRC** [comment]
@rapcmia The issue was identified, this is not a potential "Bounty" correct? Anyway, it seems to be a hasty commit that introduced this bug just for Kraken

**Comment by rapcmia** [comment]
Hi @MementoRC good day,
Yes it was decided that HF would not add bounties for community fix for `BRONZE` connectors however it is possible for anyone from the community can host the amount to open a bounty. I check the issue and seems to be on the setup itself for the connector, Ill try to check with our team about it but we can't open a bounty for it. Thank you again for your time

**Comment by MementoRC** [comment]
@rapcmia The issue is a simple indentation (or addition of `else:` clause) that segregates the `connector_config` variable for Kraken
