### ISSUE TITLE
AMM Arb v1 -  'InFlightOrder' object has no attribute 'is_approval_request' upon quickstart

### ISSUE THREAD

**Issue by sytranvn** [hummingbot/hummingbot#6081]
**Describe the bug**
Cannot quickstart `amm_arb` if database having hanging orders.

**Steps To Reproduce**

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up `amm_arb` strategy and start trading
2. After some orders created, stop and exit hummingbot (this step need some orders aren't cancelled)
3. Quick start hummingbot
4. Strategy logs error
```
2023-02-10 16:59:12,075 - 29841 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'InFlightOrder' object has no attribute 'is_approval_request'
Traceback (most recent call last):
  File "/Users/sytd/Code/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/sytd/Code/hummingbot/hummingbot/strategy/amm_arb/amm_arb.py", line 242, in apply_gateway_transaction_cancel_interval
    await gateway.cancel_outdated_orders(self._gateway_transaction_cancel_interval)
  File "/Users/sytd/Code/hummingbot/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 1027, in cancel_outdated_orders
    o for o in self.approval_orders
  File "/Users/sytd/Code/hummingbot/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 167, in approval_orders
    return [
  File "/Users/sytd/Code/hummingbot/hummingbot/connector/gateway/amm/gateway_evm_amm.py", line 170, in <listcomp>
    if approval_order.is_approval_request
AttributeError: 'InFlightOrder' object has no attribute 'is_approval_request'
```

**Release version**
v1.12.0

**Attachments**
[logs_conf_amm_arb_2.log](https://github.com/hummingbot/hummingbot/files/10729227/logs_conf_amm_arb_2.log)

**Comment by sytranvn** [comment]
After debugging I found this is because when restore tracking state, orders were recreated as `InFlightOrder` instead of `EVMInFlightOrder`.
```py
    def restore_tracking_states(self, tracking_states: Dict[str, any]):
        """
        Restore in-flight orders from saved tracking states.
        :param tracking_states: a dictionary associating order ids with the serialized order (JSON format).
        """
        for serialized_order in tracking_states.values():
            order = InFlightOrder.from_json(serialized_order)
            if order.is_open:
                self.start_tracking_order(order)
```

**Comment by MementoRC** [comment]
@sytranvn Are you preparing a PR for this find?

**Comment by sytranvn** [comment]
@MementoRC not yet.  I thought about casting tracked orders in `start` function for AMM but I didn't try.

**Comment by fengtality** [comment]
Thanks for looking into this issue. I'll test out this as well and try to fix it in the next release

**Comment by sytranvn** [comment]
Thanks @fengtality . I know you are doing a big refactor with gateway. It's best if you can include this issue in your PR.

**Comment by cardosofede** [comment]
@fengtality is this solved or can I nominate it?

**Comment by fengtality** [comment]
@cardosofede yes, you can nominate it, and I think this is a good example of an issue that we should try to resolve.

**Comment by rapcmia** [comment]
Closing ticket, i am not able to reproduce this issue
