### ISSUE TITLE
Polygon 'Token not supported' error

### ISSUE THREAD

**Issue by overlordhu** [hummingbot/hummingbot#6099]
Whatever I do on Polygon, I always get "Token not supported"

Steps to reproduce:

- Created clean docker instance
- Created gateway with 'gateway create'
- Set up uniswap and uniswapLP with appropriate information and keys
- Created strategy with uni_v3_lp on pair WMATIC-USDC
- "start"

Release: latest / 1.12.0

log snippet:

...
2023-02-20 01:23:45 | error | 	Token not supported: WMATIC | Error: Token not supported: WMATIC
    at getFullTokenFromSymbol (/usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:303:15)
    at /usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:278:24
    at Generator.next (<anonymous>)
    at /usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:4:12)
    at poolPrice (/usr/src/app/dist/src/connectors/uniswap/uniswap.controllers.js:276:12)
    at /usr/src/app/dist/src/amm/amm.controllers.js:79:52
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/dist/src/amm/amm.controllers.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
...

**Comment by fengtality** [comment]
Moving this issue to new Gateway repo
