### ISSUE TITLE
Injective exchange - Failed to cancel order due to `Request failed with status code 503`

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6146]
**Release version**
dev-1.14.0

**Steps To Reproduce**

1. Create/start the strategy using [injective ](https://github.com/hummingbot/hummingbot/pull/6139)exchange
2. Check orders placed on injective
3. stop the bot and pay attention to the logs pane/exchange

Actual:
Bot Failed to cancel orders on the exchange (status code 503)

Expected:
Orders cancelled successfully after bot stopped
Bot could handle status code 503

[logs_injective-new-commit.log](https://github.com/hummingbot/hummingbot/files/10972753/logs_injective-new-commit.log)
[315.zip](https://github.com/hummingbot/hummingbot/files/10972751/315.zip)

```
2023-03-14 18:52:13,858 - 256261 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - NETWORK - Unexpected error cancelling orders.
Traceback (most recent call last):
  File "/home/ubuntu/batch6139/hummingbot/connector/exchange_py_base.py", line 409, in cancel_all
    cancellation_results = await safe_gather(*tasks, return_exceptions=True)
  File "/home/ubuntu/batch6139/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/batch6139/hummingbot/connector/exchange_py_base.py", line 416, in cancel_all
    successful_cancellations.append(CancellationResult(client_order_id, True))
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2023-03-14 18:52:13,859 - 256261 - hummingbot.connector.gateway.clob_spot.gateway_clob_spot.GatewayCLOBSPOT - WARNING - Failed to cancel order. Check API key and network connection.
```

![image](https://user-images.githubusercontent.com/83953535/225108495-0ad6b7ac-d192-4548-9945-6dd8a9cec6f5.png)

Note: 
Orders will be cancelled after restart of the bot and start the same strategy again

**Comment by rapcmia** [comment]
The latest updates for Injective protocol fixed this issue and will be available on the release of hummingbot version `1.16.0`
