### ISSUE TITLE
Docker Installation of 1.13.0 — KeyError: 'rate_oracle_source

### ISSUE THREAD

**Issue by 0xferit** [hummingbot/hummingbot#6169]
**Describe the bug**
During installation, the Docker image throws an error. And when you try to spin up the image, it exists immediately, probably because of this error.

Here is the error message after installation: 

```
Unable to find image 'hummingbot/hummingbot:latest' locally
latest: Pulling from hummingbot/hummingbot
b549f31133a9: Pull complete 
24ad61996a0e: Pull complete 
aea2e0bc1608: Pull complete 
4bd1ad19459c: Pull complete 
49526bcde3cc: Pull complete 
ff7c83bfcd61: Pull complete 
7c81c02050ce: Pull complete 
bf908c0bf22c: Pull complete 
a3577057616a: Pull complete 
430a8ec3d29d: Pull complete 
Digest: sha256:8cde749599146e4145d679dcb2a36ea2e31d7d559f18cef345e49c45b0411f17
Status: Downloaded newer image for hummingbot/hummingbot:latest
Traceback (most recent call last):
  File "bin/hummingbot_quickstart.py", line 157, in <module>
    fork_and_start(main)
  File "/home/hummingbot/bin/docker_connection.py", line 137, in fork_and_start
    main_function()
  File "bin/hummingbot_quickstart.py", line 145, in main
    client_config_map = load_client_config_map_from_file()
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 609, in load_client_config_map_from_file
    config_validation_errors = _load_yml_data_into_map(config_data, config_map)
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 679, in _load_yml_data_into_map
    config_validation_errors = cm.validate_model()  # try coercing values to appropriate type
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 245, in validate_model
    results = validate_model(type(self._hb_config), json.loads(self._hb_config.json()))
  File "pydantic/main.py", line 1082, in pydantic.main.validate_model
  File "/home/hummingbot/hummingbot/client/config/client_config_map.py", line 1104, in post_validations
    cls.rate_oracle_source_on_validated(values)
  File "/home/hummingbot/hummingbot/client/config/client_config_map.py", line 1109, in rate_oracle_source_on_validated
    rate_source_mode: RateSourceModeBase = values["rate_oracle_source"]
KeyError: 'rate_oracle_source'

```

**Steps To Reproduce**
Simply by removing the old image and installing the new image, you can reproduce. Note that the latest image as of now is 1.13.0.

```
# 1) Delete instance
docker rm hummingbot-instance

# 2) Delete old hummingbot image
docker image rm hummingbot/hummingbot:latest

# 3) Re-create instance with latest hummingbot release
docker run -it \
--network host \
--name hummingbot-instance \
--mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_conf,destination=/conf/" \
--mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_logs,destination=/logs/" \
--mount "type=bind,source=$(pwd)/hummingbot_files/hummingbot_data,destination=/data/" \
hummingbot/hummingbot:latest
```

Here are the steps to reproduce the issue (see attachments in the section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

**Release version**
This happens during the installation of 1.13.0.

**Comment by 0xferit** [comment]
I purged everything and reinstalled it, and it worked this time. Feel free to close.
