### ISSUE TITLE
K2 - Failed to retrieve its trading pairs 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6179]
**Describe the bug**
Getting `Connector k2 failed to retrieve its trading pairs. Trading pairs autocompletion won't work.` when starting the client

![image](https://user-images.githubusercontent.com/73840223/228403133-8f450bc1-6f8e-473a-9c2b-36eece386e67.png)

```
2023-03-29 09:24:57,350 - 4487 - hummingbot.core.utils.trading_pair_fetcher - ERROR - Connector k2 failed to retrieve its trading pairs. Trading pairs autocompletion won't work.
Traceback (most recent call last):
  File "/home/rapcmia/github/hummingbot/staging/hummingbot/core/utils/trading_pair_fetcher.py", line 64, in call_fetch_pairs
    pairs = await fetch_fn
  File "/home/rapcmia/github/hummingbot/staging/hummingbot/connector/exchange/k2/k2_exchange.py", line 867, in all_trading_pairs
    return await K2APIOrderBookDataSource.fetch_trading_pairs()
  File "/home/rapcmia/github/hummingbot/staging/hummingbot/connector/exchange/k2/k2_api_order_book_data_source.py", line 62, in fetch_trading_pairs
    async with client.get(f"{constants.REST_URL}{constants.GET_TRADING_PAIRS}",
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

Note: This issue does not affect other connectors

**Steps To Reproduce**
1. Start the client and observe log pane

**Release version**
1.13.0 and development branch

**Comment by ZhangYou0122** [comment]
I got the same issue here by running the latest docker image of hummingbot(hummingbot:latest). For me this issue also only affects kucoin, my bot on binance runs without any problem.

**Comment by ZhangYou0122** [comment]
After transferring some coins to Kucoin this issue disappears.
