### ISSUE TITLE
Kucoin perpetual - Client shows an error while you place order manually on exchange

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6182]
Client shows an error while you place order manually on exchange

**Steps To Reproduce**

1. create bot using kucoin perpetual
2. start the bot 
3. place order manually on exchange
4. pay attention to log pane

Actual:
Log pane showed an Unexpected error in user stream listener loop.

Expected:
No error showed in the Client

```
2023-03-29 11:25:44,343 - 2654008 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - ERROR - Unexpected error in user stream listener loop.
Traceback (most recent call last):
  File "/home/ubuntu/staging/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 519, in _user_stream_event_listener
    self._process_trade_event_message(payload)
  File "/home/ubuntu/staging/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 580, in _process_trade_event_message
    client_order_id = str(trade_msg["tradeId"])
KeyError: 'tradeId'
```

[kucpinperp.zip](https://github.com/hummingbot/hummingbot/files/11100312/kucpinperp.zip)
[logs_kucoinperp.log](https://github.com/hummingbot/hummingbot/files/11100306/logs_kucoinperp.log)

![image](https://user-images.githubusercontent.com/83953535/228522478-6e9042f2-d200-49b7-b2fc-61565476aa98.png)

**Comment by cardosofede** [comment]
@MementoRC do you want to work on this issue?

**Comment by MementoRC** [comment]
Unfortunately, i don't have access to KuCoin perpetuals as a US person. Thanks for the thought

**Comment by nikspz** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to Kucoin perpetual connector

**Comment by nikspz** [comment]
Closing issue as paid, thank you @yancong001 for contribution
