### ISSUE TITLE
KucoinExchange - ERROR - There was an error requesting exchange info.

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6198]
Issue showing on the start of the Client only after changing kucoin API from v1 to v2 on dev-1.15.0 (latest development branch).
Note: not related to order placing/refreshing

**Steps To Reproduce**
Clone and install dev-1.15.0 (latest development branch)
Start the Client
Pay attention to the log pane

Actual:
Log pane showing KucoinExchange - ERROR - There was an error requesting exchange info.

Expected:
no issues on the log pane at Client start

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/11139907/logs_hummingbot.log)

```
2023-04-03 06:56:38,172 - 2772619 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/ubuntu/development/hummingbot/connector/exchange_py_base.py", line 1092, in _initialize_trading_pair_symbol_map
    exchange_info = await self._make_trading_pairs_request()
  File "/home/ubuntu/development/hummingbot/connector/exchange_py_base.py", line 1105, in _make_trading_pairs_request
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/home/ubuntu/development/hummingbot/connector/exchange_py_base.py", line 896, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/ubuntu/development/hummingbot/connector/exchange_py_base.py", line 938, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/ubuntu/development/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://openapi-sandbox.kucoin.com/api/v2/symbols. HTTP status is 404. Error: {"code":"404","msg":"Not Found","retry":false,"success":false}
```

![image](https://user-images.githubusercontent.com/83953535/229557734-4944082d-1397-431b-a086-43650d7a3f89.png)

**Comment by cardosofede** [comment]
@rapcmia @nikspz @carlitogetaladajr I will take this one

**Comment by nikspz** [comment]
Fixed in #6253
