### ISSUE TITLE
Kucoin perpetual - Unexpected error resulting to incorrect position and order price

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6226]
**Describe the bug**
Ran some test on kucoin perpetual and found issues on trade data specially on position side and order price. While the connector successfully create and cancel orders to open position, this is not the case when monitoring the behavior of the perpetual connector when a position is  successfully open or a take-profit order is created.

**Setup config to open short position spreads {1, 0.03}**
- Successfully filled order and cancel other side in favor of take-profit order
- However instead of creating a take-profit buy order, it created a sell order with ` Unexpected error in user stream listener loop`
   ```
    2023-04-13 21:56:01,189 - 12100 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - ERROR - Unexpected error in user stream listener loop.
    Traceback (most recent call last):
      File "/home/rapcmia/github/hummingbot/dev/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 519, in _user_stream_event_listener
        self._process_trade_event_message(payload)
      File "/home/rapcmia/github/hummingbot/dev/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 584, in _process_trade_event_message
        trade_update = self._parse_trade_update(trade_msg=trade_msg, tracked_order=fillable_order)
      File "/home/rapcmia/github/hummingbot/dev/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 626, in _parse_trade_update
        exec_price = Decimal(trade_msg["price"])
    KeyError: 'price'
   ```
- The take-profit order got filled immediately resulting to incorrect trade data
   ![image](https://user-images.githubusercontent.com/73840223/231800099-9b8c188e-5c67-402b-b711-140e27e50987.png)
   - Observed that the side both showing sell order. The order to close position should be on the buy side.
      ![image](https://user-images.githubusercontent.com/73840223/231800257-ee3a2013-2ee0-4d83-894e-6f5e7d610860.png)
      - Check the exchange trade data the sell order completed on `0.5149` is not available however on order history (screenshot) above displayed same data on the client but on the buy side

**Setup config to open long position spreads {0.03, 1}**
- Successfully filled order and cancel other side in favor of take-profit order
- The connector is able to create the correct sell take-profit order however still getting the same `Unexpected error in user stream listener loop`
- Intially set the long position spread to 1% observed that it would not immediately do trade. Set to tight spread to speed up the tests
- Take-profit order eventually filled and long position closed. Waited for another set of position open/closed
- Reviewed trade data between client and exchange
  ![image](https://user-images.githubusercontent.com/73840223/231800854-004c5f91-55b8-4123-bf26-53702c2c77b1.png)
  - Observed that the order price to close the position is incorrect. The value of order price from kucoin’s trade history is increased by 1.
      ![image](https://user-images.githubusercontent.com/73840223/231801074-50edd7fd-1b60-4e74-9908-b46e4e839e0d.png)
      - However checking the order history its the same as on the client 
         ![image](https://user-images.githubusercontent.com/73840223/231801191-d7e6a610-fe78-4e65-988b-d213676f2a64.png)

**Steps To Reproduce**
- Setup perpetual market making and use kucoin perpetual
- Observe perpetual connector behavior specially on opening and closing position
- Check client history, csv and exchange trade history

**Release version**
`dev-1.15.0`

[kucoin_perp.zip](https://github.com/hummingbot/hummingbot/files/11223539/kucoin_perp.zip)

**Comment by nikspz** [comment]
Severity: P3
Bounty: 10,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to Kucoin perpetual connector

**Comment by nikspz** [comment]
Asssiging this issue to https://github.com/yancong001

**Comment by nikspz** [comment]
For this issue was mentioned on Maintenance meeting to up Bounty: from 10,000 to 30,000 , Thank you

**Comment by nikspz** [comment]
Severity: P3
Bounty: 30,000 (https://hummingbot.org/maintenance/bugs/)
Rationale: Bug related to Kucoin perpetual connector
