### ISSUE TITLE
Binance not working

### ISSUE THREAD

**Issue by sebmeg** [hummingbot/hummingbot#6240]
**Describe the bug**
A Running bot (runs since 8 Weeks) stoppt working with the message:
`clock - Unexpected error running clock tick. (See log file for stack trace dump)`
If i stop the bot and create an ne instance connect it to binance and start a strategy it will only show the message:
`binance is not ready! Please wait..`

**Steps To Reproduce**
Setup a new Hummingbot Instance, connect to binance and try to start a Strategy.

**Release version**
Version 1.14.0 and Version 1.13.0

**Comment by sebmeg** [comment]
The trader which was running had this in his logs:

`2023-04-20 08:13:58,002 - 1 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/home/hummingbot/hummingbot/strategy/trader/trader.py", line 76, in tick
    mid_price = self._market_info.get_mid_price()
  File "/home/hummingbot/hummingbot/strategy/market_trading_pair_tuple.py", line 34, in get_mid_price
    return self.market.get_mid_price(self.trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 124, in hummingbot.connector.exchange_base.ExchangeBase.get_mid_price
    return (self.get_price(trading_pair, True) + self.get_price(trading_pair, False)) / Decimal("2")
  File "hummingbot/connector/exchange_base.pyx", line 275, in hummingbot.connector.exchange_base.ExchangeBase.get_price
    return self.c_get_price(trading_pair, is_buy)
  File "hummingbot/connector/exchange_base.pyx", line 165, in hummingbot.connector.exchange_base.ExchangeBase.c_get_price
    return self.c_quantize_order_price(trading_pair, top_price)
  File "hummingbot/connector/connector_base.pyx", line 395, in hummingbot.connector.connector_base.ConnectorBase.c_quantize_order_price
    price_quantum = self.c_get_order_price_quantum(trading_pair, price)
  File "hummingbot/connector/connector_base.pyx", line 375, in hummingbot.connector.connector_base.ConnectorBase.c_get_order_price_quantum
    return self.get_order_price_quantum(trading_pair, price)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 221, in get_order_price_quantum
    trading_rule = self._trading_rules[trading_pair]
KeyError: 'BTC-BUSD'`
