### ISSUE TITLE
Foxbit - There was an error requesting exchange info

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6301]
**Describe the bug**
While checking development branch, We noticed these `Error getting server time.` and `There was an error requesting exchange info.` for `foxbit` connector

![image](https://github.com/hummingbot/hummingbot/assets/73840223/61db05a6-ce18-412d-808c-e597b39d26eb)

```
2023-05-17 10:09:15,158 - 8058 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/connector/time_synchronizer.py", line 65, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/connector/exchange/foxbit/foxbit_web_utils.py", line 98, in get_current_server_time
    response = await rest_assistant.execute_request(url=public_rest_url(path_url=CONSTANTS.SERVER_TIME_PATH_URL,
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.foxbit.com.br/rest/v3/system/time. HTTP status is 503. Error: N/A
2023-05-17 10:09:15,159 - 8058 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
2023-05-17 10:09:15,971 - 8058 - hummingbot.connector.exchange.foxbit.foxbit_exchange.FoxbitExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/connector/exchange_py_base.py", line 1088, in _initialize_trading_pair_symbol_map
    exchange_info = await self._make_trading_pairs_request()
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/connector/exchange_py_base.py", line 1101, in _make_trading_pairs_request
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/connector/exchange_py_base.py", line 892, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/connector/exchange_py_base.py", line 934, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/rapcmia/github/hummingbot/dev/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.foxbit.com.br/rest/v3/markets. HTTP status is 503. Error: N/A

```

Note: `This error does not affect other connectors and client performance. For monitoring purpose`

**Steps To Reproduce**
1. Setup latest development branch for client
2. Start the client and observe the log panel
...

**Release version**
Development dev-1.16.0

**Attachments**
// Please attach your config file and log file to help us debug. It would be difficult for us to help you without those! 
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/11493551/logs_hummingbot.log)

**Comment by cardosofede** [comment]
@rapcmia I will close this issue since fox bit will be removed this week
