### ISSUE TITLE
Client - Failed to start startegy after recreate/update docker image to latest development

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6302]
**Describe the bug**
Failed to start the previous version created strategy with filled orders in CSV
Client return 'Unknown error during initialization.'
and `'NoneType' object has no attribute 'restore_market_states'`

**Steps To Reproduce**
0. Using the latest bash scripts in https://github.com/hummingbot/deploy-examples/tree/main
1. Create `hummingbot/hummingbot:latest` docker client and setup simple pmm (or any strategy)
2. Start strategy and wait for order fills
3. Check CSV of latest docker file (should be using the `1.15.0` version without trade_fees_in_quotes)
4. Exit the client and remove the client cointainer
5. Create development docker with (`docker build -t hummingbot/hummingbot:latest -f Dockerfile .`) using the same name of container
6. Start the container
7. Import then start strategy, observe behavior

Actual:
Failed to start same previously created in step2 strategy 

Expected:
User able to import/start previously created `strategy with filled orders in CSV`

[logs_pmm-paper1.log](https://github.com/hummingbot/hummingbot/files/11495175/logs_pmm-paper1.log)

```
2023-05-17 05:54:27,215 - 1 - hummingbot.client.hummingbot_application - ERROR - Unknown error during initialization.
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: TradeFill.trade_fee_in_quote

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/strategy/pure_market_making/start.py", line 82, in start
    self._initialize_markets(market_names)
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 319, in _initialize_markets
    self.markets_recorder = MarketsRecorder(
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 64, in __init__
    trade_fills = self.get_trades_for_config(self._config_file_path, 2000)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 153, in get_trades_for_config
    return query.limit(number_of_rows).all()
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/conda/envs/hummingbot/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: TradeFill.trade_fee_in_quote
[SQL: SELECT "TradeFill".config_file_path AS "TradeFill_config_file_path", "TradeFill".strategy AS "TradeFill_strategy", "TradeFill".market AS "TradeFill_market", "TradeFill".symbol AS "TradeFill_symbol", "TradeFill".base_asset AS "TradeFill_base_asset", "TradeFill".quote_asset AS "TradeFill_quote_asset", "TradeFill".timestamp AS "TradeFill_timestamp", "TradeFill".order_id AS "TradeFill_order_id", "TradeFill".trade_type AS "TradeFill_trade_type", "TradeFill".order_type AS "TradeFill_order_type", "TradeFill".price AS "TradeFill_price", "TradeFill".amount AS "TradeFill_amount", "TradeFill".leverage AS "TradeFill_leverage", "TradeFill".trade_fee AS "TradeFill_trade_fee", "TradeFill".trade_fee_in_quote AS "TradeFill_trade_fee_in_quote", "TradeFill".exchange_trade_id AS "TradeFill_exchange_trade_id", "TradeFill".position AS "TradeFill_position" 
FROM "TradeFill" 
WHERE "TradeFill".config_file_path = ? ORDER BY "TradeFill".timestamp DESC
 LIMIT ? OFFSET ?]
[parameters: ('pmm-paper1.yml', 2000, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-05-17 05:54:27,230 - 1 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2023-05-17 05:54:27,230 - 1 - hummingbot.client.hummingbot_application - ERROR - 'NoneType' object has no attribute 'restore_market_states'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/client/command/start_command.py", line 216, in start_market_making
    self.markets_recorder.restore_market_states(self.strategy_file_name, market)
AttributeError: 'NoneType' object has no attribute 'restore_market_states'
```

![image](https://github.com/hummingbot/hummingbot/assets/83953535/28e74a0a-fb5a-414c-a01d-ea023fc9f730)

Same on binance spot live
![image](https://github.com/hummingbot/hummingbot/assets/83953535/efa3948d-9719-4a1f-9652-f3970369d8cd)

**Comment by rapcmia** [comment]
Latest version had some changes on sqlite and users must either keep or delete the previous version to have it work
