### ISSUE TITLE
Client - TypeError during install/compile

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6365]
**Describe the bug**
While checking latest development branch (fresh installation), we are encounter `TypeError: __init__() got an unexpected keyword argument 'requote'` making the hummingbot client unusable atm on development branch 

```
Traceback (most recent call last):
  File "bin/hummingbot.py", line 10, in <module>
    from hummingbot.client.config.config_crypt import ETHKeyFileSecretManger
  File "/home/rapcmia/github/hummingbot/6322/hummingbot/client/config/config_crypt.py", line 22, in <module>
    from hummingbot.client.settings import CONF_DIR_PATH
  File "/home/rapcmia/github/hummingbot/6322/hummingbot/client/settings.py", line 13, in <module>
    from hummingbot.core.data_type.trade_fee import TradeFeeSchema
  File "/home/rapcmia/github/hummingbot/6322/hummingbot/core/data_type/trade_fee.py", line 7, in <module>
    from hummingbot.connector.utils import combine_to_hb_trading_pair, split_hb_trading_pair
  File "/home/rapcmia/github/hummingbot/6322/hummingbot/connector/utils.py", line 10, in <module>
    from zero_ex.order_utils import Order as ZeroExOrder
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/zero_ex/order_utils/__init__.py", line 31, in <module>
    from web3 import Web3
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/__init__.py", line 9, in <module>
    from web3.main import (
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/main.py", line 87, in <module>
    from web3.manager import (
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/manager.py", line 47, in <module>
    from web3.providers import (
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/providers/__init__.py", line 8, in <module>
    from .rpc import (  # noqa: F401,
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/providers/rpc.py", line 21, in <module>
    from web3._utils.request import (
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/_utils/request.py", line 13, in <module>
    from aiohttp import (
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 34, in <module>
    from yarl import URL
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/_url.py", line 80, in <module>
    class URL:
  File "/home/rapcmia/miniconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/_url.py", line 152, in URL
    _QUOTER = _Quoter(requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```

Note: Last working commit is `7d1443070382ab3d5d81b081a4091ca9872b636b`

**Steps To Reproduce**
1. Pull and install latest development branch on source

**Release version**
development 1.17.0

**Comment by nikspz** [comment]
Reproduced on dev-1.17.0

```
(hummingbot) ubuntu@ip-172-31-4-1111:~/development$ s
Traceback (most recent call last):
  File "bin/hummingbot.py", line 10, in <module>
    from hummingbot.client.config.config_crypt import ETHKeyFileSecretManger
  File "/home/ubuntu/development/hummingbot/client/config/config_crypt.py", line 22, in <module>
    from hummingbot.client.settings import CONF_DIR_PATH
  File "/home/ubuntu/development/hummingbot/client/settings.py", line 13, in <module>
    from hummingbot.core.data_type.trade_fee import TradeFeeSchema
  File "/home/ubuntu/development/hummingbot/core/data_type/trade_fee.py", line 7, in <module>
    from hummingbot.connector.utils import combine_to_hb_trading_pair, split_hb_trading_pair
  File "/home/ubuntu/development/hummingbot/connector/utils.py", line 10, in <module>
    from zero_ex.order_utils import Order as ZeroExOrder
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/zero_ex/order_utils/__init__.py", line 31, in <module>
    from web3 import Web3
     File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/__init__.py", line 9, in <module>
    from web3.main import (
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/main.py", line 87, in <module>
    from web3.manager import (
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/manager.py", line 47, in <module>
    from web3.providers import (
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/providers/__init__.py", line 8, in <module>
    from .rpc import (  # noqa: F401,
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/providers/rpc.py", line 21, in <module>
    from web3._utils.request import (
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/web3/_utils/request.py", line 13, in <module>
    from aiohttp import (
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/aiohttp/client.py", line 34, in <module>
    from yarl import URL
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/_url.py", line 80, in <module>
    class URL:
  File "/home/ubuntu/miniconda3/envs/hummingbot/lib/python3.8/site-packages/yarl/_url.py", line 152, in URL
    _QUOTER = _Quoter(requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```

**Comment by nikspz** [comment]
The issue `not showing` after ./uninstall and ./install and compile again or do Fresh installation again
Steps to fix:
```
./clean 
./unistall 
./install
conda activate hummingbot
./compile
```

Fresh installation:
no errors ✅
![image](https://github.com/hummingbot/hummingbot/assets/83953535/b8429d99-99cb-4730-844c-0b5a375f7612)
![image](https://github.com/hummingbot/hummingbot/assets/83953535/d1e42ac1-49fd-4198-9c0b-1ca76de6c5ed)

**Comment by rapcmia** [comment]
Closing ticket issue has been fixed by:
- Crosscheck and able to reproduce on both WSL ubuntu20.04 LTS and MBP(m1) both installed on fresh installation 
- Run `./uninstall` to remove conda then `./install` again
- 3/3 attempts worked and able to setup connectors, gateway and other expected behaviors
