### ISSUE TITLE
Gate.io Perpetual - multiple pairs websocket error

### ISSUE THREAD

**Issue by supervik** [hummingbot/hummingbot#6402]
**Describe the bug**

Using multiple pairs with gate.io perpetuals connector gives an error:
```
2023-06-25 21:03:45,218 - 7157 - hummingbot.connector.derivative.gate_io_perpetual.gate_io_perpetual_user_stream_data_source.GateIoPerpetualAPIUserStreamDataSource - ERROR - Unexpected error while listening to user stream. Retrying after 5 seconds...
Traceback (most recent call last):
  File "/home/ubuntu/bots/hb_1/hummingbot/core/data_type/user_stream_tracker_data_source.py", line 48, in listen_for_user_stream
    await self._process_websocket_messages(websocket_assistant=self._ws_assistant, queue=output)
  File "/home/ubuntu/bots/hb_1/hummingbot/core/data_type/user_stream_tracker_data_source.py", line 79, in _process_websocket_messages
    await self._process_event_message(event_message=data, queue=queue)
  File "/home/ubuntu/bots/hb_1/hummingbot/connector/derivative/gate_io_perpetual/gate_io_perpetual_user_stream_data_source.py", line 94, in _process_event_message
    raise IOError({
OSError: {'label': 'WSS_ERROR', 'message': 'Error received via websocket - need 1 or 2 param and here is 4.'}
```

**Steps To Reproduce**
Run any script with several pairs and Gate_io_perpetual as a connector. For example:

```
from hummingbot.strategy.script_strategy_base import ScriptStrategyBase


class LogPricesExample(ScriptStrategyBase):
    """
    This example shows how to get the ask and bid of a market and log it to the console.
    """
    markets = {"gate_io_perpetual": {"ETH-USDT", "BTC-USDT", "XRP-USDT"}}

    def on_tick(self):
        for connector_name, connector in self.connectors.items():
            self.logger().info(f"Connector: {connector_name}")
            self.logger().info(f"Best ask: {connector.get_price('ETH-USDT', True)}")
            self.logger().info(f"Best bid: {connector.get_price('ETH-USDT', False)}")
            self.logger().info(f"Mid price: {connector.get_mid_price('ETH-USDT')}")
```

**Release version**
1.16

**Additional**
The error is in user_stream_tracker_data_source.py
Documentation for Gate.io says that to subscribe to any user updates in all contracts, use **!all** in contract list. Hummingbot sends the contract list instead. I beleive gate.io is using contracts list for public data only but for private data if any wants to use more than 1 pair it should pass the string "!all".
https://www.gate.io/docs/developers/futures/ws/en/#orders-api

**Comment by cardosofede** [comment]
@supervik good catch. I will nominate this issue to the polls.

**Comment by yancong001** [comment]
i fixed it,here is pr https://github.com/hummingbot/hummingbot/pull/6419
