### ISSUE TITLE
Uniswap Connector - Timeout getting price

### ISSUE THREAD

**Issue by toxicehc** [hummingbot/hummingbot#6424]
### Describe the bug

Since yesterday I cannot get the price of a pair on uniswap polygon.

### Steps to reproduce

1. Clean install v17 source
2. Create amm_arb strategy
3. Start strategy - gets stuck on 'starting networking' - reports errors
4. 
![image](https://github.com/hummingbot/hummingbot/assets/4660657/a9709211-5360-4c8b-ae1c-c3711fe9eb43)
Log files indicate:
2023-06-29 15:28:06,510 - 10872 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/amm/price failed. See logs for more details.
2023-06-29 15:28:06,510 - 10872 - GatewayEVMAMM - WARNING - Error on POST https://localhost:15888/amm/price Error: {'message': 'Price query failed: Request failed with status code 522', 'httpErrorCode': 500, 'errorCode': 1013, 'stack': 'Error: Price query failed: Request failed with status code 522\n    at /home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:74:23\n    at Generator.throw (<anonymous>)\n    at rejected (/home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)'}
2023-06-29 15:28:06,813 - 10872 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/amm/price failed. See logs for more details.
2023-06-29 15:28:06,814 - 10872 - GatewayEVMAMM - WARNING - Error on POST https://localhost:15888/amm/price Error: {'message': 'Price query failed: Request failed with status code 522', 'httpErrorCode': 500, 'errorCode': 1013, 'stack': 'Error: Price query failed: Request failed with status code 522\n    at /home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:74:23\n    at Generator.throw (<anonymous>)\n    at rejected (/home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)'}
2023-06-29 15:28:22,161 - 10872 - hummingbot.core.gateway.gateway_http_client - WARNING - Call to https://localhost:15888/amm/price failed. See logs for more details.
2023-06-29 15:28:22,161 - 10872 - GatewayEVMAMM - WARNING - Error on POST https://localhost:15888/amm/price Error: {'message': 'Price query failed: Request failed with status code 522', 'httpErrorCode': 500, 'errorCode': 1013, 'stack': 'Error: Price query failed: Request failed with status code 522\n    at /home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:74:23\n    at Generator.throw (<anonymous>)\n    at rejected (/home/toxicehc/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)'}
2023-06-29 15:28:22,161 - 10872 - hummingbot.strategy.amm_arb.amm_arb - INFO - No arbitrage opportunity.

### Release version

V1.17

### Type of installation

Source

### Attach required files

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/11906202/logs_hummingbot.log)
[logs_conf_amm_arb_1.log](https://github.com/hummingbot/hummingbot/files/11906203/logs_conf_amm_arb_1.log)

**Comment by nikspz** [comment]
hi @toxicehc upon checking could be related to the issue using `infura` nodeURL / on the uniswap side. We'll investigate this one

**Comment by nikspz** [comment]
Reproduced on another alchemy nodeURL, will investigate more.
![image](https://github.com/hummingbot/hummingbot/assets/83953535/d42d9820-9cc4-4689-a241-972fca46766d)

**Comment by toxicehc** [comment]
Seems something definately changed on the uniswap side, looking at some manual transactions versus Gateway Transactions its gone from Multicall to execute:
![image](https://github.com/hummingbot/hummingbot/assets/4660657/360b2eeb-2782-49e5-8a11-2508270e1484)

**Comment by toxicehc** [comment]
> Reproduced on another alchemy nodeURL, will investigate more. ![image](https://user-images.githubusercontent.com/83953535/249863585-d42d9820-9cc4-4689-a241-972fca46766d.png)

Hello Nick - since the PR on the dev gateway was done yesterday it is now working on the updated code from Vadim

**Comment by nikspz** [comment]
![image](https://github.com/hummingbot/hummingbot/assets/83953535/22ea903b-e032-43e0-b762-3f46d779dd35)
Yep Seems fixed on latest development (dev-1.18.0)

**Comment by fengtality** [comment]
This appears to be an issue with Uniswap's router: https://github.com/Uniswap/smart-order-router as it's not returning a price for a swap:

```
2023-06-30 07:31:45 | info |     Fetching pair data for 0x6B175474E89094C44Da98b954EedeAC495271d0F-0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2. | undefined
2023-06-30 07:32:07 | info |     18 request(s) sent in last 300 seconds. | undefined
2023-06-30 07:32:49 | error |     Price query failed: Request failed with status code 522 | Error: Price query failed: Request failed with status code 522
    at /Users/feng/Code/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:74:23
    at Generator.throw (<anonymous>)
    at rejected (/Users/feng/Code/gateway/dist/src/connectors/uniswap/uniswap.controllers.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Setting the flag `useRouter` to false fixes this issue. This is currently on `development` branch and will be included in the v1.18 release

**Comment by cardosofede** [comment]
@fengtality probably this issue needs to be moved to the Gateway repo since it's an issue with the SDK
