### ISSUE TITLE
Kucoin perpetual - Error requesting exchange info

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6483]
### Describe the bug

Upon starting the hummingbot client, observe the error on the log panel `There was an error requesting exchange info.`

```
2023-07-17 13:11:05,241 - 36677 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rapcomia/github/development/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 789, in _initialize_trading_pair_symbol_map
    all_exchange_info = await self._market_data_for_all_product_types()
  File "/Users/rapcomia/github/development/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 780, in _market_data_for_all_product_types
    exchange_info = await self._api_get(
  File "/Users/rapcomia/github/development/hummingbot/connector/exchange_py_base.py", line 865, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/Users/rapcomia/github/development/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 936, in _api_request
    resp = await rest_assistant.execute_request(
  File "/Users/rapcomia/github/development/hummingbot/core/web_assistant/rest_assistant.py", line 66, in execute_request
    response = await self.call(request=request, timeout=timeout)
  File "/Users/rapcomia/github/development/hummingbot/core/web_assistant/rest_assistant.py", line 84, in call
    resp = await wait_for(self._connection.call(request), timeout)
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/Users/rapcomia/github/development/hummingbot/core/web_assistant/connections/rest_connection.py", line 10, in call
    aiohttp_resp = await self._client_session.request(
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api-sandbox-futures.kucoin.com:443 ssl:default [nodename nor servname provided, or not known]
```

Checking the `kucoin perpetual` connector with perpetual market-making strategy seems to work just fine, created this ticket for monitoring purpose 👀 

### Steps to reproduce

1. Start hummingbot client
2. Check the log panel for the error message

### Release version

dev-1.18.0

### Type of installation

Source

**Comment by nikspz** [comment]
Fixed with https://github.com/hummingbot/hummingbot/pull/6589, merged to latest development
