### ISSUE TITLE
dYdX market order error using PositionExecutor smart component

### ISSUE THREAD

**Issue by talkinandy** [hummingbot/hummingbot#6531]
### Describe the bug

I can't execute market order on dYdX using PositionExecutor smart component. The same code works fine with Binance Perpetual.

Here's the code

```
                    long_position = PositionExecutor(
                        position_config=PositionConfig(
                            timestamp=self.current_timestamp,
                            trading_pair='ZRX-USD',
                            exchange=self.exchange,
                            side=TradeType.BUY,
                            amount=20,
                            entry_price=current_price,
                            stop_loss=stop_loss,
                            take_profit=self.take_profit,
                            time_limit=sys.maxsize,
                            open_order_type=OrderType.MARKET,
                            take_profit_order_type=OrderType.MARKET,
                            stop_loss_order_type=OrderType.MARKET,
                            time_limit_order_type=OrderType.MARKET,
                            trailing_stop=TrailingStop(
                                activation_price_delta=trailing_stop_activation_delta,
                                trailing_delta=self.trailing_stop_trailing_delta
                            ),
                            leverage=self.leverage,
                        ),
                        strategy=self,
                    )
```

This is the error I get:
```
2023-08-20 21:41:58,280 - 1 - hummingbot.connector.derivative.dydx_perpetual.dydx_perpetual_derivative.DydxPerpetualDerivative - NETWORK - Error submitting sell MARKET order to Dydx_perpetual for 185 ZRX-USD 0.1805.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 453, in _create_order
    exchange_order_id = await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 471, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/hummingbot/hummingbot/connector/derivative/dydx_perpetual/dydx_perpetual_derivative.py", line 287, in _place_order
    resp = await self._api_post(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 869, in _api_post
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 907, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 75, in execute_request
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request POST https://api.dydx.exchange/v3/orders. HTTP status is 400. Error: {"errors":[{"msg":"Order with timeInForce: GTT, triggerPrice: undefined or trailingPercent: undefined will not be treated as MARKET"}]}
```

### Steps to reproduce

1. Connect dYdX
2. Send market order

### Release version

dev 1.19

### Type of installation

Docker

### Attach required files

Log file is too big ( over 60MB)
Still reproducing the error in dydx to get smaller logs.

**Comment by yancong001** [comment]
solved, here (https://github.com/hummingbot/hummingbot/pull/6536)

**Comment by nikspz** [comment]
Fix Merged to development and will be part of release version 1.20.0
