### ISSUE TITLE
Binance Perpetual lack of handling for non existing order

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#6537]
### Describe the bug

When the connector sends a cancel order request, it's not managing the exception of the api_request of Unknown order sent:
```
2023-08-23 11:22:07,010 - 15 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - ERROR - Failed to cancel order x-3QreWesySCRUT60395524f6835a4fa
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 520, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 540, in _execute_order_cancel_and_process_update
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 223, in _place_cancel
    cancel_result = await self._api_delete(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 875, in _api_delete
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/derivative/binance_perpetual/binance_perpetual_derivative.py", line 857, in _api_request
    raise IOError(f"Error executing request {method.name} {path_url}. "
OSError: Error executing request DELETE /order. HTTP status is 400. Error: {"code":-2011,"msg":"Unknown order sent."}

```

### Steps to reproduce

1. Run a strategy in Binance Perpetual that fails canceling one order because it was never placed, example margin insufficient 

### Release version

dev 1.19

### Type of installation

Source

**Comment by nikspz** [comment]
Adding P3 Bounty for this issue

Severity: P3
Bounty: 10,000 HBOT
Rationale: 
- Binance Perpetual fails canceling one order because it was never placed, example -  margin insufficient

**Comment by nikspz** [comment]
https://github.com/hummingbot/hummingbot/pull/6584

**Comment by rapcmia** [comment]
Fix has been deployed to development and will be part of release version 1.21.0

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to cardosofede. The fix has been deployed on development branch and next hummingbot version 1.21.0.
