### ISSUE TITLE
Kucoin Sandbox (Testnet) Trading pairs not found -  Cannot connect to host api-sandbox-futures.kucoin.com:443 ssl:default 

### ISSUE THREAD

**Issue by cardosofede** [hummingbot/hummingbot#6577]
### Describe the bug

When starting the bot, the trading pairs fetcher is asking for the trading pairs of all the connectors.
Currently, Kucoin Testnet is not working and the team told us that it's going to be discontinued

### Steps to reproduce

1. Start the bot
2. Check that Kucoin raises the failure

### Release version

dev-1.20

### Type of installation

Source

### Attach required files

Traceback (most recent call last):
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 789, in _initialize_trading_pair_symbol_map
    all_exchange_info = await self._market_data_for_all_product_types()
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 780, in _market_data_for_all_product_types
    exchange_info = await self._api_get(
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 936, in _api_request
    resp = await rest_assistant.execute_request(
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 93, in execute_request_and_get_response
    response = await self.call(request=request, timeout=timeout)
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 107, in call
    resp = await wait_for(self._connection.call(request), timeout)
  File "/Users/dardonacci/anaconda3/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/Users/dardonacci/Documents/work/hummingbot/hummingbot/core/web_assistant/connections/rest_connection.py", line 10, in call
    aiohttp_resp = await self._client_session.request(
  File "/Users/dardonacci/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/dardonacci/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/dardonacci/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/dardonacci/anaconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1169, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api-sandbox-futures.kucoin.com:443 ssl:default [nodename nor servname provided, or not known]

**Comment by rapcmia** [comment]
Kucoin Testnet has been removed from development 1.21.0
