### ISSUE TITLE
Kucoin perpetual - Error fetching status update for order

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6586]
### Describe the bug

While checking kucoin perpetual long term logs, we noticed that there are instances of `Unexpected error while fetching account updates.` occurred when trying to create or cancel orders 

When creating orders to open position
```
2023-09-27 11:14:03,027 - 5575 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BCH-USDT) Creating 1 LIMIT bid orders at (Size, Price): ['0.05 BCH, 213.72 USDT'] to OPEN position.
2023-09-27 11:14:03,027 - 5575 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BCH-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['0.05 BCH, 215 USDT'] to OPEN position.
2023-09-27 11:14:03,191 - 5575 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order HummingbotSBHUT6064e9557a01cf6555ccc5f5a for 0.05 to OPEN a BCH-USDT position.
2023-09-27 11:14:03,192 - 5575 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1695784443.0, "type": "OrderType.LIMIT", "trading_pair": "BCH-USDT", "amount": "0.05", "price": "215.00", "order_id": "HummingbotSBHUT6064e9557a01cf6555ccc5f5a", "creation_timestamp": 1695784443.0, "exchange_order_id": "96348369202491392", "leverage": 1, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "kucoin_perpetual"}
2023-09-27 11:14:03,364 - 5575 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order HummingbotBBHUT6064e95579f9ef6555ccc5f5a for 0.05 to OPEN a BCH-USDT position.
2023-09-27 11:14:03,364 - 5575 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1695784443.0, "type": "OrderType.LIMIT", "trading_pair": "BCH-USDT", "amount": "0.05", "price": "213.72", "order_id": "HummingbotBBHUT6064e95579f9ef6555ccc5f5a", "creation_timestamp": 1695784443.0, "exchange_order_id": "96348369886134272", "leverage": 1, "position": "OPEN", "event_name": "BuyOrderCreatedEvent", "event_source": "kucoin_perpetual"}
2023-09-27 11:14:03,467 - 5575 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Error fetching status update for the order HummingbotSBHUT6064e8a8d6bc6f6555ccc5f5a: {'msg': 'error.getOrder.orderNotExist', 'code': '100001'}.
2023-09-27 11:14:03,467 - 5575 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Failed to fetch status update for the order HummingbotSBHUT6064e8a8d6bc6f6555ccc5f5a.
2023-09-27 11:14:03,467 - 5575 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/stg/hummingbot/connector/exchange_py_base.py", line 780, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/Users/rapcomia/github/hummingbot/stg/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 285, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/Users/rapcomia/github/hummingbot/stg/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/rapcomia/github/hummingbot/stg/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 402, in _update_order_status
    self._process_order_event_message(order_status)
  File "/Users/rapcomia/github/hummingbot/stg/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 712, in _process_order_event_message
    new_state = updatable_order.current_state
AttributeError: 'NoneType' object has no attribute 'current_state'
2023-09-27 11:14:03,469 - 5575 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Could not fetch account updates from Kucoin_perpetual. Check API key and network connection.
```

When cancelling order (the example below is when renewing stop loss order)
```
2023-09-27 12:31:01,063 - 5575 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BCH-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['0.05 BCH, 214.05 USDT'] to CLOSE position.
2023-09-27 12:31:01,873 - 5575 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order HummingbotSBHUT6064fa899482bf6555ccc5f5a for 0.05 to CLOSE a BCH-USDT position.
2023-09-27 12:31:01,873 - 5575 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1695789061.0, "type": "OrderType.LIMIT", "trading_pair": "BCH-USDT", "amount": "0.05", "price": "214.05", "order_id": "HummingbotSBHUT6064fa899482bf6555ccc5f5a", "creation_timestamp": 1695789061.0, "exchange_order_id": "96367741031702528", "leverage": 1, "position": "CLOSE", "event_name": "SellOrderCreatedEvent", "event_source": "kucoin_perpetual"}
2023-09-27 12:34:01,001 - 5575 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (BCH-USDT) Canceling the limit order HummingbotSBHUT6064fa899482bf6555ccc5f5a. [clock=2023-09-27 04:34:01+00:00]
2023-09-27 12:34:01,001 - 5575 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Canceling the limit order HummingbotSBHUT6064fa899482bf6555ccc5f5a to renew stop loss.
2023-09-27 12:34:01,119 - 5575 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1695789241.0, "order_id": "HummingbotSBHUT6064fa899482bf6555ccc5f5a", "exchange_order_id": "96367741031702528", "event_name": "OrderCancelledEvent", "event_source": "kucoin_perpetual"}
2023-09-27 12:34:01,120 - 5575 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order HummingbotSBHUT6064fa899482bf6555ccc5f5a.
2023-09-27 12:34:01,206 - 5575 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/stg/hummingbot/connector/exchange_py_base.py", line 780, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/Users/rapcomia/github/hummingbot/stg/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 285, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/Users/rapcomia/github/hummingbot/stg/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/rapcomia/github/hummingbot/stg/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 402, in _update_order_status
    self._process_order_event_message(order_status)
  File "/Users/rapcomia/github/hummingbot/stg/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 712, in _process_order_event_message
    new_state = updatable_order.current_state
AttributeError: 'NoneType' object has no attribute 'current_state'
2023-09-27 12:34:01,206 - 5575 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Could not fetch account updates from Kucoin_perpetual. Check API key and network connection.
```

While this is true, there were no stuck orders or causing performance issue. Created ticket for monitoring purpose and will add further updates

### Steps to reproduce

1. Setup kucoin_perpetual on script orp perpetual market making 
2. Run for couple of days and review log file 

### Release version

dev-1.20.0

### Type of installation

Source

### Attach required files

[logs_perp-kucoin.log](https://github.com/hummingbot/hummingbot/files/12735055/logs_perp-kucoin.log)

**Comment by rapcmia** [comment]
Not able to reproduced when reviewing long term bots
