### ISSUE TITLE
Client - Unhandled error in background task: Non-hexadecimal digit found

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6587]
### Describe the bug

Upd: 
Workaround:
You could use `./start -p yourpassword` (instead of just ./start)

Warning message about Non-hexadecimal digit found

![Issue hexideximal delete data folder as workaround](https://github.com/hummingbot/hummingbot/assets/83953535/ac2c3b92-d4bc-4e29-88cf-f332acc4f498)

### Steps to reproduce

1. Run perpetual connectors using scripts and the perpetual market-making strategy. (reproduced as well on spot)
2. Perform a series of trades and intentionally leave an open position.
3. Stop the Hummingbot client.
4. Relaunch the Hummingbot client.
5. Observe the "unhandled error" in the log panel upon starting the client, even before importing any data or performing any actions.

### Release version

dev-1.20.0

### Type of installation

Source

### Attach required files

[Issue hexideximal.zip](https://github.com/hummingbot/hummingbot/files/12737863/Issue.hexideximal.zip)
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/12737864/logs_hummingbot.log)

**Comment by nostoz** [comment]
I have the same issue with dev-1.20.0, works fine when downgrading to dev-1.18.0

**Comment by nikspz** [comment]
reproduced on dev-1.22.0.
Seems not related to data folder since no trades happened

Steps to reproduce:
1. do the fresh source installation of latest development branch 
2. connect some exchanges (on our case its binance spot + perp and kucoin spot + perp)
3. then relaunch Client with just `./start`

Actual:
After restart Client returns an error Unhandled error in background task: Non-hexadecimal digit found

```
2023-11-22 12:25:24,506 - 3238495 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Non-hexadecimal digit found
Traceback (most recent call last):
  File "/home/nikita/staging1/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/staging1/hummingbot/core/utils/async_call_scheduler.py", line 127, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/nikita/staging1/hummingbot/core/utils/async_call_scheduler.py", line 116, in schedule_async_call
    return await fut
  File "/home/nikita/staging1/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nikita/staging1/hummingbot/client/config/security.py", line 55, in decrypt_all
    cls.decrypt_connector_config(file)
  File "/home/nikita/staging1/hummingbot/client/config/security.py", line 61, in decrypt_connector_config
    cls._secure_configs[connector_name] = load_connector_config_map_from_file(file_path)
  File "/home/nikita/staging1/hummingbot/client/config/config_helpers.py", line 668, in load_connector_config_map_from_file
    _load_yml_data_into_map(config_data, config_map)
  File "/home/nikita/staging1/hummingbot/client/config/config_helpers.py", line 750, in _load_yml_data_into_map
    config_validation_errors = cm.validate_model()  # try coercing values to appropriate type
  File "/home/nikita/staging1/hummingbot/client/config/config_helpers.py", line 199, in validate_model
    self.decrypt_all_secure_data()
  File "/home/nikita/staging1/hummingbot/client/config/config_helpers.py", line 237, in decrypt_all_secure_data
    decrypted_value = Security.secrets_manager.decrypt_secret_value(attr=traversal_item.attr, value=value)
  File "/home/nikita/staging1/hummingbot/client/config/config_crypt.py", line 59, in decrypt_secret_value
    value = binascii.unhexlify(value)
binascii.Error: Non-hexadecimal digit found
```

![non-hexi found reproduced](https://github.com/hummingbot/hummingbot/assets/83953535/8c452ac4-51dd-4bc5-b9da-b12ec3595393)


for Workaround:
Use `./start -p yourpassword` (instead of just ./start)
In this case Client not showing this warning on startup

![non-hexi found reproduced workaround](https://github.com/hummingbot/hummingbot/assets/83953535/457e722c-5bcf-4b76-9000-d9fffa08b3f9)

**Comment by bitphage** [comment]
There is a problem somewhere in `ClientConfigAdapter`, maybe in `decrypt_all_secure_data()` logic. Basically for me I see that during parsing of `conf/connectors/kucoin.yml` `kucoin_secret_key` is decrypted twice.

In the following code block of `decrypt_all_secure_data()` :
```python
            if isinstance(value, SecretStr):
                value = value.get_secret_value()
```

First time secret value is long encoded string as seen in the connector config
Second time it is decoded value, and it's trying to decode it second time and here is `binascii.Error: Non-hexadecimal digit found` error is happening.

Decrypted value is assigned in line
```
setattr(config_model, final_config_element, decrypted_value)
```
The question is why the same config param is processed twice. Looks like `traverse()` method is emitting same config element twice for some reason.

Here is a quick dirty fix to workaround the issue. 

```python
diff --git a/hummingbot/client/config/config_helpers.py b/hummingbot/client/config/config_helpers.py
index d0718eedb..45544f9a1 100644
--- a/hummingbot/client/config/config_helpers.py
+++ b/hummingbot/client/config/config_helpers.py
@@ -54,6 +54,9 @@ class ConfigTraversalItem:
     field_info: FieldInfo
     type_: Type
 
+    def __hash__(self):
+        return hash((self.depth, self.config_path))
+
 
 class ClientConfigAdapter:
     def __init__(self, hb_config: BaseClientModel):
@@ -222,11 +225,11 @@ class ClientConfigAdapter:
     def decrypt_all_secure_data(self):
         from hummingbot.client.config.security import Security  # avoids circular import
 
-        secure_config_items = (
+        secure_config_items = {
             traversal_item
             for traversal_item in self.traverse()
             if traversal_item.client_field_data is not None and traversal_item.client_field_data.is_secure
-        )
+        }
         for traversal_item in secure_config_items:
             value = traversal_item.value
             if isinstance(value, SecretStr):
```

What's happening here is that using set comprehension all duplicated config items are eliminated. It's not fixing the root cause.

Also I'm disappointed that such core components like config parser doesn't have a dedicated unit-tests.

**Comment by hanryang0106** [comment]
It has not been fixed yet. This problem occurs after connecting exchange. (for me, binance futures)

**Comment by hanryang0106** [comment]
For Docker users, add command in docker-compose.yml. As you may know, this is just the workaround.

(command: ["/bin/bash", "-lc", "conda activate hummingbot && ./bin/hummingbot_quickstart.py -p [your_password] 2>> ./logs/errors.log"])

**Comment by gordonkoehn** [comment]
I confirm. I am observing the same issue with password enabled and _kucoin_ and _binance_ connected; on the latest version _2.1.0_. Yet the workaround above indeed works.

**Comment by posido** [comment]
I am getting that error after a fresh installation (WLS2) and after adding the API key and secret using "connect bybit_perpeptual":

2025-02-01 09:50:35,244 - 675944 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Non-hexadecimal digit found
Traceback (most recent call last):
  File "/home/user/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/user/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 127, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/user/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 116, in schedule_async_call
    return await fut
  File "/home/user/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/user/miniconda3/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/hummingbot/hummingbot/client/config/security.py", line 65, in decrypt_all
    cls.decrypt_connector_config(file)
  File "/home/user/hummingbot/hummingbot/client/config/security.py", line 71, in decrypt_connector_config
    cls._secure_configs[connector_name] = load_connector_config_map_from_file(file_path)
  File "/home/user/hummingbot/hummingbot/client/config/config_helpers.py", line 668, in load_connector_config_map_from_file
    _load_yml_data_into_map(config_data, config_map)
  File "/home/user/hummingbot/hummingbot/client/config/config_helpers.py", line 750, in _load_yml_data_into_map
    config_validation_errors = cm.validate_model()  # try coercing values to appropriate type
  File "/home/user/hummingbot/hummingbot/client/config/config_helpers.py", line 199, in validate_model
    self.decrypt_all_secure_data()
  File "/home/user/hummingbot/hummingbot/client/config/config_helpers.py", line 237, in decrypt_all_secure_data
    decrypted_value = Security.secrets_manager.decrypt_secret_value(attr=traversal_item.attr, value=value)
  File "/home/user/hummingbot/hummingbot/client/config/config_crypt.py", line 59, in decrypt_secret_value
    value = binascii.unhexlify(value)
binascii.Error: Non-hexadecimal digit found

**Comment by Zeus-Xu0810** [comment]
@posido I also encountered the same problem as you, how did you solve it？

**Comment by posido** [comment]
Hi, I did not solve it. Right now I don't use Hummimbot until it is fixed.

**Comment by nikspz** [comment]
> I am getting that error after a fresh installation (WLS2) and after adding the API key and secret using "connect bybit_perpeptual":
> 

Hi there's separate issue for Bybit_perpetual, going to fix it
https://github.com/hummingbot/hummingbot/issues/7415

**Comment by umutgur** [comment]
I also have same issue for binance connector.

**Comment by nikspz** [comment]
> I also have same issue for binance connector.

can't reproduce, could you send screenshot of whole terminal (bot Client)

latest development (dev-2.4.0):
![Image](https://github.com/user-attachments/assets/aea7775c-0d84-4acc-befa-ac1f366c3c05)

**Comment by paCrH50036JL** [comment]
> There is a problem somewhere in `ClientConfigAdapter`, maybe in `decrypt_all_secure_data()` logic. Basically for me I see that during parsing of `conf/connectors/kucoin.yml` `kucoin_secret_key` is decrypted twice.
> 
> In the following code block of `decrypt_all_secure_data()` :
> 
>             if isinstance(value, SecretStr):
>                 value = value.get_secret_value()
> First time secret value is long encoded string as seen in the connector config Second time it is decoded value, and it's trying to decode it second time and here is `binascii.Error: Non-hexadecimal digit found` error is happening.
> 
> Decrypted value is assigned in line
> 
> ```
> setattr(config_model, final_config_element, decrypted_value)
> ```
> 
> The question is why the same config param is processed twice. Looks like `traverse()` method is emitting same config element twice for some reason.
> 
> Here is a quick dirty fix to workaround the issue.
> 
> diff --git a/hummingbot/client/config/config_helpers.py b/hummingbot/client/config/config_helpers.py
> index d0718eedb..45544f9a1 100644
> --- a/hummingbot/client/config/config_helpers.py
> +++ b/hummingbot/client/config/config_helpers.py
> @@ -54,6 +54,9 @@ class ConfigTraversalItem:
>      field_info: FieldInfo
>      type_: Type
>  
> +    def __hash__(self):
> +        return hash((self.depth, self.config_path))
> +
>  
>  class ClientConfigAdapter:
>      def __init__(self, hb_config: BaseClientModel):
> @@ -222,11 +225,11 @@ class ClientConfigAdapter:
>      def decrypt_all_secure_data(self):
>          from hummingbot.client.config.security import Security  # avoids circular import
>  
> -        secure_config_items = (
> +        secure_config_items = {
>              traversal_item
>              for traversal_item in self.traverse()
>              if traversal_item.client_field_data is not None and traversal_item.client_field_data.is_secure
> -        )
> +        }
>          for traversal_item in secure_config_items:
>              value = traversal_item.value
>              if isinstance(value, SecretStr):
> What's happening here is that using set comprehension all duplicated config items are eliminated. It's not fixing the root cause.
> 
> Also I'm disappointed that such core components like config parser doesn't have a dedicated unit-tests.

problem solved, thx
