### ISSUE TITLE
Error requesting exchange info

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6591]
### Describe the bug

VertexExchange - ERROR - There was an error requesting exchange info

Note: Not affecting other connectors

```
2023-09-28 05:26:30,022 - 3320866 - hummingbot.connector.exchange.vertex.vertex_exchange.VertexExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/nikita/staging1/hummingbot/connector/exchange/vertex/vertex_exchange.py", line 711, in _initialize_trading_pair_symbol_map
    exchange_info = await self.build_exchange_market_info()
  File "/home/nikita/staging1/hummingbot/connector/exchange/vertex/vertex_exchange.py", line 681, in build_exchange_market_info
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/home/nikita/staging1/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/nikita/staging1/hummingbot/connector/exchange/vertex/vertex_exchange.py", line 884, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/nikita/staging1/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/nikita/staging1/hummingbot/core/web_assistant/rest_assistant.py", line 99, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://test.vertexprotocol-backend.com/query?type=all_products. HTTP status is 403. Error: {"reason": "ip", "blocked": true}

```

### Steps to reproduce

1. Setup latest development branch for client
2. Start the client and observe the log panel

### Release version

dev-1.20.0

### Type of installation

Source

**Comment by nikspz** [comment]
Should be related to the IP blocked
