### ISSUE TITLE
Client - deletion of connectors .yml files returns error after restart

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6601]
### Describe the bug

After deletion of connectors .yml files returns error after restart

### Steps to reproduce

1. Clone and install latest dev branch
2. connect API keys of live exchanges (binance, kucoin, gate.io)
3. open conf folder and remove some of them (binance and kucoin yml files)
4. restart the client
5. Review the logs

### Release version

dev-1.21.0

### Type of installation

Source

### Attach required files

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/12799737/logs_hummingbot.log)

```

2023-10-04 05:30:22,527 - 3449775 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte
Traceback (most recent call last):
  File "/home/nikita/development1/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/nikita/development1/hummingbot/core/utils/async_call_scheduler.py", line 127, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/nikita/development1/hummingbot/core/utils/async_call_scheduler.py", line 116, in schedule_async_call
    return await fut
  File "/home/nikita/development1/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nikita/development1/hummingbot/client/config/security.py", line 55, in decrypt_all
    cls.decrypt_connector_config(file)
  File "/home/nikita/development1/hummingbot/client/config/security.py", line 61, in decrypt_connector_config
    cls._secure_configs[connector_name] = load_connector_config_map_from_file(file_path)
  File "/home/nikita/development1/hummingbot/client/config/config_helpers.py", line 664, in load_connector_config_map_from_file
    _load_yml_data_into_map(config_data, config_map)
  File "/home/nikita/development1/hummingbot/client/config/config_helpers.py", line 746, in _load_yml_data_into_map
    config_validation_errors = cm.validate_model()  # try coercing values to appropriate type
  File "/home/nikita/development1/hummingbot/client/config/config_helpers.py", line 195, in validate_model
    self.decrypt_all_secure_data()
  File "/home/nikita/development1/hummingbot/client/config/config_helpers.py", line 233, in decrypt_all_secure_data
    decrypted_value = Security.secrets_manager.decrypt_secret_value(attr=traversal_item.attr, value=value)
  File "/home/nikita/development1/hummingbot/client/config/config_crypt.py", line 60, in decrypt_secret_value
    decrypted_value = Account.decrypt(value.decode(), self._password).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte
```

![Error message showing when delete connectors yml files](https://github.com/hummingbot/hummingbot/assets/83953535/4359f954-ed65-478d-8cba-6b1b134be118)

**Comment by rapcmia** [comment]
Fix added
