### ISSUE TITLE
Binance perpetual - Unhandled error in background task: 'NoneType' object has no attribute 'amount'

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6603]
### Describe the bug

We ran a long term bot running on a modified `v2_market-making_dman_v3_multiple_pairs.py` with 3 market pairs on Binance perp and reviewed the log files, we observed that there are some occurrences that when it was placing take profit orders to close a position, we are getting the `ERROR - Unhandled error in background task: 'NoneType' object has no attribute 'amount'`

```
2023-10-11 02:34:00,543 - 15 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object has no attribute 'amount'
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/smart_components/smart_component_base.py", line 72, in control_loop
    await self.control_task()
  File "/home/hummingbot/hummingbot/smart_components/executors/position_executor/position_executor.py", line 222, in control_task
    self.control_barriers()
  File "/home/hummingbot/hummingbot/smart_components/executors/position_executor/position_executor.py", line 262, in control_barriers
    self.control_take_profit()
  File "/home/hummingbot/hummingbot/smart_components/executors/position_executor/position_executor.py", line 291, in control_take_profit
    elif not math.isclose(self.take_profit_order.order.amount, self.open_order.executed_amount_base):
AttributeError: 'NoneType' object has no attribute 'amount'
```

It seems that the code is trying to access an attribute called 'amount' on an object, but the object is None. While the error happened, it was able to create the take profit order and eventually filled (see sample clientID `x-3QreWesySTBUT607597bc0ddc21b13`)

![image](https://github.com/hummingbot/hummingbot/assets/73840223/5266c1ea-3620-473a-99b6-c5644c6df559)

---

Note: opened this ticket for monitoring:
```
- Noticed that this happened when placing order for take profit (checking with stop loss)
- Order status was filled and not expired 
- No stuck orders ✅ 
```

### Steps to reproduce

1. Setup a long term bot on cloud for more than 24hours
2. Review log file and look for instances of placing orders

### Release version

dev-1.21.0

### Type of installation

Source

### Attach required files

[logs_test_mm_dman_v3_multipairs.log](https://github.com/hummingbot/hummingbot/files/12864807/logs_test_mm_dman_v3_multipairs.log) `added # comments`

**Comment by cardosofede** [comment]
@rapcmia this issue should be solved in order_level_builder branch

**Comment by rapcmia** [comment]
Fixed
