### ISSUE TITLE
Client - TIME_LIMIT orders to close binance spot position used inaccurate time

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6604]
### Describe the bug

Client - TIME_LIMIT order to close binance spot position used inaccurate time.
Also logs indicate insufficient balance events (when balance is sufficient since its the SELL of base asset)
Issue reproduced multiple times for previous tests

### Steps to reproduce

1. Clone and install latest dev branch
2. connect binance
3. set up v2_market_making_dman_v3 strategy using default time limit (12 hours)
4. ran a bot to trigger time limit
5. review OPEN and CLOSED time not matched with time limit set (12 hours VS 12 hours and 1.5 min)

### Release version

dev-1.21.0

### Type of installation

Source

### Attach required files

[logs_v2_market-making_dman_v3_mul2.log](https://github.com/hummingbot/hummingbot/files/12870034/logs_v2_market-making_dman_v3_mul2.log)
[!binance-spot.zip](https://github.com/hummingbot/hummingbot/files/12870043/binance-spot.zip)

```
2023-10-11 03:26:20,092 - 3874661 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order
2023-10-11 03:26:20,096 - 3874661 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1696994780.0, "order_id": "x-XEKWYICXSMCUT607686309cf9e7c6e", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "binance"}
2023-10-11 03:26:20,099 - 3874661 - hummingbot.connector.client_order_tracker - INFO - Order x-XEKWYICXSMCUT607686309cf9e7c6e has failed. Order Update: OrderUpdate(trading_pair='MATIC-USDT', update_timestamp=1696994779.0, new_state=<OrderState.FAILED: 6>, client_order_id='x-XEKWYICXSMCUT607686309cf9e7c6e', exchange_order_id=None, misc_updates=None)
2023-10-11 03:26:20,387 - 3874661 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - NETWORK - Error submitting sell MARKET order to Binance for 23.00000000 MATIC-USDT NaN.
Traceback (most recent call last):
  File "/home/nikita/development/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/nikita/development/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/nikita/development/hummingbot/connector/exchange/binance/binance_exchange.py", line 198, in _place_order
    order_result = await self._api_post(
  File "/home/nikita/development/hummingbot/connector/exchange_py_base.py", line 867, in _api_post
    return await self._api_request(*args, **kwargs)
  File "/home/nikita/development/hummingbot/connector/exchange_py_base.py", line 905, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/nikita/development/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/nikita/development/hummingbot/core/web_assistant/rest_assistant.py", line 99, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request POST https://api.binance.com/api/v3/order. HTTP status is 400. Error: {"code":-2010,"msg":"Account has insufficient balance for requested action."}
2023-10-11 03:26:20,388 - 3874661 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - WARNING - Failed to submit SELL order to Binance. Check API key and network connection.
2023-10-11 03:26:20,392 - 3874661 - hummingbot.strategy.script_strategy_base - INFO - Creating MATIC-USDT sell order: price: NaN amount: 23.00000000.
2023-10-11 03:26:20,393 - 3874661 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order
2023-10-11 03:26:20,397 - 3874661 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1696994780.0, "order_id": "x-XEKWYICXSMCUT60768630d995e7c6e", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "binance"}
2023-10-11 03:26:20,400 - 3874661 - hummingbot.connector.client_order_tracker - INFO - Order x-XEKWYICXSMCUT60768630d995e7c6e has failed. Order Update: OrderUpdate(trading_pair='MATIC-USDT', update_timestamp=1696994780.0, new_state=<OrderState.FAILED: 6>, client_order_id='x-XEKWYICXSMCUT60768630d995e7c6e', exchange_order_id=None, misc_updates=None)
2023-10-11 03:26:20,689 - 3874661 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - NETWORK - Error submitting sell MARKET order to Binance for 23.00000000 MATIC-USDT NaN.
Traceback (most recent call last):
  File "/home/nikita/development/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/nikita/development/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/nikita/development/hummingbot/connector/exchange/binance/binance_exchange.py", line 198, in _place_order
    order_result = await self._api_post(
  File "/home/nikita/development/hummingbot/connector/exchange_py_base.py", line 867, in _api_post
    return await self._api_request(*args, **kwargs)
  File "/home/nikita/development/hummingbot/connector/exchange_py_base.py", line 905, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/nikita/development/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/nikita/development/hummingbot/core/web_assistant/rest_assistant.py", line 99, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request POST https://api.binance.com/api/v3/order. HTTP status is 400. Error: {"code":-2010,"msg":"Account has insufficient balance for requested action."}
2023-10-11 03:26:20,690 - 3874661 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - WARNING - Failed to submit SELL order to Binance. Check API key and network connection.
2023-10-11 03:26:20,691 - 3874661 - hummingbot.strategy.script_strategy_base - INFO - (MATIC-USDT) Canceling the limit order x-XEKWYICXSMCUT607685127ead17c6e. [clock=2023-10-11 03:26:20+00:00]
2023-10-11 03:26:20,695 - 3874661 - hummingbot.strategy.script_strategy_base - INFO - Creating MATIC-USDT sell order: price: NaN amount: 23.00000000.
2023-10-11 03:26:20,700 - 3874661 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order
2023-10-11 03:26:20,705 - 3874661 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1696994780.0, "order_id": "x-XEKWYICXSMCUT6076863122fb47c6e", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "binance"}
2023-10-11 03:26:20,708 - 3874661 - hummingbot.connector.client_order_tracker - INFO - Order x-XEKWYICXSMCUT6076863122fb47c6e has failed. Order Update: OrderUpdate(trading_pair='MATIC-USDT', update_timestamp=1696994780.0, new_state=<OrderState.FAILED: 6>, client_order_id='x-XEKWYICXSMCUT6076863122fb47c6e', exchange_order_id=None, misc_updates=None)
2023-10-11 03:26:21,114 - 3874661 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1696994780.0, "order_id": "x-XEKWYICXSMCUT607685127ead17c6e", "exchange_order_id": "3071529452", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2023-10-11 03:26:21,127 - 3874661 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXSMCUT607685127ead17c6e.
2023-10-11 03:26:21,132 - 3874661 - hummingbot.connector.client_order_tracker - INFO - The SELL order x-XEKWYICXSMCUT607686316dd6b7c6e amounting to 23.00000000/23.00000000 MATIC has been filled.
2023-10-11 03:26:21,134 - 3874661 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1696994781.0, "order_id": "x-XEKWYICXSMCUT607686316dd6b7c6e", "trading_pair": "MATIC-USDT", "trade_type": "TradeType.SELL", "order_type": "OrderType.MARKET", "price": "0.51370000", "amount": "23.00000000", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "0.01181510"}]}, "exchange_trade_id": "351113508", "exchange_order_id": "3071535366", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "binance"}
2023-10-11 03:26:21,170 - 3874661 - hummingbot.connector.client_order_tracker - INFO - Created MARKET SELL order x-XEKWYICXSMCUT607686316dd6b7c6e for 23.00000000 MATIC-USDT.
2023-10-11 03:26:21,172 - 3874661 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Close Order Created
2023-10-11 03:26:21,191 - 3874661 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1696994781.0, "type": "OrderType.MARKET", "trading_pair": "MATIC-USDT", "amount": "23.00000000", "price": "NaN", "order_id": "x-XEKWYICXSMCUT607686316dd6b7c6e", "creation_timestamp": 1696994780.0, "exchange_order_id": "3071535366", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "binance"}
2023-10-11 03:26:21,364 - 3874661 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1696994781.0, "order_id": "x-XEKWYICXSMCUT607686316dd6b7c6e", "base_asset": "MATIC", "quote_asset": "USDT", "base_asset_amount": "23.00000000", "quote_asset_amount": "11.8151000000000000", "order_type": "OrderType.MARKET", "exchange_order_id": "3071535366", "event_name": "SellOrderCompletedEvent", "event_source": "binance"}
2023-10-11 03:26:21,367 - 3874661 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Closed by CloseType.TIME_LIMIT
```

![image](https://github.com/hummingbot/hummingbot/assets/83953535/5acf5346-c43d-4803-8700-02cc750537c0)

**Comment by nikspz** [comment]
Closing this issue since reproduced for trailing stop as well
https://github.com/hummingbot/hummingbot/issues/6612
