### ISSUE TITLE
Injective - Unable to delegate account getting error "Could not contact DNS servers"

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6613]
### Describe the bug

When setting up account for injective v2 using `account_delegation_script.py` on mainnet and testnet, we are getting an error of `DNS resolution failed for sentry.exchange.grpc.injective.network:443: C-ares status is not ARES_SUCCESS qtype=A name=sentry.exchange.grpc.injective.network is_balancer=0: Could not contact DNS servers`

```
(hummingbot) (hummingbot) rapcmia@mishka injective_v2 % python account_delegation_script.py
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/dev/hummingbot/connector/exchange/injective_v2/account_delegation_script.py", line 106, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/rapcomia/github/hummingbot/dev/hummingbot/connector/exchange/injective_v2/account_delegation_script.py", line 30, in main
    composer = await client.composer()
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 866, in composer
    spot_markets=await self.all_spot_markets(),
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 136, in all_spot_markets
    await self._initialize_tokens_and_markets()
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 878, in _initialize_tokens_and_markets
    markets_info = (await self.get_spot_markets()).markets
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 491, in get_spot_markets
    return await self.stubSpotExchange.Markets(req)
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for sentry.exchange.grpc.injective.network:443: C-ares status is not ARES_SUCCESS qtype=A name=sentry.exchange.grpc.injective.network is_balancer=0: Could not contact DNS servers"
        debug_error_string = "UNKNOWN:DNS resolution failed for sentry.exchange.grpc.injective.network:443: C-ares status is not ARES_SUCCESS qtype=A name=sentry.exchange.grpc.injective.network is_balancer=0: Could not contact DNS servers {created_time:"2023-10-20T13:05:21.637464+08:00", grpc_status:14}"
>
```
- Getting the above error for mainnet and testnet
- Tried to change `line 29, insecure=true` then add `sentry0-3` still no go
   ![image](https://github.com/hummingbot/hummingbot/assets/73840223/44d2a3ad-c172-4188-976a-db0435cb500b)

### Steps to reproduce

1. Clone latest development branch 
2. Conda activate hummingbot 
3. Go to hummingbot/connector/exchange/injective_v2
4. Setup delegate account then run `python account_delegation_script.py`

### Release version

dev-1.21.0

### Type of installation

Source

**Comment by rapcmia** [comment]
When adding wallet to from client getting the same error on mainnet/testnet

![image](https://github.com/hummingbot/hummingbot/assets/73840223/dbc75826-4b6c-45fd-9d7e-8f96c5b9b1d2)

**Comment by rapcmia** [comment]
Issue does not occur when checking the injective v2 today

![image](https://github.com/hummingbot/hummingbot/assets/73840223/1a42ea0e-13a4-4f71-8460-004282d75e6e)

![image](https://github.com/hummingbot/hummingbot/assets/73840223/e7795650-6b98-4263-acba-afaaf1a6270d)
