### ISSUE TITLE
simple_vwap_example.py function ‘‘‘get_quote_volumequote_volume_for_base_amount‘‘‘ does not exist

### ISSUE THREAD

**Issue by rolandkofler** [hummingbot/hummingbot#6643]
### Describe the bug

Running the example is fails because the function does not exist

### Steps to reproduce

1.  runn the example
2. see in the logs
3. observe the error: 2023-11-05 19:07:16,001 - 11875 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/Users/ro/hummingbot/hummingbot/strategy/script_strategy_base.py", line 60, in tick
    self.on_tick()
  File "/Users/ro/hummingbot/scripts/simple_vwap_example.py", line 43, in on_tick
    self.init_vwap_stats()
  File "/Users/ro/hummingbot/scripts/simple_vwap_example.py", line 79, in init_vwap_stats
    orderbook_query = vwap["connector"].get_quote_volumequote_volume_for_base_amount(vwap["trading_pair"], vwap["is_buy"],
AttributeError: 'hummingbot.connector.exchange.paper_trade.paper_tr' object has no attribute 'get_quote_volumequote_volume_for_base_amount'

### Release version

1.2.1

### Type of installation

Source

**Comment by rolandkofler** [comment]
I don't know how but it works as expected and it was a strange problem. I believe it it because python interpreter and my myopathy in finding the function in the source code
