### ISSUE TITLE
Client - Unhandled error in background task: MAC mismatch after password reset

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6662]
### Describe the bug

While running some test and deleted the `.password_verification` from ./conf folder to reset password. Client wont start with errorr below: 

```
2023-11-17 22:25:17,430 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: MAC mismatch
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/core/utils/async_call_scheduler.py", line 127, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/core/utils/async_call_scheduler.py", line 116, in schedule_async_call
    return await fut
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/client/config/security.py", line 55, in decrypt_all
    cls.decrypt_connector_config(file)
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/client/config/security.py", line 61, in decrypt_connector_config
    cls._secure_configs[connector_name] = load_connector_config_map_from_file(file_path)
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/client/config/config_helpers.py", line 668, in load_connector_config_map_from_file
    _load_yml_data_into_map(config_data, config_map)
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/client/config/config_helpers.py", line 750, in _load_yml_data_into_map
    config_validation_errors = cm.validate_model()  # try coercing values to appropriate type
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/client/config/config_helpers.py", line 199, in validate_model
    self.decrypt_all_secure_data()
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/client/config/config_helpers.py", line 237, in decrypt_all_secure_data
    decrypted_value = Security.secrets_manager.decrypt_secret_value(attr=traversal_item.attr, value=value)
  File "/Users/rapcomia/github/hummingbot/test01/hummingbot/client/config/config_crypt.py", line 60, in decrypt_secret_value
    decrypted_value = Account.decrypt(value.decode(), self._password).decode()
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/eth_account/account.py", line 176, in decrypt
    return HexBytes(decode_keyfile_json(keyfile, password_bytes))
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/eth_keyfile/keyfile.py", line 56, in decode_keyfile_json
    return _decode_keyfile_json_v3(keyfile_json, password)
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/site-packages/eth_keyfile/keyfile.py", line 178, in _decode_keyfile_json_v3
    raise ValueError("MAC mismatch")
ValueError: MAC mismatch
```

### Steps to reproduce

1.  Setup latest development branch 
2.  Setup initial password and open the client 
3. Close the client and delete file /conf/`.password_verification`
4. Start client again and enter new password
5. Observe behavior 

### Release version

dev-1.22.0

### Type of installation

Source

### Attach required files

[errors.log](https://github.com/hummingbot/hummingbot/files/13392944/errors.log)

**Comment by wakamex** [comment]
same issue on main branch, commit cdfc1f8b9a8e8ef1feb52567ba9c1b38bd588e7a

**Comment by rapcmia** [comment]
Reproduced on staging 1.25.0
```
2024-02-21 09:36:13,118 - 7579 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'utf-8' codec can't decode byte 0xc2 in position 4: invalid continuation byte
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/utils/async_call_scheduler.py", line 127, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/utils/async_call_scheduler.py", line 116, in schedule_async_call
    return await fut
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/security.py", line 65, in decrypt_all
    cls.decrypt_connector_config(file)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/security.py", line 71, in decrypt_connector_config
    cls._secure_configs[connector_name] = load_connector_config_map_from_file(file_path)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/config_helpers.py", line 668, in load_connector_config_map_from_file
    _load_yml_data_into_map(config_data, config_map)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/config_helpers.py", line 750, in _load_yml_data_into_map
    config_validation_errors = cm.validate_model()  # try coercing values to appropriate type
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/config_helpers.py", line 199, in validate_model
    self.decrypt_all_secure_data()
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/config_helpers.py", line 237, in decrypt_all_secure_data
    decrypted_value = Security.secrets_manager.decrypt_secret_value(attr=traversal_item.attr, value=value)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/config_crypt.py", line 60, in decrypt_secret_value
    decrypted_value = Account.decrypt(value.decode(), self._password).decode()
```
- Tried to delete the `/conf/.password_verification` and setup diff wallet, no go, getting `ValueError: MAC mismatch`
- Revert the password back to original ✅ 
- Assuming something to do with the original password since there are already connectors added
    - Removed all connector.yml files on `conf/connector` folder
        - No error found and able to start client, added few connectors for tests then repeat steps to reset client password and use diff password
        - Error mismatched happened again ❌ 
        - Run using `./bin/hummingbot.py`, Able prompted to enter password but ended with same error

Workaround - User must remove the .password_verification and all connector.yml files on `conf/connector` from previous password to be able to reset.

---

[] Update docs https://hummingbot.org/client/password/#deleting-a-password

**Comment by rapcmia** [comment]
Closing ticket, workaround added to [docs](https://hummingbot.org/client/password/#deleting-a-password:~:text=Note%20that%20if%20you%20do%20remove%20the%20.password_verification%20file%20you%27ll%20also%20need%20to%20remove%20the%20existing%20connector.yml%20files%20under%20the%20conf/connector%20folder%20otherwise%20you%27ll%20run%20into%20an%20issue%20where%20the%20bot%20throws%20an%20error%20message%20and%20doesn%27t%20start.)
```
Note that if you do remove the .password_verification file you'll also need to remove the existing connector.yml files under the conf/connector folder otherwise you'll run into an issue where the bot throws an error message and doesn't start.
```
