### ISSUE TITLE
Bug Report: Unexpected error while processing event XXX

### ISSUE THREAD

**Issue by fengtality** [hummingbot/hummingbot#6666]
### Describe the bug

When running a strategy on Kraken, the following errors are emitted in the log:

<img width="613" alt="Screen Shot 2023-11-19 at 10 52 23 AM" src="https://github.com/hummingbot/hummingbot/assets/1795030/2fc944b2-a9e0-4ce0-994c-59db60fe1ff0">

### Steps to reproduce

- Run a V2 script on Kraken spot
- `development` version
- See attached script
[v2_market-making_dman_v3_multiple_pairs.py.zip](https://github.com/hummingbot/hummingbot/files/13416059/v2_market-making_dman_v3_multiple_pairs.py.zip)
- See attached logs
[logs_v2_market-making_dman_v3_multiple_pairs.log](https://github.com/hummingbot/hummingbot/files/13416066/logs_v2_market-making_dman_v3_multiple_pairs.log)

The log error is below. So far, it doesn't 

```
2023-11-20 06:37:15,654 - 23475 - hummingbot.connector.exchange.kraken.kraken_exchange - ERROR - Unexpected error while processing event 201.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/feng/Code/hummingbot/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/feng/Code/hummingbot/hummingbot/smart_components/executors/position_executor/position_executor.py", line 338, in process_order_created_event
    self.open_order.order = self.get_in_flight_order(self.exchange, event.order_id)
  File "/Users/feng/Code/hummingbot/hummingbot/smart_components/smart_component_base.py", line 65, in get_in_flight_order
    order = connector._order_tracker.fetch_order(client_order_id=order_id)
AttributeError: 'hummingbot.connector.exchange.kraken.kraken_exchan' object has no attribute '_order_tracker'
```

### Release version

v1.22.0-development

### Type of installation

Source

**Comment by deepak079** [comment]
I got this same error while running my v2 script on binance perpetual testnet exchange

**Comment by rapcmia** [comment]
Kraken connector has been updated
