### ISSUE TITLE
Client - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 2: invalid start byte

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6671]
### Describe the bug

When setting up hummingbot client, there are instances of this error when 2 or more connectors are added or atleast one of them is gate_io. It seems this is related to decrypting connector config or related to encryption. 

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 2: invalid start byte
2023-11-22 19:06:38,926 - 1800 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'utf-8' codec can't decode byte 0xac in position 2: invalid start byte
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/utils/async_call_scheduler.py", line 127, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/utils/async_call_scheduler.py", line 116, in schedule_async_call
    return await fut
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/Users/rapcomia/anaconda3/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/security.py", line 55, in decrypt_all
    cls.decrypt_connector_config(file)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/security.py", line 61, in decrypt_connector_config
    cls._secure_configs[connector_name] = load_connector_config_map_from_file(file_path)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/config_helpers.py", line 668, in load_connector_config_map_from_file
    _load_yml_data_into_map(config_data, config_map)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/config_helpers.py", line 750, in _load_yml_data_into_map
    config_validation_errors = cm.validate_model()  # try coercing values to appropriate type
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/config_helpers.py", line 199, in validate_model
    self.decrypt_all_secure_data()
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/config_helpers.py", line 237, in decrypt_all_secure_data
    decrypted_value = Security.secrets_manager.decrypt_secret_value(attr=traversal_item.attr, value=value)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/client/config/config_crypt.py", line 60, in decrypt_secret_value
    decrypted_value = Account.decrypt(value.decode(), self._password).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 2: invalid start byte
```

The error does not affect the performance of the client nor the exchanged used on script/strategies. Initial workaround is to open the client by either:
- `./start -p yourpassword` 
- `bin/hummingbot`

### Steps to reproduce

1. Connect 2 or more connectors or atleast one of them is gate_io
2. When successfully connected, relaunch the hummingbot client 
3. Observe behavior when the hummingbot client opens 
4. Relaunch hummingbot using `./start -p yourpassword` or `bin/hummingbot.py`

### Release version

1.22.0 or dev-1.22.0

### Type of installation

Source

### Attach required files

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/13439865/logs_hummingbot.log)

**Comment by unrelenting-d1x** [comment]
I have the same issue but the problem is: cannot start up an instance from docker. it will hung after inputed the password

**Comment by chiangqiqi** [comment]
also encounter with this issue and yes, I connect to gate_io
1. Connect 2 or more connectors or atleast one of them is gate_io

**Comment by gordonkoehn** [comment]
It still appears in `v2.2.0`. Got `binance`, `kucoin` and `okx` connected. It worked fine with the first two. Workaround with `./start -p yourpassword` still works.

**Comment by rapcmia** [comment]
not able to reproduce
