### ISSUE TITLE
Vega perpetual - OSError: Skipped order update with order fills

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6724]
### Describe the bug

When testing Vega perpetual using v2 strategies (dmanv3 complex market), initially started ok with creating and canceling orders however  we ended with the connector getting `Failed to fetch trade updates...OSError: Skipped order update with order fills..` and causing active orders stuck on exchange  

- The connector creating 7 sell orders
- The connector created 6/7 and one order ended up with OSError: Skipped order update with order fills for VGHBSEPUT60c970e6d81ac49e0c14f9f - waiting for exchange order id.
```
**# Creating 7 sell orders 

2023-12-16 02:13:01,913 - 2700261 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT sell order: price: 2271.765575792712749950534796 amount: 0.006602793950148611196567207450.
2023-12-16 02:13:01,914 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2023-12-16 02:13:01,915 - 2700261 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT sell order: price: 2279.787284390283726991161258 amount: 0.006579561217270174196724440846.
2023-12-16 02:13:01,915 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2023-12-16 02:13:01,915 - 2700261 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT sell order: price: 2287.808992987854704031787720 amount: 0.006556491405521645542650028610.
2023-12-16 02:13:01,916 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2023-12-16 02:13:01,916 - 2700261 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT sell order: price: 2295.830701585425681072414183 amount: 0.006533582807147534889282168659.
2023-12-16 02:13:01,916 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2023-12-16 02:13:01,916 - 2700261 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT sell order: price: 2303.852410182996658113040647 amount: 0.006510833738177064556137934771.
2023-12-16 02:13:01,917 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2023-12-16 02:13:01,917 - 2700261 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT sell order: price: 2311.874118780567635153667109 amount: 0.006488242538011530204691236909.
2023-12-16 02:13:01,917 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2023-12-16 02:13:01,918 - 2700261 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT sell order: price: 2319.895827378138612194293572 amount: 0.006465807569020222432227054496.
2023-12-16 02:13:01,920 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order

# Created orders 6/7 successfully
# Got an error on one with orderID VGHBSEPUT60c970e6d81ac49e0c14f9f

2023-12-16 02:13:06,930 - 2700261 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order VGHBSEPUT60c970e6d798549e0c14f9f for 0.006 to OPEN a ETHUSDPERP-USDT position.
2023-12-16 02:13:06,931 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2023-12-16 02:13:06,931 - 2700261 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702692786.0, "type": "OrderType.LIMIT", "trading_pair": "ETHUSDPERP-USDT", "amount": "0.006", "price": "2271.76", "order_id": "VGHBSEPUT60c970e6d798549e0c14f9f", "creation_timestamp": 1702692781.0, "exchange_order_id": "53f031e8893ad96e9473b6fa4c8c0de0c1248fa0822b9680a2fb6b3d64455d79", "leverage": 41, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "vega_perpetual"}
2023-12-16 02:13:06,944 - 2700261 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order VGHBSEPUT60c970e6d7d0b49e0c14f9f for 0.006 to OPEN a ETHUSDPERP-USDT position.
2023-12-16 02:13:06,945 - 2700261 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702692786.0, "type": "OrderType.LIMIT", "trading_pair": "ETHUSDPERP-USDT", "amount": "0.006", "price": "2279.78", "order_id": "VGHBSEPUT60c970e6d7d0b49e0c14f9f", "creation_timestamp": 1702692781.0, "exchange_order_id": "16c9083cbcfd4285ec31b7c5d6870b8115b5ef01e48ffb3b90838fc03d6cc0c3", "leverage": 41, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "vega_perpetual"}
2023-12-16 02:13:06,955 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2023-12-16 02:13:06,956 - 2700261 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order VGHBSEPUT60c970e6d83cc49e0c14f9f for 0.006 to OPEN a ETHUSDPERP-USDT position.
2023-12-16 02:13:06,956 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2023-12-16 02:13:06,957 - 2700261 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702692786.0, "type": "OrderType.LIMIT", "trading_pair": "ETHUSDPERP-USDT", "amount": "0.006", "price": "2303.85", "order_id": "VGHBSEPUT60c970e6d83cc49e0c14f9f", "creation_timestamp": 1702692781.0, "exchange_order_id": "947e63a6b7f0a33ecc50cb971c008e34f149ff97c511fa8d3c06b6b54e47de61", "leverage": 41, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "vega_perpetual"}
2023-12-16 02:13:06,983 - 2700261 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order VGHBSEPUT60c970e6d7f8649e0c14f9f for 0.006 to OPEN a ETHUSDPERP-USDT position.
2023-12-16 02:13:06,983 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2023-12-16 02:13:06,984 - 2700261 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702692786.0, "type": "OrderType.LIMIT", "trading_pair": "ETHUSDPERP-USDT", "amount": "0.006", "price": "2287.80", "order_id": "VGHBSEPUT60c970e6d7f8649e0c14f9f", "creation_timestamp": 1702692781.0, "exchange_order_id": "bd29a08bc759f5f395ea2dbd8a916308a0d345e2bcdf39d4740c91c0aec02fe7", "leverage": 41, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "vega_perpetual"}
2023-12-16 02:13:06,994 - 2700261 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order VGHBSEPUT60c970e6d880249e0c14f9f for 0.006 to OPEN a ETHUSDPERP-USDT position.
2023-12-16 02:13:06,995 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2023-12-16 02:13:06,996 - 2700261 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702692786.0, "type": "OrderType.LIMIT", "trading_pair": "ETHUSDPERP-USDT", "amount": "0.006", "price": "2319.89", "order_id": "VGHBSEPUT60c970e6d880249e0c14f9f", "creation_timestamp": 1702692781.0, "exchange_order_id": "70d98c65f20f67d1984a573e174f4574d0b306a35b162cf32cb8372a9fc08f6a", "leverage": 41, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "vega_perpetual"}
2023-12-16 02:13:07,007 - 2700261 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order VGHBSEPUT60c970e6d85e749e0c14f9f for 0.006 to OPEN a ETHUSDPERP-USDT position.
2023-12-16 02:13:07,008 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2023-12-16 02:13:07,008 - 2700261 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702692786.0, "type": "OrderType.LIMIT", "trading_pair": "ETHUSDPERP-USDT", "amount": "0.006", "price": "2311.87", "order_id": "VGHBSEPUT60c970e6d85e749e0c14f9f", "creation_timestamp": 1702692781.0, "exchange_order_id": "1e2fcfaec0fa7f0798ff40de8fff283234e222c0abbc948368a0fec38285c0f7", "leverage": 41, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "vega_perpetual"}
2023-12-16 02:14:11,425 - 2700261 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - WARNING - Failed to fetch trade updates for order VGHBSEPUT60c970e6d81ac49e0c14f9f. Error: Skipped order update with order fills for VGHBSEPUT60c970e6d81ac49e0c14f9f - waiting for exchange order id.
Traceback (most recent call last):
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/core/data_type/in_flight_order.py", line 294, in get_exchange_order_id
    await self.exchange_order_id_update_event.wait()
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 598, in _all_trade_updates_for_order
    exchange_order_id = await tracked_order.get_exchange_order_id()
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/core/data_type/in_flight_order.py", line 293, in get_exchange_order_id
    async with timeout(GET_EX_ORDER_ID_TIMEOUT):
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/connector/exchange_py_base.py", line 954, in _update_orders_fills
    trade_updates = await self._all_trade_updates_for_order(order=order)
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 618, in _all_trade_updates_for_order
    raise IOError(f"Skipped order update with order fills for {tracked_order.client_order_id} "
OSError: Skipped order update with order fills for VGHBSEPUT60c970e6d81ac49e0c14f9f - waiting for exchange order id.**
```
  - 2023-12-16 02:14:11,425 OSerror for VGHBSEPUT60c970e6d81ac49e0c14f9f started and occurred everytime connector on canceling order event
  - 2023-12-16 02:20:14,795 Order has been considered lost

After the order lost event, observed that the connector begun to only create same price and amount:
- These orders ended with order failed and error submitting order to exchange
- Orders that are initially created has not been cancelled and stuck on exchange
- Getting `ValueError: Failed transaction submission`
```
# Creating order on 2295.830701585425681072414183 amount: 0.006533582807147534889282168659.
# Order VGHBSEPUT60c970e6d81ac49e0c14f9f has failed 
# ValueError: Failed transaction submission for VGHBSEPUT60c97283abb4549e0c14f9f with {'success': True, 'txHash': '48BD1C81597DC53721A8AAF1E9F94CCE5D03E1E0011EA0856F9DB37839DD0C79', 'code': 89, 'data': '70617274792069732062616E6E65642066726F6D2073656E64696E67207472616E73616374696F6E73', 'log': '', 'height': '0'}

2023-12-16 02:20:14,796 - 2700261 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT sell order: price: 2295.830701585425681072414183 amount: 0.006533582807147534889282168659.
2023-12-16 02:20:14,796 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2023-12-16 02:20:14,799 - 2700261 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702693213.0, "order_id": "VGHBSEPUT60c970e6d81ac49e0c14f9f", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "vega_perpetual"}
2023-12-16 02:20:14,800 - 2700261 - hummingbot.connector.client_order_tracker - INFO - Order VGHBSEPUT60c970e6d81ac49e0c14f9f has failed. Order Update: OrderUpdate(trading_pair='ETHUSDPERP-USDT', update_timestamp=1702693213.0, new_state=<OrderState.FAILED: 6>, client_order_id='VGHBSEPUT60c970e6d81ac49e0c14f9f', exchange_order_id=None, misc_updates=None)
2023-12-16 02:20:15,480 - 2700261 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - NETWORK - Error submitting sell LIMIT order to Vega_perpetual for 0.006 ETHUSDPERP-USDT 2295.83.
Traceback (most recent call last):
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 434, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 535, in _place_order
    raise ValueError(f"Failed transaction submission for {order_id} with {response}")
ValueError: Failed transaction submission for VGHBSEPUT60c97283abb4549e0c14f9f with {'success': True, 'txHash': '48BD1C81597DC53721A8AAF1E9F94CCE5D03E1E0011EA0856F9DB37839DD0C79', 'code': 89, 'data': '70617274792069732062616E6E65642066726F6D2073656E64696E67207472616E73616374696F6E73', 'log': '', 'height': '0'}
2023-12-16 02:20:15,481 - 2700261 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - WARNING - Failed to submit SELL order to Vega_perpetual. Check API key and network connection.


# Observed that it begaun creating same sell order but with different order id 
# Ended with same result with ValueError on order ID ValueError: Failed transaction submission

2023-12-16 02:20:15,482 - 2700261 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT sell order: price: 2295.830701585425681072414183 amount: 0.006533582807147534889282168659.
2023-12-16 02:20:15,482 - 2700261 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2023-12-16 02:20:15,486 - 2700261 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1702693215.0, "order_id": "VGHBSEPUT60c97283abb4549e0c14f9f", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "vega_perpetual"}
2023-12-16 02:20:15,487 - 2700261 - hummingbot.connector.client_order_tracker - INFO - Order VGHBSEPUT60c97283abb4549e0c14f9f has failed. Order Update: OrderUpdate(trading_pair='ETHUSDPERP-USDT', update_timestamp=1702693215.0, new_state=<OrderState.FAILED: 6>, client_order_id='VGHBSEPUT60c97283abb4549e0c14f9f', exchange_order_id=None, misc_updates=None)
2023-12-16 02:20:15,925 - 2700261 - hummingbot.strategy.script_strategy_base - INFO - (ETHUSDPERP-USDT) Canceling the limit order VGHBSEPUT60c972845330349e0c14f9f. [clock=2023-12-16 02:20:15+00:00]
2023-12-16 02:20:15,926 - 2700261 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - NETWORK - Error submitting sell LIMIT order to Vega_perpetual for 0.006 ETHUSDPERP-USDT 2295.83.
Traceback (most recent call last):
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 434, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/ralph/github/hummingbot/6628-new/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 535, in _place_order
    raise ValueError(f"Failed transaction submission for {order_id} with {response}")
ValueError: Failed transaction submission for VGHBSEPUT60c972845330349e0c14f9f with {'success': True, 'txHash': '3F353FA91302B5664263DDFD5F3E09D541BB8C27432C13A90D2BD6D5575E40E0', 'code': 89, 'data': '70617274792069732062616E6E65642066726F6D2073656E64696E67207472616E73616374696F6E73', 'log': '', 'height': '0'}
2023-12-16 02:20:15,928 - 2700261 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - WARNING - Failed to submit SELL order to Vega_perpetual. Check API key and network connection.
```
  - 2023-12-16 02:20:14,796 Issue started here
  - 2023-12-16 02:26:57,626 Continues until stop command is initiated
    ![image](https://github.com/hummingbot/hummingbot/assets/73840223/da351d16-b56f-40da-a622-e489b226c4de)

### Steps to reproduce

1. Setup vega perpetual on development branch 
2. Use [dmanv3 complex markets](https://gist.github.com/rapcmia/4d7687e11e5174c74a57a5a672e896e5) script 
3. Observe connector behavior when running long term 

### Release version

dev-1.23.0

### Type of installation

Source

### Attach required files

https://drive.google.com/drive/folders/1a2WGUx1AVY8TlI0L24k-5dLXEmXEsln1?usp=sharing

**Comment by rapcmia** [comment]
Not able to reproduce after reduce the number of order levels. The issue was related to the API getting banned due to one orders `Rejected as spam— party is banned from sending transactions`
