### ISSUE TITLE
Injective - There was an error requesting exchange info.

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6733]
### Describe the bug

Issue related to injective_v2 (not affecting other connectors)

```
2023-12-21 14:01:20,679 - 2977521 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/injective_v2_exchange.py", line 852, in _initialize_trading_pair_symbol_map
    mapping = await self._data_source.spot_market_and_trading_pair_map()
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/data_sources/injective_grantee_data_source.py", line 157, in spot_market_and_trading_pair_map
    await self.update_markets()
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/data_sources/injective_grantee_data_source.py", line 278, in update_markets
    markets = await self._query_executor.spot_markets(status="active")
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/injective_query_executor.py", line 174, in spot_markets
    response = await self._sdk_client.get_spot_markets(status=status)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 491, in get_spot_markets
    return await self.stubSpotExchange.Markets(req)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Received http2 header with status: 503"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-12-21T14:01:20.678548284+00:00", grpc_status:14, grpc_message:"Received http2 header with status: 503"}"
>
2023-12-21 14:01:20,702 - 2977521 - hummingbot.connector.derivative.injective_v2_perpetual.injective_v2_perpetual_derivative.InjectiveV2PerpetualDerivative - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/nikita/staging/hummingbot/connector/derivative/injective_v2_perpetual/injective_v2_perpetual_derivative.py", line 956, in _initialize_trading_pair_symbol_map
    mapping = await self._data_source.derivative_market_and_trading_pair_map()
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/data_sources/injective_grantee_data_source.py", line 172, in derivative_market_and_trading_pair_map
    await self.update_markets()
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/data_sources/injective_grantee_data_source.py", line 278, in update_markets
    markets = await self._query_executor.spot_markets(status="active")
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/injective_query_executor.py", line 174, in spot_markets
    response = await self._sdk_client.get_spot_markets(status=status)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 491, in get_spot_markets
    return await self.stubSpotExchange.Markets(req)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Received http2 header with status: 503"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Received http2 header with status: 503", grpc_status:14, created_time:"2023-12-21T14:01:20.698890358+00:00"}"
>
2023-12-21 14:01:20,703 - 2977521 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/injective_v2_exchange.py", line 852, in _initialize_trading_pair_symbol_map
    mapping = await self._data_source.spot_market_and_trading_pair_map()
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/data_sources/injective_grantee_data_source.py", line 157, in spot_market_and_trading_pair_map
    await self.update_markets()
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/data_sources/injective_grantee_data_source.py", line 278, in update_markets
    markets = await self._query_executor.spot_markets(status="active")
  File "/home/nikita/staging/hummingbot/connector/exchange/injective_v2/injective_query_executor.py", line 174, in spot_markets
    response = await self._sdk_client.get_spot_markets(status=status)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 491, in get_spot_markets
    return await self.stubSpotExchange.Markets(req)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Received http2 header with status: 503"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Received http2 header with status: 503", grpc_status:14, created_time:"2023-12-21T14:01:20.699016774+00:00"}"
>
```

### Steps to reproduce

1. Clone latest development/master branch
2. Start the client
3. Review the issue

### Release version

dev-1.23.0

### Type of installation

Source

### Attach required files

![image](https://github.com/hummingbot/hummingbot/assets/83953535/db2aa9df-2ad9-41b7-90a3-3ed7e1d65ef5)

![image](https://github.com/hummingbot/hummingbot/assets/83953535/37a96297-4304-4649-9b46-790919b4b754)

**Comment by rapcmia** [comment]
As of version 1.25.0 and development branch, getting same error but with different error upon opening hummingbot client  
```
2024-02-29 06:16:56,615 - 187573 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/ralph/github/hummingbot/6844/hummingbot/connector/exchange/injective_v2/injective_v2_exchange.py", line 799, in _initialize_trading_pair_symbol_map
    mapping = await self._data_source.spot_market_and_trading_pair_map()
  File "/home/ralph/github/hummingbot/6844/hummingbot/connector/exchange/injective_v2/data_sources/injective_read_only_data_source.py", line 115, in spot_market_and_trading_pair_map
    await self.update_markets()
  File "/home/ralph/github/hummingbot/6844/hummingbot/connector/exchange/injective_v2/data_sources/injective_read_only_data_source.py", line 220, in update_markets
    ) = await self._get_markets_and_tokens()
  File "/home/ralph/github/hummingbot/6844/hummingbot/connector/exchange/injective_v2/data_sources/injective_data_source.py", line 1587, in _get_markets_and_tokens
    spot_markets: Dict[str, SpotMarket] = await self.query_executor.spot_markets()
  File "/home/ralph/github/hummingbot/6844/hummingbot/connector/exchange/injective_v2/injective_query_executor.py", line 161, in spot_markets
    return await self._sdk_client.all_spot_markets()
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 324, in all_spot_markets
    await self._initialize_tokens_and_markets()
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 2653, in _initialize_tokens_and_markets
    markets_info = (await self.fetch_spot_markets(market_statuses=["active"]))["markets"]
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 1325, in fetch_spot_markets
    return await self.exchange_spot_api.fetch_markets(
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/client/indexer/grpc/indexer_grpc_spot_api.py", line 29, in fetch_markets
    response = await self._execute_call(call=self._stub.Markets, request=request)
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/client/indexer/grpc/indexer_grpc_spot_api.py", line 240, in _execute_call
    return await self._assistant.execute_call(call=call, request=request)
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/utils/grpc_api_request_assistant.py", line 12, in execute_call
    metadata = await self._metadata_provider()
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/core/network.py", line 331, in exchange_metadata
    return await self.cookie_assistant.exchange_metadata(metadata_query_provider=metadata_query_provider)
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/core/network.py", line 25, in exchange_metadata
    cookie = await self.exchange_cookie(metadata_query_provider=metadata_query_provider)
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/core/network.py", line 113, in exchange_cookie
    await self._fetch_exchange_cookie(metadata_query_provider=metadata_query_provider)
  File "/home/ralph/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/core/network.py", line 133, in _fetch_exchange_cookie
    raise RuntimeError(f"Error fetching exchange cookie ({metadata})")
RuntimeError: Error fetching exchange cookie (Metadata((('alt-svc', 'h3=":443"; ma=2592000'), ('server', 'Caddy'), ('date', 'Thu, 29 Feb 2024 06:16:56 GMT'))))
```

**Comment by nikspz** [comment]
version 1.27.0 source

![image](https://github.com/hummingbot/hummingbot/assets/83953535/f8825e23-05ac-404a-a456-7fca839d80d9)


```
2024-05-01 19:07:24,766 - 88521 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/nikita/development1/hummingbot/connector/exchange/injective_v2/injective_v2_exchange.py", line 799, in _initialize_trading_pair_symbol_map
    mapping = await self._data_source.spot_market_and_trading_pair_map()
  File "/home/nikita/development1/hummingbot/connector/exchange/injective_v2/data_sources/injective_read_only_data_source.py", line 115, in spot_market_and_trading_pair_map
    await self.update_markets()
  File "/home/nikita/development1/hummingbot/connector/exchange/injective_v2/data_sources/injective_read_only_data_source.py", line 220, in update_markets
    ) = await self._get_markets_and_tokens()
  File "/home/nikita/development1/hummingbot/connector/exchange/injective_v2/data_sources/injective_data_source.py", line 1595, in _get_markets_and_tokens
    spot_markets: Dict[str, SpotMarket] = await self.query_executor.spot_markets()
  File "/home/nikita/development1/hummingbot/connector/exchange/injective_v2/injective_query_executor.py", line 161, in spot_markets
    return await self._sdk_client.all_spot_markets()
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 337, in all_spot_markets
    await self._initialize_tokens_and_markets()
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 3115, in _initialize_tokens_and_markets
    markets_info = (await self.fetch_spot_markets(market_statuses=["active"]))["markets"]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/async_client.py", line 1787, in fetch_spot_markets
    return await self.exchange_spot_api.fetch_markets(
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/client/indexer/grpc/indexer_grpc_spot_api.py", line 29, in fetch_markets
    response = await self._execute_call(call=self._stub.Markets, request=request)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/client/indexer/grpc/indexer_grpc_spot_api.py", line 240, in _execute_call
    return await self._assistant.execute_call(call=call, request=request)
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pyinjective/utils/grpc_api_request_assistant.py", line 15, in execute_call
    result = json_format.MessageToDict(
TypeError: MessageToDict() got an unexpected keyword argument 'including_default_value_fields'
```
