### ISSUE TITLE
Injective  - Unexpected error while running the transactions check process

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6734]
### Describe the bug

When running test on injective spot exchange, we observed that there are instances of the connector creating orders returned `unexpected error while running the transaction check process`

```

2023-12-22 11:46:39,005 - 16886 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (INJ-USDT) Creating 1 bid orders at (Size, Price): ['0.5 INJ, 39.52 USDT']
2023-12-22 11:46:39,006 - 16886 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (INJ-USDT) Creating 1 ask orders at (Size, Price): ['0.5 INJ, 39.583 USDT']
2023-12-22 11:46:47,056 - 16886 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - ERROR - Unexpected error while running the transactions check process
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange/injective_v2/injective_v2_exchange.py", line 905, in _check_orders_transactions
    await asyncio.shield(task)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange/injective_v2/injective_v2_exchange.py", line 927, in _check_orders_creation_transactions
    order_updates = await self._data_source.order_updates_for_transaction(
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange/injective_v2/data_sources/injective_grantee_data_source.py", line 357, in order_updates_for_transaction
    transaction_data = str(base64.b64decode(transaction_info["data"]["data"]))
KeyError: 'data'
```

Client is stuck on this behavior and orders are active but not on exchange 
![image](https://github.com/hummingbot/hummingbot/assets/73840223/79d675d9-5975-46cd-88a2-4d766e8cf749)
![image](https://github.com/hummingbot/hummingbot/assets/73840223/b36bde46-525c-4b36-890c-696ec1897ba3)

Waited for couple more minutes and ended up with `There was a problem updating order... (order not found).`
```
2023-12-22 11:59:51,001 - 16886 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (INJ-USDT) Canceling the limit order BIJUT60d11311fba0c7ae57bd8df4233d974642083223cfcf0. [clock=2023-12-22 03:59:51+00:00]
2023-12-22 11:59:51,002 - 16886 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (INJ-USDT) Canceling the limit order SIJUT60d11311fbab67ae57bd8df4233d974642083223cfcf0. [clock=2023-12-22 03:59:51+00:00]
2023-12-22 12:00:01,083 - 16886 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - WARNING - Error fetching status update for the active order BIJUT60d11311fba0c7ae57bd8df4233d974642083223cfcf0: There was a problem updating order BIJUT60d11311fba0c7ae57bd8df4233d974642083223cfcf0 (order not found).
2023-12-22 12:00:01,084 - 16886 - hummingbot.connector.exchange.injective_v2.injective_v2_exchange.InjectiveV2Exchange - WARNING - Error fetching status update for the active order SIJUT60d11311fbab67ae57bd8df4233d974642083223cfcf0: There was a problem updating order SIJUT60d11311fbab67ae57bd8df4233d974642083223cfcf0 (order not found).
```

### Steps to reproduce

1.  Setup Injective spot on Pure market making
2.  Start the strategy and observe behavior 

### Release version

dev-1.23.0

### Type of installation

Source

### Attach required files

[logs_pmm-injective.log](https://github.com/hummingbot/hummingbot/files/13748235/logs_pmm-injective.log)
[pmm-injective.yml.log](https://github.com/hummingbot/hummingbot/files/13748234/pmm-injective.yml.log)

**Comment by cxfshelter** [comment]
How did it work out? @rapcmia
