### ISSUE TITLE
Bitmex perpetual - Not compatible with v2 strategies

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6753]
### Describe the bug
We are looking into bronze connectors to run on v2 strategies and started with bitmex perpetuals. We setup a simple dmanv3 multiple pair script and observed the following issues:

Getting Unexpected error while processing event 200..AttributeError: 'BitmexPerpetualDerivative' object has no attribute '_order_tracker'
```
2024-01-05 12:51:56,316 - 16866 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704430316000, "type": "OrderType.LIMIT", "trading_pair": "XRP-USDT", "amount": "44.07796359841251130075310003", "price": "0.5671768375638022174896285512", "order_id": "bitmex_perpBXPUT60e2b9b882746cad9b3d", "creation_timestamp": 1704430316.039713, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "bitmex_perpetual"}
2024-01-05 12:51:56,316 - 16866 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - ERROR - Unexpected error while processing event 200.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/executors/position_executor/position_executor.py", line 339, in process_order_created_event
    self.open_order.order = self.get_in_flight_order(self.exchange, event.order_id)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/smart_component_base.py", line 65, in get_in_flight_order
    order = connector._order_tracker.fetch_order(client_order_id=order_id)
AttributeError: 'BitmexPerpetualDerivative' object has no attribute '_order_tracker'
```
- Comparing both binance and bitmex perpetuals `_derivative.py` file
    - bitmex perpetual seems to be using the old template using `client_order_tracker`
    ![image](https://github.com/hummingbot/hummingbot/assets/73840223/12956c89-fb6d-46c9-9f10-e3df8bec28b5)
    - binance perpetual 
    ![image](https://github.com/hummingbot/hummingbot/assets/73840223/f0cd13f9-1257-42b0-a68f-53134ba74c39)
    - The connector still able to proceed with creating orders. 

---

`Multiple markets`: When a position executor is opened and trailing stop has started, the connector began spamming placing order close with `Order amount or notional size is insufficient`
```
# order bitmex_perpBSIUT60e2d1afa7701fe08c2d has been successfully created 

2024-01-05 14:39:09,488 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - INFO - Created order bitmex_perpBSIUT60e2d1afa7701fe08c2d for 20 SEI-USDT.
2024-01-05 14:39:09,489 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436749000, "type": "OrderType.LIMIT", "trading_pair": "SEI-USDT", "amount": "27.55198903991517371372968568", "price": "0.7259004049045446134349278901", "order_id": "bitmex_perpBSIUT60e2d1afa7701fe08c2d", "creation_timestamp": 1704436749.2151139, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:09,497 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - ERROR - Unexpected error while processing event 200.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/executors/position_executor/position_executor.py", line 339, in process_order_created_event
    self.open_order.order = self.get_in_flight_order(self.exchange, event.order_id)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/smart_component_base.py", line 65, in get_in_flight_order
    order = connector._order_tracker.fetch_order(client_order_id=order_id)
AttributeError: 'BitmexPerpetualDerivative' object has no attribute '_order_tracker'
2024-01-05 14:39:09,556 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - INFO - Created order bitmex_perpBSIUT60e2d1afa8752fe08c2d for 20 SEI-USDT.
2024-01-05 14:39:09,556 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436749000, "type": "OrderType.LIMIT", "trading_pair": "SEI-USDT", "amount": "28.36737930235889326712737036", "price": "0.7050351668663624944652858871", "order_id": "bitmex_perpBSIUT60e2d1afa8752fe08c2d", "creation_timestamp": 1704436749.222819, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:09,564 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - ERROR - Unexpected error while processing event 200.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/executors/position_executor/position_executor.py", line 339, in process_order_created_event
    self.open_order.order = self.get_in_flight_order(self.exchange, event.order_id)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/smart_component_base.py", line 65, in get_in_flight_order
    order = connector._order_tracker.fetch_order(client_order_id=order_id)
AttributeError: 'BitmexPerpetualDerivative' object has no attribute '_order_tracker'

# order bitmex_perpBSIUT60e2d1afa7701fe08c2d has been cmopleted
# opened long position

2024-01-05 14:39:09,591 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436749.0, "order_id": "bitmex_perpBSIUT60e2d1afa7701fe08c2d", "trading_pair": "SEI-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "0.7257", "amount": "20", "trade_fee": {"percent": "0.0001", "percent_token": null, "flat_fees": []}, "exchange_trade_id": "bitmex_perpBSIUT60e2d1afa7701fe08c2d", "exchange_order_id": "", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:09,592 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - INFO - The market buy order bitmex_perpBSIUT60e2d1afa7701fe08c2d has completed according to user stream.
2024-01-05 14:39:09,593 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436749.0, "order_id": "bitmex_perpBSIUT60e2d1afa7701fe08c2d", "base_asset": "SEI", "quote_asset": "USDT", "base_asset_amount": "20", "quote_asset_amount": "14.5140", "order_type": "OrderType.LIMIT", "exchange_order_id": "e72747ee-4691-401e-bc44-04fb057a9352", "event_name": "BuyOrderCompletedEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:09,593 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Completed
2024-01-05 14:39:09,663 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - INFO - Created order bitmex_perpBSIUT60e2d1afa946ffe08c2d for 20 SEI-USDT.
2024-01-05 14:39:09,663 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436749000, "type": "OrderType.LIMIT", "trading_pair": "SEI-USDT", "amount": "29.23250373522733095027470521", "price": "0.6841699288281803754956438842", "order_id": "bitmex_perpBSIUT60e2d1afa946ffe08c2d", "creation_timestamp": 1704436749.2266738, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:09,670 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - ERROR - Unexpected error while processing event 200.
Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/executors/position_executor/position_executor.py", line 339, in process_order_created_event
    self.open_order.order = self.get_in_flight_order(self.exchange, event.order_id)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/smart_component_base.py", line 65, in get_in_flight_order
    order = connector._order_tracker.fetch_order(client_order_id=order_id)
AttributeError: 'BitmexPerpetualDerivative' object has no attribute '_order_tracker'

# Trailing stop activated and every milliseconds, connector trying to place order with `Order amount or notional size is insufficient`

2024-01-05 14:39:10,218 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Trailing stop activated at 12515550.6516
2024-01-05 14:39:10,219 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,219 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,219 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b09f78bfe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,221 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,221 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,221 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b09f78bfe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,221 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b09fff9fe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,223 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,223 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,223 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b09fff9fe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,223 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0a0910fe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,225 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,225 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,225 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0a0910fe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,225 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0a0ffafe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,227 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,227 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,227 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0a0ffafe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,227 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0a1760fe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,228 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,228 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,229 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0a1760fe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,229 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0a1db0fe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,231 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,231 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,231 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0a1db0fe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,266 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0a2797fe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,267 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,267 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,268 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0a2797fe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,297 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0ab5f2fe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,299 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,299 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,299 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0ab5f2fe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,326 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0b3217fe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,327 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,328 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,328 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0b3217fe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,328 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0ba0fcfe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,330 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,330 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,330 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0ba0fcfe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,331 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0ba9c2fe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,332 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,333 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,333 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0ba9c2fe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,333 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0bb4c0fe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,334 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,335 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,335 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0bb4c0fe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,335 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0bbc9ffe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,337 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,337 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,337 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0bbc9ffe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,369 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0bc752fe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,371 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,372 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-05 14:39:10,372 - 21577 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Failed to place bitmex_perpSSIUT60e2d1b0bc752fe08c2d on bitmex. Order amount or notional size is insufficient
2024-01-05 14:39:10,372 - 21577 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704436750000, "order_id": "bitmex_perpSSIUT60e2d1b0c4d0cfe08c2d", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "bitmex_perpetual"}
2024-01-05 14:39:10,374 - 21577 - hummingbot.strategy.script_strategy_base - INFO - Creating SEI-USDT sell order: price: NaN amount: 0.
2024-01-05 14:39:10,375 - 21577 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
```
- Compared to using single markets, connector has been able to create multiple order levels however getting rate limited:
    ```
    2024-01-06 00:42:04,605 - 24950 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - INFO - Created order bitmex_perpSSIUT60e35872d3db4f40cafa for 20 SEI-USDT.
    2024-01-06 00:42:04,607 - 24950 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704472924000, "type": "OrderType.LIMIT", "trading_pair": "SEI-USDT", "amount": "25.96823062801969425518457553", "price": "0.7701718413737445970136741752", "order_id": "bitmex_perpSSIUT60e35872d3db4f40cafa", "creation_timestamp": 1704472924.212977, "exchange_order_id": null, "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "bitmex_perpetual"}
    2024-01-06 00:42:04,607 - 24950 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - ERROR - Unexpected error while processing event 201.
    Traceback (most recent call last):
      File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
        typed_listener.c_call(arg)
      File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
        self(arg)
      File "/Users/rapcomia/github/hummingbot/development/hummingbot/core/event/event_forwarder.py", line 24, in __call__
        self._to_function(self.current_event_tag, self.current_event_caller, arg)
      File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/executors/position_executor/position_executor.py", line 339, in process_order_created_event
        self.open_order.order = self.get_in_flight_order(self.exchange, event.order_id)
      File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/smart_component_base.py", line 65, in get_in_flight_order
        order = connector._order_tracker.fetch_order(client_order_id=order_id)
    AttributeError: 'BitmexPerpetualDerivative' object has no attribute '_order_tracker'
    2024-01-06 00:42:04,608 - 24950 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - ERROR - Error fetching /order
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_derivative.py", line 1172, in _api_request
        return await web_utils.api_request(
      File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_web_utils.py", line 86, in api_request
        raise IOError(f"Error executing request {method.name} {path}. "
    OSError: Error executing request POST /order. HTTP status is 429. Error: {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
    2024-01-06 00:42:04,608 - 24950 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Error executing request POST /order. HTTP status is 429. Error: {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
    2024-01-06 00:42:04,608 - 24950 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Error submitting SELL LIMIT order to bitmex for 20 SEI-USDT at 0.9011.
    2024-01-06 00:42:04,608 - 24950 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - INFO - Error executing request POST /order. HTTP status is 429. Error: {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
    Traceback (most recent call last):
      File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_derivative.py", line 912, in execute_order
        creation_response = await self.place_order(
      File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_derivative.py", line 858, in place_order
        return await self._api_request(
      File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_derivative.py", line 1186, in _api_request
        raise e
      File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_derivative.py", line 1172, in _api_request
        return await web_utils.api_request(
      File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_web_utils.py", line 86, in api_request
        raise IOError(f"Error executing request {method.name} {path}. "
    OSError: Error executing request POST /order. HTTP status is 429. Error: {"error":{"message":"Rate limit exceeded, retry in 1 seconds.","name":"RateLimitError"}}
    ```

---

When connector tries to fetch update on a active open position, we are getting `OSError: Error executing request GET /position. HTTP status is 503`
```
2024-01-06 01:01:10,345 - 24950 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - ERROR - Error fetching /position
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_derivative.py", line 1172, in _api_request
    return await web_utils.api_request(
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_web_utils.py", line 86, in api_request
    raise IOError(f"Error executing request {method.name} {path}. "
OSError: Error executing request GET /position. HTTP status is 503. Error: {"error":{"message":"Engine Error: 503","name":"HTTPError"}}
2024-01-06 01:01:10,348 - 24950 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - WARNING - Error executing request GET /position. HTTP status is 503. Error: {"error":{"message":"Engine Error: 503","name":"HTTPError"}}
2024-01-06 01:01:10,349 - 24950 - hummingbot.connector.derivative.bitmex_perpetual.bitmex_perpetual_derivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_derivative.py", line 666, in _status_polling_loop
    await safe_gather(
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_derivative.py", line 748, in _update_positions
    positions = await self._api_request(
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_derivative.py", line 1186, in _api_request
    raise e
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_derivative.py", line 1172, in _api_request
    return await web_utils.api_request(
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/derivative/bitmex_perpetual/bitmex_perpetual_web_utils.py", line 86, in api_request
    raise IOError(f"Error executing request {method.name} {path}. "
OSError: Error executing request GET /position. HTTP status is 503. Error: {"error":{"message":"Engine Error: 503","name":"HTTPError"}}
```

### Steps to reproduce

1. Add API keys for bitmex_perpetual connector
2. Setup the `v2_market-making_dman_v3_multiple_pairs.py` script using the connector
3. Setup multiple markets, order level 3 or more. Observe behavior 
4. Setup single market, order level 3 or more. Observe behavior 

_Please be advised that this is a bronze connector which has not been updated to latest connector standards._

### Release version

dev-1.24.0

### Type of installation

Source

### Attach required files

[logs_test01.log](https://github.com/hummingbot/hummingbot/files/13844849/logs_test01.log)

**Comment by rapcmia** [comment]
bitmex removed
