### ISSUE TITLE
Hyperliquid - Error on submit market order due to reduce only order would increase position.

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6757]
### Describe the bug

When reviewing hyperliquid running on dmanv3 with runtime of 2days, observed that there are instances of this submit of order failed due to `reduce only order would increase position.` when closing a position executor.

See sample on error below using order id: 0x981eef5312be54e87e24402a0222d43b
```
2024-01-08 00:15:07,840 - 1 - hummingbot.strategy.script_strategy_base - INFO - Creating SOL-USD sell order: price: NaN amount: 0.22.
2024-01-08 00:15:07,841 - 1 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0.22 | TP Partial execution: 0
2024-01-08 00:15:08,829 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Error submitting sell MARKET order to Hyperliquid_perpetual for 0.21 SOL-USD 83.9419999999999930651028989814221858978271484375.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 390, in _place_order
    raise IOError(f"Error submitting order {order_id}: {o_order_result['error']}")
OSError: Error submitting order 0x981eef5312be54e87e24402a0222d43b: Reduce only order would increase position.
2024-01-08 00:15:08,830 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Failed to submit SELL order to Hyperliquid_perpetual. Check API key and network connection.
2024-01-08 00:15:08,831 - 1 - hummingbot.strategy.script_strategy_base - INFO - Creating SOL-USD sell order: price: NaN amount: 0.21.
2024-01-08 00:15:08,832 - 1 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0.21 | TP Partial execution: 0
2024-01-08 00:15:08,833 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704672908.0, "order_id": "0x981eef5312be54e87e24402a0222d43b", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "hyperliquid_perpetual"}
2024-01-08 00:15:08,837 - 1 - hummingbot.connector.client_order_tracker - INFO - Order 0x981eef5312be54e87e24402a0222d43b has failed. Order Update: OrderUpdate(trading_pair='SOL-USD', update_timestamp=1704672908.0, new_state=<OrderState.FAILED: 6>, client_order_id='0x981eef5312be54e87e24402a0222d43b', exchange_order_id=None, misc_updates=None)
```

![image](https://github.com/hummingbot/hummingbot/assets/73840223/06e03a6b-4b5e-4a27-980b-7e271d57fa7d)

We also noticed that this errors cause the connector not able to submit orders and statuses `rejected` on Hyperliquid exchange 
![image](https://github.com/hummingbot/hummingbot/assets/73840223/16f4b66d-0556-4afe-8ae0-ddc1a606dd8f)
- Checking the hyperliquid explorer, we are still not able to confirm what caused this status to be rejected. 
   ![image](https://github.com/hummingbot/hummingbot/assets/73840223/ba4ed661-de90-4c8a-baec-ecf6feb143f2)
   - Here is one sample of orders data on explorer which has been placed successfully https://app.hyperliquid.xyz/explorer/tx/0xc35566910373dd4e34c904070bcafe02016700df64d67a01c83037ee581598d9

### Steps to reproduce

1.  Setup hyperliquid connector using dmanv3 
2. Run for couple of days 
3. Observe connector behavior when placing order for closing position executor which is a market order type.

### Release version

dev-1.24.0

### Type of installation

Source

### Attach required files

[logs_v2_market-making_dman_v3_complex_config.log](https://github.com/hummingbot/hummingbot/files/13859070/logs_v2_market-making_dman_v3_complex_config.log)
[logs_v2_market-making_dman_v3_complex_config.log.2024-01-06.log](https://github.com/hummingbot/hummingbot/files/13859076/logs_v2_market-making_dman_v3_complex_config.log.2024-01-06.log)

**Comment by yancong001** [comment]
I removed the reduce only logic so we can test if the problem still exists. (https://github.com/hummingbot/hummingbot/pull/6790/files)

**Comment by rapcmia** [comment]
fixed

**Comment by rohithje09** [comment]
Not fixed am still getting the error
