### ISSUE TITLE
Hyperliquid - Unexpected error while processing event 201

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6765]
### Describe the bug

We setup long term bot for hyperliquid using v2 strategy with multiple pairs and observed this `IntegrityError` happened when an order has been created

```
2024-01-09 11:49:00,621 - 1 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order 0xa454109eacc221530a6aa63dad4eb002 for 0.18 to OPEN a SOL-USD position.
2024-01-09 11:49:00,622 - 1 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2024-01-09 11:49:00,634 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704800940.0, "type": "OrderType.LIMIT", "trading_pair": "SOL-USD", "amount": "0.18", "price": "106.4599999999999937472239253111183643341064453125", "order_id": "0xa454109eacc221530a6aa63dad4eb002", "creation_timestamp": 1704800939.0, "exchange_order_id": "None", "leverage": 20, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "hyperliquid_perpetual"}
2024-01-09 11:49:00,723 - 1 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order 0xa454109eacc221530a6aa63dad4eb002 for 0.18 to OPEN a SOL-USD position.
2024-01-09 11:49:00,724 - 1 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Open Order Created
2024-01-09 11:49:00,729 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - ERROR - Unexpected error while processing event 201.
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: Order.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
    typed_listener.c_call(arg)
  File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
    self(arg)
  File "/home/hummingbot/hummingbot/core/event/event_forwarder.py", line 24, in __call__
    self._to_function(self.current_event_tag, self.current_event_caller, arg)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 304, in _did_create_order
    self.save_market_states(self._config_file_path, market, session=session)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 237, in save_market_states
    market_states: Optional[MarketState] = self.get_market_states(config_file_path, market, session=session)
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 265, in get_market_states
    market_states: Optional[MarketState] = query.one_or_none()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1665, in execute
    ) = compile_state_cls.orm_pre_session_exec(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
    session._autoflush()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2264, in _autoflush
    util.raise_(e, with_traceback=sys.exc_info()[2])
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2253, in _autoflush
    self.flush()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
    with util.safe_reraise():
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(sqlite3.IntegrityError) UNIQUE constraint failed: Order.id
[SQL: INSERT INTO "Order" (id, config_file_path, strategy, market, symbol, base_asset, quote_asset, creation_timestamp, order_type, amount, leverage, price, last_status, last_update_timestamp, exchange_order_id, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('0xa454109eacc221530a6aa63dad4eb002', 'hyperliquid_a', 'hyperliquid_a', 'hyperliquid_perpetual', 'SOL-USD', 'SOL', 'USD', 1704800939000, 'LIMIT', 180000, 20, 106459999, 'SellOrderCreated', 1704800939000, 'None', 'OPEN')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
2024-01-09 11:49:00,767 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1704800940.0, "type": "OrderType.LIMIT", "trading_pair": "SOL-USD", "amount": "0.18", "price": "106.4599999999999937472239253111183643341064453125", "order_id": "0xa454109eacc221530a6aa63dad4eb002", "creation_timestamp": 1704800939.0, "exchange_order_id": "None", "leverage": 20, "position": "OPEN", "event_name": "SellOrderCreatedEvent", "event_source": "hyperliquid_perpetual"}
```
- Issue started at `2024-01-09 11:48:59,339`
- The following sell order ids has been spotted with no `exchange_id`
    - `0xc108956d4bcee55cfaadc54199488807`
    - `0xa98668b9f6ae05e549334462597e7a76`
    - `0xa454109eacc221530a6aa63dad4eb002`
    - All of these orders return the same error mentioned aboved
    - Another is it also returned an error `Error fetching status update for the active order`
      ```
      2024-01-09 11:49:12,004 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Error fetching status update for the active order 0xc108956d4bcee55cfaadc54199488807: invalid literal for int() with base 10: 'None'.
      2024-01-09 11:49:12,005 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Error fetching status update for the active order 0xa98668b9f6ae05e549334462597e7a76: invalid literal for int() with base 10: 'None'.
      2024-01-09 11:49:12,006 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Error fetching status update for the active order 0xa454109eacc221530a6aa63dad4eb002: invalid literal for int() with base 10: 'None'.
      ```
       - These orders ended up as lost orders, see sample log below:
          ```
          2024-01-09 11:49:48,194 - 1 - hummingbot.connector.client_order_tracker - WARNING - The order 0xc108956d4bcee55cfaadc54199488807(None) will be considered lost. Please check its status in the exchange.
          ```
        - There are instances of the connector getting `TypeError: 'NoneType' object is not iterable` when connector fetching trade updates on one of the sell orders
          ```
          2024-01-09 11:49:53,051 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Failed to fetch trade updates for order 0xa454109eacc221530a6aa63dad4eb002. Error: 'NoneType' object is not iterable
          Traceback (most recent call last):
            File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 955, in _update_orders_fills
              for trade_update in trade_updates:
          TypeError: 'NoneType' object is not iterable
          ```
- Around `2024-01-09 11:49:48,208` that the connector started placing sell orders again
    - These sell orders have been successfully submitted and cancelled at the set refresh time (30mins) same with the other active orders that was initially submitted with the orders reported above

### Steps to reproduce

1.  Setup `hyperliquid_perpetual` with v2 strategy
2. Setup the script to support multiple market pairs 
3. Run the script for couple of hours and observe behavior of the connector when order is created 

### Release version

dev-1.24.0

### Type of installation

Source

### Attach required files

[logs_hyperliquid_a.log](https://github.com/hummingbot/hummingbot/files/13886872/logs_hyperliquid_a.log)
https://gist.github.com/rapcmia/ce78f7dc1dd4b6f43dcec0a6adcabaea `script used`

**Comment by rapcmia** [comment]
Review bot runtime of 3d and 10hrs and found this behavior happened as well on perpetual market making strategy
- Review logs and found out this
- Stopped the bot tonight since connector seems to be stuck on this error `Error fetching status update for the active order 0xe0b8cfd581811013faf79da65fa050a4: invalid literal for int() with base 10: 'None'.`
- `Unexpected error while processing event 201` happened 
    ```
    2024-01-15 05:07:48,127 - 1 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order 0x45da72757a1ac4b58db2df8129fe5f25 for 0.20 to CLOSE a SOL-USD position.
    2024-01-15 05:07:48,140 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1705295268.0, "type": "OrderType.LIMIT", "trading_pair": "SOL-USD", "amount": "0.20", "price": "95.93500000000000227373675443232059478759765625", "order_id": "0x45da72757a1ac4b58db2df8129fe5f25", "creation_timestamp": 1705295267.0, "exchange_order_id": "None", "leverage": 20, "position": "CLOSE", "event_name": "BuyOrderCreatedEvent", "event_source": "hyperliquid_perpetual"}
    2024-01-15 05:07:48,272 - 1 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order 0x45da72757a1ac4b58db2df8129fe5f25 for 0.20 to CLOSE a SOL-USD position.
    2024-01-15 05:07:48,276 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - ERROR - Unexpected error while processing event 200.
    Traceback (most recent call last):
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
        self.dialect.do_execute(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
        cursor.execute(statement, parameters)
    sqlite3.IntegrityError: UNIQUE constraint failed: Order.id
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "hummingbot/core/pubsub.pyx", line 165, in hummingbot.core.pubsub.PubSub.c_trigger_event
        typed_listener.c_call(arg)
      File "hummingbot/core/event/event_listener.pyx", line 25, in hummingbot.core.event.event_listener.EventListener.c_call
        self(arg)
      File "/home/hummingbot/hummingbot/core/event/event_forwarder.py", line 24, in __call__
        self._to_function(self.current_event_tag, self.current_event_caller, arg)
      File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 304, in _did_create_order
        self.save_market_states(self._config_file_path, market, session=session)
      File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 237, in save_market_states
        market_states: Optional[MarketState] = self.get_market_states(config_file_path, market, session=session)
      File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 265, in get_market_states
        market_states: Optional[MarketState] = query.one_or_none()
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
        return self._iter().one_or_none()
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
        result = self.session.execute(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1665, in execute
        ) = compile_state_cls.orm_pre_session_exec(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 312, in orm_pre_session_exec
        session._autoflush()
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2264, in _autoflush
        util.raise_(e, with_traceback=sys.exc_info()[2])
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
        raise exception
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2253, in _autoflush
        self.flush()
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
        self._flush(objects)
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
        with util.safe_reraise():
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
        compat.raise_(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
        raise exception
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
        flush_context.execute()
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
        rec.execute(self)
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
        util.preloaded.orm_persistence.save_obj(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
        _emit_insert_statements(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
        c = connection._execute_20(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
        return meth(self, args_10style, kwargs_10style, execution_options)
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
        return connection._execute_clauseelement(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
        ret = self._execute_context(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
        self._handle_dbapi_exception(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
        util.raise_(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
        raise exception
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
        self.dialect.do_execute(
      File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
    (sqlite3.IntegrityError) UNIQUE constraint failed: Order.id
    [SQL: INSERT INTO "Order" (id, config_file_path, strategy, market, symbol, base_asset, quote_asset, creation_timestamp, order_type, amount, leverage, price, last_status, last_update_timestamp, exchange_order_id, position) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
    [parameters: ('0x45da72757a1ac4b58db2df8129fe5f25', 'perp-hyperliquid1.yml', 'perpetual_market_making', 'hyperliquid_perpetual', 'SOL-USD', 'SOL', 'USD', 1705295267000, 'LIMIT', 200000, 20, 95935000, 'BuyOrderCreated', 1705295267000, 'None', 'CLOSE')]
    (Background on this error at: https://sqlalche.me/e/14/gkpj)
    2024-01-15 05:07:48,278 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1705295268.0, "type": "OrderType.LIMIT", "trading_pair": "SOL-USD", "amount": "0.20", "price": "95.93500000000000227373675443232059478759765625", "order_id": "0x45da72757a1ac4b58db2df8129fe5f25", "creation_timestamp": 1705295267.0, "exchange_order_id": "None", "leverage": 20, "position": "CLOSE", "event_name": "BuyOrderCreatedEvent", "event_source": "hyperliquid_perpetual"}
    2024-01-15 05:08:00,110 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Error fetching status update for the active order 0x45da72757a1ac4b58db2df8129fe5f25: invalid literal for int() with base 10: 'None'.
    2024-01-15 05:08:12,090 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Error fetching status update for the active order 0x45da72757a1ac4b58db2df8129fe5f25: invalid literal for int() with base 10: 'None'.
    2024-01-15 05:08:24,112 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Error fetching status update for the active order 0x45da72757a1ac4b58db2df8129fe5f25: invalid literal for int() with base 10: 'None'.
    2024-01-15 05:08:36,138 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Error fetching status update for the active order 0x45da72757a1ac4b58db2df8129fe5f25: invalid literal for int() with base 10: 'None'.
    2024-01-15 05:08:36,138 - 1 - hummingbot.connector.client_order_tracker - WARNING - The order 0x45da72757a1ac4b58db2df8129fe5f25(None) will be considered lost. Please check its status in the exchange.
    2024-01-15 05:08:36,150 - 1 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1705295316.0, "order_id": "0x45da72757a1ac4b58db2df8129fe5f25", "order_type": "OrderType.LIMIT", "event_name": "MarketOrderFailureEvent", "event_source": "hyperliquid_perpetual"}
    2024-01-15 05:08:36,150 - 1 - hummingbot.connector.client_order_tracker - INFO - Order 0x45da72757a1ac4b58db2df8129fe5f25 has failed. Order Update: OrderUpdate(trading_pair='SOL-USD', update_timestamp=1705295316.0, new_state=<OrderState.FAILED: 6>, client_order_id='0x45da72757a1ac4b58db2df8129fe5f25', exchange_order_id=None, misc_updates=None)
    2024-01-15 05:08:37,001 - 1 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (SOL-USD) Creating 1 LIMIT bid orders at (Size, Price): ['0.2 SOL, 95.93500000000000227373675443 USD'] to CLOSE position.
    2024-01-15 05:08:37,206 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Failed to fetch trade updates for order 0x45da72757a1ac4b58db2df8129fe5f25. Error: 'NoneType' object is not iterable
    Traceback (most recent call last):
      File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 955, in _update_orders_fills
        for trade_update in trade_updates:
    TypeError: 'NoneType' object is not iterable
    2024-01-15 05:08:37,208 - 1 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Error fetching status update for the lost order 0x45da72757a1ac4b58db2df8129fe5f25: invalid literal for int() with base 10: 'None'.
    ```
    - Same scenario where the order submitted from the connector does not have `exchange_id `
    - The connector seems to recover from this error but this is issue happened all time 

Steps to reproduce:
- Setup hyperliquid_perpetual with multiple order levels on perpetual market making strategy 
- Run for couple of days and observe behavior 

[logs_perp-hyperliquid1.log.2024-01-12.log](https://github.com/hummingbot/hummingbot/files/13939764/logs_perp-hyperliquid1.log.2024-01-12.log) `start`
[logs_perp-hyperliquid1.log.2024-01-13.log](https://github.com/hummingbot/hummingbot/files/13939765/logs_perp-hyperliquid1.log.2024-01-13.log)
[logs_perp-hyperliquid1.log.2024-01-14.log](https://github.com/hummingbot/hummingbot/files/13939766/logs_perp-hyperliquid1.log.2024-01-14.log)
[logs_perp-hyperliquid1.log](https://github.com/hummingbot/hummingbot/files/13939762/logs_perp-hyperliquid1.log) `end`
[perp-hyperliquid1.yml.log](https://github.com/hummingbot/hummingbot/files/13939776/perp-hyperliquid1.yml.log) `remove .log`

**Comment by yancong001** [comment]
fixed here(https://github.com/hummingbot/hummingbot/pull/6789)

**Comment by rapcmia** [comment]
fixed
