### ISSUE TITLE
Hyperliquid - Failed to submit market order due to "Order has zero size."

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6799]
### Describe the bug

Ran tests on Hyperliquid connector for couple of days then review logs. Observed that there are instances of failed to submit market orders when connector is trying to place a close order using v2 strategy

```
2024-01-19 16:25:58,509 - 615066 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-19 16:25:59,702 - 615066 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Error submitting sell MARKET order to Hyperliquid_perpetual for 0.00 SOL-USD 84.8780000000000001136868377216160297393798828125.
Traceback (most recent call last):
  File "/home/test01/development/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/test01/development/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/test01/development/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 393, in _place_order
    raise IOError(f"Error submitting order {order_id}: {o_order_result['error']}")
OSError: Error submitting order 0xc88b1c9d64aa088b41388e2a24ad8d98: Order has zero size.
2024-01-19 16:25:59,714 - 615066 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - WARNING - Failed to submit SELL order to Hyperliquid_perpetual. Check API key and network connection.
2024-01-19 16:25:59,719 - 615066 - hummingbot.strategy.script_strategy_base - INFO - Creating SOL-USD sell order: price: NaN amount: 0.
2024-01-19 16:25:59,720 - 615066 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing close order --> Filled amount: 0 | TP Partial execution: 0
2024-01-19 16:25:59,720 - 615066 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1705681559.0, "order_id": "0xc88b1c9d64aa088b41388e2a24ad8d98", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "hyperliquid_perpetual"}
2024-01-19 16:25:59,720 - 615066 - hummingbot.connector.client_order_tracker - INFO - Order 0xc88b1c9d64aa088b41388e2a24ad8d98 has failed. Order Update: OrderUpdate(trading_pair='SOL-USD', update_timestamp=1705681559.0, new_state=<OrderState.FAILED: 6>, client_order_id='0xc88b1c9d64aa088b41388e2a24ad8d98', exchange_order_id=None, misc_updates=None)
```

### Steps to reproduce

1. Add hyperliquid_perpetual and use v2 strategy
2. On this issue, we are using this [script](https://gist.github.com/rapcmia/ce78f7dc1dd4b6f43dcec0a6adcabaea)
3. Run the bot and observe behavior when placing close orders 

### Release version

dev-1.24.0

### Type of installation

Source

### Attach required files

[logs_hyperliquid_a.log](https://github.com/hummingbot/hummingbot/files/14010527/logs_hyperliquid_a.log)
[logs_hyperliquid_a.log.2024-01-19.log](https://github.com/hummingbot/hummingbot/files/14010528/logs_hyperliquid_a.log.2024-01-19.log)
[logs_hyperliquid_a.log.2024-01-20.log](https://github.com/hummingbot/hummingbot/files/14010529/logs_hyperliquid_a.log.2024-01-20.log)

**Comment by yancong001** [comment]
I see that the strategy sends a market order with a price of NaN and a amount of 0, but the exchange's market order does not allow the amount to be 0.
I think it's normal

**Comment by rapcmia** [comment]
Added `max retries` on position executor for this type of behavior
