### ISSUE TITLE
Hyperliquid - Failed to submit order due to "Only post-only orders allowed immediately after a network upgrade"

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6800]
### Describe the bug

Run tests on the connector for couple of days then review logs, observed there was a server disconnection event which eventually reconnected however getting failed to submit order when placing open orders. Took 2-3mins before connector was able to successfully create orders 

Server disconnected
```
2024-01-19 23:02:15,690 - 615066 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_api_order_book_data_source.HyperliquidPerpetualAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/test01/development/hummingbot/core/data_type/order_book_tracker_data_source.py", line 78, in listen_for_subscriptions
    ws: WSAssistant = await self._connected_websocket_assistant()
  File "/home/test01/development/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_api_order_book_data_source.py", line 91, in _connected_websocket_assistant
    await ws.connect(ws_url=url, ping_timeout=CONSTANTS.HEARTBEAT_TIME_INTERVAL)
  File "/home/test01/development/hummingbot/core/web_assistant/ws_assistant.py", line 43, in connect
    await self._connection.connect(ws_url=ws_url, ws_headers=ws_headers, ping_timeout=ping_timeout, message_timeout=message_timeout)
  File "/home/test01/development/hummingbot/core/web_assistant/connections/ws_connection.py", line 35, in connect
    self._connection = await self._client_session.ws_connect(
  File "/home/test01/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 825, in _ws_connect
    resp = await self.request(
  File "/home/test01/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 601, in _request
    await resp.start(conn)
  File "/home/test01/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 965, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/test01/miniconda3/envs/hummingbot/lib/python3.10/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```
  - Reconnected at `2024-01-19 23:03:56,333`

Failed to place open order 
```
2024-01-19 23:04:31,628 - 615066 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2024-01-19 23:04:32,783 - 615066 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Error submitting buy LIMIT order to Hyperliquid_perpetual for 0.22 SOL-USD 89.1779999999999972715158946812152862548828125.
Traceback (most recent call last):
  File "/home/test01/development/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/test01/development/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/test01/development/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 393, in _place_order
    raise IOError(f"Error submitting order {order_id}: {o_order_result['error']}")
OSError: Error submitting order 0x4a9681af62b86ea2936595c9b930c5b6: Only post-only orders allowed immediately after a network upgrade
```
  - The error happened after we got reconnected from server disconnection 
  - This issue happened for 2-3mins then connector was able to create orders again 

### Steps to reproduce

1.  Add hyperliquid_perpetual 
2. Run either v1 or v2 strategy for couple of days 
3. Observe logs for possible server disconnection

### Release version

dev-1.24.0

### Type of installation

Source

### Attach required files

[logs_hyperliquid_a.log.2024-01-19.log](https://github.com/hummingbot/hummingbot/files/14010757/logs_hyperliquid_a.log.2024-01-19.log)

**Comment by yancong001** [comment]
I guess this is caused by the exchange upgrade server, after the upgrade is completed, only postonly orders are usually allowed to be sent, you can ask their official personnel if this is the case

**Comment by rapcmia** [comment]
We have been monitoring our hyperliquid bots for couple of days and not able to reproduce this error. Closing ticket
