### ISSUE TITLE
Bitfinex Order Book Tracker - Not Iterable / Not Subscriptable

### ISSUE THREAD

**Issue by 0xferit** [hummingbot/hummingbot#6834]
### Describe the bug

During the execution, CPU utilization maxed out, so I checked the logs and found a lot of these errors:

```
2024-02-04 23:00:00,051 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - ERROR - 'float' object is not subscriptable
2024-02-04 23:00:00,051 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - NETWORK - Unexpected error processing order book messages for PNK-USD.
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/bitfinex/bitfinex_order_book_tracker.py", line 185, in _track_single_book
--
2024-02-05 00:00:00,029 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - ERROR - 'float' object is not subscriptable
2024-02-05 00:00:00,029 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - NETWORK - Unexpected error processing order book messages for PNK-USD.
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/bitfinex/bitfinex_order_book_tracker.py", line 185, in _track_single_book
--
2024-02-05 01:00:00,187 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - ERROR - 'float' object is not subscriptable
2024-02-05 01:00:00,187 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - NETWORK - Unexpected error processing order book messages for PNK-USD.
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/bitfinex/bitfinex_order_book_tracker.py", line 185, in _track_single_book
--
2024-02-05 02:00:00,045 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - ERROR - 'int' object is not iterable
2024-02-05 02:00:00,045 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - NETWORK - Unexpected error processing order book messages for PNK-USD.
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/bitfinex/bitfinex_order_book_tracker.py", line 185, in _track_single_book
--
2024-02-05 03:00:00,057 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - ERROR - 'int' object is not iterable
2024-02-05 03:00:00,057 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - NETWORK - Unexpected error processing order book messages for PNK-USD.
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/bitfinex/bitfinex_order_book_tracker.py", line 185, in _track_single_book
--
2024-02-05 04:00:00,037 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - ERROR - 'int' object is not iterable
2024-02-05 04:00:00,037 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - NETWORK - Unexpected error processing order book messages for PNK-USD.
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/bitfinex/bitfinex_order_book_tracker.py", line 185, in _track_single_book
--
2024-02-05 05:00:00,052 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - ERROR - 'float' object is not subscriptable
2024-02-05 05:00:00,052 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - NETWORK - Unexpected error processing order book messages for PNK-USD.
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/bitfinex/bitfinex_order_book_tracker.py", line 185, in _track_single_book
--
2024-02-05 06:00:00,041 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - ERROR - 'float' object is not subscriptable
2024-02-05 06:00:00,042 - 17241 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - NETWORK - Unexpected error processing order book messages for PNK-USD.
Traceback (most recent call last):
  File "/root/hummingbot/hummingbot/connector/exchange/bitfinex/bitfinex_order_book_tracker.py", line 185, in _track_single_book
--
```

### Steps to reproduce

1. Run on Bitfinex with PMM strategy
2. Wait for several hours
3. Observe logs

### Release version

1.24.0

### Type of installation

Source

### Attach required files

[logs_conf_2024.log](https://github.com/hummingbot/hummingbot/files/14165603/logs_conf_2024.log)
[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/14165605/logs_hummingbot.log)
<img width="1130" alt="Screenshot 2024-02-05 at 12 25 21" src="https://github.com/hummingbot/hummingbot/assets/3106907/d728aa5d-767b-43a9-aca2-e1086361e5bf">

**Comment by posix4e** [comment]
Why is this code commented out https://github.com/hummingbot/hummingbot/blob/cdfc1f8b9a8e8ef1feb52567ba9c1b38bd588e7a/hummingbot/connector/exchange/bitfinex/bitfinex_order_book_tracker.py#L212

**Comment by posix4e** [comment]
I got a different error, when you see *** that's me ommiting some private data
```
2024-02-09 09:43:53,037 - 25203 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2024-02-09 09:43:53,041 - 25203 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-02-09 09:43:53,513 - 25203 - hummingbot.connector.exchange.bitfinex.bitfinex_exchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting netw
orking...
2024-02-09 09:43:53,516 - 25203 - hummingbot.connector.exchange.bitfinex.bitfinex_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order
 book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "***/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 78, in listen_for_subscriptions
    ws: WSAssistant = await self._connected_websocket_assistant()
  File "***/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 200, in _connected_websocket_assistant
    raise NotImplementedError
NotImplementedError
2024-02-09 09:43:54,017 - 25203 - hummingbot.connector.exchange.bitfinex.bitfinex_order_book_tracker - INFO - Initialized order book for HMT-USD. 1/1 completed.
2024-02-09 09:43:54,526 - 25203 - hummingbot.connector.exchange.bitfinex.bitfinex_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order
 book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "***/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 78, in listen_for_subscriptions
    ws: WSAssistant = await self._connected_websocket_assistant()
  File "***/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 200, in _connected_websocket_assistant
    raise NotImplementedError
NotImplementedError
2024-02-09 09:43:55,527 - 25203 - hummingbot.connector.exchange.bitfinex.bitfinex_api_order_book_data_source - ERROR - Unexpected error occurred when listening to order
 book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File ***/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 78, in listen_for_subscriptions
    ws: WSAssistant = await self._connected_websocket_assistant()
  File "***/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 200, in _connected_websocket_assistant
    raise NotImplementedError
NotImplementedError
2024-02-09 09:43:56,007 - 25203 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (***) Creating 49 bid orders at (Size, Price): ['***']
2024-02-09 09:43:56,009 - 25203 - hummingbot.strategy.pure_market_making.pure_market_making - INFO - (***) Creating 49 ask orders at (Size, Price): ['***']
2024-02-09 09:43:56,512 - 25203 - hummingbot.connector.exchange.bitfinex.bitfinex_websocket - ERROR - _listen error Couldn't place order buy-***
Traceback (most recent call last):
  File "***/hummingbot/hummingbot/connector/exchange/bitfinex/bitfinex_websocket.py", line 122, in messages
    raise e
  File "***/hummingbot/hummingbot/connector/exchange/bitfinex/bitfinex_websocket.py", line 119, in messages

```

**Comment by 0xferit** [comment]
After dealing with 100% CPU utilization for almost a year, I noticed the issue might be related to error messages. Although I'm not sure yet, eliminating error messages tends to fix the problem. I will investigate logging logic myself, and I'm sharing this insight publicly hoping it may help you find the root cause.

Also see: https://github.com/hummingbot/hummingbot/pull/6738#issuecomment-1937062129

**Comment by nikspz** [comment]
Closing since this connector version removed in 2.3.0 release
