### ISSUE TITLE
Vega perpetual - Unstable node resulting to failed to submit orders 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6835]
### Describe the bug

When starting vega connector with perpetual market making strategy or v2 strategy, observed that the connector starts creating orders but failed due to error below:

```
2024-02-06 12:24:55,388 - 15 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-02-06 12:24:56,000 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:24:57,000 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:24:57,845 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-06 12:24:58,001 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:24:59,001 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:25:00,001 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:25:01,004 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:25:02,004 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:25:03,058 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:25:04,000 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:25:04,111 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - INFO - Connected to Vega Protocol endpoint: https://vega-data.bharvest.io/
2024-02-06 12:25:04,594 - 15 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for BTCUSDPERP-USDT. 1/2 completed.
2024-02-06 12:25:05,001 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:25:05,699 - 15 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for ETHUSDPERP-USDT. 2/2 completed.
2024-02-06 12:25:06,003 - 15 - hummingbot.strategy.script_strategy_base - WARNING - vega_perpetual is not ready. Please wait...
2024-02-06 12:25:08,001 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - ERROR - Position mode PositionMode.HEDGE is not supported. Mode not set.
2024-02-06 12:25:08,002 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - ERROR - Position mode PositionMode.HEDGE is not supported. Mode not set.
2024-02-06 12:25:08,121 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - WARNING - Exceeded max leverage allowed. Leverage for ETHUSDPERP-USDT has been reduced to 41
2024-02-06 12:25:08,122 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - WARNING - Exceeded max leverage allowed. Leverage for BTCUSDPERP-USDT has been reduced to 64
2024-02-06 12:25:08,237 - 15 - hummingbot.data_feed.candles_feed.binance_perpetual_candles.binance_perpetual_candles - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-06 12:25:08,398 - 15 - hummingbot.data_feed.candles_feed.binance_perpetual_candles.binance_perpetual_candles - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-06 12:25:08,814 - 15 - hummingbot.data_feed.candles_feed.binance_perpetual_candles.binance_perpetual_candles - INFO - Subscribed to public klines...
2024-02-06 12:25:09,253 - 15 - hummingbot.data_feed.candles_feed.binance_perpetual_candles.binance_perpetual_candles - INFO - Subscribed to public klines...
2024-02-06 12:25:09,256 - 15 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-06 12:25:10,429 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT buy order: price: 2310.204460538656803494289973 amount: 0.008657242396344744951150208016.
2024-02-06 12:25:10,430 - 15 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2024-02-06 12:25:10,430 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT buy order: price: 2303.162386861850973162964405 amount: 0.008683712496386667689492978472.
2024-02-06 12:25:10,430 - 15 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2024-02-06 12:25:10,431 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating ETHUSDPERP-USDT buy order: price: 2296.120313185045142831638837 amount: 0.008710344961086624458847718904.
2024-02-06 12:25:10,431 - 15 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2024-02-06 12:25:10,431 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating BTCUSDPERP-USDT sell order: price: 42997.98112867220701021638017 amount: 0.0004651381175350919814626246511.
2024-02-06 12:25:10,432 - 15 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2024-02-06 12:25:10,432 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating BTCUSDPERP-USDT sell order: price: 43159.04550587553389957956312 amount: 0.0004634022779136128996869538633.
2024-02-06 12:25:10,432 - 15 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2024-02-06 12:25:10,433 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating BTCUSDPERP-USDT sell order: price: 43320.10988307886078894274607 amount: 0.0004616793460122810188148594192.
2024-02-06 12:25:10,433 - 15 - hummingbot.smart_components.executors.position_executor.position_executor - INFO - Placing open order
2024-02-06 12:25:12,358 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - NETWORK - Error submitting buy LIMIT order to Vega_perpetual for 0.008 ETHUSDPERP-USDT 2310.20.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/hummingbot/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 456, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/hummingbot/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 543, in _place_order
    transaction = await self._auth.sign_payload(order_payload, "order_submission")
  File "/home/hummingbot/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_auth.py", line 78, in sign_payload
    self._client: Client = Client(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/vega/client.py", line 54, in __init__
    self._starting_block_height = self._core_data_client.LastBlockHeight(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/grpc/_channel.py", line 1160, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:3002: connect: connection refused""
	debug_error_string = "UNKNOWN:Error received from peer ipv4:54.180.211.130:3007 {created_time:"2024-02-06T12:25:12.356527762+00:00", grpc_status:14, grpc_message:"connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:3002: connect: connection refused\""}"
>
2024-02-06 12:25:12,360 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - WARNING - Failed to submit BUY order to Vega_perpetual. Check API key and network connection.
```
- Tried to stop, exit then relaunch client again to check if it will work but no go
- On the event of the issue, its not connecting to other nodes but only `https://vega-data.bharvest.io/`
- Checked the vega node status:
   ![image](https://github.com/hummingbot/hummingbot/assets/73840223/f1d353bc-472d-41fd-9a36-b30e8efefffa)
   - For perpetual market making strategy, same behavior but trying to connect to https://darling.network/ with timeout error:
      ```
      2024-02-06 12:31:47,819 - 15 - hummingbot.client.hummingbot_application - INFO - start command initiated.
      2024-02-06 12:31:50,569 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - WARNING - Exceeded max leverage allowed. Leverage for ETHUSDPERP-USDT has been reduced to 41
      2024-02-06 12:31:51,098 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
      2024-02-06 12:31:57,003 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - INFO - Connected to Vega Protocol endpoint: https://darling.network/
      2024-02-06 12:32:07,004 - 15 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - Changing position mode to ONEWAY succeeded.
      2024-02-06 12:32:07,235 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - WARNING - Exceeded max leverage allowed. Leverage for ETHUSDPERP-USDT has been reduced to 41
      2024-02-06 12:32:08,002 - 15 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETHUSDPERP-USDT) Creating 1 LIMIT bid orders at (Size, Price): ['1 ETHUSDPERP, 2304.8 USDT'] to OPEN position.
      2024-02-06 12:32:08,003 - 15 - hummingbot.strategy.perpetual_market_making.perpetual_market_making - INFO - (ETHUSDPERP-USDT) Creating 1  LIMIT ask orders at (Size, Price): ['1 ETHUSDPERP, 2351.36 USDT'] to OPEN position.
      2024-02-06 12:32:39,744 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - NETWORK - Error submitting buy LIMIT order to Vega_perpetual for 1.000 ETHUSDPERP-USDT 2304.80.
      Traceback (most recent call last):
        File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
          await self._place_order_and_process_update(order=order, **kwargs,)
        File "/home/hummingbot/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 456, in _place_order_and_process_update
          exchange_order_id, update_timestamp = await self._place_order(
        File "/home/hummingbot/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 543, in _place_order
          transaction = await self._auth.sign_payload(order_payload, "order_submission")
        File "/home/hummingbot/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_auth.py", line 78, in sign_payload
          self._client: Client = Client(
        File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/vega/client.py", line 47, in __init__
          channel=self._new_channel(),
        File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/vega/client.py", line 70, in _new_channel
          grpc.channel_ready_future(channel).result(timeout=30)
        File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/grpc/_utilities.py", line 162, in result
          self._block(timeout)
        File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/grpc/_utilities.py", line 106, in _block
          raise grpc.FutureTimeoutError()
      grpc.FutureTimeoutError
      2024-02-06 12:32:39,753 - 15 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - WARNING - Failed to submit BUY order to Vega_perpetual. Check API key and network connection.
      ```
       
Note: In the past, connector would be able to reconnect to other available endpoints but atm it is not

### Steps to reproduce

1. Add vega_perpetual 
2. Setup simple perpetual market making strategy or dmanv3 
3. Start and observe connector behavior 

### Release version

dev-1.25.0

### Type of installation

Source

### Attach required files

[logs_perp-vega1.log](https://github.com/hummingbot/hummingbot/files/14179700/logs_perp-vega1.log)
[logs_vega_dmanv3.log](https://github.com/hummingbot/hummingbot/files/14179701/logs_vega_dmanv3.log)

**Comment by rapcmia** [comment]
- The nodes available are for the community to use therefore due to the load it is delayed, disconnect or fails tvega
- It is recommended to [setup a private node](https://docs.vega.xyz/mainnet/node-operators) when market making on Vega Protocol
