### ISSUE TITLE
Unhandled error in background task: Odd-length string

### ISSUE THREAD

**Issue by 0xferit** [hummingbot/hummingbot#6836]
### Describe the bug

After running Hummingbot, as the first message on the log pane, I see the following error.

`async_utils - Unhandled error in background task: Odd-length string (See log file for stack trace dump)`

### Steps to reproduce

1. Build from source
2. ./start
3. Observe log pane

### Release version

1.24.0

### Type of installation

Source

### Attach required files

[logs_hummingbot.log](https://github.com/hummingbot/hummingbot/files/14181460/logs_hummingbot.log)

**Comment by AlexeyBoiler** [comment]
Did you manage to solve the problem?

**Comment by 0xferit** [comment]
No, I couldn't.

**Comment by flingjie** [comment]
from the log, it is an error reported when parsing the yml configuration file. It may be a configuration problem.

**Comment by rapcmia** [comment]
Reproduced when running docker
![image](https://github.com/hummingbot/hummingbot/assets/73840223/61e853cd-c5f1-4628-adc6-e74e1b400be1)

```
2024-05-24 06:53:02,742 - 14 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Odd-length string
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 127, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 116, in schedule_async_call
    return await fut
  File "/home/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/opt/conda/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hummingbot/hummingbot/client/config/security.py", line 65, in decrypt_all
    cls.decrypt_connector_config(file)
  File "/home/hummingbot/hummingbot/client/config/security.py", line 71, in decrypt_connector_config
    cls._secure_configs[connector_name] = load_connector_config_map_from_file(file_path)
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 668, in load_connector_config_map_from_file
    _load_yml_data_into_map(config_data, config_map)
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 750, in _load_yml_data_into_map
    config_validation_errors = cm.validate_model()  # try coercing values to appropriate type
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 199, in validate_model
    self.decrypt_all_secure_data()
  File "/home/hummingbot/hummingbot/client/config/config_helpers.py", line 237, in decrypt_all_secure_data
    decrypted_value = Security.secrets_manager.decrypt_secret_value(attr=traversal_item.attr, value=value)
  File "/home/hummingbot/hummingbot/client/config/config_crypt.py", line 59, in decrypt_secret_value
    value = binascii.unhexlify(value)
binascii.Error: Odd-length string
```

compose file used:
```
version: "3.9"
services:
  hummingbot:
    container_name: hummingbot
    # image: hummingbot/hummingbot:latest
    build: # Uncomment this and comment image if you want to build it locally
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./conf/controllers:/home/hummingbot/conf/controllers
      - ./conf/scripts:/home/hummingbot/conf/scripts
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./certs:/home/hummingbot/certs
      - ./scripts:/home/hummingbot/scripts
      - ./controllers:/home/hummingbot/controllers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
    #  environment:
    #    - CONFIG_PASSWORD=a
```

---

Steps to reproduce:
1. Clone hummingbot source (development or latest)
2. Modify the docker compose file to build local image
3. Run `docker compose up -d` then `docker attach hummingbot`

**Comment by cjelsa** [comment]
Same issue here

Installed from source on Ubuntu 22.04.4 LTS

10889 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: Odd-length string
Traceback (most recent call last):
  File "/home/cjelsa/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/cjelsa/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 127, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/home/cjelsa/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 116, in schedule_async_call
    return await fut
  File "/home/cjelsa/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/home/cjelsa/miniconda3/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cjelsa/hummingbot/hummingbot/client/config/security.py", line 65, in decrypt_all
    cls.decrypt_connector_config(file)
  File "/home/cjelsa/hummingbot/hummingbot/client/config/security.py", line 71, in decrypt_connector_config
    cls._secure_configs[connector_name] = load_connector_config_map_from_file(file_path)
  File "/home/cjelsa/hummingbot/hummingbot/client/config/config_helpers.py", line 668, in load_connector_config_map_from_file
    _load_yml_data_into_map(config_data, config_map)
  File "/home/cjelsa/hummingbot/hummingbot/client/config/config_helpers.py", line 750, in _load_yml_data_into_map
    config_validation_errors = cm.validate_model()  # try coercing values to appropriate type
  File "/home/cjelsa/hummingbot/hummingbot/client/config/config_helpers.py", line 199, in validate_model
    self.decrypt_all_secure_data()
  File "/home/cjelsa/hummingbot/hummingbot/client/config/config_helpers.py", line 237, in decrypt_all_secure_data
    decrypted_value = Security.secrets_manager.decrypt_secret_value(attr=traversal_item.attr, value=value)
  File "/home/cjelsa/hummingbot/hummingbot/client/config/config_crypt.py", line 59, in decrypt_secret_value
    value = binascii.unhexlify(value)
binascii.Error: Odd-length string

**Comment by IvanLetteri** [comment]
In my case, Odd-length issue happens only when I use ./start , not when I start the bot using ./bin/hummingbot.py

**Comment by rapcmia** [comment]
Related to https://github.com/hummingbot/hummingbot/issues/6671
For workaround on source build, use `bin/hummingbot.py`
