### ISSUE TITLE
Hyperliquid - Error submitting LIMIT orders on ETH-USD pair

### ISSUE THREAD

**Issue by mlguys** [hummingbot/hummingbot#6838]
### Describe the bug

User `yny` reported on HB Discord that he got errors when submitting LIMIT orders. The user was trying to run `perpetual_market_making` strategy on ETH-USD on Hyper Liquid.

Error massage for the bug:

```
2024-02-06 09:53:41,980 - 15 - hummingbot.connector.derivative.hyperliquid_perpetual.hyperliquid_perpetual_derivative.HyperliquidPerpetualDerivative - NETWORK - Error submitting buy LIMIT order to Hyperliquid_perpetual for 0.0050 ETH-USD 2332.09999999999990905052982270717620849609375.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/hummingbot/hummingbot/connector/derivative/hyperliquid_perpetual/hyperliquid_perpetual_derivative.py", line 391, in _place_order
    o_order_result = order_result['response']["data"]["statuses"][0]
TypeError: string indices must be integers
```

Link to user's bug: https://discord.com/channels/530578568154054663/1204364757805563925

### Steps to reproduce

1. Add hyperliquid_perpetual and use `perpetual_market_making` strategy
2. Run strategy on ETH-USD pair and set leverage to 3
3. Observe behavior when placing limit orders

### Release version

N/A

### Type of installation

Docker

### Attach required files

[Hummingbot Feb 6.txt](https://github.com/hummingbot/hummingbot/files/14183787/Hummingbot.Feb.6.txt)

**Comment by nikspz** [comment]
Works on source, will check docker now

![image](https://github.com/hummingbot/hummingbot/assets/83953535/27021a46-5566-4879-b0b1-c4a6ed108b83)

**Comment by nikspz** [comment]
Docker on latest development branch
![image](https://github.com/hummingbot/hummingbot/assets/83953535/ef24709b-a99f-47d1-aa77-66c5a991ffbf)
