### ISSUE TITLE
Vega perpetual - No symbols found for exchange 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6865]
### Describe the bug

Ticket created for monitoring purpose.

Vega Protocol currently suspended all markets making the connector not available until further notice. 

![image](https://github.com/hummingbot/hummingbot/assets/73840223/86d294b2-49ab-471b-bed7-778a962c2371)

![image](https://github.com/hummingbot/hummingbot/assets/73840223/d6b23858-181d-4522-9ec8-150b6ab0d4c6)

```
2024-02-22 10:39:27,217 - 6086 - hummingbot.connector.derivative.vega_perpetual.vega_perpetual_derivative.VegaPerpetualDerivative - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange_py_base.py", line 1073, in _initialize_trading_pair_symbol_map
    self._initialize_trading_pair_symbols_from_exchange_info(exchange_info=exchange_info)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/derivative/vega_perpetual/vega_perpetual_derivative.py", line 1005, in _initialize_trading_pair_symbols_from_exchange_info
    raise ValueError("No symbols found for exchange.")
ValueError: No symbols found for exchange.
```

### Steps to reproduce

1.  `connect vega_perpetual`
2.  Setup simple perp market making and select market
3. Observe no market available

### Release version

master and development 1.25.0

### Type of installation

Source

**Comment by rapcmia** [comment]
Markets no available for trade
