### ISSUE TITLE
Kucoin - with order_refresh_time (15mins or more) got OSError executing request, error code 400002 Invalid KC-API-TIMESTAMP

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6866]
### Describe the bug

When running test on kucoin spot, we observed instances of these errors while the connector was fetching trade updates, balances or trying to cancel an active order

Failed to fetch trade updates:
```
2024-02-22 14:59:16,360 - 71791 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - WARNING - Failed to fetch trade updates. Error: Error executing request GET https://api.kucoin.com/api/v1/fills. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}
```

Failed to cancel order: 
```
2024-02-22 15:17:04,438 - 71791 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - ERROR - Failed to cancel order BSLUT611f300c7f139e43fde9f696090a26c784d
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange_py_base.py", line 520, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange_py_base.py", line 540, in _execute_order_cancel_and_process_update
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 226, in _place_cancel
    cancel_result = await self._api_delete(
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange_py_base.py", line 875, in _api_delete
    return await self._api_request(*args, **kwargs)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange_py_base.py", line 905, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/web_assistant/rest_assistant.py", line 99, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request DELETE https://api.kucoin.com/api/v1/orders/65d6f1206100db0007218806. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}
```

Failed to update balance:
```
2024-02-22 17:09:16,591 - 71791 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - WARNING - Failed to update balances. Error: Error executing request GET https://api.kucoin.com/api/v1/accounts. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange_py_base.py", line 938, in _update_all_balances
    await self._update_balances()
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 320, in _update_balances
    response = await self._api_get(
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/connector/exchange_py_base.py", line 905, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/core/web_assistant/rest_assistant.py", line 99, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.kucoin.com/api/v1/accounts. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}
```
  - On the attached log file:
    - 2024-02-22 17:57:19,179 - Failed to cancel error occurred 
    - 2024-02-22 18:02:24,273 - Connector fixed itself and orders canceled successfully
    - Took 5mins to cancel orders ok and seen happened again on later timeframes 
    - This is also observed when stop command is initiated causing orders to be stuck on exchange.
      - Tried to run again stop command so it can try to recheck active orders but still same error

### Steps to reproduce

1. Add Kucoin spot API keys 
2. Setup a v1(Pure Market Making) or v2 strategy script with long refresh time (15mins or more)
3. Start and observe after couple of hours 

### Release version

dev-1.25.0

### Type of installation

Source

### Attach required files

[logs_pmm-kucoin1.log](https://github.com/hummingbot/hummingbot/files/14373669/logs_pmm-kucoin1.log)

**Comment by rapcmia** [comment]
Not able to reproduce after testing 3/3 local and cloud

**Comment by rapcmia** [comment]
After reviewing logs of bot running on kucoin via hbot-deploy, found this issue occurred on most of the instances with more than 10mins refresh time. Test has been done on both local and cloud

Unexpected error while listening to user stream. Retrying after 5 seconds...
```
2024-06-20 23:03:07,725 - 14 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for XCAD-USDT. 1/1 completed.
2024-06-20 23:03:07,858 - 14 - hummingbot.connector.exchange.kucoin.kucoin_api_user_stream_data_source.KucoinAPIUserStreamDataSource - ERROR - Unexpected error while listening to user stream. Retrying after 5 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/user_stream_tracker_data_source.py", line 45, in listen_for_user_stream
    self._ws_assistant = await self._connected_websocket_assistant()
  File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_api_user_stream_data_source.py", line 34, in _connected_websocket_assistant
    connection_info = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request POST https://api.kucoin.com/api/v1/bullet-private. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}
```

Failed to fetch updates
```
2024-06-20 22:59:19,860 - 14 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - WARNING - Failed to fetch trade updates. Error: Error executing request GET https://api.kucoin.com/api/v1/fills. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}
```

Failed to fetch balances
```
2024-06-20 23:04:13,722 - 14 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - WARNING - Failed to update balances. Error: Error executing request GET https://api.kucoin.com/api/v1/accounts. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 940, in _update_all_balances
    await self._update_balances()
  File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 326, in _update_balances
    response = await self._api_get(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.kucoin.com/api/v1/accounts. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}
```

Unexpected error while fetching trading fees.
```
2024-06-20 23:05:50,691 - 14 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - NETWORK - Unexpected error while fetching trading fees.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 752, in _trading_fees_polling_loop
    await safe_gather(self._update_trading_fees())
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 370, in _update_trading_fees
    resp = await self._api_get(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.kucoin.com/api/v1/trade-fees. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}
```

**Comment by Jbekker** [comment]
This should be fixed with #7103, can we close this issue?
