### ISSUE TITLE
MEXC 700013 Invalid content Type.

### ISSUE THREAD

**Issue by ivants-xchange-bg** [hummingbot/hummingbot#6875]
### Describe the bug

Cannot connect with MEXC. Maybe its related to:
https://github.com/ccxt/ccxt/issues/21345

### Steps to reproduce

1. Install Docker version
2. Setup MEXC connection
3. 

### Release version

latest

### Type of installation

Docker

### Attach required files

2024-02-26 13:04:55,288 - 14 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2024-02-26 13:04:55,299 - 14 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-02-26 13:04:56,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:04:56,001 - 14 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-02-26 13:04:56,423 - 14 - hummingbot.connector.exchange.mexc.mexc_api_user_stream_data_source.MexcAPIUserStreamDataSource - INFO - Successfully obtained listen key aaa95757bda8d253ec187e4d5a0c39722ab426d1a8b17172db31ccc5f4d32c98
2024-02-26 13:04:56,923 - 14 - hummingbot.connector.exchange.mexc.mexc_api_order_book_data_source.MexcAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2024-02-26 13:04:56,977 - 14 - hummingbot.connector.exchange.mexc.mexc_api_user_stream_data_source.MexcAPIUserStreamDataSource - INFO - Subscribed to private order changes and balance updates channels...
2024-02-26 13:04:57,034 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:04:57,613 - 14 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - NETWORK - Error fetching trades update for the order CHANGE-USDT: Error executing request GET https://api.mexc.com/api/v3/myTrades. HTTP status is 400. Error: {"code":700013,"msg":"Invalid content Type."}.
2024-02-26 13:04:57,613 - 14 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - WARNING - Failed to fetch trade update for CHANGE-USDT.
2024-02-26 13:04:57,873 - 14 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - WARNING - Failed to update balances. Error: Error executing request GET https://api.mexc.com/api/v3/account. HTTP status is 400. Error: {"code":700013,"msg":"Invalid content Type."}
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 938, in _update_all_balances
    await self._update_balances()
  File "/home/hummingbot/hummingbot/connector/exchange/mexc/mexc_exchange.py", line 526, in _update_balances
    account_info = await self._api_get(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 905, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 99, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.mexc.com/api/v3/account. HTTP status is 400. Error: {"code":700013,"msg":"Invalid content Type."}
2024-02-26 13:04:58,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:04:59,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:00,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:01,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:02,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:03,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:04,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:05,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:06,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:07,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:08,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:09,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:10,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:11,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:12,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:13,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:14,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:15,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:16,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:17,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:18,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:19,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:20,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:21,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:22,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:23,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:24,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:25,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:26,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:27,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:28,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:29,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:30,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:31,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:32,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:33,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:34,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:35,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:36,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:37,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:38,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:39,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:40,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:41,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:42,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:43,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:44,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:45,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:46,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:47,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:48,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:49,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:50,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:51,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:52,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:53,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:54,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:55,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:56,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:57,002 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:58,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:05:59,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:00,002 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:00,646 - 14 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - NETWORK - Error fetching trades update for the order CHANGE-USDT: Error executing request GET https://api.mexc.com/api/v3/myTrades. HTTP status is 400. Error: {"code":700013,"msg":"Invalid content Type."}.
2024-02-26 13:06:00,647 - 14 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - WARNING - Failed to fetch trade update for CHANGE-USDT.
2024-02-26 13:06:00,895 - 14 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - WARNING - Failed to update balances. Error: Error executing request GET https://api.mexc.com/api/v3/account. HTTP status is 400. Error: {"code":700013,"msg":"Invalid content Type."}
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 938, in _update_all_balances
    await self._update_balances()
  File "/home/hummingbot/hummingbot/connector/exchange/mexc/mexc_exchange.py", line 526, in _update_balances
    account_info = await self._api_get(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 905, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 99, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.mexc.com/api/v3/account. HTTP status is 400. Error: {"code":700013,"msg":"Invalid content Type."}
2024-02-26 13:06:01,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:02,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:03,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:04,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:05,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:06,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:07,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:08,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:09,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:10,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:11,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:12,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:13,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:14,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:15,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:16,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:17,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:18,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:19,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:20,002 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:21,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:22,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:23,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:24,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:25,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:26,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:27,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:28,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:29,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:30,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:31,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:32,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:33,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:34,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:35,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:36,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:37,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:38,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:39,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:40,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:41,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:42,052 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:43,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:44,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:45,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:46,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:47,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:48,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:49,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:50,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:51,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:52,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:53,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:54,070 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:55,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:56,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:57,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:58,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:06:59,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:00,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:01,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:02,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:03,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:04,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:05,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:06,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:07,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:08,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:09,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:10,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:11,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:12,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:13,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:14,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:15,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:16,007 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:17,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:18,002 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:19,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:20,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:21,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:22,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:23,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:24,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:25,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:26,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:27,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:28,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:29,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:30,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:31,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:32,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:33,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:34,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:35,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:36,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:37,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:38,074 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:39,010 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:40,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:41,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:42,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:43,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:44,000 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:45,003 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:46,015 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:47,001 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:48,005 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:49,007 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:50,007 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:51,004 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:52,008 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:53,014 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:54,179 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:55,010 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:56,013 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:57,012 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:58,018 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:07:59,015 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:08:00,032 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:08:00,626 - 14 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - NETWORK - Error fetching trades update for the order CHANGE-USDT: Error executing request GET https://api.mexc.com/api/v3/myTrades. HTTP status is 400. Error: {"code":700013,"msg":"Invalid content Type."}.
2024-02-26 13:08:00,627 - 14 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - WARNING - Failed to fetch trade update for CHANGE-USDT.
2024-02-26 13:08:00,898 - 14 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - WARNING - Failed to update balances. Error: Error executing request GET https://api.mexc.com/api/v3/account. HTTP status is 400. Error: {"code":700013,"msg":"Invalid content Type."}
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 938, in _update_all_balances
    await self._update_balances()
  File "/home/hummingbot/hummingbot/connector/exchange/mexc/mexc_exchange.py", line 526, in _update_balances
    account_info = await self._api_get(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 905, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 99, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.mexc.com/api/v3/account. HTTP status is 400. Error: {"code":700013,"msg":"Invalid content Type."}
2024-02-26 13:08:01,017 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:08:02,025 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...
2024-02-26 13:08:03,044 - 14 - hummingbot.strategy.script_strategy_base - WARNING - mexc is not ready. Please wait...

**Comment by nikspz** [comment]
@ivants-xchange-bg #6867 Related 

Fix pushed to development branch, will be available in upcoming 1.25.0 release

**Comment by ivants-xchange-bg** [comment]
> Fix pushed to development branch, will be available in upcoming 1.25.0 release

Many thanks!
Is this includes a new docker image release and is there a due time?

**Comment by nikspz** [comment]
available under development tag here https://hub.docker.com/r/hummingbot/hummingbot/tags
