### ISSUE TITLE
v2 strategy controller - getting an decimal.DivisionByZero

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6922]
### Describe the bug

When setting up the controller `market_making.pmm_simple` on either spot and perpetual connectors, I am getting the `decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]`

```
2024-03-20 12:33:58,737 - 39241 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-03-20 12:33:59,000 - 39241 - hummingbot.strategy.script_strategy_base - WARNING - kucoin is not ready. Please wait...
2024-03-20 12:34:00,011 - 39241 - hummingbot.strategy.script_strategy_base - WARNING - kucoin is not ready. Please wait...
2024-03-20 12:34:00,196 - 39241 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-03-20 12:34:01,001 - 39241 - hummingbot.strategy.script_strategy_base - WARNING - kucoin is not ready. Please wait...
2024-03-20 12:34:01,270 - 39241 - hummingbot.connector.exchange.kucoin.kucoin_api_user_stream_data_source.KucoinAPIUserStreamDataSource - INFO - Subscribed to private order changes and balance updates channels...
2024-03-20 12:34:01,658 - 39241 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for LOOM-USDT. 1/1 completed.
2024-03-20 12:34:02,001 - 39241 - hummingbot.strategy.script_strategy_base - WARNING - kucoin is not ready. Please wait...
2024-03-20 12:34:02,143 - 39241 - hummingbot.connector.exchange.kucoin.kucoin_api_order_book_data_source.KucoinAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2024-03-20 12:34:04,814 - 39241 - hummingbot.smart_components.smart_component_base - ERROR - [<class 'decimal.DivisionByZero'>]
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/smart_components/smart_component_base.py", line 69, in control_loop
    await self.control_task()
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/smart_components/controllers/controller_base.py", line 153, in control_task
    executor_actions: List[ExecutorAction] = self.determine_executor_actions()
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/smart_components/controllers/market_making_controller_base.py", line 232, in determine_executor_actions
    actions.extend(self.create_actions_proposal())
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/smart_components/controllers/market_making_controller_base.py", line 243, in create_actions_proposal
    price, amount = self.get_price_and_amount(level_id)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/smart_components/controllers/market_making_controller_base.py", line 310, in get_price_and_amount
    return order_price, Decimal(amounts_quote[int(level)]) / order_price
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```

This is also observed when setting up `market_making.dman_maker`

```
2024-03-20 13:13:22,562 - 47194 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2024-03-20 13:13:22,565 - 47194 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-03-20 13:13:23,001 - 47194 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2024-03-20 13:13:23,699 - 47194 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-03-20 13:13:23,767 - 47194 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_derivative.BinancePerpetualDerivative - INFO - Leverage for LOOM-USDT successfully set to 20.
2024-03-20 13:13:23,810 - 47194 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for LOOM-USDT. 1/1 completed.
2024-03-20 13:13:24,001 - 47194 - hummingbot.strategy.script_strategy_base - WARNING - binance_perpetual is not ready. Please wait...
2024-03-20 13:13:24,143 - 47194 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_user_stream_data_source.BinancePerpetualUserStreamDataSource - INFO - Successfully obtained listen key ZWN5UVDmSGzsgxTfWlaevoBn9rCma2vvo51Q3BG7E2j6jKwiDRit0kTaoY9zkJTF
2024-03-20 13:13:24,183 - 47194 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
2024-03-20 13:13:26,675 - 47194 - hummingbot.smart_components.smart_component_base - ERROR - [<class 'decimal.DivisionByZero'>]
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/smart_components/smart_component_base.py", line 69, in control_loop
    await self.control_task()
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/smart_components/controllers/controller_base.py", line 153, in control_task
    executor_actions: List[ExecutorAction] = self.determine_executor_actions()
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/smart_components/controllers/market_making_controller_base.py", line 232, in determine_executor_actions
    actions.extend(self.create_actions_proposal())
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/smart_components/controllers/market_making_controller_base.py", line 243, in create_actions_proposal
    price, amount = self.get_price_and_amount(level_id)
  File "/Users/rapcomia/github/hummingbot/staging/hummingbot/smart_components/controllers/market_making_controller_base.py", line 310, in get_price_and_amount
    return order_price, Decimal(amounts_quote[int(level)]) / order_price
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```

### Steps to reproduce

1. Create controller-config `market_making.pmm_simple` or `market_making.dman_maker`
2. Create script-config 
3. Start the script 

### Release version

dev-1.26.0

### Type of installation

Source

### Attach required files

[logs_conf_pmm_simple.log](https://github.com/hummingbot/hummingbot/files/14662148/logs_conf_pmm_simple.log)
[conf_pmm_simple.yml.log](https://github.com/hummingbot/hummingbot/files/14662154/conf_pmm_simple.yml.log) `remove .log`

**Comment by cardosofede** [comment]
@rapcmia can you show the config of the controllers. I'm running those controllers and are working for me

**Comment by rapcmia** [comment]
> @rapcmia can you show the config of the controllers. I'm running those controllers and are working for me

The controllers configs are available here https://www.notion.so/hummingbot-foundation/V2-Strategies-on-Spot-connectors-ac685c57968144d1bed995d89f16a61e

**Comment by rapcmia** [comment]
Closing ticket, issue related to spreads too wide.
