### ISSUE TITLE
V2 strategy - Getting ERROR - [<class 'decimal.DivisionByZero'>]

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6941]
### Describe the bug

When running test on `pmm_simple` controller on spot exchange, im getting the error `ERROR - [<class 'decimal.DivisionByZero'>]`

![image](https://github.com/hummingbot/hummingbot/assets/73840223/f54fd423-42da-42e5-ad26-2e80f3c75fdc)

```

2024-04-01 12:57:06,010 - 21155 - hummingbot.smart_components.smart_component_base - ERROR - [<class 'decimal.DivisionByZero'>]
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/smart_component_base.py", line 69, in control_loop
    await self.control_task()
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/controllers/controller_base.py", line 165, in control_task
    executor_actions: List[ExecutorAction] = self.determine_executor_actions()
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/controllers/market_making_controller_base.py", line 236, in determine_executor_actions
    actions.extend(self.create_actions_proposal())
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/controllers/market_making_controller_base.py", line 247, in create_actions_proposal
    price, amount = self.get_price_and_amount(level_id)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/smart_components/controllers/market_making_controller_base.py", line 314, in get_price_and_amount
    return order_price, Decimal(amounts_quote[int(level)]) / order_price
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
```

Note: Ran tests on Binance, Kucoin and Kraken all getting same error

### Steps to reproduce

1. Create a simple controller-config on `pmm_simple` and `dman_maker`
2. Create script config then start 
3. Observe script when creating orders 

### Release version

Latest and dev-1.27.0

### Type of installation

Source

### Attach required files

[Archive.zip](https://github.com/hummingbot/hummingbot/files/14819575/Archive.zip)

**Comment by cardosofede** [comment]
@rapcmia the issue is that your configs are using buy and sell spreads of 1.0 (100%)
If you want to use 1 percent put 0.01, here is the revised config

```
id: binance_spot
controller_name: pmm_simple
controller_type: market_making
manual_kill_switch: null
candles_config: []
connector_name: binance
trading_pair: XRP-USDT
total_amount_quote: 50.0
buy_spreads:
- 0.01
sell_spreads:
- 0.01
buy_amounts_pct: null
sell_amounts_pct: null
executor_refresh_time: 180
cooldown_time: 15
leverage: 20
position_mode: HEDGE
stop_loss: 0.03
take_profit: 0.02
time_limit: 300
take_profit_order_type: 2
trailing_stop:
  activation_price: 0.015
  trailing_delta: 0.003
top_order_refresh_time: null
```

**Comment by rapcmia** [comment]
Thanks Fede. This issue is closed, issue was set spread was too high resulting to price error.
