### ISSUE TITLE
Kucoin - Creating orders with no exchange_id on pmm_dynamic controller

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6942]
### Describe the bug

When running tests on pmm_dynamic on different connector, observed that for kucoin spot the script creates a order with no `exchange_order_id` thats only available on client but not on kucoin exchange. This causes: 

Failed to cancel order
```
2024-04-01 13:41:50,951 - 46171 - hummingbot.strategy.script_strategy_base - INFO - (LOOM-USDT) Canceling the limit order SLMUT6150267804d58427a5f43b7e998527393b7. [clock=2024-04-01 05:41:50+00:00]
2024-04-01 13:41:51,092 - 46171 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - ERROR - Failed to cancel order SLMUT6150267804c75427a5f43b7e998527393b7
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/exchange_py_base.py", line 520, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/exchange_py_base.py", line 540, in _execute_order_cancel_and_process_update
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/connector/exchange/kucoin/kucoin_exchange.py", line 231, in _place_cancel
    if tracked_order.exchange_order_id in cancel_result["data"].get("cancelledOrderIds", []):
KeyError: 'data'
```

Failed to fetch updates 
```
2024-04-01 13:42:01,227 - 46171 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - WARNING - Error fetching status update for the active order SLMUT6150267804c75427a5f43b7e998527393b7: 'data'.
2024-04-01 13:42:01,647 - 46171 - hummingbot.connector.exchange.kucoin.kucoin_exchange.KucoinExchange - WARNING - Error fetching status update for the active order SLMUT61502724ca5b8427a5f43b7e998527393b7: 'data'.
```

Note: Setup a wallet that can only create 1 sell order and config with 2 order levels each side

### Steps to reproduce

1. Create a simple pmm_dynamic controller script on kucoin spot
2. Create script config then start
3. Observe after reaching the refresh time, script tries to cancel and order that does not exist on exchange 

### Release version

dev-1.27.0

### Type of installation

Source

### Attach required files

[conf_market_making.pmm_dynamic_1c.yml.log](https://github.com/hummingbot/hummingbot/files/14819841/conf_market_making.pmm_dynamic_1c.yml.log) `remove .log`
[logs_conf_kucoin.log](https://github.com/hummingbot/hummingbot/files/14819844/logs_conf_kucoin.log)

**Comment by rapcmia** [comment]
Related to #6890
