### ISSUE TITLE
How i can use pycharm debug humming bot?

### ISSUE THREAD

**Issue by cCurious** [hummingbot/hummingbot#6957]
When I use pycharm to debug the humming bot, the following error occurred

Traceback (most recent call last):
  File "C:\Users\jjjj\Desktop\hummingbot\hummingbot\client\config\config_data_types.py", line 8, in <module>
    from pydantic.schema import default_ref_template
ImportError: cannot import name 'default_ref_template' from 'pydantic.schema' (C:\Users\jjjj\AppData\Local\Programs\Python\Python38\lib\site-packages\pydantic\schema.py)

**Comment by nikspz** [comment]
@cCurious Check the guide here
https://hummingbot.org/installation/debug/#pycharm

**Comment by xdex-deep** [comment]
/Users/wyf/Local/Workspace/xdex/bots/hummingbot/venv/bin/python /Users/wyf/Local/Workspace/xdex/bots/hummingbot/bin/hummingbot.py 
Traceback (most recent call last):
  File "/Users/wyf/Local/Workspace/xdex/bots/hummingbot/bin/hummingbot.py", line 10, in <module>
    from hummingbot.client.config.client_config_map import ClientConfigMap
  File "/Users/wyf/Local/Workspace/xdex/bots/hummingbot/hummingbot/client/config/client_config_map.py", line 12, in <module>
    from hummingbot.client.config.config_data_types import BaseClientModel, ClientConfigEnum, ClientFieldData
  File "/Users/wyf/Local/Workspace/xdex/bots/hummingbot/hummingbot/client/config/config_data_types.py", line 8, in <module>
    from pydantic.schema import default_ref_template
ImportError: cannot import name 'default_ref_template' from 'pydantic.schema' (/Users/wyf/Local/Workspace/xdex/bots/hummingbot/venv/lib/python3.9/site-packages/pydantic/schema.py)

same error, can not debug
