### ISSUE TITLE
Binance - Error calculating fee in quote: Could not find the exchange rate for BNB-USDT using the rate source binance rate oracle 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#6964]
### Describe the bug

When testing the XEMM script on development, we found this error occurred when taker market order is completed 

```
2024-04-11 22:23:34,562 - 49854 - hummingbot.connector.markets_recorder - ERROR - Error calculating fee in quote: Could not find the exchange rate for BNB-USDT using the rate source binance rate oracle (please verify it has been correctly configured), will be stored in the DB as 0.
2024-04-11 22:23:34,568 - 49854 - hummingbot.connector.client_order_tracker - INFO - The SELL order x-XEKWYICXSLMUT615d2e67ab045c584 amounting to 10.00000000/10.00000000 LOOM has been filled.
2024-04-11 22:23:34,568 - 49854 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1712845414.0, "order_id": "x-XEKWYICXSLMUT615d2e67ab045c584", "trading_pair": "LOOM-USDT", "trade_type": "TradeType.SELL", "order_type": "OrderType.MARKET", "price": "0.10248000", "amount": "10.00000000", "trade_fee": {"percent": "0", "percent_token": "BNB", "flat_fees": [{"token": "BNB", "amount": "0.00000127"}]}, "exchange_trade_id": "25508774", "exchange_order_id": "386600785", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "binance"}
2024-04-11 22:23:34,569 - 49854 - hummingbot.connector.markets_recorder - ERROR - Error calculating fee in quote: Could not find the exchange rate for BNB-USDT using the rate source binance rate oracle (please verify it has been correctly configured), will be stored in the DB as 0.
2024-04-11 22:23:34,575 - 49854 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1712845414.0, "order_id": "x-XEKWYICXBLMUT615d2e67a955dc584", "base_asset": "LOOM", "quote_asset": "USDT", "base_asset_amount": "10.00000000", "quote_asset_amount": "1.0253000000000000", "order_type": "OrderType.MARKET", "exchange_order_id": "386600784", "event_name": "BuyOrderCompletedEvent", "event_source": "binance"}
2024-04-11 22:23:34,578 - 49854 - hummingbot.connector.client_order_tracker - INFO - BUY order x-XEKWYICXBLMUT615d2e67a955dc584 completely filled.
2024-04-11 22:23:34,578 - 49854 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1712845414.0, "order_id": "x-XEKWYICXSLMUT615d2e67ab045c584", "base_asset": "LOOM", "quote_asset": "USDT", "base_asset_amount": "10.00000000", "quote_asset_amount": "1.0248000000000000", "order_type": "OrderType.MARKET", "exchange_order_id": "386600785", "event_name": "SellOrderCompletedEvent", "event_source": "binance"}
2024-04-11 22:23:34,581 - 49854 - hummingbot.connector.client_order_tracker - INFO - SELL order x-XEKWYICXSLMUT615d2e67ab045c584 completely filled.
```

### Steps to reproduce

1. Setup a v2 strategy and use binance as spot connector 
2. Setup a script where an market order filled

### Release version

dev-1.27.0

### Type of installation

Source

**Comment by rapcmia** [comment]
Issue reproduced when testing 2 controllers on 1 script-config (binance + mexc connectors)
![image](https://github.com/user-attachments/assets/97768443-e3f8-4ab9-b368-8bb86f1e447e)
```
2024-08-06 12:59:29,021 - 31110 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-08-06 12:59:29,112 - 31110 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1722920369.0, "order_id": "x-XEKWYICXBNTUT61efc955dd8ef1fca", "exchange_order_id": "954054329", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2024-08-06 12:59:29,112 - 31110 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXBNTUT61efc955dd8ef1fca.
2024-08-06 12:59:29,396 - 31110 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1722920369.0, "order_id": "x-XEKWYICXSNTUT61efc99042cca1fca", "exchange_order_id": "954062678", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2024-08-06 12:59:29,397 - 31110 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXSNTUT61efc99042cca1fca.
2024-08-06 12:59:29,492 - 31110 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1722920369.0, "order_id": "HUMBOTBFOUT61efc99ea5ea61fca8544", "exchange_order_id": "C02__449368869891518464049", "event_name": "OrderCancelledEvent", "event_source": "mexc"}
2024-08-06 12:59:29,496 - 31110 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order HUMBOTBFOUT61efc99ea5ea61fca8544.
2024-08-06 12:59:29,579 - 31110 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1722920369.0, "order_id": "HUMBOTSFOUT61efca84eff9e1fca8544", "exchange_order_id": "C02__449369883373772806049", "event_name": "OrderCancelledEvent", "event_source": "mexc"}
2024-08-06 12:59:29,582 - 31110 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order HUMBOTSFOUT61efca84eff9e1fca8544.
2024-08-06 12:59:31,703 - 31110 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Could not find the exchange rate for BNB-USDT using the rate source binance rate oracle (please verify it has been correctly configured)
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/runnable_base.py", line 69, in control_loop
    await self.control_task()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 276, in control_task
    self.control_barriers()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 399, in control_barriers
    self.control_stop_loss()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 452, in control_stop_loss
    if self.net_pnl_pct <= -self.config.triple_barrier_config.stop_loss:
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/executor_base.py", line 202, in net_pnl_pct
    return self.get_net_pnl_pct()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 236, in get_net_pnl_pct
    return self.net_pnl_quote / self.open_filled_amount_quote if self.open_filled_amount_quote != Decimal("0") else Decimal("0")
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/executor_base.py", line 195, in net_pnl_quote
    return self.get_net_pnl_quote()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 219, in get_net_pnl_quote
    return self.trade_pnl_quote - self.cum_fees_quote
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/executor_base.py", line 209, in cum_fees_quote
    return self.get_cum_fees_quote()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 228, in get_cum_fees_quote
    return sum([order.cum_fees_quote for order in orders if order])
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 228, in <listcomp>
    return sum([order.cum_fees_quote for order in orders if order])
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/models/executors.py", line 59, in cum_fees_quote
    return self.order.cumulative_fee_paid(token=self.order.quote_asset)
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/core/data_type/in_flight_order.py", line 306, in cumulative_fee_paid
    total_fee_in_token += trade_update.fee.fee_amount_in_token(
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/core/data_type/trade_fee.py", line 225, in fee_amount_in_token
    conversion_rate: Decimal = self._get_exchange_rate(conversion_pair, exchange, rate_source)
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/core/data_type/trade_fee.py", line 193, in _get_exchange_rate
    raise ValueError(f"Could not find the exchange rate for {trading_pair} using the rate source "
ValueError: Could not find the exchange rate for BNB-USDT using the rate source binance rate oracle (please verify it has been correctly configured)
2024-08-06 12:59:31,707 - 31110 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Could not find the exchange rate for BNB-USDT using the rate source binance rate oracle (please verify it has been correctly configured)
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/runnable_base.py", line 69, in control_loop
    await self.control_task()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 276, in control_task
    self.control_barriers()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 399, in control_barriers
    self.control_stop_loss()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 452, in control_stop_loss
    if self.net_pnl_pct <= -self.config.triple_barrier_config.stop_loss:
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/executor_base.py", line 202, in net_pnl_pct
    return self.get_net_pnl_pct()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 236, in get_net_pnl_pct
    return self.net_pnl_quote / self.open_filled_amount_quote if self.open_filled_amount_quote != Decimal("0") else Decimal("0")
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/executor_base.py", line 195, in net_pnl_quote
    return self.get_net_pnl_quote()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 219, in get_net_pnl_quote
    return self.trade_pnl_quote - self.cum_fees_quote
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/executor_base.py", line 209, in cum_fees_quote
    return self.get_cum_fees_quote()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 228, in get_cum_fees_quote
    return sum([order.cum_fees_quote for order in orders if order])
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 228, in <listcomp>
    return sum([order.cum_fees_quote for order in orders if order])
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/models/executors.py", line 59, in cum_fees_quote
    return self.order.cumulative_fee_paid(token=self.order.quote_asset)
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/core/data_type/in_flight_order.py", line 306, in cumulative_fee_paid
    total_fee_in_token += trade_update.fee.fee_amount_in_token(
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/core/data_type/trade_fee.py", line 225, in fee_amount_in_token
    conversion_rate: Decimal = self._get_exchange_rate(conversion_pair, exchange, rate_source)
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/core/data_type/trade_fee.py", line 193, in _get_exchange_rate
    raise ValueError(f"Could not find the exchange rate for {trading_pair} using the rate source "
ValueError: Could not find the exchange rate for BNB-USDT using the rate source binance rate oracle (please verify it has been correctly configured)
2024-08-06 12:59:32,708 - 31110 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Could not find the exchange rate for BNB-USDT using the rate source binance rate oracle (please verify it has been correctly configured)
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/runnable_base.py", line 69, in control_loop
    await self.control_task()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 276, in control_task
    self.control_barriers()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 399, in control_barriers
    self.control_stop_loss()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 452, in control_stop_loss
    if self.net_pnl_pct <= -self.config.triple_barrier_config.stop_loss:
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/executor_base.py", line 202, in net_pnl_pct
    return self.get_net_pnl_pct()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 236, in get_net_pnl_pct
    return self.net_pnl_quote / self.open_filled_amount_quote if self.open_filled_amount_quote != Decimal("0") else Decimal("0")
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/executor_base.py", line 195, in net_pnl_quote
    return self.get_net_pnl_quote()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 219, in get_net_pnl_quote
    return self.trade_pnl_quote - self.cum_fees_quote
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/executor_base.py", line 209, in cum_fees_quote
    return self.get_cum_fees_quote()
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 228, in get_cum_fees_quote
    return sum([order.cum_fees_quote for order in orders if order])
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/executors/position_executor/position_executor.py", line 228, in <listcomp>
    return sum([order.cum_fees_quote for order in orders if order])
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/strategy_v2/models/executors.py", line 59, in cum_fees_quote
    return self.order.cumulative_fee_paid(token=self.order.quote_asset)
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/core/data_type/in_flight_order.py", line 306, in cumulative_fee_paid
    total_fee_in_token += trade_update.fee.fee_amount_in_token(
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/core/data_type/trade_fee.py", line 225, in fee_amount_in_token
    conversion_rate: Decimal = self._get_exchange_rate(conversion_pair, exchange, rate_source)
  File "/Users/rapcomia/github/hummingbot/dev-hummingbot/hummingbot/core/data_type/trade_fee.py", line 193, in _get_exchange_rate
    raise ValueError(f"Could not find the exchange rate for {trading_pair} using the rate source "
ValueError: Could not find the exchange rate for BNB-USDT using the rate source binance rate oracle (please verify it has been correctly configured)
```
- Initiate `stop` command wont stop the errors from the log panel ❌ 
- Initiate `exit` command ✅ 
[08062024.zip](https://github.com/user-attachments/files/16505446/08062024.zip)

**Comment by rapcmia** [comment]
Closing ticket: Not able to reproduce on running xemm  controller-config binance/kucoin market pairs
