### ISSUE TITLE
Binance - unable to place orders due to API update

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#6985]
### Describe the bug

![image](https://github.com/hummingbot/hummingbot/assets/83953535/0e4fc844-a542-4316-9b59-714017d1e22e)
https://binance-docs.github.io/apidocs/spot/en/#change-log

### Steps to reproduce

1. Create strategy using binance spot
2. start the strategy

### Release version

dev-1.27.0

### Type of installation

Source

### Attach required files

[logs_conf_pure_mm_1.log](https://github.com/hummingbot/hummingbot/files/15106713/logs_conf_pure_mm_1.log)
[logs_conf_pure_mm_2.log](https://github.com/hummingbot/hummingbot/files/15106714/logs_conf_pure_mm_2.log)

```
2024-04-25 07:32:26,419 - 1478431 - hummingbot.connector.exchange.binance.binance_api_order_book_data_source.BinanceAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/home/nikita/staging/hummingbot/core/data_type/order_book_tracker_data_source.py", line 79, in listen_for_subscriptions
    await self._subscribe_channels(ws)
  File "/home/nikita/staging/hummingbot/connector/exchange/binance/binance_api_order_book_data_source.py", line 75, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'XRP-USDT'
2024-04-25 07:32:27,024 - 1478431 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/nikita/staging/hummingbot/connector/exchange_py_base.py", line 780, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/home/nikita/staging/hummingbot/connector/exchange/binance/binance_exchange.py", line 282, in _status_polling_loop_fetch_updates
    await self._update_order_fills_from_trades()
  File "/home/nikita/staging/hummingbot/connector/exchange/binance/binance_exchange.py", line 383, in _update_order_fills_from_trades
    "symbol": await self.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/home/nikita/miniconda3/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'XRP-USDT'
```

![image](https://github.com/hummingbot/hummingbot/assets/83953535/a9393c68-6d05-4923-a6b0-a07dae9bd896)

**Comment by mlguys** [comment]
@nikspz Could you test this PR? https://github.com/hummingbot/hummingbot/pull/6986

**Comment by nikspz** [comment]
Acceptance: Binance spot works according to updated connector standards

Sponsor: Hummingbot Foundation
Bounty amount: 50k HBOT
Developer portion: 50k HBOT

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @mlguys. The fix has been deployed on development branch and hummingbot version 1.27.0.
