### ISSUE TITLE
time_synchronizer - Error getting server time

### ISSUE THREAD

**Issue by AstaMimic** [hummingbot/hummingbot#7001]
### Describe the bug

Each time I start hummingbot, I see these two error lines:

12:52:54 - time_synchronizer - Error getting server time. (See log file for stack trace dump)        
12:52:54 - time_synchronizer - Could not refresh server time. Check network connection.   

Please note:
- I am located in the USA. 
- I do not have a VPN on. 
- Coinbase Advanced Trade is my rate oracle source.
- I have no active connectors set up.
- Version 1.27.0

Troubleshooting Steps Taken:
- Full reinstall (./clean, ./install, ./compile) in a new directory

In the log files I see:

`2024-04-29 13:05:31,547 - 7386 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/time_synchronizer.py", line 65, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange/binance/binance_web_utils.py", line 69, in get_current_server_time
    response = await rest_assistant.execute_request(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.com/api/v3/time. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
2024-04-29 13:05:31,548 - 7386 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
2024-04-29 13:05:31,622 - 7386 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 1074, in _initialize_trading_pair_symbol_map
    exchange_info = await self._make_trading_pairs_request()
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 1087, in _make_trading_pairs_request
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.com/api/v3/exchangeInfo. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}`

### Steps to reproduce

1. Install hummingbot
2. Run hummingbot in the United States without a VPN.

### Release version

1.27.0

### Type of installation

Source

### Attach required files

`2024-04-29 13:05:31,547 - 7386 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/time_synchronizer.py", line 65, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange/binance/binance_web_utils.py", line 69, in get_current_server_time
    response = await rest_assistant.execute_request(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.com/api/v3/time. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
2024-04-29 13:05:31,548 - 7386 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
2024-04-29 13:05:31,622 - 7386 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 1074, in _initialize_trading_pair_symbol_map
    exchange_info = await self._make_trading_pairs_request()
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 1087, in _make_trading_pairs_request
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.com/api/v3/exchangeInfo. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
2024-04-29 13:11:11,521 - 7386 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-04-29 13:11:13,600 - 7386 - hummingbot.client.hummingbot_application - ERROR - MQTT is already stopped!
2024-04-29 13:12:21,401 - 7555 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/time_synchronizer.py", line 65, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange/binance/binance_web_utils.py", line 69, in get_current_server_time
    response = await rest_assistant.execute_request(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.com/api/v3/time. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
2024-04-29 13:12:21,402 - 7555 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
2024-04-29 13:12:21,484 - 7555 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 1074, in _initialize_trading_pair_symbol_map
    exchange_info = await self._make_trading_pairs_request()
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 1087, in _make_trading_pairs_request
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/Users/alecotto/Documents/code/botcamp/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.com/api/v3/exchangeInfo. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
`

**Comment by ak4noir** [comment]
I was coming running into this too. Make sure to remove `binance` from the `paper_trades` attribute in your `conf_client.yml`. It is probably safe to remove any values that you will not be using there.

**Comment by AstaMimic** [comment]
oh great shout!

> I was coming running into this too. Make sure to remove `binance` from the `paper_trades` attribute in your `conf_client.yml`. It is probably safe to remove any values that you will not be using there.

Great shout! I'm trying to purge any geo restricted connections from my hummingbot installation. Are there any other areas where binance may be sneakily connected to or relied upon?

**Comment by ak4noir** [comment]
> Great shout! I'm trying to purge any geo restricted connections from my hummingbot installation. Are there any other areas where binance may be sneakily connected to or relied upon?

not that I am aware of.
