### ISSUE TITLE
Bug Report: Can't start an instance #133

### ISSUE THREAD

**Issue by edsonPrimo** [hummingbot/hummingbot#7009]
### Describe the bug

I created a new instance on the dashboard, but when I start it, it suddenly shuts down after few seconds.

Using version 1.25 of hummingbot works fine

```
Traceback (most recent call last):
  File "/home/hummingbot/./bin/hummingbot_quickstart.py", line 15, in <module>
    from bin.hummingbot import UIStartListener, detect_available_port
  File "/home/hummingbot/bin/hummingbot.py", line 19, in <module>
    from hummingbot.client.hummingbot_application import HummingbotApplication
  File "/home/hummingbot/hummingbot/client/hummingbot_application.py", line 9, in <module>
    from hummingbot.client.command import __all__ as commands
  File "/home/hummingbot/hummingbot/client/command/__init__.py", line 2, in <module>
    from .config_command import ConfigCommand
  File "/home/hummingbot/hummingbot/client/command/config_command.py", line 8, in <module>
    from hummingbot.client.command.gateway_command import GatewayCommand
  File "/home/hummingbot/hummingbot/client/command/gateway_command.py", line 22, in <module>
    from hummingbot.client.ui.completer import load_completer
  File "/home/hummingbot/hummingbot/client/ui/completer.py", line 29, in <module>
    from hummingbot.strategy.strategy_v2_base import StrategyV2ConfigBase
  File "/home/hummingbot/hummingbot/strategy/strategy_v2_base.py", line 16, in <module>
    from hummingbot.connector.markets_recorder import MarketsRecorder
  File "/home/hummingbot/hummingbot/connector/markets_recorder.py", line 49, in <module>
    from hummingbot.smart_components.controllers.controller_base import ControllerConfigBase
ModuleNotFoundError: No module named 'hummingbot.smart_components.controllers.controller_base'
```

I tried on MacOS and WSL2.

### Steps to reproduce

1.Fresh install of the dashboard
2.Create an instance
3.Try to start the instance

### Release version

1.27

### Type of installation

Source

**Comment by rapcmia** [comment]
https://github.com/hummingbot/dashboard/issues/133
