### ISSUE TITLE
V2 strategy - Unhandled error in background task when running status command 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#7012]
### Describe the bug

While reviewing bots for trader experiments, one of our scripts return an error when executing `status` command

![image](https://github.com/hummingbot/hummingbot/assets/73840223/f0951e26-cf8b-4d24-8e94-2d3032250e9b)

```
2024-05-06 11:57:30,896 - 15 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 1 validation error for PerformanceReport
close_type_counts -> __key__
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/status_command.py", line 152, in status_check_all
    self.notify(await self.strategy_status())
  File "/home/hummingbot/hummingbot/client/command/status_command.py", line 78, in strategy_status
    st_status = self.strategy.format_status()
  File "/home/hummingbot/hummingbot/strategy/strategy_v2_base.py", line 382, in format_status
    performance_report = self.executor_orchestrator.generate_performance_report(controller_id)
  File "/home/hummingbot/hummingbot/smart_components/executors/executor_orchestrator.py", line 183, in generate_performance_report
    report = PerformanceReport(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PerformanceReport
close_type_counts -> __key__
  none is not an allowed value (type=type_error.none.not_allowed)
```

### Steps to reproduce

QA to add, need to reproduce the issue 

### Release version

dev-1.28.0

### Type of installation

Source

### Attach required files

n/a

**Comment by rapcmia** [comment]
After monitoring XEMM today, got our first 2 trades and check history which works ok however when running status command this issue occurred 
![image](https://github.com/hummingbot/hummingbot/assets/73840223/0d76b5d7-e220-4e51-b75d-5859e9e41682)

Checking if we can reproduce this on other v2 strategy controllers
