### ISSUE TITLE
Binance US is still using old rate limits

### ISSUE THREAD

**Issue by sytranvn** [hummingbot/hummingbot#7017]
### Describe the bug

I'm running a few bots on same IP and recently got banned because violating binance.us rate limits. From the log I think binance.us is using old rate limits while hummingbot is using new one. My work around is just disabling binance.us from rate oracle since I don't need that info. 
I'm not running the latest version but I believe this issue also affect latest one.  Raising this so people can be aware of the issue.

### Steps to reproduce

1. Run a few bots on binance exchange
2. Observe the log

### Release version

1.21.0

### Type of installation

Docker

### Attach required files

```
There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 1019, in _initialize_trading_pair_symbol_map
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 846, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 879, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 78, in execute_request
    raise ioe
OSError: Error executing request GET https://api.binance.us/api/v3/exchangeInfo. HTTP status is 429. Error: {"code":-1003,"msg":"Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use WebSocket Streams for live updates to avoid polling the API."}

2024-05-07 02:52:51.334 There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 1019, in _initialize_trading_pair_symbol_map
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 846, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 879, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 78, in execute_request
    raise ioe
OSError: Error executing request GET https://api.binance.us/api/v3/exchangeInfo. HTTP status is 418. Error: {"code":-1003,"msg":"Way too much request weight used; IP banned until 1715050408547. Please use WebSocket Streams for live updates to avoid bans."}
```

**Comment by mlguys** [comment]
Hey @sytranvn, this issue has been resolved in the latest release. We've split the binance and binance.us into separated oracle.

**Comment by sytranvn** [comment]
@mlguys great! Please close this issue.
