### ISSUE TITLE
Funding rate arb - Getting unexpected error running clock tick

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#7023]
### Describe the bug

When running tests, we observed an error happened while on `status --live`. It started with `Unhandled error in background task: cannot unpack non-iterable NoneType object` then ended with ` Unexpected error running clock tick.` on every tick

![image](https://github.com/hummingbot/hummingbot/assets/73840223/a6045946-66b8-4b4d-b9cf-1b7d32c89db1)
```

2024-05-10 21:34:49,456 - 37988 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-05-10 21:47:46,892 - 37988 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_user_stream_data_source.BinancePerpetualUserStreamDataSource - WARNING - The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1008 msg data: 1008)
2024-05-10 21:47:52,003 - 37988 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_user_stream_data_source.BinancePerpetualUserStreamDataSource - INFO - Successfully obtained listen key FIDPXvxoAuCXItr6RWnSa7o81qzAYIgzzDQpAXuq9rjzLiczq5PekQfZB78cfX3H
2024-05-10 21:50:49,423 - 37988 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - WARNING - The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1008 msg data: 1008)
2024-05-10 21:50:49,966 - 37988 - hummingbot.connector.derivative.binance_perpetual.binance_perpetual_api_order_book_data_source.BinancePerpetualAPIOrderBookDataSource - INFO - Subscribed to public order book, trade and funding info channels...
2024-05-10 22:00:58,475 - 37988 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/client/command/status_command.py", line 145, in status_check_all
    await self.strategy_status(live=True) + "\n\n Press escape key to stop update.", 0.1
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/client/command/status_command.py", line 78, in strategy_status
    st_status = self.strategy.format_status()
  File "/Users/rapcomia/github/hummingbot/development/scripts/funding_rate_arb.py", line 334, in format_status
    connector_1, connector_2, side, funding_rate_diff = best_combination
TypeError: cannot unpack non-iterable NoneType object
2024-05-10 22:00:59,002 - 37988 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/strategy/script_strategy_base.py", line 75, in tick
    self.on_tick()
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/strategy/strategy_v2_base.py", line 286, in on_tick
    executor_actions: List[ExecutorAction] = self.determine_executor_actions()
  File "/Users/rapcomia/github/hummingbot/development/hummingbot/strategy/strategy_v2_base.py", line 295, in determine_executor_actions
    actions.extend(self.create_actions_proposal())
  File "/Users/rapcomia/github/hummingbot/development/scripts/funding_rate_arb.py", line 225, in create_actions_proposal
    connector_1, connector_2, trade_side, expected_profitability = best_combination
TypeError: cannot unpack non-iterable NoneType object
```

### Steps to reproduce

Most of the tests the bot is on `status --live` mode 
- Occurred while on funding rate paid/received event 
- Sudden failed websocket connection from one of exchanges (binance)
- QA to add more `TBA` 

### Release version

dev-1.28.0

### Type of installation

Source

### Attach required files

[05102024.zip](https://github.com/hummingbot/hummingbot/files/15277000/05102024.zip)

**Comment by hrzisme** [comment]
Same question, have u sovle this ?

**Comment by James240200** [comment]
Hey im having this issue. Any solutions?

**Comment by thebocher** [comment]
@fengtality @cardosofede the problem is with function `get_most_profitable_combination` in `v2_funding_rate_arb.py`. When it fails to find best combination, it returns `None`, but functions `format_status` and `create_actions_proposal` dont expect `None`.

I tried putting `if not best_combination: continue`, but later there are problems with creating corresponding LONG and SHORT orders

Hope this helps a bit :>
