### ISSUE TITLE
Kucoin_perpetual - Error fetching status update after a day longrun

### ISSUE THREAD

**Issue by bossdebitbotz** [hummingbot/hummingbot#7067]
### Describe the bug

ubuntu 22.04 vultr vm tokyo

bot will run for a day then this:

024-06-04 16:16:48,407 - 14 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1717517808.0, "order_id": "HummingbotBAEUT61a12c6d6efafef630f2ab2fe", "trading_pair": "AAVE-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.MARKET", "price": "101.22", "amount": "0.81", "trade_fee": {"percent": "0.0006", "percent_token": "USDT", "flat_fees": []}, "exchange_trade_id": "1695019289836", "exchange_order_id": "187504707852312576", "leverage": 20, "position": "CLOSE", "event_name": "OrderFilledEvent", "event_source": "kucoin_perpetual"}
2024-06-04 16:16:48,586 - 14 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1717517808.0, "order_id": "HummingbotBAEUT61a12c6d6efafef630f2ab2fe", "base_asset": "AAVE", "quote_asset": "USDT", "base_asset_amount": "0.81", "quote_asset_amount": "81.9882", "order_type": "OrderType.MARKET", "exchange_order_id": "187504707852312576", "event_name": "BuyOrderCompletedEvent", "event_source": "kucoin_perpetual"}
2024-06-04 16:16:48,587 - 14 - hummingbot.connector.client_order_tracker - INFO - BUY order HummingbotBAEUT61a12c6d6efafef630f2ab2fe completely filled.
2024-06-04 16:48:13,096 - 14 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Unexpected error while fetching account updates.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 780, in _status_polling_loop
    await self._status_polling_loop_fetch_updates()
  File "/home/hummingbot/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 285, in _status_polling_loop_fetch_updates
    await safe_gather(
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 437, in _update_positions
    raw_responses: List[Dict[str, Any]] = await self._api_get(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/derivative/kucoin_perpetual/kucoin_perpetual_derivative.py", line 927, in _api_request
    resp = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api-futures.kucoin.com/api/v1/positions. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}
2024-06-04 16:48:13,106 - 14 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Could not fetch account updates from Kucoin_perpetual. Check API key and network connection.
2024-06-04 16:48:13,107 - 14 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Error fetching status update for the order HummingbotBAEUT61a118842f222ef630f2ab2fe: Error executing request GET https://api-futures.kucoin.com/api/v1/orders/187482291818217472. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}.
2024-06-04 16:48:13,107 - 14 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Failed to fetch status update for the order HummingbotBAEUT61a118842f222ef630f2ab2fe.
2024-06-04 16:48:13,109 - 14 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Error fetching status update for the order HummingbotBAEUT61a1188ba296bef630f2ab2fe: Error executing request GET https://api-futures.kucoin.com/api/v1/orders/187482323405582336. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}.
2024-06-04 16:48:13,110 - 14 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Failed to fetch status update for the order HummingbotBAEUT61a1188ba296bef630f2ab2fe.
2024-06-04 16:48:13,116 - 14 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - NETWORK - Error fetching status update for AAVE-USDT: Error executing request GET https://api-futures.kucoin.com/api/v1/recentFills. HTTP status is 400. Error: {"code":"400002","msg":"Invalid KC-API-TIMESTAMP"}.
2024-06-04 16:48:13,117 - 14 - hummingbot.connector.derivative.kucoin_perpetual.kucoin_perpetual_derivative.KucoinPerpetualDerivative - WARNING - Failed to fetch status update for AAVE-USDT.

im experiencing the same issue with binance

### Steps to reproduce

1.  start bot in dashboard
2. wait for a day
3.  throw up hands in frustration

### Release version

1.28

### Type of installation

Docker

### Attach required files

[logs_hummingbot (2).log](https://github.com/user-attachments/files/15568149/logs_hummingbot.2.log)
[logs_kuaave15-2024.06.04_02.36.log](https://github.com/user-attachments/files/15568150/logs_kuaave15-2024.06.04_02.36.log)

**Comment by nikspz** [comment]
hi @bossdebitbotz 
Could you send your config here as well?

**Comment by bossdebitbotz** [comment]
buy_amounts_pct:
- 0.1111111111111111
- 0.2222222222222222
- 0.33333333333333326
buy_spreads:
- 0.005
- 0.01
- 0.015
candles_config: []
connector_name: kucoin_perpetual
controller_name: dman_maker_v2
controller_type: market_making
cooldown_time: 3600.0
dca_amounts:
- 0.16666666666666663
- 0.33333333333333326
- 0.5
dca_spreads:
- 0.0
- 0.01
- 0.02
executor_activation_bounds:
- 0.001
executor_refresh_time: 3600.0
id: dman_maker_v2-kucoin_perpetual-AAVE-1.5
leverage: 20
manual_kill_switch: null
position_mode: HEDGE
sell_amounts_pct:
- 0.1111111111111111
- 0.2222222222222222
sell_spreads:
- 0.005
- 0.02
stop_loss: 0.02
take_profit: 0.02200000000000001
time_limit: 21600
top_executor_refresh_time: 3600
total_amount_quote: 2250
trading_pair: AAVE-USDT
trailing_stop:
  activation_price: 0.009999999999999997
  trailing_delta: 0.0010000000000000002

**Comment by rapcmia** [comment]
Fix has been deployed on development 2.0.1
