### ISSUE TITLE
Mexc - Unable to submit close market order due to TypeError: unsupported operand type(s) 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#7090]
### Describe the bug

When reviewing long term bot running on pmm_simple controller using mexc, found this bug on logs causing retry logic to failed and complete close order executor 

![image](https://github.com/hummingbot/hummingbot/assets/73840223/0fd9db01-60e0-440b-8541-cb841f62d23c)
```
# Creating sell order to open executor HUMBOTSFOUT61b65c434d4fa6c5be879
2024-06-21 12:42:37,706 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating FIRO-USDT sell order: price: 1.266035000000000000260937105 amount: 31.59470314801723490405539312.
2024-06-21 12:42:37,900 - 15 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT SELL order HUMBOTSFOUT61b65c434d4fa6c5be879 for 31.59 FIRO-USDT.
2024-06-21 12:42:37,920 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1718973755.0, "type": "OrderType.LIMIT", "trading_pair": "FIRO-USDT", "amount": "31.59", "price": "1.266", "order_id": "HUMBOTSFOUT61b65c434d4fa6c5be879", "creation_timestamp": 1718973755.0, "exchange_order_id": "C02__432816613046304768049", "leverage": 1, "position": "NIL", "event_name": "SellOrderCreatedEvent", "event_source": "mexc"}
2024-06-21 12:42:42,181 - 15 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - INFO - Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking...
2024-06-21 12:42:53,502 - 15 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-06-21 12:42:53,669 - 15 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for FIRO-USDT. 1/1 completed.
2024-06-21 12:42:53,888 - 15 - hummingbot.connector.exchange.mexc.mexc_api_user_stream_data_source.MexcAPIUserStreamDataSource - INFO - Successfully obtained listen key 5a166192dac1757b180a13655843e6e421daa0dd3e3f25276dc16e37fbad32d9
2024-06-21 12:42:59,570 - 15 - hummingbot.connector.exchange.mexc.mexc_api_order_book_data_source.MexcAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2024-06-21 12:42:59,887 - 15 - hummingbot.connector.exchange.mexc.mexc_api_user_stream_data_source.MexcAPIUserStreamDataSource - INFO - Subscribed to private order changes and balance updates channels...
2024-06-21 12:45:31,572 - 15 - hummingbot.strategy.script_strategy_base - INFO - (FIRO-USDT) Canceling the limit order HUMBOTBFOUT61b65bc6a4a1f6c5be879. [clock=2024-06-21 12:45:27+00:00]
2024-06-21 12:45:31,818 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1718973927.0, "order_id": "HUMBOTBFOUT61b65bc6a4a1f6c5be879", "exchange_order_id": "C02__432816064750129152049", "event_name": "OrderCancelledEvent", "event_source": "mexc"}
2024-06-21 12:45:31,818 - 15 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order HUMBOTBFOUT61b65bc6a4a1f6c5be879.
2024-06-21 12:45:34,389 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Not enough budget to open position.
2024-06-21 12:45:38,156 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating FIRO-USDT buy order: price: 1.239974999999999999739271062 amount: 32.25871489344543237437108045.
2024-06-21 12:45:41,853 - 15 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order HUMBOTBFOUT61b65cef64c696c5be879 for 32.25 FIRO-USDT.
2024-06-21 12:45:41,870 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1718973939.0, "type": "OrderType.LIMIT", "trading_pair": "FIRO-USDT", "amount": "32.25", "price": "1.239", "order_id": "HUMBOTBFOUT61b65cef64c696c5be879", "creation_timestamp": 1718973935.0, "exchange_order_id": "C02__432817374140518400049", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "mexc"}

# Sell order filled HUMBOTSFOUT61b65c434d4fa6c5be879, 
2024-06-21 12:46:04,264 - 15 - hummingbot.connector.client_order_tracker - INFO - The SELL order HUMBOTSFOUT61b65c434d4fa6c5be879 amounting to 31.59/31.59 FIRO has been filled.
2024-06-21 12:46:04,361 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1718973958.0, "order_id": "HUMBOTSFOUT61b65c434d4fa6c5be879", "trading_pair": "FIRO-USDT", "trade_type": "TradeType.SELL", "order_type": "OrderType.LIMIT", "price": "1.266", "amount": "31.59", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "0"}]}, "exchange_trade_id": "432816613046304768X1", "exchange_order_id": "C02__432816613046304768049", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "mexc"}
2024-06-21 12:46:04,545 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1718973958.0, "order_id": "HUMBOTSFOUT61b65c434d4fa6c5be879", "base_asset": "FIRO", "quote_asset": "USDT", "base_asset_amount": "31.59", "quote_asset_amount": "39.99294", "order_type": "OrderType.LIMIT", "exchange_order_id": "C02__432816613046304768049", "event_name": "SellOrderCompletedEvent", "event_source": "mexc"}
2024-06-21 12:46:04,546 - 15 - hummingbot.connector.client_order_tracker - INFO - SELL order HUMBOTSFOUT61b65c434d4fa6c5be879 completely filled.
2024-06-21 12:47:44,167 - 15 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - INFO - Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking...
2024-06-21 12:47:59,441 - 15 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-06-21 12:47:59,870 - 15 - hummingbot.connector.exchange.mexc.mexc_api_user_stream_data_source.MexcAPIUserStreamDataSource - INFO - Successfully obtained listen key 6f51708ba1f05266edf722b09bdea2fc04dd3aac166026a846b0b2012bb2382e
2024-06-21 12:48:00,042 - 15 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for FIRO-USDT. 1/1 completed.
2024-06-21 12:48:03,452 - 15 - hummingbot.connector.exchange.mexc.mexc_api_order_book_data_source.MexcAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2024-06-21 12:48:03,710 - 15 - hummingbot.connector.exchange.mexc.mexc_api_user_stream_data_source.MexcAPIUserStreamDataSource - INFO - Subscribed to private order changes and balance updates channels...

# Creating buy close market order @31.59 however kept on getting error
2024-06-21 12:49:42,157 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating FIRO-USDT buy order: price: NaN amount: 31.59.
2024-06-21 12:49:42,166 - 15 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - NETWORK - Error submitting buy MARKET order to Mexc for 31.59 FIRO-USDT NaN.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/hummingbot/hummingbot/connector/exchange/mexc/mexc_exchange.py", line 201, in _place_order
    "quoteOrderQty": f"{price * amount:f}",
TypeError: unsupported operand type(s) for *: 'hummingbot.core.data_type.order_book_query_result.ClientOrderBookQueryResult' and 'decimal.Decimal'
```
- Close order failed after 11/10 retries
    ```
    2024-06-21 12:50:11,549 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - ERROR - Close order failed. Retrying 11/10
    2024-06-21 12:50:11,553 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1718974209.0, "order_id": "HUMBOTBFOUT61b65df40e9c16c5be879", "order_type": "OrderType.MARKET", "event_name": "MarketOrderFailureEvent", "event_source": "mexc"}
    2024-06-21 12:50:11,553 - 15 - hummingbot.connector.client_order_tracker - INFO - Order HUMBOTBFOUT61b65df40e9c16c5be879 has failed. Order Update: OrderUpdate(trading_pair='FIRO-USDT', update_timestamp=1718974209.0, new_state=<OrderState.FAILED: 6>, client_order_id='HUMBOTBFOUT61b65df40e9c16c5be879', exchange_order_id=None, misc_updates=None)
    ``` 
- The open buy order of this order cycle got successfully cancelled after 5mins refresh time ✅

### Steps to reproduce

1. Setup a v2 script or controller using mexc
2. Monitor and observed behavior when placing close market order
3. Connector using v2 strategy getting error when closing executor 

### Release version

dev-1.29

### Type of installation

Source

### Attach required files

https://drive.google.com/drive/u/0/folders/1NDRpB-Q5p-FMDOp6hsjuHhGGkeB1gnuK

**Comment by nikspz** [comment]
Fix #7126 Merged to development and part of release version 2.0.1
