### ISSUE TITLE
Binance - Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#7098]
### Describe the bug

When testing binance using pmm_simple controller from hummingbot deploy, observed random network disconnection from the exchange causes error and unexpected behaviors:

```
hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - INFO - Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking..
```
Note: Compare behavior when client is offline or no internet connection and expected that `rate_oracle` should be disconnected too but on this test it was not.

---

A close market order created but got disconnected from binance, lets see order id `XEKWYICXBAXUT61bd01332d3706c5b`
```
# succesfully cancelled buy XEKWYICXBAXUT61bcfcdccce776c5b close order and create buy XEKWYICXBAXUT61bd01332d3706c5b close market order 
2024-06-26 19:32:29,507 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating AVAX-USDT buy order: price: NaN amount: 0.74000000.
2024-06-26 19:32:29,510 - 15 - hummingbot.strategy.script_strategy_base - INFO - (AVAX-USDT) Canceling the limit order x-XEKWYICXBAXUT61bcfcdccce776c5b. [clock=2024-06-26 19:32:29+00:00]
2024-06-26 19:32:30,557 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
2024-06-26 19:32:32,562 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
2024-06-26 19:32:34,514 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating AVAX-USDT buy order: price: NaN amount: 0.78000000.
2024-06-26 19:32:34,516 - 15 - hummingbot.strategy.script_strategy_base - INFO - (AVAX-USDT) Canceling the limit order x-XEKWYICXBAXUT61bcfd9c84eb36c5b. [clock=2024-06-26 19:32:34+00:00]
2024-06-26 19:32:34,590 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
2024-06-26 19:32:35,538 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.78000000
2024-06-26 19:32:36,666 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
2024-06-26 19:32:37,541 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.78000000
2024-06-26 19:32:38,670 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
2024-06-26 19:32:39,543 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.78000000

...
# network reconnected and buy XEKWYICXBAXUT61bd01332d3706c5b close market order created  
2024-06-26 19:32:39,918 - 15 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-06-26 19:32:39,953 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719430359.0, "order_id": "x-XEKWYICXBAXUT61bcfcdccce776c5b", "exchange_order_id": "3208099018", "event_name": "OrderCancelledEvent", "event_source": "binance"}
2024-06-26 19:32:39,953 - 15 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order x-XEKWYICXBAXUT61bcfcdccce776c5b.
2024-06-26 19:32:40,015 - 15 - hummingbot.connector.client_order_tracker - INFO - Created MARKET BUY order x-XEKWYICXBAXUT61bd01332d3706c5b for 0.74000000 AVAX-USDT.
```
- Observed that it started to spam `..waiting for close order to be filled`
- Observed that the market order was recognized as limit order at `2024-06-26 19:33:08,890` and getting cancelled?
  ```
  # cancelling limit order on XEKWYICXBAXUT61bd01332d3706c5b which was created as market order to close position?
  2024-06-26 19:33:08,890 - 15 - hummingbot.strategy.script_strategy_base - INFO - (AVAX-USDT) Canceling the limit order x-XEKWYICXBAXUT61bd01332d3706c5b. [clock=2024-06-26 19:33:08+00:00]
  2024-06-26 19:33:09,811 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - No fill on close order, will be retried.
  2024-06-26 19:33:09,812 - 15 - hummingbot.strategy.script_strategy_base - INFO - (AVAX-USDT) Canceling the limit order x-XEKWYICXBAXUT61bd0157b39c16c5b. [clock=2024-06-26 19:33:09+00:00]
  2024-06-26 19:33:10,894 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - No fill on close order, will be retried.
  2024-06-26 19:33:11,815 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - No fill on close order, will be retried.
  2024-06-26 19:33:12,897 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - No fill on close order, will be retried.
  2024-06-26 19:33:13,819 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - No fill on close order, will be retried.
  2024-06-26 19:33:14,903 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - No fill on close order, will be retried.
  2024-06-26 19:33:15,823 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - No fill on close order, will be retried.
  2024-06-26 19:33:16,908 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - No fill on close order, will be retried.
  ```
- found that after a minute it that the order was completely filled 
  ```
  # the buy XEKWYICXBAXUT61bd01332d3706c5b market order was filled here as ordertype.MARKET from @2024-06-26 19:32:29,507, took 1min to complete
  2024-06-26 19:33:46,396 - 15 - hummingbot.connector.client_order_tracker - INFO - The BUY order x-XEKWYICXBAXUT61bd01332d3706c5b amounting to 0.74000000/0.74000000 AVAX has been filled.
  2024-06-26 19:33:46,398 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719430426.0, "order_id": "x-XEKWYICXBAXUT61bd01332d3706c5b", "trading_pair": "AVAX-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.MARKET", "price": "26.33000000", "amount": "0.74000000", "trade_fee": {"percent": "0", "percent_token": "AVAX", "flat_fees": [{"token": "AVAX", "amount": "0.00074000"}]}, "exchange_trade_id": "280628320", "exchange_order_id": "3208159973", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "binance"}
  2024-06-26 19:33:47,848 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719430427.0, "order_id": "x-XEKWYICXBAXUT61bd01332d3706c5b", "base_asset": "AVAX", "quote_asset": "USDT", "base_asset_amount": "0.74000000", "quote_asset_amount": "19.48420000", "order_type": "OrderType.MARKET", "exchange_order_id": "3208159973", "event_name": "BuyOrderCompletedEvent", "event_source": "binance"}
  2024-06-26 19:33:47,849 - 15 - hummingbot.connector.client_order_tracker - INFO - BUY order x-XEKWYICXBAXUT61bd01332d3706c5b completely filled
  ```

---

Cancelling close limit order and creating close market order when suddenly got binance network disconnected, see order id `XEKWYICXBAXUT61bcfd9c84eb36c5b`
  ```
  # no cancellation completed for buy XEKWYICXBAXUT61bcfd9c84eb36c5b and also in the process of creating close market order @0.78000000
  2024-06-26 19:32:29,507 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating AVAX-USDT buy order: price: NaN amount: 0.74000000.
  2024-06-26 19:32:29,510 - 15 - hummingbot.strategy.script_strategy_base - INFO - (AVAX-USDT) Canceling the limit order x-XEKWYICXBAXUT61bcfcdccce776c5b. [clock=2024-06-26 19:32:29+00:00]
  2024-06-26 19:32:30,557 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
  2024-06-26 19:32:32,562 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
  2024-06-26 19:32:34,514 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating AVAX-USDT buy order: price: NaN amount: 0.78000000.
  2024-06-26 19:32:34,516 - 15 - hummingbot.strategy.script_strategy_base - INFO - (AVAX-USDT) Canceling the limit order x-XEKWYICXBAXUT61bcfd9c84eb36c5b. [clock=2024-06-26 19:32:34+00:00]
  2024-06-26 19:32:34,590 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
  2024-06-26 19:32:35,538 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.78000000
  2024-06-26 19:32:36,666 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
  2024-06-26 19:32:37,541 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.78000000
  2024-06-26 19:32:38,670 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
  2024-06-26 19:32:39,543 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.78000000
  
  ...
  2024-06-26 19:32:42,760 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
  2024-06-26 19:32:43,569 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.78000000
  2024-06-26 19:32:44,763 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
  2024-06-26 19:32:45,575 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.78000000
  2024-06-26 19:32:46,765 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
  2024-06-26 19:32:47,579 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.78000000
  2024-06-26 19:32:48,775 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.74000000
  2024-06-26 19:32:49,585 - 15 - hummingbot.strategy_v2.executors.position_executor.position_executor - INFO - Waiting for close order to be filled --> Filled amount: 0 | Open amount: 0.78000000
  2024-06-26 19:32:50,675 - 15 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - NETWORK - Error submitting buy MARKET order to Binance for 0.78000000 AVAX-USDT NaN.
  Traceback (most recent call last):
    File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
      await self._place_order_and_process_update(order=order, **kwargs,)
    File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
      exchange_order_id, update_timestamp = await self._place_order(
    File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_exchange.py", line 198, in _place_order
      order_result = await self._api_post(
    File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 867, in _api_post
      return await self._api_request(*args, **kwargs)
    File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 927, in _api_request
      raise last_exception
    File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
      request_result = await rest_assistant.execute_request(
    File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
      response = await self.execute_request_and_get_response(
    File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
      raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
  OSError: Error executing request POST https://api.binance.com/api/v3/order. HTTP status is 400. Error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
  ```
  - Observed failed to submit market order due to `OSError: **Error** executing request POST https://api.binance.com/api/v3/order. HTTP status is 400. **Error**: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}`
      - This resulted to retry 1/10 only once
      - This event seems to have retired
  - This close limit order was supposed to be cancelled but was filled `2024-06-26 19:32:34,516` which closes the executor
    ```
    2024-06-26 22:30:40,047 - 15 - hummingbot.connector.client_order_tracker - INFO - The BUY order x-XEKWYICXBAXUT61bcfd9c84eb36c5b amounting to 0.78000000/0.78000000 AVAX has been filled.
    2024-06-26 22:30:40,049 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719441040.0, "order_id": "x-XEKWYICXBAXUT61bcfd9c84eb36c5b", "trading_pair": "AVAX-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "26.04000000", "amount": "0.78000000", "trade_fee": {"percent": "0", "percent_token": "AVAX", "flat_fees": [{"token": "AVAX", "amount": "0.00078000"}]}, "exchange_trade_id": "280640425", "exchange_order_id": "3208106752", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "binance"}
    2024-06-26 22:30:40,087 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719441040.0, "order_id": "x-XEKWYICXBAXUT61bcfd9c84eb36c5b", "base_asset": "AVAX", "quote_asset": "USDT", "base_asset_amount": "0.78000000", "quote_asset_amount": "20.3112000000000000", "order_type": "OrderType.LIMIT", "exchange_order_id": "3208106752", "event_name": "BuyOrderCompletedEvent", "event_source": "binance"}
    2024-06-26 22:30:40,087 - 15 - hummingbot.connector.client_order_tracker - INFO - BUY order x-XEKWYICXBAXUT61bcfd9c84eb36c5b completely filled.
    ```

---

Cancelling two limit orders but got binance network disconnected
```

# creating/created orders 
2024-06-26 19:16:27,233 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating AVAX-USDT buy order: price: 25.96274999999999999454082522 amount: 0.7891230658558427333533853115.
2024-06-26 19:16:27,393 - 15 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-XEKWYICXBAXUT61bcfd9d7a9b46c5b for 0.78000000 AVAX-USDT.
2024-06-26 19:16:27,407 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719429387.0, "type": "OrderType.LIMIT", "trading_pair": "AVAX-USDT", "amount": "0.78000000", "price": "25.96000000", "order_id": "x-XEKWYICXBAXUT61bcfd9d7a9b46c5b", "creation_timestamp": 1719429387.0, "exchange_order_id": "3208106809", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "binance"}
2024-06-26 19:17:09,449 - 15 - hummingbot.strategy.script_strategy_base - INFO - (AVAX-USDT) Canceling the limit order x-XEKWYICXBAXUT61bcfa6b3f11e6c5b. [clock=2024-06-26 19:17:09+00:00]
2024-06-26 19:17:10,455 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating AVAX-USDT buy order: price: 26.08392499999999999727145344 amount: 0.7480544098310059791113544580.
2024-06-26 19:17:10,585 - 15 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order x-XEKWYICXBAXUT61bcfdc6b2d856c5b for 0.74000000 AVAX-USDT.
2024-06-26 19:17:10,599 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719429430.0, "type": "OrderType.LIMIT", "trading_pair": "AVAX-USDT", "amount": "0.74000000", "price": "26.08000000", "order_id": "x-XEKWYICXBAXUT61bcfdc6b2d856c5b", "creation_timestamp": 1719429430.0, "exchange_order_id": "3208109570", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "binance"}


# cancelling 2 buy limit orders to open executor 
# failed to cancel XEKWYICXBAXUT61bcfdc6b2d856c5b 
# failed to cancel XEKWYICXBAXUT61bcfd9d7a9b46c5b
2024-06-26 19:32:41,549 - 15 - hummingbot.strategy.script_strategy_base - INFO - (AVAX-USDT) Canceling the limit order x-XEKWYICXBAXUT61bcfd9d7a9b46c5b. [clock=2024-06-26 19:32:41+00:00]
2024-06-26 19:32:41,549 - 15 - hummingbot.strategy.script_strategy_base - INFO - (AVAX-USDT) Canceling the limit order x-XEKWYICXBAXUT61bcfdc6b2d856c5b. [clock=2024-06-26 19:32:41+00:00]

...
# failed to cancel orderXEKWYICXBAXUT61bcfd9d7a9b46c5b
2024-06-26 19:32:57,362 - 15 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - Failed to cancel order x-XEKWYICXBAXUT61bcfd9d7a9b46c5b
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 520, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 540, in _execute_order_cancel_and_process_update
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_exchange.py", line 221, in _place_cancel
    cancel_result = await self._api_delete(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 875, in _api_delete
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 927, in _api_request
    raise last_exception
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request DELETE https://api.binance.com/api/v3/order. HTTP status is 400. Error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

...
# failed to cancel order XEKWYICXBAXUT61bcfdc6b2d856c5b
024-06-26 19:33:07,378 - 15 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - Failed to cancel order x-XEKWYICXBAXUT61bcfdc6b2d856c5b
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 520, in _execute_order_cancel
    cancelled = await self._execute_order_cancel_and_process_update(order=order)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 540, in _execute_order_cancel_and_process_update
    cancelled = await self._place_cancel(order.client_order_id, order)
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_exchange.py", line 221, in _place_cancel
    cancel_result = await self._api_delete(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 875, in _api_delete
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 927, in _api_request
    raise last_exception
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request DELETE https://api.binance.com/api/v3/order. HTTP status is 400. Error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

...
# buy order that was supposed to be cancelled @2024-06-26 19:32:41,549 has been filled after 3hrs
2024-06-26 22:23:13,126 - 15 - hummingbot.connector.client_order_tracker - INFO - The BUY order x-XEKWYICXBAXUT61bcfdc6b2d856c5b amounting to 0.74000000/0.74000000 AVAX has been filled.
2024-06-26 22:23:13,128 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719440593.0, "order_id": "x-XEKWYICXBAXUT61bcfdc6b2d856c5b", "trading_pair": "AVAX-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "26.08000000", "amount": "0.74000000", "trade_fee": {"percent": "0", "percent_token": "AVAX", "flat_fees": [{"token": "AVAX", "amount": "0.00074000"}]}, "exchange_trade_id": "280640170", "exchange_order_id": "3208109570", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "binance"}
2024-06-26 22:23:13,178 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719440593.0, "order_id": "x-XEKWYICXBAXUT61bcfdc6b2d856c5b", "base_asset": "AVAX", "quote_asset": "USDT", "base_asset_amount": "0.74000000", "quote_asset_amount": "19.2992000000000000", "order_type": "OrderType.LIMIT", "exchange_order_id": "3208109570", "event_name": "BuyOrderCompletedEvent", "event_source": "binance"}
2024-06-26 22:23:13,178 - 15 - hummingbot.connector.client_order_tracker - INFO - BUY order x-XEKWYICXBAXUT61bcfdc6b2d856c5b completely filled.

...
# buy XEKWYICXBAXUT61bcfd9c84eb36c5b that should be cancelled was filled after 3hrs
2024-06-26 22:30:40,047 - 15 - hummingbot.connector.client_order_tracker - INFO - The BUY order x-XEKWYICXBAXUT61bcfd9c84eb36c5b amounting to 0.78000000/0.78000000 AVAX has been filled.
2024-06-26 22:30:40,049 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719441040.0, "order_id": "x-XEKWYICXBAXUT61bcfd9c84eb36c5b", "trading_pair": "AVAX-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT", "price": "26.04000000", "amount": "0.78000000", "trade_fee": {"percent": "0", "percent_token": "AVAX", "flat_fees": [{"token": "AVAX", "amount": "0.00078000"}]}, "exchange_trade_id": "280640425", "exchange_order_id": "3208106752", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "binance"}
2024-06-26 22:30:40,087 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1719441040.0, "order_id": "x-XEKWYICXBAXUT61bcfd9c84eb36c5b", "base_asset": "AVAX", "quote_asset": "USDT", "base_asset_amount": "0.78000000", "quote_asset_amount": "20.3112000000000000", "order_type": "OrderType.LIMIT", "exchange_order_id": "3208106752", "event_name": "BuyOrderCompletedEvent", "event_source": "binance"}
2024-06-26 22:30:40,087 - 15 - hummingbot.connector.client_order_tracker - INFO - BUY order x-XEKWYICXBAXUT61bcfd9c84eb36c5b completely filled.
```
  - Observed from the logs that there was failed to cancel order occurred, therefore the limit order was active on the exchange
  - Observed when tracing what happened to the order id, it was filled after 3hrs. Did not create a close order so it seems my base asset has increased
  - This resulted on some orders submitted returning failed due to `"code":-2010,"msg":"Account has insufficient balance for requested action."`

---

Creating orders when binance network disconnected
```
# there are creating orders to open executor
2024-06-26 19:32:41,554 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating AVAX-USDT sell order: price: 26.45662500000000000273999574 amount: 0.7375164111806106270028865443.
2024-06-26 19:32:41,555 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating AVAX-USDT sell order: price: 26.58825000000000000547999146 amount: 0.7705586068300388674260242465.
2024-06-26 19:32:42,572 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating AVAX-USDT buy order: price: 26.20332499999999999725896343 amount: 0.7446457700292318869338962262.
2024-06-26 19:32:42,573 - 15 - hummingbot.strategy.script_strategy_base - INFO - Creating AVAX-USDT buy order: price: 26.07164999999999999451792687 amount: 0.7858269376141817232653324395.

...
# This timestamp is where it started to return failed to submit limit order for the orders above 
2024-06-26 19:33:07,438 - 15 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - NETWORK - Error submitting sell LIMIT order to Binance for 0.73000000 AVAX-USDT 26.45000000.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 452, in _create_order
    await self._place_order_and_process_update(order=order, **kwargs,)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 469, in _place_order_and_process_update
    exchange_order_id, update_timestamp = await self._place_order(
  File "/home/hummingbot/hummingbot/connector/exchange/binance/binance_exchange.py", line 198, in _place_order
    order_result = await self._api_post(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 867, in _api_post
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 927, in _api_request
    raise last_exception
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request POST https://api.binance.com/api/v3/order. HTTP status is 400. Error: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
```
  - The retry already exceed 11/10 attempts
  - It was able to start creating orders successfully at `2024-06-26 19:33:41,968`

### Steps to reproduce

1.  Setup a pmm_simple controller with multiple order levels with spreads enough to trigger order fill
2. Run the bot for couple of hours or overnight
3. Review the logs and compare on the scenarios above 

### Release version

dev-1.29.0

### Type of installation

Source

### Attach required files

[06272024_binance_pmm_simple.zip](https://github.com/user-attachments/files/16014288/06272024_binance_pmm_simple.zip)

**Comment by rapcmia** [comment]
Ran bot over the weekend and not able to reproduce using setup:
```
id: EmHdKhWPN2KnvqEeLzNtuHete7udQb9q8tT3oA4iMHnt
controller_name: pmm_simple
controller_type: market_making
manual_kill_switch: null
candles_config: []
connector_name: binance
trading_pair: NOT-USDT
total_amount_quote: 60.0
buy_spreads:
- 0.01
- 0.015
sell_spreads:
- 0.01
- 0.015
buy_amounts_pct: null
sell_amounts_pct: null
executor_refresh_time: 3600
cooldown_time: 15
leverage: 1
position_mode: HEDGE
stop_loss: 0.015
take_profit: 0.01
time_limit: 3660
take_profit_order_type: 2
trailing_stop:
  activation_price: 0.015
  trailing_delta: 0.003
```

**Comment by aldi7th** [comment]
I also often encounter this problem, it seems to happen especially easily when retrying, it's quite frustrating.
