### ISSUE TITLE
Non-hexadecimal digit found

### ISSUE THREAD

**Issue by s1korrrr** [hummingbot/hummingbot#7109]
### Describe the bug

Random case whenever i run the bot.

Traceback (most recent call last):
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 127, in call_async
    return await self.schedule_async_call(coro, timeout_seconds, app_warning_msg=app_warning_msg)
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 116, in schedule_async_call
    return await fut
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/core/utils/async_call_scheduler.py", line 79, in _coro_scheduler
    fut.set_result(await coro)
  File "/Users/xxx/anaconda3/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/client/config/security.py", line 65, in decrypt_all
    cls.decrypt_connector_config(file)
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/client/config/security.py", line 71, in decrypt_connector_config
    cls._secure_configs[connector_name] = load_connector_config_map_from_file(file_path)
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/client/config/config_helpers.py", line 668, in load_connector_config_map_from_file
    _load_yml_data_into_map(config_data, config_map)
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/client/config/config_helpers.py", line 750, in _load_yml_data_into_map
    config_validation_errors = cm.validate_model()  # try coercing values to appropriate type
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/client/config/config_helpers.py", line 199, in validate_model
    self.decrypt_all_secure_data()
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/client/config/config_helpers.py", line 237, in decrypt_all_secure_data
    decrypted_value = Security.secrets_manager.decrypt_secret_value(attr=traversal_item.attr, value=value)
  File "/Users/xxx/dev/trading/hummingbot/hummingbot/client/config/config_crypt.py", line 59, in decrypt_secret_value
    value = binascii.unhexlify(value)
binascii.Error: Non-hexadecimal digit found

### Steps to reproduce

1. ./install
2. ./compile
3. Add the keys (connect binance...)
4. ./start 

### Release version

any

### Type of installation

Source

**Comment by rapcmia** [comment]
Please refer to this ticket https://github.com/hummingbot/hummingbot/issues/6587
