### ISSUE TITLE
pre_commit.errors.FatalError: git failed. Is it installed, and are you in a Git repository directory?

### ISSUE THREAD

**Issue by hack3rcon** [hummingbot/hummingbot#7176]
Hello,
I want to install the Hummingbot from the source code. I have two questions:

1- Should I run all the commands as a normal user or root user?

2- I did **./install,** but I got the following error:

```
pre-commit.log
### version information

pre-commit version: 2.18.1
git --version: git version 2.39.2
sys.version:
    3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
sys.executable: /home/docki/miniconda3/envs/hummingbot/bin/python
os.name: posix
sys.platform: linux

### error information

An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?

Traceback (most recent call last):
  File "/home/docki/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pre_commit/git.py", line 58, in get_root
    cmd_output('git', 'rev-parse', '--show-cdup')[1].strip(),
  File "/home/docki/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pre_commit/util.py", line 152, in cmd_output
    returncode, stdout_b, stderr_b = cmd_output_b(*cmd, **kwargs)
  File "/home/docki/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'rev-parse', '--show-cdup')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: detected dubious ownership in repository at '/home/docki/Containers/hummingbot'
    To add an exception for this directory, call:
    
    	git config --global --add safe.directory /home/docki/Containers/hummingbot
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docki/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/docki/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pre_commit/main.py", line 326, in main
    _adjust_args_and_chdir(args)
  File "/home/docki/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pre_commit/main.py", line 143, in _adjust_args_and_chdir
    toplevel = git.get_root()
  File "/home/docki/miniconda3/envs/hummingbot/lib/python3.10/site-packages/pre_commit/git.py", line 64, in get_root
    raise FatalError(
pre_commit.errors.FatalError: git failed. Is it installed, and are you in a Git repository directory?
```
Where is the problem?

Thank you.

**Comment by hack3rcon** [comment]
Hi,
I solved that error with `git config --global --add safe.directory /home/docki/Containers/hummingbot` command, but I got the following error:
```
Requirement already satisfied: objgraph in /home/docki/miniconda3/envs/hummingbot/lib/python3.10/site-packages (3.6.1)
An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '.git/hooks/pre-commit'
Check the log at /home/docki/.cache/pre-commit/pre-commit.log
```
Any idea?

**Comment by hack3rcon** [comment]
Hi,
The problem was related to the permission. I had cloned the repository with the root account.
