### ISSUE TITLE
Mexc - KeyError["NET-USDT"], I found some issue tried to solve this problem but it did not work (I have already fetch the newest branch)

### ISSUE THREAD

**Issue by CodeCat-maker** [hummingbot/hummingbot#7181]
### Describe the bug

I tried the XEMM v1 and v2 version, they both have this bug.
trading_pair: NET-USDT

```shell
2024-08-21 14:05:42,376 - 15 - hummingbot.connector.exchange.mexc.mexc_exchange.MexcExchange - WARNING - Could not fetch account updates from Mexc. Check API key and network connection.
2024-08-21 14:05:42,963 - 15 - hummingbot.connector.exchange.mexc.mexc_api_order_book_data_source.MexcAPIOrderBookDataSource - ERROR - Unexpected error occurred subscribing to order book trading and delta streams...
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange/mexc/mexc_api_order_book_data_source.py", line 76, in _subscribe_channels
    symbol = await self._connector.exchange_symbol_associated_to_pair(trading_pair=trading_pair)
  File "hummingbot/connector/exchange_base.pyx", line 97, in exchange_symbol_associated_to_pair
    return symbol_map.inverse[trading_pair]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in __getitem__
    return self._fwdm[key]
KeyError: 'NET-USDT'
```

### Steps to reproduce

1. 
2. 
3. 

### Release version

2.0.0

### Type of installation

Docker

**Comment by PtrckM** [comment]
use this fix https://github.com/hummingbot/hummingbot/pull/7175

**Comment by nikspz** [comment]
fix merged to latest development and release 2.0.1
