### ISSUE TITLE
Time_Synchronizer Error getting server time

### ISSUE THREAD

**Issue by archnerd420** [hummingbot/hummingbot#7242]
### Describe the bug

Hummingbot's time synchronizer returns errors on any system. Fresh install or old, using version 1.x to 2.0.1, the logs fill up quickly with time synchronizer errors. 

This appears to be due to my location in the USA, Hummingbot using Binance".com" for time, and Binance.com blocking the USA. 

Quote from traceback:
> "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."

I found a way for USA local Users to patch their systems - change line 4 of hummingbot/connector/exchange/binance/binance_constants.py to `DEFAULT_DOMAIN = "us"`

It seems that some level of domain auto-detect may exist but is non-working.

### Steps to reproduce

1. Be in the United States
2. Follow the official Hummingbot Installation Guide
3. Launch Hummingbot
4. Time synchronizer errors will appear frequently in the output window and logs.

### Release version

2.0.1

### Type of installation

Source

### Attach required files

From logs.hummingbot.log:
`2024-09-29 12:35:21,565 - 3057 - hummingbot.connector.time_synchronizer - NETWORK - Error getting server time.
Traceback (most recent call last):
  File "/home/jack/build/hummingbot/hummingbot/connector/time_synchronizer.py", line 66, in update_server_time_offset_with_time_provider
    server_time_ms: float = await time_provider
  File "/home/jack/build/hummingbot/hummingbot/connector/exchange/binance/binance_web_utils.py", line 69, in get_current_server_time
    response = await rest_assistant.execute_request(
  File "/home/jack/build/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/jack/build/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.com/api/v3/time. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}
2024-09-29 12:35:21,567 - 3057 - hummingbot.connector.time_synchronizer - WARNING - Could not refresh server time. Check network connection.
2024-09-29 12:35:21,737 - 3057 - hummingbot.connector.exchange.binance.binance_exchange.BinanceExchange - ERROR - There was an error requesting exchange info.
Traceback (most recent call last):
  File "/home/jack/build/hummingbot/hummingbot/connector/exchange_py_base.py", line 1074, in _initialize_trading_pair_symbol_map
    exchange_info = await self._make_trading_pairs_request()
  File "/home/jack/build/hummingbot/hummingbot/connector/exchange_py_base.py", line 1087, in _make_trading_pairs_request
    exchange_info = await self._api_get(path_url=self.trading_pairs_request_path)
  File "/home/jack/build/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/jack/build/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/jack/build/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/jack/build/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.binance.com/api/v3/exchangeInfo. HTTP status is 451. Error: {
  "code": 0,
  "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error."
}`

**Comment by joeyfigaro** [comment]
What was the reasoning behind using binance for synchronizing time?

**Comment by archnerd420** [comment]
Binance is the default time server. I'd rather use the exchanges I'm trading on. I have not found the config file with the time server variable yet.

**Comment by cardosofede** [comment]
@archnerd420 I think that is not going to block you from trading but maybe the issue is that the rate oracle is configured for hummingbot. Try in the terminal: config rate_oracle_source and change it for one exchange allowed in your country.
the message will also appear when starting hummingbot because binance is listed as a paper trade compatible exchange, so by default will try to get all the data from the available pairs to make the comparison, if you don't want that, go to the conf_client.yml and remove from paper trade binance.

**Comment by realsetvin** [comment]
> [@archnerd420](https://github.com/archnerd420) I think that is not going to block you from trading but maybe the issue is that the rate oracle is configured for hummingbot. Try in the terminal: config rate_oracle_source and change it for one exchange allowed in your country. the message will also appear when starting hummingbot because binance is listed as a paper trade compatible exchange, so by default will try to get all the data from the available pairs to make the comparison, if you don't want that, go to the conf_client.yml and remove from paper trade binance.

shouldnt the application be smart enough to detect which region its being operated in and adjust accordingly?
