### ISSUE TITLE
Dexalot - The websocket connection was closed

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#7325]
### Describe the bug

When reviewing a dexalot instance from dashboard that has been running over 2 days, observed these instance of errors `The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1000 msg data: None)` and seem to stopped the connection from hummingbot and dexalot exchange 

```
2024-12-05 06:39:49,530 - 15 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT BUY order 0xb8bd24f7cfec0a9063ad4e2d0b390369fd96d70e9ee6316e3bb63264217f8aba for 0.485 AVAX-USDC at 51.473.
2024-12-05 06:39:49,538 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733380789.0, "type": "OrderType.LIMIT", "trading_pair": "AVAX-USDC", "amount": "0.485", "price": "51.473", "order_id": "0xb8bd24f7cfec0a9063ad4e2d0b390369fd96d70e9ee6316e3bb63264217f8aba", "creation_timestamp": 1733380782.0, "exchange_order_id": "0x000000000000000000000000000000000000000000000000000000006feff327", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "dexalot"}
2024-12-05 06:41:12,007 - 15 - hummingbot.strategy.script_strategy_base - INFO - Skipping rebalance due a low amount to sell that may cause future imbalance
.... trimmed from logs 

024-12-05 06:52:41,342 - 15 - hummingbot.connector.exchange.dexalot.dexalot_api_user_stream_data_source.DexalotAPIUserStreamDataSource - WARNING - The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1000 msg data: None)
2024-12-05 06:52:41,541 - 15 - hummingbot.connector.exchange.dexalot.dexalot_api_order_book_data_source.DexalotAPIOrderBookDataSource - WARNING - The websocket connection was closed (WS error: )
2024-12-05 06:52:41,669 - 15 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking...
2024-12-05 06:52:59,406 - 15 - hummingbot.connector.exchange.dexalot.dexalot_api_order_book_data_source.DexalotAPIOrderBookDataSource - ERROR - Unexpected error occurred when listening to order book streams. Retrying in 5 seconds...
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1345, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 964, in _resolve_host
    await future
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1020, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/resolver.py", line 36, in resolve
    infos = await self._loop.getaddrinfo(
  File "/opt/conda/envs/hummingbot/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/opt/conda/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.10/socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/data_type/order_book_tracker_data_source.py", line 78, in listen_for_subscriptions
    ws: WSAssistant = await self._connected_websocket_assistant()
  File "/home/hummingbot/hummingbot/connector/exchange/dexalot/dexalot_api_order_book_data_source.py", line 78, in _connected_websocket_assistant
    await ws.connect(ws_url=url, ping_timeout=CONSTANTS.WS_HEARTBEAT_TIME_INTERVAL)
  File "/home/hummingbot/hummingbot/core/web_assistant/ws_assistant.py", line 45, in connect
    await self._connection.connect(
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/ws_connection.py", line 39, in connect
    self._connection = await self._client_session.ws_connect(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 1002, in _ws_connect
    resp = await self.request(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1351, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host api.dexalot.com:443 ssl:default [Temporary failure in name resolution]
2024-12-05 06:52:41,342 - 15 - hummingbot.connector.exchange.dexalot.dexalot_api_user_stream_data_source.DexalotAPIUserStreamDataSource - WARNING - The websocket connection was closed (The WS connection was closed unexpectedly. Close code = 1000 msg data: None)
2024-12-05 06:52:41,541 - 15 - hummingbot.connector.exchange.dexalot.dexalot_api_order_book_data_source.DexalotAPIOrderBookDataSource - WARNING - The websocket connection was closed (WS error: )
2024-12-05 06:52:41,669 - 15 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking...
.... trimmed from logs

2024-12-05 06:56:20,652 - 15 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-12-05 06:56:25,503 - 15 - hummingbot.connector.exchange.dexalot.dexalot_api_order_book_data_source.DexalotAPIOrderBookDataSource - INFO - Subscribed to public order book and trade channels...
2024-12-05 06:56:25,726 - 15 - hummingbot.connector.exchange.dexalot.dexalot_api_user_stream_data_source.DexalotAPIUserStreamDataSource - INFO - Subscribed to private order changes and trade updates channels...
2024-12-05 06:56:35,128 - 15 - hummingbot.connector.exchange.dexalot.dexalot_exchange.DexalotExchange - INFO - Network status has changed to NetworkStatus.CONNECTED. Starting networking...
2024-12-05 06:56:35,129 - 15 - hummingbot.core.data_type.order_book_tracker - INFO - Initialized order book for AVAX-USDC. 1/1 completed.
2024-12-05 06:56:35,908 - 15 - hummingbot.connector.exchange.dexalot.dexalot_exchange.DexalotExchange - WARNING - Ask orderbook for AVAX-USDC is empty.
2024-12-05 06:56:35,908 - 15 - hummingbot.connector.exchange.dexalot.dexalot_exchange.DexalotExchange - WARNING - Bid orderbook for AVAX-USDC is empty.
.... trimmed from logs

2024-12-05 07:39:43,248 - 15 - hummingbot.strategy.script_strategy_base - INFO - (AVAX-USDC) Canceling the limit order 0xb8bd24f7cfec0a9063ad4e2d0b390369fd96d70e9ee6316e3bb63264217f8aba. [clock=2024-12-05 07:39:43+00:00]
2024-12-05 07:39:49,626 - 15 - hummingbot.connector.exchange.dexalot.dexalot_exchange.DexalotExchange - WARNING - {'code': -32000, 'message': 'nonce too low: next nonce 13175, tx nonce 13174'} Attempt cancelAddList 1/5
2024-12-05 07:39:49,941 - 15 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1733384389.0, "order_id": "0xb8bd24f7cfec0a9063ad4e2d0b390369fd96d70e9ee6316e3bb63264217f8aba", "exchange_order_id": "0x000000000000000000000000000000000000000000000000000000006feff327", "event_name": "OrderCancelledEvent", "event_source": "dexalot"}
2024-12-05 07:39:49,941 - 15 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order 0xb8bd24f7cfec0a9063ad4e2d0b390369fd96d70e9ee6316e3bb63264217f8aba.
```
  - It seems getting timeouts or disconnection from dexalot when an order is placed for the longest time
  - Observed when the hummingbot and dexalot return connection, it spams orderbook for bid and ask for the selected market is empty in which it recovers after couple of minutes ❌ 
  - Gap between order created and cancellation is around 3600s which is correct ✅
  - There has no orders affected nor stuck orders on exchange ✅ 

Note: The instance where this log was taken is still running as of the time of this issue was reported. Monitoring for possible issues on orders when hit sudden wss disconnection

### Steps to reproduce

1.  Setup a bot on dashboard or standalone hummingbot client 
2.  Use dexalot as connecto on v2 strategies 
3.  Setup a config with long refresh time (on this test its using 3600s)

### Release version

dev-2.2

### Type of installation

Source

### Attach required files

[logs_dexalot-avaxusdc-2024.12.03_23.26.log](https://github.com/user-attachments/files/18024525/logs_dexalot-avaxusdc-2024.12.03_23.26.log)

**Comment by rapcmia** [comment]
When hummingbot and dexalot connection closed due to this issue, observed the following errors occurred:

The connector returns failed to update balances ❌ 
```
2024-12-03 16:10:10,562 - 15 - hummingbot.connector.exchange.dexalot.dexalot_exchange.DexalotExchange - WARNING - Failed to update balances. Error: 
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1345, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 989, in _resolve_host
    return await asyncio.shield(resolved_host_task)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 939, in _update_all_balances
    await self._update_balances()
  File "/home/hummingbot/hummingbot/connector/exchange/dexalot/dexalot_exchange.py", line 828, in _update_balances
    self._account_balances, self._account_available_balances = await self._tx_client.get_balances(
  File "/home/hummingbot/hummingbot/connector/exchange/dexalot/data_sources/dexalot_data_source.py", line 63, in get_balances
    balances = await self.portfolio_sub_manager.functions.getBalances(Account.from_key(self._private_key).address, 50).call()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/contract/async_contract.py", line 307, in call
    return await async_call_contract_function(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/contract/utils.py", line 305, in async_call_contract_function
    return_data = await async_w3.eth.call(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/eth/async_eth.py", line 272, in call
    return await self._durin_call(transaction, block_identifier, state_override)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/eth/async_eth.py", line 291, in _durin_call
    return await self._call(transaction, block_identifier, state_override)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/module.py", line 118, in caller
    result = await async_w3.manager.coro_request(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/manager.py", line 344, in coro_request
    response = await self._coro_make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/manager.py", line 224, in _coro_make_request
    return await request_func(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/gas_price_strategy.py", line 126, in middleware
    return await make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/names.py", line 139, in middleware
    return await make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/attrdict.py", line 69, in middleware
    response = await make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/formatting.py", line 178, in middleware
    await async_web3_formatters_builder(async_w3, method),
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/validation.py", line 161, in async_build_method_validators
    w3_chain_id = await async_w3.eth.chain_id
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/eth/async_eth.py", line 155, in chain_id
    return await self._chain_id()
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/module.py", line 118, in caller
    result = await async_w3.manager.coro_request(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/manager.py", line 344, in coro_request
    response = await self._coro_make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/manager.py", line 224, in _coro_make_request
    return await request_func(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/gas_price_strategy.py", line 126, in middleware
    return await make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/names.py", line 139, in middleware
    return await make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/attrdict.py", line 69, in middleware
    response = await make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/formatting.py", line 185, in middleware
    response = await make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/buffered_gas_estimate.py", line 58, in middleware
    return await make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/formatting.py", line 185, in middleware
    response = await make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/middleware/exception_retry_request.py", line 167, in middleware
    return await make_request(method, params)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/providers/async_rpc.py", line 91, in make_request
    raw_response = await async_make_post_request(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/_utils/request.py", line 241, in async_make_post_request
    response = await async_get_response_from_post_request(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/web3/_utils/request.py", line 234, in async_get_response_from_post_request
    response = await session.post(endpoint_uri, *args, **kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 607, in _request
    with timer:
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/helpers.py", line 671, in __exit__
    raise asyncio.TimeoutError from exc_val
asyncio.exceptions.TimeoutError
2024-12-03 16:10:11,154 - 15 - hummingbot.core.rate_oracle.rate_oracle - INFO - Network status has changed to NetworkStatus.NOT_CONNECTED. Stopping networking...
2024-12-03 16:10:12,356 - 15 - hummingbot.client.performance - WARNING - Could not find exchange rate for AVAX-USDC using binance rate oracle. PNL value will be inconsistent.
2024-12-03 16:10:14,360 - 15 - hummingbot.client.performance - WARNING - Could not find exchange rate for AVAX-USDC using binance rate oracle. PNL value will be inconsistent.
2024-12-03 16:10:16,362 - 15 - hummingbot.client.performance - WARNING - Could not find exchange rate for AVAX-USDC using binance rate oracle. PNL value will be inconsistent.
2024-12-03 16:10:16,541 - 15 - hummingbot.connector.exchange.dexalot.dexalot_api_order_book_data_source.DexalotAPIOrderBookDataSource - WARNING - The websocket connection was closed (WS error: )
```

---

Connector failed to fetch order updates ❌ 
```
2024-12-03 16:10:30,556 - 15 - hummingbot.connector.exchange.dexalot.dexalot_exchange.DexalotExchange - WARNING - Failed to fetch trade updates for order 0x4abfd7d2fc496b986bfb4a909a4125b3ba7563cbb041e079f3dab9ebe4c7f87c. Error: Cannot connect to host api.dexalot.com:443 ssl:default [Temporary failure in name resolution]
Traceback (most recent call last):
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1345, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 989, in _resolve_host
    return await asyncio.shield(resolved_host_task)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1345, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 964, in _resolve_host
    await future
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1020, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/resolver.py", line 36, in resolve
    infos = await self._loop.getaddrinfo(
  File "/opt/conda/envs/hummingbot/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/opt/conda/envs/hummingbot/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/hummingbot/lib/python3.10/socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 955, in _update_orders_fills
    trade_updates = await self._all_trade_updates_for_order(order=order)
  File "/home/hummingbot/hummingbot/connector/exchange/dexalot/dexalot_exchange.py", line 754, in _all_trade_updates_for_order
    all_fills_response = await self._api_get(
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 94, in execute_request_and_get_response
    response = await self.call(request=request, timeout=timeout)
  File "/home/hummingbot/hummingbot/core/web_assistant/rest_assistant.py", line 108, in call
    resp = await wait_for(self._connection.call(request), timeout)
  File "/opt/conda/envs/hummingbot/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/home/hummingbot/hummingbot/core/web_assistant/connections/rest_connection.py", line 10, in call
    aiohttp_resp = await self._client_session.request(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/aiohttp/connector.py", line 1351, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host api.dexalot.com:443 ssl:default [Temporary failure in name resolution]
```

[logs_dexalot-avaxusdc-2024.12.03_23.26.log.2024-12-03.log](https://github.com/user-attachments/files/18032690/logs_dexalot-avaxusdc-2024.12.03_23.26.log.2024-12-03.log)
