### ISSUE TITLE
Coinbase advanced trade - Failed to connect API Keys

### ISSUE THREAD

**Issue by nikspz** [hummingbot/hummingbot#7326]
### Describe the bug

Coinbase advanced trade - Failed to connect API Keys

### Steps to reproduce

1. Clone and install latest dev branch
2. connect coinbase_advanced_trade

Actual:
Failed to connect

```
2024-12-06 08:57:55,559 - 2101920 - hummingbot.connector.exchange.coinbase_advanced_trade.coinbase_advanced_trade_exchange.CoinbaseAdvancedTradeExchange - ERROR - Error getting all trading pairs from Coinbase Advanced Trade: Error executing request GET https://api.coinbase.com/api/v3/brokerage/products. HTTP status is 401. Error: Unauthorized
Traceback (most recent call last):
  File "/home/hbot02/nikita/coinbase6889candles/hummingbot/connector/exchange/coinbase_advanced_trade/coinbase_advanced_trade_exchange.py", line 720, in _initialize_market_assets
    products: Dict[str, Any] = await self._api_get(
  File "/home/hbot02/nikita/coinbase6889candles/hummingbot/connector/exchange/coinbase_advanced_trade/coinbase_advanced_trade_exchange.py", line 1091, in _api_get
    return await super()._api_get(*args, **kwargs)
  File "/home/hbot02/nikita/coinbase6889candles/hummingbot/connector/exchange_py_base.py", line 863, in _api_get
    return await self._api_request(*args, **kwargs)
  File "/home/hbot02/nikita/coinbase6889candles/hummingbot/connector/exchange_py_base.py", line 906, in _api_request
    request_result = await rest_assistant.execute_request(
  File "/home/hbot02/nikita/coinbase6889candles/hummingbot/core/web_assistant/rest_assistant.py", line 47, in execute_request
    response = await self.execute_request_and_get_response(
  File "/home/hbot02/nikita/coinbase6889candles/hummingbot/core/web_assistant/rest_assistant.py", line 100, in execute_request_and_get_response
    raise IOError(f"Error executing request {method.name} {url}. HTTP status is {response.status}. "
OSError: Error executing request GET https://api.coinbase.com/api/v3/brokerage/products. HTTP status is 401. Error: Unauthorized

```

![image](https://github.com/user-attachments/assets/a5d09af5-9903-4ce5-96d8-b8d3a2c73f32)

### Release version

dev-2.2.0

### Type of installation

Source

**Comment by nikspz** [comment]
![image](https://github.com/user-attachments/assets/96d739c3-9cc9-463b-8fee-b765ec7c5259)
Seems related to location
