### ISSUE TITLE
dYdX v4 - Unexpected error running clock tick

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#7330]
### Describe the bug

Setup a hummingbot client using directional_trading.bollinger_v1 on `dYdX v4 perpetual` which long and short threshold both set to `1`. At first the connector works as expected since it only supports One-way mode position and reviewed trade history got no amount doubled. 

While reviewing the log files around 22hrs time, the bot was returning a spam error of `Unexpected error running clock tick`
![image](https://github.com/user-attachments/assets/f7b5fc66-efbe-4c4d-9fa6-2bc137d9cdaa)
```
2024-12-07 18:21:19,004 - 2560561 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/home/rapcomia/hummingbot/hummingbot/dev-dydx/hummingbot/strategy/script_strategy_base.py", line 75, in tick
    self.on_tick()
  File "/home/rapcomia/hummingbot/hummingbot/dev-dydx/scripts/v2_with_controllers.py", line 83, in on_tick
    super().on_tick()
  File "/home/rapcomia/hummingbot/hummingbot/dev-dydx/hummingbot/strategy/strategy_v2_base.py", line 294, in on_tick
    self.executor_orchestrator.execute_action(action)
  File "/home/rapcomia/hummingbot/hummingbot/dev-dydx/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 102, in execute_action
    self.store_executor(action)
  File "/home/rapcomia/hummingbot/hummingbot/dev-dydx/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 168, in store_executor
    MarketsRecorder.get_instance().store_or_update_executor(executor)
  File "/home/rapcomia/hummingbot/hummingbot/dev-dydx/hummingbot/connector/markets_recorder.py", line 205, in store_or_update_executor
    serialized_config = executor.executor_info.json()
  File "pydantic/main.py", line 505, in pydantic.main.BaseModel.json
  File "/home/rapcomia/miniconda3/envs/dydx-hummingbot/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/rapcomia/miniconda3/envs/dydx-hummingbot/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/rapcomia/miniconda3/envs/dydx-hummingbot/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 88, in pydantic.json.pydantic_encoder
  File "pydantic/json.py", line 38, in pydantic.json.decimal_encoder
TypeError: '>=' not supported between instances of 'str' and 'int'
``` 
- Reviewed sqlite, all recorded executors are recorded with correct close types and orderids 
- The error continuously happened every tick while executors are created, cancelled and filled 

### Steps to reproduce

1. Setup dYdX v4 perpetual using v2 strategy, (directional_trading.bollinger_v1)
2. Run the bot for long time and check status after couple of hours 

### Release version

dev-2.2.0

### Type of installation

Source

### Attach required files

[12102024.zip](https://github.com/user-attachments/files/18079792/12102024.zip)

**Comment by ipezygj** [comment]
This looks resolved by the pydantic v1 → v2 migration and can probably be verified/closed.

**Root cause (on the v1 codebase this was filed against):** the crash is in pydantic v1's `decimal_encoder`, triggered by a **non-finite `Decimal`** in the serialized `executor_info`. `Decimal("NaN").as_tuple().exponent` is the string `'n'`, and v1's encoder does `dec_value.as_tuple().exponent >= 0`, i.e. `'n' >= 0` → exactly the reported `TypeError: '>=' not supported between instances of 'str' and 'int'`. The NaN reaches serialization via `custom_info` (the top-level `ExecutorInfo` Decimal fields are already sanitized to finite via `_safe_decimal`, but the `custom_info` dict is passed through as-is and can carry an unfilled/NaN price).

**Why it no longer reproduces on current `development`:** `MarketsRecorder.store_or_update_executor` now uses `executor_info.model_dump_json()` (pydantic v2), and v2 has no `decimal_encoder`:

```python
from decimal import Decimal
from pydantic import BaseModel
from typing import Dict

class M(BaseModel):
    custom_info: Dict

# NaN Decimal inside custom_info (the crash path): serializes cleanly in v2
print(M(custom_info={"price": Decimal("NaN")}).model_dump_json())
# -> {"custom_info":{"price":"NaN"}}   (no TypeError)
```

Typed `Decimal` fields (e.g. on the executor config) additionally can't even hold a non-finite value in v2 — they're rejected at validation (`Input should be a finite number`) — so that path is closed too.

I couldn't re-run the exact long-running dYdX v2 scenario, so it'd be worth a quick confirmation on current `development`, but the specific `decimal_encoder` crash path from the traceback no longer exists. (Minor cosmetic residual: a NaN in `custom_info` now serializes to the string `"NaN"` in the DB rather than crashing — harmless, but could be normalized to `null` if desired.)

**Comment by ipezygj** [comment]
Opened #8390 to close the residual noted above: it extends the existing `_safe_decimal` coercion to `custom_info`, so a non-finite `Decimal` (the NaN that produced the original pydantic-v1 `decimal_encoder` crash) is normalized to a finite value instead of being persisted as the string `"NaN"` — keeping `custom_info` consistent with the typed `ExecutorInfo` fields. Happy to take this one.

**Comment by ipezygj** [comment]
I'd like to claim this one — could a maintainer assign it to me?

Fix is already implemented and open as PR #8390: it sanitizes non-finite Decimals in executor `custom_info` before they reach the clock tick path, which is the root cause of the unexpected error here. Happy to address review feedback on the PR.
