### ISSUE TITLE
Dexalot - Unexpected error while retrieve rates from dexalot 

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#7335]
### Describe the bug

Ran dexalot using v2 controller for couple of days and observed that most of the time it has been returning `Unexpected error while retrieving rates from Dexalot. Check the log file for more info.`

```
024-12-11 18:15:53,657 - 15 - hummingbot.core.rate_oracle.sources.rate_source_base - ERROR - Unexpected error while retrieving rates from Dexalot. Check the log file for more info.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/utils/__init__.py", line 17, in memoize
    return cache[key]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/cachetools/ttl.py", line 82, in __getitem__
    return self.__missing__(key)
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/cachetools/cache.py", line 68, in __missing__
    raise KeyError(key)
KeyError: "((<hummingbot.core.rate_oracle.sources.dexalot_rate_source.DexalotRateSource object at 0x77b6cb5247c0>,), {'quote_token': 'USDC'})"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/core/rate_oracle/sources/dexalot_rate_source.py", line 33, in get_prices
    if Decimal(str(record["low"])) > 0 and Decimal(str(record["high"])) > 0:
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
... trimmed

# last occurence of error
2024-12-11 20:22:11,783 - 15 - hummingbot.core.rate_oracle.sources.rate_source_base - ERROR - Unexpected error while retrieving rates from Dexalot. Check the log file for more info.
```
  - Error have been occurring for around 2hrs
  - Despite error happening, the connector was able to place and cancel orders on exchange
  - Did manual cashout via dashboard ✅
      - No orders stuck on exchange

---

Observed also that while the error is happening and initiate `stop` command from dashboard (press the square icon button on upper right), it began to return unexpected errors ❌ 
  ```
  2024-12-13 04:06:26,533 - 15 - hummingbot.connector.exchange.dexalot.dexalot_exchange.DexalotExchange - ERROR - Unexpected error while processing queued individual orders
  Traceback (most recent call last):
    File "/home/hummingbot/hummingbot/connector/exchange/dexalot/dexalot_exchange.py", line 857, in _process_queued_orders
      else self._orders_processing_delta_time)
  AttributeError: 'DexalotExchange' object has no attribute '_orders_processing_delta_time'
  2024-12-13 04:06:26,549 - 15 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: 'NoneType' object has no attribute 'tick_size'
  Traceback (most recent call last):
    File "/home/hummingbot/hummingbot/connector/exchange/dexalot/dexalot_exchange.py", line 857, in _process_queued_orders
      else self._orders_processing_delta_time)
  AttributeError: 'DexalotExchange' object has no attribute '_orders_processing_delta_time'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
      return await c
    File "/home/hummingbot/hummingbot/connector/exchange/dexalot/dexalot_exchange.py", line 865, in _process_queued_orders
      await self._sleep(self.clock.tick_size * 0.5)
  AttributeError: 'NoneType' object has no attribute 'tick_size'
  ```

### Steps to reproduce

1.  Import the attached controller and scripts
2. Deploy a bot using dashboard 
3. Manually change the `rate_oracle_source` to dexalot

Note: How to change rate oracle from Binance to Dexalot ❗ 
  1. Go to instance page, select the dexalot container and stop active controller 
  2. Go to terminal, attach the docker container using `docker attach ..` command
  3. Run `config rate_oracle_source` and select `dexalot`
  4. Run `config global_token.global_token_name` set to `USDC`
  5. Check conf_client.yml on `./bots/instance/hummingbot_container_name`
 
![image](https://github.com/user-attachments/assets/9c652b12-fe1d-45c7-9f84-de6e9c1ac308)

### Release version

dev-2.2.0

### Type of installation

Source

### Attach required files

[hummingbot-dexalot_balance_test-2024.12.12_02.14.zip](https://github.com/user-attachments/files/18122441/hummingbot-dexalot_balance_test-2024.12.12_02.14.zip)

**Comment by nikspz** [comment]
- Sponsor: HB Foundation connector pots (Dexalot Sponsored)
- Bounty amount: 125 USDC
- Developer portion: 100 USDC

**Comment by isreallee82** [comment]
can i fix this @nikspz

**Comment by jaykayudo** [comment]
Can i work on this? @nikspz

**Comment by nikspz** [comment]
blocked with https://github.com/hummingbot/hummingbot/issues/7378

**Comment by jeffmarcilliat** [comment]
I'd like to work on this bug fix. The issue appears to be:

1. `decimal.InvalidOperation` in `dexalot_rate_source.py:33` - need to add validation for malformed decimal values from the API response
2. Missing `_orders_processing_delta_time` attribute in `DexalotExchange`
3. Null clock reference during shutdown

I'll submit a PR with fixes for these issues.

**Comment by divol89** [comment]
I am claiming this bug bounty. I have identified the root causes and can provide a fix within 2-3 days.

Root Causes:
1. Decimal conversion error when API returns null/invalid price values
2. Missing attribute initialization in DexalotExchange class
3. NoneType error when clock is not yet initialized

Proposed Solution:
- Add null checks before Decimal conversion in get_prices()
- Initialize missing attributes in __init__
- Add guard clauses for uninitialized dependencies

ETA: 2-3 days for PR with fixes and tests

I am an active contributor to the Hummingbot ecosystem (claimed EVEDEX connector bounty #7810). Ready to work on this!

**Comment by divol89** [comment]
Hi! I'd like to work on this Dexalot rate fix. I've reviewed the error logs and understand the issue with Decimal conversion and the missing attributes. Can I take this bounty?

**Comment by divol89** [comment]
I'd like to work on this Dexalot rate fix bounty. I can investigate and fix the rate retrieval error. Please assign this to me so I can start debugging.

**Comment by divol89** [comment]
I would like to work on this bounty. I can fix the decimal conversion error and the missing attribute issue. ETA 24-48 hours.

**Comment by nikspz** [comment]
> I would like to work on this bounty. I can fix the decimal conversion error and the missing attribute issue. ETA 24-48 hours.

This bounty is closed

**Comment by keys668** [comment]
"Hi team, I'm a quantitative developer with extensive Python experience. Looking at the traceback, this is clearly a decimal.InvalidOperation caused by record["low"] returning None or an empty string from the Dexalot API, which crashes when cast to Decimal.

I can implement a robust safe-parsing logic (handling None and catching InvalidOperation) to bypass these dirty records. I can submit a clean PR to fix this within the next 12 hours. Could you assign this to me?"

**Comment by ivahelfenstein-max** [comment]
Hi @nikspz @fengtality — I've submitted PR #8129 which fixes the Dexalot rate source bug described in this issue.

**Fixes implemented:**
- **Bug 1**: `decimal.InvalidOperation` crash when Dexalot API returns `None` values for price fields (now skips invalid records)
- **Bug 2**: Missing `_orders_processing_delta_time` attribute on `DexalotExchange` class (added initialization)

The fix is minimal and targeted. I'd appreciate assignment to this bounty if it's still open. Happy to address any review feedback.

PR: https://github.com/hummingbot/hummingbot/pull/8129

**Comment by xyaz1313** [comment]
Fixed in #8176

**Root cause:** `Decimal(str(record["low"]))` crashes when the API returns None, empty string, or non-numeric values for `low`/`high` fields.

**Fix:** Added validation and try/except around Decimal conversion in `dexalot_rate_source.py`. Invalid records are now gracefully skipped instead of crashing the entire rate fetch.

Test case added to cover None, empty string, and 'N/A' edge cases.

**Comment by iMENGiCHAO** [comment]
## 🎯 Bounty Submission I've submitted a PR that fixes both issues reported in #7335: - **PR #8196**: Fix Dexalot exchange AttributeError and rate source data parsing errors ### Fixes Applied 1. **AttributeError**: Added missing `_orders_processing_delta_time` initialization 2. **InvalidOperation**: Added validation for empty/null/invalid price data with proper exception handling ### Testing The fix handles edge cases (empty, null, None, non-numeric values) and skips invalid records gracefully. Ready for review! @hummingbot/maintainers

**Comment by rapcmia** [comment]
Retested this issue on development branch and not able to reproduce:
- start v2 strategy with dexalot then stop after few trades ok 
- start v2 strategy with dexalot and left it with filled orders for couple of hours then set `manual_cashout` to true ok 

If this issue appears again, will reopen and share log files to investigate
