### ISSUE TITLE
Strategy v2 - Unexpected error clock tick due to TypeError

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#7340]
### Describe the bug

When monitoring connector performance using grid_strike, observed an instance where it returned the `unexpected error running clock tick` 

![image](https://github.com/user-attachments/assets/7b46f143-7114-42fe-aebe-b753e7c565d0)

```
2024-12-17 02:27:48,237 - 2930080 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/home/hummingbot/hummingbot/development/hummingbot/strategy/script_strategy_base.py", line 75, in tick
    self.on_tick()
  File "/home/hummingbot/hummingbot/development/scripts/v2_with_controllers.py", line 83, in on_tick
    super().on_tick()
  File "/home/hummingbot/hummingbot/development/hummingbot/strategy/strategy_v2_base.py", line 294, in on_tick
    self.executor_orchestrator.execute_action(action)
  File "/home/hummingbot/hummingbot/development/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 102, in execute_action
    self.store_executor(action)
  File "/home/hummingbot/hummingbot/development/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 168, in store_executor
    MarketsRecorder.get_instance().store_or_update_executor(executor)
  File "/home/hummingbot/hummingbot/development/hummingbot/connector/markets_recorder.py", line 205, in store_or_update_executor
    serialized_config = executor.executor_info.json()
  File "pydantic/main.py", line 505, in pydantic.main.BaseModel.json
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 88, in pydantic.json.pydantic_encoder
  File "pydantic/json.py", line 38, in pydantic.json.decimal_encoder
TypeError: '>=' not supported between instances of 'str' and 'int'
```
- Reviewed log file and whle this occurred, orders are placed okay
- `stop` command does not help stop the `unexpected error running clock tick`

### Steps to reproduce

1. Import the files needed on the attached zip file
2. Start the strategy and let it run for couple of hours 

### Release version

dev-2.2.0

### Type of installation

Source

### Attach required files

[12172024.zip](https://github.com/user-attachments/files/18164206/12172024.zip)

**Comment by isreallee82** [comment]
can i try reproduce this on any connector @rapcmia

**Comment by rapcmia** [comment]
This error happened on one of my bots running after 5days / 16hrs again
![image](https://github.com/user-attachments/assets/e8ca1d17-fd07-4327-ad73-96d11f8cd6be)

Stop command initiated, still continuously posting the error on logs 
![image](https://github.com/user-attachments/assets/ea814d0a-6785-4646-80c6-df8572b73567)

```
# start here 
2024-12-22 15:25:50,620 - 3349614 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order x-MG43PCSNBCWUT629dd7eb46d3499ed for 19.40000000 COW-USDT at 0.76860000.
2024-12-22 15:25:50,657 - 3349614 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734881150.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "COW-USDT", "amount": "19.40000000", "price": "0.76860000", "order_id": "x-MG43PCSNBCWUT629dd7eb46d3499ed", "creation_timestamp": 1734881150.0, "exchange_order_id": "178645313", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "binance"}
2024-12-22 15:25:50,658 - 3349614 - hummingbot.connector.client_order_tracker - INFO - Created LIMIT_MAKER BUY order x-MG43PCSNBCWUT629dd7eb46fbb99ed for 19.40000000 COW-USDT at 0.76860000.
2024-12-22 15:25:50,672 - 3349614 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1734881150.0, "type": "OrderType.LIMIT_MAKER", "trading_pair": "COW-USDT", "amount": "19.40000000", "price": "0.76860000", "order_id": "x-MG43PCSNBCWUT629dd7eb46fbb99ed", "creation_timestamp": 1734881150.0, "exchange_order_id": "178645314", "leverage": 1, "position": "NIL", "event_name": "BuyOrderCreatedEvent", "event_source": "binance"}
2024-12-22 15:25:51,028 - 3349614 - hummingbot.core.clock - ERROR - Unexpected error running clock tick.
Traceback (most recent call last):
  File "hummingbot/core/clock.pyx", line 119, in hummingbot.core.clock.Clock.run_til
    child_iterator.c_tick(self._current_tick)
  File "hummingbot/strategy/strategy_py_base.pyx", line 44, in hummingbot.strategy.strategy_py_base.StrategyPyBase.c_tick
    self.tick(timestamp)
  File "/home/hummingbot/hummingbot/development/hummingbot/strategy/script_strategy_base.py", line 75, in tick
    self.on_tick()
  File "/home/hummingbot/hummingbot/development/scripts/v2_with_controllers.py", line 83, in on_tick
    super().on_tick()
  File "/home/hummingbot/hummingbot/development/hummingbot/strategy/strategy_v2_base.py", line 294, in on_tick
    self.executor_orchestrator.execute_action(action)
  File "/home/hummingbot/hummingbot/development/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 102, in execute_action
    self.store_executor(action)
  File "/home/hummingbot/hummingbot/development/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 168, in store_executor
    MarketsRecorder.get_instance().store_or_update_executor(executor)
  File "/home/hummingbot/hummingbot/development/hummingbot/connector/markets_recorder.py", line 205, in store_or_update_executor
    serialized_config = executor.executor_info.json()
  File "pydantic/main.py", line 505, in pydantic.main.BaseModel.json
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/hummingbot/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 88, in pydantic.json.pydantic_encoder
  File "pydantic/json.py", line 38, in pydantic.json.decimal_encoder
TypeError: '>=' not supported between instances of 'str' and 'int'
```
