### ISSUE TITLE
Script config - Unhandled error in background task after time_to_cash_out

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/hummingbot#7353]
### Describe the bug

When running tests, decided to set my script with `time_to_cashout` to observe behavior. It seems to behave as expected:

```
2024-12-27 19:03:29,005 - 32213 - hummingbot.strategy.script_strategy_base - INFO - Cash out time reached. Stopping the controllers.
2024-12-27 19:03:29,006 - 32213 - hummingbot.strategy.script_strategy_base - INFO - Cash out for controller 56U9kXQumRqBeowJuus96FwvFwRQH8o25NjAMc6TRbFz.
2024-12-27 19:03:31,660 - 32213 - hummingbot.strategy.script_strategy_base - INFO - (SOL-USDT) Canceling the limit order 93027a12dac34fBCBSLUTa724895c968. [clock=2024-12-27 11:03:31+00:00]
2024-12-27 19:03:31,660 - 32213 - hummingbot.strategy.script_strategy_base - INFO - (SOL-USDT) Canceling the limit order 93027a12dac34fBCBSLUT68662e4468c. [clock=2024-12-27 11:03:31+00:00]
2024-12-27 19:03:31,660 - 32213 - hummingbot.strategy.script_strategy_base - INFO - (SOL-USDT) Canceling the limit order 93027a12dac34fBCBSLUTca65758592a. [clock=2024-12-27 11:03:31+00:00]
2024-12-27 19:03:31,660 - 32213 - hummingbot.strategy.script_strategy_base - INFO - (SOL-USDT) Canceling the limit order 93027a12dac34fBCBSLUTcc874ffd2de. [clock=2024-12-27 11:03:31+00:00]
2024-12-27 19:03:31,661 - 32213 - hummingbot.strategy.script_strategy_base - INFO - (SOL-USDT) Canceling the limit order 93027a12dac34fBCBSLUTf9ce55bf2a2. [clock=2024-12-27 11:03:31+00:00]
2024-12-27 19:03:31,661 - 32213 - hummingbot.strategy.script_strategy_base - INFO - (SOL-USDT) Canceling the limit order 93027a12dac34fBCSSLUTeacc3edb906. [clock=2024-12-27 11:03:31+00:00]
2024-12-27 19:03:31,720 - 32213 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1735297411.0, "order_id": "93027a12dac34fBCBSLUTa724895c968", "exchange_order_id": "2107027761188642817", "event_name": "OrderCancelledEvent", "event_source": "okx_perpetual"}
2024-12-27 19:03:31,720 - 32213 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order 93027a12dac34fBCBSLUTa724895c968.
2024-12-27 19:03:31,858 - 32213 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1735297411.0, "order_id": "93027a12dac34fBCBSLUT68662e4468c", "exchange_order_id": "2107025735071375361", "event_name": "OrderCancelledEvent", "event_source": "okx_perpetual"}
2024-12-27 19:03:31,858 - 32213 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order 93027a12dac34fBCBSLUT68662e4468c.
2024-12-27 19:03:31,862 - 32213 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1735297411.0, "order_id": "93027a12dac34fBCBSLUTca65758592a", "exchange_order_id": "2107022713360556036", "event_name": "OrderCancelledEvent", "event_source": "okx_perpetual"}
2024-12-27 19:03:31,862 - 32213 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order 93027a12dac34fBCBSLUTca65758592a.
2024-12-27 19:03:31,915 - 32213 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1735297411.0, "order_id": "93027a12dac34fBCBSLUTf9ce55bf2a2", "exchange_order_id": "2107023735898316800", "event_name": "OrderCancelledEvent", "event_source": "okx_perpetual"}
2024-12-27 19:03:31,916 - 32213 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order 93027a12dac34fBCBSLUTf9ce55bf2a2.
2024-12-27 19:03:31,921 - 32213 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1735297411.0, "order_id": "93027a12dac34fBCBSLUTcc874ffd2de", "exchange_order_id": "2107024746960461824", "event_name": "OrderCancelledEvent", "event_source": "okx_perpetual"}
2024-12-27 19:03:31,921 - 32213 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order 93027a12dac34fBCBSLUTcc874ffd2de.
2024-12-27 19:03:31,925 - 32213 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1735297411.0, "order_id": "93027a12dac34fBCSSLUTeacc3edb906", "exchange_order_id": "2107026813913473024", "event_name": "OrderCancelledEvent", "event_source": "okx_perpetual"}
2024-12-27 19:03:31,925 - 32213 - hummingbot.connector.client_order_tracker - INFO - Successfully canceled order 93027a12dac34fBCSSLUTeacc3edb906.
2024-12-27 19:03:32,002 - 32213 - hummingbot.strategy.script_strategy_base - INFO - All executors have finalized their execution. Stopping the strategy.
2024-12-27 19:03:32,002 - 32213 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-12-27 19:03:32,937 - 32213 - hummingbot.connector.client_order_tracker - INFO - Created MARKET SELL order 93027a12dac34fBCSSLUT2e7a1146126 for 0.07 to CLOSE a SOL-USDT position at NaN.
2024-12-27 19:03:32,941 - 32213 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1735297412.0, "type": "OrderType.MARKET", "trading_pair": "SOL-USDT", "amount": "0.07", "price": "NaN", "order_id": "93027a12dac34fBCSSLUT2e7a1146126", "creation_timestamp": 1735297412.0, "exchange_order_id": "2107050992566083584", "leverage": 20, "position": "CLOSE", "event_name": "SellOrderCreatedEvent", "event_source": "okx_perpetual"}
2024-12-27 19:03:32,983 - 32213 - hummingbot.connector.client_order_tracker - INFO - The SELL order 93027a12dac34fBCSSLUT2e7a1146126 amounting to 0.07/0.07 SOL has been filled at 191.11 USDT.
2024-12-27 19:03:32,990 - 32213 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1735297412.0, "order_id": "93027a12dac34fBCSSLUT2e7a1146126", "trading_pair": "SOL-USDT", "trade_type": "TradeType.SELL", "order_type": "OrderType.MARKET", "price": "191.11", "amount": "0.07", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "0.00668885"}]}, "exchange_trade_id": "601603634", "exchange_order_id": "2107050992566083584", "leverage": 20, "position": "CLOSE", "event_name": "OrderFilledEvent", "event_source": "okx_perpetual"}
2024-12-27 19:03:32,999 - 32213 - hummingbot.core.event.event_reporter - EVENT_LOG - {"timestamp": 1735297412.0, "order_id": "93027a12dac34fBCSSLUT2e7a1146126", "base_asset": "SOL", "quote_asset": "USDT", "base_asset_amount": "0.07", "quote_asset_amount": "13.3777", "order_type": "OrderType.MARKET", "exchange_order_id": "2107050992566083584", "event_name": "SellOrderCompletedEvent", "event_source": "okx_perpetual"}
2024-12-27 19:03:32,999 - 32213 - hummingbot.connector.client_order_tracker - INFO - SELL order 93027a12dac34fBCSSLUT2e7a1146126 completely filled.
2024-12-27 19:03:33,002 - 32213 - hummingbot.strategy.script_strategy_base - INFO - All executors have finalized their execution. Stopping the strategy.
2024-12-27 19:03:33,002 - 32213 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-12-27 19:03:34,001 - 32213 - hummingbot.strategy.script_strategy_base - INFO - All executors have finalized their execution. Stopping the strategy.
2024-12-27 19:03:34,001 - 32213 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-12-27 19:03:35,002 - 32213 - hummingbot.strategy.script_strategy_base - INFO - All executors have finalized their execution. Stopping the strategy.
2024-12-27 19:03:35,003 - 32213 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-12-27 19:03:36,004 - 32213 - hummingbot.strategy.script_strategy_base - INFO - All executors have finalized their execution. Stopping the strategy.
2024-12-27 19:03:36,004 - 32213 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-12-27 19:03:37,119 - 32213 - hummingbot.strategy.script_strategy_base - INFO - All executors have finalized their execution. Stopping the strategy.
2024-12-27 19:03:37,126 - 32213 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-12-27 19:03:38,003 - 32213 - hummingbot.strategy.script_strategy_base - INFO - All executors have finalized their execution. Stopping the strategy.
2024-12-27 19:03:38,004 - 32213 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
2024-12-27 19:03:39,001 - 32213 - hummingbot.strategy.script_strategy_base - INFO - All executors have finalized their execution. Stopping the strategy.
2024-12-27 19:03:39,002 - 32213 - hummingbot.client.hummingbot_application - INFO - stop command initiated.
```
- However it begun to log `All executors have finalized their execution. Stopping the strategy.` again
- Following with an error of `Unhandled error in background task` on every tick
  ```
  2024-12-27 19:03:39,150 - 32213 - hummingbot.core.utils.async_utils - ERROR - Unhandled error in background task: (builtins.TypeError) Object of type GridExecutorConfig is not JSON serializable
  [SQL: UPDATE "Executors" SET close_type=?, config=? WHERE "Executors".id = ?]
  [parameters: [{'close_type': <CloseType.EARLY_STOP: 5>, 'config': GridExecutorConfig(id='2nxcGuEjUjgNuUo3QBSwNWEx7WDpnSWeNcEyWANrttrD', type='grid_executor', times ... (832 characters truncated) ... der_type=<OrderType.MARKET: 1>), leverage=20, level_id=None, deduct_base_fees=False), 'Executors_id': '2nxcGuEjUjgNuUo3QBSwNWEx7WDpnSWeNcEyWANrttrD'}]]
  Traceback (most recent call last):
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
      context = constructor(
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
      param = [
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
      processors[key](compiled_params[key])
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 2669, in process
      serialized = json_serializer(value)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/__init__.py", line 231, in dumps
      return _default_encoder.encode(obj)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 199, in encode
      chunks = self.iterencode(o, _one_shot=True)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 257, in iterencode
      return _iterencode(o, 0)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 179, in default
      raise TypeError(f'Object of type {o.__class__.__name__} '
  TypeError: Object of type GridExecutorConfig is not JSON serializable
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/Users/rapcomia/github/hummingbot/hummingbot/staging_2.2.0/hummingbot/core/utils/async_utils.py", line 9, in safe_wrapper
      return await c
    File "/Users/rapcomia/github/hummingbot/hummingbot/staging_2.2.0/hummingbot/client/command/stop_command.py", line 33, in stop_loop
      await self.strategy.on_stop()
    File "/Users/rapcomia/github/hummingbot/hummingbot/staging_2.2.0/scripts/v2_with_controllers.py", line 77, in on_stop
      await super().on_stop()
    File "/Users/rapcomia/github/hummingbot/hummingbot/staging_2.2.0/hummingbot/strategy/strategy_v2_base.py", line 286, in on_stop
      self.executor_orchestrator.store_all_executors()
    File "/Users/rapcomia/github/hummingbot/hummingbot/staging_2.2.0/hummingbot/strategy_v2/executors/executor_orchestrator.py", line 87, in store_all_executors
      MarketsRecorder.get_instance().store_or_update_executor(executor)
    File "/Users/rapcomia/github/hummingbot/hummingbot/staging_2.2.0/hummingbot/connector/markets_recorder.py", line 208, in store_or_update_executor
      session.commit()
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
      self._transaction.commit(_to_root=self.future)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 832, in commit
      self._prepare_impl()
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
      self.session.flush()
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
      self._flush(objects)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
      with util.safe_reraise():
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
      compat.raise_(
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
      raise exception
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
      flush_context.execute()
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
      rec.execute(self)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
      util.preloaded.orm_persistence.save_obj(
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 237, in save_obj
      _emit_update_statements(
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1001, in _emit_update_statements
      c = connection._execute_20(
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
      return meth(self, args_10style, kwargs_10style, execution_options)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
      return connection._execute_clauseelement(
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
      ret = self._execute_context(
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1816, in _execute_context
      self._handle_dbapi_exception(
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
      util.raise_(
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
      raise exception
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
      context = constructor(
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
      param = [
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
      processors[key](compiled_params[key])
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 2669, in process
      serialized = json_serializer(value)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/__init__.py", line 231, in dumps
      return _default_encoder.encode(obj)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 199, in encode
      chunks = self.iterencode(o, _one_shot=True)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 257, in iterencode
      return _iterencode(o, 0)
    File "/Users/rapcomia/miniconda3/envs/hummingbot/lib/python3.10/json/encoder.py", line 179, in default
      raise TypeError(f'Object of type {o.__class__.__name__} '
  sqlalchemy.exc.StatementError: (builtins.TypeError) Object of type GridExecutorConfig is not JSON serializable
  [SQL: UPDATE "Executors" SET close_type=?, config=? WHERE "Executors".id = ?]
  ```

### Steps to reproduce

1.  Set any v2 controller config
2. Set script-config, make sure to add value to `time_to_cashout`

### Release version

dev-2.2.0

### Type of installation

Source

### Attach required files

[logs_okxperp1.log](https://github.com/user-attachments/files/18260050/logs_okxperp1.log)
[logs_test-arb.log](https://github.com/user-attachments/files/18260051/logs_test-arb.log)

**Comment by rapcmia** [comment]
Not able to reproduce on v2.4.0
