### ISSUE TITLE
Unexpected error while fetching bybit trading fees

### ISSUE THREAD

**Issue by snde** [hummingbot/hummingbot#7361]
### Describe the bug

I am executing arbitrage between Bybit and Jupiter with the trading pair PENGU-USDT. The exchange is reporting that it cannot fetch the trading fee, and the trading pair also seems incorrect. The screenshot includes my configuration and logs.
![1735438881116](https://github.com/user-attachments/assets/e48a06c6-c17b-4711-a792-edbea4422cae)
![1735438856390](https://github.com/user-attachments/assets/e00cfe79-1165-4943-a9e6-5a851a70a4a8)

### Steps to reproduce

1. cex bybit
2. dex jupiter
3. pengu-usdt 

### Release version

v2.2.0

### Type of installation

Docker

**Comment by nikspz** [comment]
cc: https://discord.com/channels/530578568154054663/563462222878212098/1326494722939818054
```
2025-01-06 16:20:53,342 - 15 - hummingbot.connector.exchange.bybit.bybit_exchange.BybitExchange - NETWORK - Unexpected error while fetching trading fees.
Traceback (most recent call last):
  File "/home/hummingbot/hummingbot/connector/exchange_py_base.py", line 752, in _trading_fees_polling_loop
    await safe_gather(self._update_trading_fees())
  File "/home/hummingbot/hummingbot/core/utils/async_utils.py", line 22, in safe_gather
    return await asyncio.gather(*args, **kwargs)
  File "/home/hummingbot/hummingbot/connector/exchange/bybit/bybit_exchange.py", line 309, in _update_trading_fees
    trading_pair = await self.trading_pair_associated_to_exchange_symbol(symbol=tpfee["symbol"])
  File "hummingbot/connector/exchange_base.pyx", line 108, in trading_pair_associated_to_exchange_symbol
    return symbol_map[symbol]
  File "/opt/conda/envs/hummingbot/lib/python3.10/site-packages/bidict/_base.py", line 524, in getitem
    return self._fwdm[key]
KeyError: 'CTANUSDT'
2025-01-06 16:20:53,342 - 15 - hummingbot.connector.exchange.bybit.bybit_exchange.BybitExchange - WARNING - Could not fetch new trading fees from Bybit. Check network connection.
[17:16]
Like this
[17:16]
I am trading XRPUSDT but the error shows CTANUSDT
```

**Comment by rapcmia** [comment]
Fix has been merged to development and will be part of release version 2.3.0
